### ISSUE TITLE
v1.3.0.2 select ... from A inner join B .....inner join C .... group by .. order by ...结果空错误

### ISSUE THREAD

**Issue by yoyoch1** [MyCATApache/Mycat-Server#100]
多个表一起join ，然后group by 汇总，可以查出结果，但如果 追加order by排序 ,则会结果为empty。
两个解析器一样情况，原来v1.2支持。

解析器：druidparser；采用DB 自增序列

**Comment by apachemycat** [comment]
是否是1.3.0.2版本？
完整的SQL是怎样的，是否有别名，另外Mycat后端是否有报错，若报错，贴出错误堆栈

**Comment by yoyoch1** [comment]
1.Debug信息：
....................................
01/20 00:21:11.193  DEBUG [$_NIOREACTOR-1-RW] (MultiNodeQueryHandler.java:230) -on row end reseponse MySQLConnection [id=9, lastTime=1421684471181, schema=db04, borrowed=true, fromSlaveDB=false, threadId=387, charset=utf8, txIsolation=3, autocommit=true, attachment=dn3{
SELECT SUM(A.Qty) as Qty
,hour(A.CreatedDt) AS H，B.CName		
FROM SalesOrder As A
JOIN Customer As B ON A.CNo = B.CNo 
WHERE  B.ID =130 and A.CreatedDt BETWEEN  '2014-11-01 00:00:00' AND '2014-12-12 23:59:59'  		
GROUP BY H
order by A.CreatedDt

}, respHandler=org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler@234efbf, host=localhost, port=3310, statusSync=StatusSync [schemaCmd=null, charCmd=null, isoCmd=null, acCmd=null, executed=true], writeQueue=0, modifiedSQLExecuted=false]

01/20 00:21:11.194  DEBUG [$_NIOREACTOR-3-RW] (PhysicalDBPool.java:417) -select read source hostM1 for dataHost:H3310
01/20 00:21:11.195  DEBUG [$_NIOREACTOR-0-RW] (MultiNodeQueryHandler.java:230) -on row end reseponse MySQLConnection [id=16, lastTime=1421684471181, schema=db10, borrowed=true, fromSlaveDB=false, threadId=522, charset=utf8, txIsolation=3, autocommit=true, attachment=dn9{
SELECT SUM(A.Qty) as Qty
,hour(A.CreatedDt) AS H，B.CName		
FROM SalesOrder As A
JOIN Customer As B ON A.CNo = B.CNo 
WHERE  B.ID =130 and A.CreatedDt BETWEEN  '2014-11-01 00:00:00' AND '2014-12-12 23:59:59'  		
GROUP BY H
order by A.CreatedDt
}, respHandler=org.opencloudb.mysql.nio.handler.MultiNodeQueryHandler@234efbf, host=localhost, port=3309, statusSync=StatusSync [schemaCmd=null, charCmd=null, isoCmd=null, acCmd=null, executed=true], writeQueue=0, modifiedSQLExecuted=false]
...........................................................

01/20 00:21:11.332  DEBUG [BusinessExecutor3] (MultiNodeQueryHandler.java:287) -output merge result ,total data 0 start :0 end :-1 package id start:9
01/20 00:21:11.333  DEBUG [BusinessExecutor3] (MultiNodeQueryHandler.java:315) -last packet id:10
01/20 00:21:11.333  DEBUG [BusinessExecutor3] (DataMergeService.java:315) -clear data 


2.显示结果：Empty set(0.04 sec)
3.尝试：去掉B.CName也同样问题；只要去掉order by结果就出来；后台无错误异常。
4.节点与DB对应：dn0=db01...............dn9=db10，应该也不会跟这有关系吧。

**Comment by songwie** [comment]
group by，order by 只要列加别名就会报错，去掉列别名：例如，order by a.name 报错，order by name 不报错，这是个bug ，可以暂时这么用

**Comment by yoyoch1** [comment]
该问题已经彻底解决。
@songwie    已经支持别名。
