### ISSUE TITLE
Mycat 1.5 出现语法解析错误！

### ISSUE THREAD

**Issue by springlin2012** [MyCATApache/Mycat-Server#1001]
Mysql version: 5.7
Exec sql: select * from sam_test;

Err info:
![image](https://cloud.githubusercontent.com/assets/2259506/17125744/c5a6eb94-5328-11e6-9d24-4459035ba478.png)
 
日志分析因mycat如下SQL导致: 
SELECT
	STATE AS 状态,
	ROUND(SUM(DURATION), 7) AS 期间,
	CONCAT(
		ROUND(
			SUM(DURATION)/*100,3), '%') AS '百分比' 
FROM INFORMATION_SCHEMA.PROFILING 
WHERE 1=1
QUERY_ID = ''
GROUP BY STATE 
ORDER BY SEQ
;

**Comment by zzcclp** [comment]
你是采用navicat客户端查询的吧？这个不是mycat的bug，用navicat会产生一些额外的查询语句，你的schema没有的表才会导致的。

**Comment by springlin2012** [comment]
@zzcclp schema没有的表才会导致, 是什么意思, 你一般用什么工具？

**Comment by zzcclp** [comment]
也是navicat，忽略那些错误，INFORMATION_SCHEMA在你的mycat schema中并没有定义，那是navicat额外执行的查询性能状态相关的查询，直接忽略。

**Comment by springlin2012** [comment]
@zzcclp 好的, 谢谢;
感觉有点奇怪, 之前我用navicat 的时候并没有报这个错误! 还是看看源码

**Comment by magicdoom** [comment]
1.6 alpha已经修复

**Comment by springlin2012** [comment]
@magicdoom 
是修复那一块源码，是否可同步到1.5版本，能兼容么？
