### ISSUE TITLE
LatestMonthPartion分片24时问题

### ISSUE THREAD

**Issue by tangrm** [MyCATApache/Mycat-Server#1003]
由于LatestMonthPartion分片的分片键为字符串，格式为yyyyMMddHH，如果在小时部分写成了24会自动计划一个分片，这样对于跨月的是不是会有问题呢？
![image](https://cloud.githubusercontent.com/assets/12824649/17162115/94a2e292-53e5-11e6-9a71-c43e1d8c3f1b.png)
是不是应该杜绝24时这种写入方法？

**Comment by magicdoom** [comment]
这个貌似应该应用上去避免传入不正确的值
