### ISSUE TITLE
不支持变量

### ISSUE THREAD

**Issue by tangrm** [MyCATApache/Mycat-Server#1005]
无法像mysql一样支持用户变更 @value，可赋值，但取不出结果，结果为NULL。
SET @value = '123';
SELECT @value;

**Comment by HashZhang** [comment]
这个请问生产上的应用场景是什么？如果有必要，就添加这个功能

**Comment by tangrm** [comment]
生产应用上暂时没用到，只是在例行维护数据库时有用到，比如需要统计一些数据什么的。

**Comment by magicdoom** [comment]
暂时不支持     中间件有变量不太合适
