### ISSUE TITLE
mycat运行postgresql出问题！！！

### ISSUE THREAD

**Issue by zbb456123vb** [MyCATApache/Mycat-Server#1008]
第一次测试用mycat运行postgresql就出现问题，希望得到解决。mycat能启动，但是无法正常运行。
mycat版本1.5
postgresql版本为9.4.8
jdbc驱动版本为postgresql-9.4.1209.jar

以下为schema.xml关于连接的配置
![image](https://cloud.githubusercontent.com/assets/20138420/17268539/bd53b74e-565f-11e6-835a-0acb293dd499.png)

以下为server.xml配置
![image](https://cloud.githubusercontent.com/assets/20138420/17268550/fcb3837e-565f-11e6-8618-4ab7a83836b3.png)
![image](https://cloud.githubusercontent.com/assets/20138420/17268557/117abe8a-5660-11e6-896c-2cad889c5483.png)

以下是启动mycat的错误日志
(1)wrapper.log错误日志
![image](https://cloud.githubusercontent.com/assets/20138420/17268572/6239d8e2-5660-11e6-9159-1eb79df3785f.png)
(2)mycat.log错误日志
![image](https://cloud.githubusercontent.com/assets/20138420/17268583/b55df33c-5660-11e6-8520-37b42d9766ba.png)
![image](https://cloud.githubusercontent.com/assets/20138420/17268586/c5f52724-5660-11e6-9ec9-72c79fa7ac2f.png)
![image](https://cloud.githubusercontent.com/assets/20138420/17268589/d5f69fe0-5660-11e6-8b8d-4bd9e4f8fc82.png)
![image](https://cloud.githubusercontent.com/assets/20138420/17268592/efa5d3d4-5660-11e6-937c-5e4634e56ae8.png)

**Comment by zbb456123vb** [comment]
希望得到大神解决

**Comment by zbb456123vb** [comment]
就没知道的么。。自己顶一个

**Comment by little-pan** [comment]
自己配置问题。。。

**Comment by zbb456123vb** [comment]
请问，如何配置。。求救。。

**Comment by zbb456123vb** [comment]
求救求救。。。

**Comment by HashZhang** [comment]
你这个配置和日志报错不一致啊，localhost2是什么

**Comment by zbb456123vb** [comment]
修改了，不报错了。但8066端口还是连接不上。。

**Comment by HashZhang** [comment]
后台日志是什么？

**Comment by magicdoom** [comment]
需要给出详细的出错信息   否则别人帮不了你

**Comment by magicdoom** [comment]
除0的那个问题已经解决    请下载最新1.6验证问题是否还存在

**Comment by zbb456123vb** [comment]
之前试过了，如果有mysql一起运行就没有问题。是不是mycat必须安装mysql，由mysql转发？

**Comment by magicdoom** [comment]
你如果dataHost配置了mysql  才需要mysql

**Comment by magicdoom** [comment]
jdbc:postgresql://192.168.0.102:5432/base     jdbc的url最后需要配置上库名

**Comment by magicdoom** [comment]
不加库名   pg的驱动不认这个url

**Comment by zbb456123vb** [comment]
哦。mysql的是直接用集合名当逻辑库名，如果pgsql用实际的库名，是不是太麻烦了？这样也没法分片啊。。

**Comment by zbb456123vb** [comment]
mysql的是localhost:8066/schema名，这样就行。如果pg要用实际库当连接的话，不会太麻烦么。。

**Comment by magicdoom** [comment]
等1.6的pg原始协议稳定了可以使用     native方式
