### ISSUE TITLE
mysql5.7 配置ssl后，mycat1.6连接不上

### ISSUE THREAD

**Issue by WenTao-Love** [MyCATApache/Mycat-Server#1013]
can't connect to mysql server ,errmsg:Host 'LAPTOP-1VV4JSL7' is not allowed to connect to this MySQL server MySQLConnection [id=35, lastTime=1470135624736, user=root, schema=test, old shema=test, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=192.168.2.102, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]

我用其它客户端可以连接，mycat1.6支持mysql ssl连接吗？

**Comment by magicdoom** [comment]
mycat暂时不支持ssl

**Comment by magicdoom** [comment]
欢迎志愿者提交pr来支持

**Comment by zhoutaoo** [comment]
这个有计划支持吗？
