### ISSUE TITLE
结果集顺序不确定，bug？

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#1018]
同一个sql查询，无排序字段，多次执行，每次得到的结果集顺序是不确定的。可否加以改善？

**Comment by magicdoom** [comment]
这个不是bug   由于mycat是并发执行sql，所以各分片返回的先后顺序并不能保证。如果需要顺序，加order by即可

**Comment by bluoy** [comment]
如果加order by，就提高了mycat的二次排序成本。大结果集二次排序的代价还是太高了，如果是大并发场合，情况就更糟糕了。

**Comment by magicdoom** [comment]
如果不加order by也有顺序  那需要等待   更消耗资源了

**Comment by HashZhang** [comment]
是的，最好order by的东西不要加

**Comment by bluoy** [comment]
此bug不单是无序，还会造成多次查询结果集的不一致。

下面是验证示例(dn表示分库节点号)：
mysql> select * from test limit 5;
+------+-------+------+
| id   | value | dn   |
+------+-------+------+
|    1 |     1 |    1 |
|    2 |     2 |    1 |
|    3 |     3 |    1 |
|    4 |     4 |    1 |
|    5 |     5 |    1 |
+------+-------+------+
5 rows in set (0.00 sec)

mysql> select * from test limit 5;
+------+-------+------+
| id   | value | dn   |
+------+-------+------+
|    1 |     1 |    1 |
|    1 |    20 |    2 |
|    2 |     2 |    1 |
|    2 |    21 |    2 |
|    3 |     3 |    1 |
+------+-------+------+
5 rows in set (0.01 sec)

**Comment by magicdoom** [comment]
并发执行  先到先输出     你要强制按一个顺序就需要等待或者暂存数据   这个对性能有影响的

**Comment by bluoy** [comment]
代价，其实一直都有，无论是按序，还是order by，以及其他的二次归并处理。
所以，还是取决于对该问题的定性。
如果对于固定的输入，却不能保证一致的输出。在大部分业务中，是不可忍受的。

**Comment by magicdoom** [comment]
其实oracle的分页语句加了orderby 都没发保证 前后页的一致性        所以如果没有代价小的方式去实现 暂时维持现状  欢迎开拓思路继续

**Comment by bluoy** [comment]
验证了DRDS，是按照节点顺序输出的。

**Comment by magicdoom** [comment]
你可以想想有什么代价小的实现方式
