### ISSUE TITLE
使用mycat多租户问题 对接jpa, 无法成功进行分库查询

### ISSUE THREAD

**Issue by PepperYan** [MyCATApache/Mycat-Server#1026]
connection = DriverManager.getConnection(jdbcurl,username,password);
Statement st = c.createStatement();
 return print( "test jdbc " , st.executeQuery("/* !mycat:schema=DEMODB*/select * from demo "));

在使用 mycat 多租户分库方案 对接到 jpa 时, 发现不能查询正确的库, 最后发现是注释中 !mycat标识前若是有空格的话, 就不能正确识别到目标库.

**Comment by magicdoom** [comment]
mycat提供了几种注释方式   就是因为有些环境适用

**Comment by ShinEDL** [comment]
@magicdoom 除了/*!mycat*/还有其他的注解方式吗？

**Comment by ShinEDL** [comment]
@magicdoom 除了/\*!mycat\*/还有其他的注解方式吗？

**Comment by magicdoom** [comment]
目前支持这三种    /*!mycat*/      /*#mycat*/     /**mycat*/

**Comment by magicdoom** [comment]
!mycat标识前若是有空格的话  这个不符合注解规范的

**Comment by ShinEDL** [comment]
@magicdoom 但是使用spring data jpa或者hibernate的话，它们都会给注释内容的前后加上空格（/* ！macat */），这导致我们无法使用mycat的多租户功能。因此我们希望mycat能否解决这个问题，使之能够配合spring data jpa。 : )

**Comment by ShinEDL** [comment]
@magicdoom 但是使用spring data jpa或者hibernate的话，它们都会给注释内容的前后加上空格（/*  !mycat  */），这导致我们无法使用mycat的多租户功能。因此我们希望mycat能否解决这个问题，使之能够配合spring data jpa。 : )
