### ISSUE TITLE
canRunnINReadDB的判断

### ISSUE THREAD

**Issue by max-lim** [MyCATApache/Mycat-Server#1031]
org.opencloudb.route.RouteResultsetNode 函数如下：
public boolean canRunnINReadDB(boolean autocommit) {
		return canRunInReadDB && autocommit && !hasBlanceFlag
			|| canRunInReadDB && !autocommit && hasBlanceFlag;
}

这是读取readhost的条件：
canRunInReadDB 表示判断sql 类型的结果
autocommit 表示客户端连接的 commit状态
hasBlanceFlag 表示sql是否有balance标志

如果java项目用spring处理事务（ISOLATION_READ_COMMITTED级别），请求sql时，事务处理会发起 set commit=0，那么autocommit=false ，从而导致查询sql不能走readhost

不知道官方为什么要加 autocommit 这个条件? 完全没必要

**Comment by magicdoom** [comment]
仔细看指南吧   mycat设计读写分离与事务有关是有原因的
