### ISSUE TITLE
1.5/1.6 UPDATE后SELECT ROW_COUNT()返回-1

### ISSUE THREAD

**Issue by Kagamine** [MyCATApache/Mycat-Server#1040]
UPDATE后SELECT ROW_COUNT()返回-1

**Comment by magicdoom** [comment]
目前mycat返回的ok包和eof包   里面都已经有影响行数了        可以从这个里面取  不需要再执行sql     也欢迎提交pr来支持

**Comment by Kagamine** [comment]
包里返回的也是-1

**Comment by magicdoom** [comment]
后续会改进在返回包里返回   这个issue先开着

**Comment by magicdoom** [comment]
返回包里的是正常的       SELECT ROW_COUNT()这个欢迎其他人提交pr来支持
