### ISSUE TITLE
带库名操作会出错find no Route:xxxxxxx

### ISSUE THREAD

**Issue by w602350769** [MyCATApache/Mycat-Server#1043]
SELECT * FROM EMPLOYEE LIMIT 0,100; 正常工作

SELECT * FROM `TESTDB`.`employee` LIMIT 0, 1000; 会报错

错误代码： 1064
 find no Route:select * from `TESTDB`.`employee` limit 0, 100

**Comment by magicdoom** [comment]
在schema上配置checkSQLschema="true"即可
