### ISSUE TITLE
sqlengine/mpp/DataNodeMergeManager.java 代码严谨性错误

### ISSUE THREAD

**Issue by skeght** [MyCATApache/Mycat-Server#1047]
Map<String, Integer> mergeColsMap = rrs.getMergeCols();

            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("isHasAggrColumn:" + rrs.getMergeCols().toString());
            }

            if (mergeColsMap != null) {

mergeColsMap为空 LOGGER.debug空指针报错。

**Comment by skeght** [comment]
if (mergeColsMap != null) {
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("isHasAggrColumn:" + mergeColsMap.toString());
                }


移到if里面即可

**Comment by magicdoom** [comment]
欢迎提交个pr吧

**Comment by magicdoom** [comment]
已经合并
