### ISSUE TITLE
Insert或Update Binary字段时，_binary'...' mycat会将内容改变(1.5/1.6)

### ISSUE THREAD

**Issue by Kagamine** [MyCATApache/Mycat-Server#1057]
Insert或Update Binary字段时，`_binary'...'` mycat会将内容改变(1.5/1.6)
只有使用`X'...'`这种将字节转换为HEX的形式字符串才能正确存储Binary

**Comment by magicdoom** [comment]
查询会不会有问题

**Comment by Kagamine** [comment]
查询正常，返回的字节都是正确的

**Comment by magicdoom** [comment]
blob字段可以使用这种办法来支持

**Comment by etongs** [comment]
我也遇到了这个问题，是怎么解决的
