### ISSUE TITLE
严重bug，请尽快回复，mysql sql查询加MAX会出现其他字段查出来的是第一条信息

### ISSUE THREAD

**Issue by 252987283** [MyCATApache/Mycat-Server#1061]
select aa,bb from table 
查出来的结果：
aa     bb
1       "AAA"
2       "BBB"
select max(aa),bb from table 
查出来的结果：
aa     bb
2        "AAA"

查出来的bb字段结果不对，不使用mycat查出来的正确是
正确结果应该是：
aa     bb
2        "BBB"

**Comment by magicdoom** [comment]
你这个语句有问题吧   max同时   另外一个字段想干啥

**Comment by 252987283** [comment]
@magicdoom  语句应该没问题，通过某个字段的最大值找出当前行，
用mysql与mycat查出来的不一样，项目中用mycat发现的这个问题，应该和mysql的返回值一致才对

**Comment by 252987283** [comment]
@magicdoom sql写的有问题，我重新写个例子
mysql:
(SELECT bbb,MAX(ddd) ,ccc FROM  
 (SELECT bbb,ccc,ddd   FROM test_mycat      
 ORDER BY ddd DESC) t GROUP BY ccc)
正确返回：
bbb	MAX(ddd)	ccc
success	3	my

相同的sql用mycat返回确是:
bbb	MAX(ddd)	ccc
failed	3	my


数据库表test_mycat 数据里有3条数据
id		bbb	ccc	ddd
1		failed	my	1
2		failed	my	2
3		success	my	3

**Comment by magicdoom** [comment]
重复了   先关闭
