### ISSUE TITLE
关于mycat大小写不敏感的疑问

### ISSUE THREAD

**Issue by liushifa** [MyCATApache/Mycat-Server#1062]
由于老的业务库名，表名，字段名都是大小写敏感的，而mycat是大小写不敏感的，所以能不能让mycat也支持大小写敏感呢？如果不支持的话，老的业务迁移基本是不可能的事情，上万张表的修改很累，只能用在新的业务上，而新的业务对于分库分表需求不是很大，所以希望能支持哈

**Comment by magicdoom** [comment]
这个涉及到很多地方  比如druid修改sql后的大小写就不是我们能控制的   所以现在很难实现你的这个需求
