### ISSUE TITLE
这是mycat解析sql的BUG还是默认mycat机制有什么办法处理吗？

### ISSUE THREAD

**Issue by 252987283** [MyCATApache/Mycat-Server#1063]
之前sql写的有问题，我重新写个例子
mysql:
(SELECT bbb,MAX(ddd) ,ccc FROM  
 (SELECT bbb,ccc,ddd   FROM test_mycat      
 ORDER BY ddd DESC) t GROUP BY ccc)
正确返回：
bbb	MAX(ddd)	ccc
success	3	my

相同的sql用mycat返回确是:
bbb	MAX(ddd)	ccc
failed	3	my

数据库表test_mycat 数据里有3条数据
id		bbb	       ccc	ddd
1		failed	my	1
2		failed	my	2
3		success	my	3

**Comment by magicdoom** [comment]
暂时不支持子查询

**Comment by 252987283** [comment]
@magicdoom 请问大哥那mycat如何支持先排序后分组的功能呢？

**Comment by magicdoom** [comment]
排序拿到外面

**Comment by 252987283** [comment]
大哥，这样不行的，加到外面不用子查询都是先分组后排序啊
有什么其他好办法？

**Comment by magicdoom** [comment]
暂时不支持子查询    你再研究看看怎么写吧     后续1.7或许会实现子查询
