### ISSUE TITLE
Insert into child table时，NIO会机率性卡死，revision 647 引入的问题。

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#107]
更新
====
最近查了下原来的svn版本库，发现是647对NIO的更新引入的问题。
---------------------------------------------------------------------------------------------------------
mycat：cpu: i3 4核心，os: ubuntu 14.04 64bit， jdk 1.7.0_02, 使用mysql协议连接mysql服务器。
mysql：cpu: i3 4核心，os: xp sp3, 单机双mysql实例配置

故障现象：
只要是对child table进行insert操作，就会机率性卡死，5分钟后返回，log中抛同样的异常。

初步跟踪了代码（版本与master同步）：
SystemConfig中缺省已经有避免单核心的逻辑，所以可以排除单线程这个原因。
FetchStoreNodeOfChildTableHandler中的execute()函数，5分钟阀值在此处定义，卡死是因为dataNode始终为null,所以一直在循环等待直到超时。dataNode为空，是因为MySQLConnection中的handleData()函数没有进入handleRowPacket()触发上述Handler的rowResponse()，其实出错时连handleData()都没触发。
使用wireshark监听网络通信，mysql应答是正常的。
也就是说，mycat接受到了正常应答包，但没有触发handleData()函数。难道时NIOReactor的问题？

**Comment by wdw1206** [comment]
【宗师】Leader-us
这个以后要把ER分片获取父表ID的改成异步方式，才能彻底解决

**Comment by shihao138096** [comment]
我在虚拟机上页遇到类似问题，随机出现
