### ISSUE TITLE
通过mycat执行存储过程，始终不返回结果

### ISSUE THREAD

**Issue by fuzzywy** [MyCATApache/Mycat-Server#1071]
使用mycat分片，一共4个节点。
每个节点有同一张表A，B，并且都有存储过程C。
存储过程C：关联A和一个全局表，将计算的结果写入B。
通过mycat调用存储过程C
/*!mycat:sql=select 1 from A*/call C();

可以观察到4个节点都有调用C的process。
其中3个节点5分钟之后，process终止，另外一个10分钟后，process终止。
确认4个节点的C表全部有数据写入。

但是mycat的控制台始终没有返回，处于阻塞状态。
执行CTRL+C后，直接退出控制台。
^CCtrl-C -- sending "KILL QUERY 2" to server ...
Ctrl-C -- query aborted.
^CCtrl-C -- sending "KILL 2" to server ...
Ctrl-C -- query aborted.
^CCtrl-C -- exit!
Aborted

================================
日志未任何异常
版本：1.5.1-Release

**Comment by magicdoom** [comment]
你调用代码是怎么写的

**Comment by magicdoom** [comment]
如果是命令行  可能是注解被过滤掉了   请用jdbc写程序来测试

**Comment by fuzzywy** [comment]
我是直接在控制台用命令行执行的。
本来是一个批处理的脚本，执行的时候发现脚本一直被阻塞在这一步，直到超时。
然后我单独把这个存储过程拉出来执行，发现是存储过程一直不返回。

请问，注解被过滤掉了是什么意思。必须写代码实现吗

**Comment by magicdoom** [comment]
mycat有几种注解的方式  你都试试看

**Comment by fuzzywy** [comment]
刚刚编码试了一下，也是一样的问题
		Connection conn = null;
		try {
			Class.forName("com.mysql.jdbc.Driver").newInstance();
			conn = DriverManager.getConnection("jdbc:mysql://10.40.57.190:8066/MR_CZ?user=mr&password=mr");
			PreparedStatement cStmt = conn.prepareStatement("/*!mycat:sql=select 1 from MRO*/{call mroPciMod3()}");
			boolean hadResults = cStmt.execute();
			System.out.println(hadResults);
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			if (conn != null) {
				try {
					conn.close();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}

我再试试其它的注解方式

**Comment by magicdoom** [comment]
去看权威指南  或者群里写的说明文档

2016-08-23 11:47 GMT+08:00 wangyang <notifications@github.com>:

**Comment by magicdoom** [comment]
你多了大括号

2016-08-23 12:43 GMT+08:00 nange <magicdoom@gmail.com>:

**Comment by fuzzywy** [comment]
仔细看了mycat权威指南第5章：mycat注解
只找到下面的描述
=====
Call
1. 若是要在所有的分片上都执行存储过秳，则使用一个在所有分片上都包含的表，不添加任何分片条件 调用存储过程
2. 若是单个分片执行，使用能确任返这个分片的表及分片条件
=====
我现在使用的就是第一个规则，没有添加分片的条件
其它的注解方式如 读写分离，多表shareJoin，读写分离数据源选择，多租户支持都不适用。

**Comment by fuzzywy** [comment]
如果选择使用分片规则，指定单个节点执行。
其中3个节点的存储过程都能正常返回
执行时间为5分钟左右
mysql> /*!mycat:sql=select * from MRO where userLabel='LD31J06'*/call mroPciMod3();
Query OK, 741 rows affected, 64 warnings (4 min 42.37 sec)

------------------
另外一个节点的执行时间超过了10分钟，存储过程也一直不返回。
这个跟时间有关系吗，除了query的超时，是不是mycat内部也有超时的机制

**Comment by fuzzywy** [comment]
控制台退出之后，关闭所有节点的连接。
执行时间最长的节点，statusSync貌似有异常
statusSync=null, writeQueue=0, modifiedSQLExecuted=false
statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@4dc2f330
statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
statusSync=null, writeQueue=0, modifiedSQLExecuted=false]

**Comment by fuzzywy** [comment]
@magicdoom 应该是mysql的问题。
单独执行最慢的节点，虽然有数据生成，但是存储过程一直不退出。
谢谢了
