### ISSUE TITLE
LOAD DATA local INFILE导入的所有Boolean类型全部变成了false

### ISSUE THREAD

**Issue by wangjingfei** [MyCATApache/Mycat-Server#1074]
使用MyCAT导入的Boolean类型全变成了false，使用MySQL导入正常。

MyCAT版本：5.5.8-mycat-1.5.1-RELEASE-20160811220036

**Comment by ZzzCrazyPig** [comment]
@wangjingfei  你指的boolean类型是哪个类型?还是你前一个issue里面的bit(1)?

**Comment by wangjingfei** [comment]
是bit(1)，只不过这次是用LOAD DATA方式导入的。

**Comment by ZzzCrazyPig** [comment]
@wangjingfei load data的数据量是否很小就会出现这个问题? 我可以尝试debug一下

**Comment by ZzzCrazyPig** [comment]
@wangjingfei  你好，我这边以你之前的表为例子，先导出表数据

```sql
select id, hex(isDeleted)  into outfile 'e:/tab_web_user-data.txt'
fields terminated by ','
lines terminated by '\r\n'
from tab_web_user;
```
然后通过mycat执行load data导入数据，并没有发生你说的情况，导入语句为:

```sql
load data local infile 'e:/tab_web_user-data.txt'
into table tab_web_user
fields terminated by ','
lines terminated by '\r\n'
(id, isDeleted);
```

但是如果不以**`hex(isDeleted)`**来导出boolean字段，而**直接导出`isDeleted`字段**，查看数据文件本身该字段显示为不可见字符。使用mycat load data导入，确实全部为false（或者有可能是NULL）。

**也就是说以hex([bit(1)_column_name])的方式导出boolean字段，可以绕过这个bug。**

**【温馨提示】**

使用mysql命令行工具执行:
```sql
select id,isDeleted from tab_web_user;
```
`isDeleted`字段同样显示为不可见字符。得使用`hex(isDeleted)`才能返回正常的0和1

**Comment by wangjingfei** [comment]
hex应该可以解决问题，但是这样的话我就需要手动处理所有的boolean类型了（目前我有300+表，有的表里边有十几二十列boolean数据），你们计划什么时候修复这个bug呢？谢谢了，看好你们！

**Comment by ZzzCrazyPig** [comment]
@wangjingfei 你load data的数据是以前导出的？不能重新用hex导出一次？

**Comment by wangjingfei** [comment]
Sorry，可以的。因为之前使用了mysqldump导出，以为没有对应参数。看文档应该可以使用mysqldump的`--hex-blob`参数导出。

目前没有问题了，非常感谢！

**Comment by ZzzCrazyPig** [comment]
@wangjingfei 恩，建议还是以可见形式导出，这个bug我fix代码并pr到1.6。1.5版本就不改动了。用hex导出能解决问题就OK！

**Comment by wangjingfei** [comment]
好的，非常感谢！
