### ISSUE TITLE
MyCAT eye不停的报“xxx死机”，这个死机到底是什么意思呢？

### ISSUE THREAD

**Issue by wangjingfei** [MyCATApache/Mycat-Server#1083]
大概一小时会报一次，但是操作系统和数据库貌似都是正常的。那么到底是MyCAT Eye错了呢，还是MyCAT真的出问题了？除了报“xxx死机”之外，能不能给出一些稍微有点价值的错误信息呢？

目前在进行灰度部署，经常遇到这种报错不敢继续了。

**Comment by magicdoom** [comment]
mycat eye不太完善   以后考虑重构

**Comment by mousycoder** [comment]
不太完善啊，那到底现在是用mycat-web还是mycat-eye ，这2个什么区别？ 希望能跟上大佬的步伐，少走弯路

**Comment by Fxdemon** [comment]
可以使用cobar 的原生监控

**Comment by mousycoder** [comment]
文档很少啊，咋开启
