### ISSUE TITLE
使用mycat查询,经常性阻塞。

### ISSUE THREAD

**Issue by fuzzywy** [MyCATApache/Mycat-Server#1085]
使用mycat查询，经常性出现阻塞，不返回结果。
用控制台，JDBC，PDO(PHP)都测试过，都存在这种问题。
参考git-hub上的相似问题，设置AIO=1,将mutiNodeLimitType注释掉，都不行。
机器是2CPU,12核,24线程，不存在单线程的问题。

用9066端口，show @@connection命令。
可以看到阻塞的线程，但是线程的NET_IN和NET_OUT一直维持在固定值，不会增加。
但是正常的线程，能看到NET_OUT明显增加。

请问，这个问题能否用修改配置的方法解决。因为

出现的频率挺高的，非常影响使用体验。
附上server.xml文件。

版本 1.5.1-RELEASE
![capture](https://cloud.githubusercontent.com/assets/8663680/18240319/7b4cc616-737d-11e6-86df-7280579fe619.PNG)

**Comment by zhuam** [comment]
不推荐 AIO， 请用NIO

**Comment by ZzzCrazyPig** [comment]
@fuzzywy mycat logs目录下的日志文件请查看一下，是否有出现什么异常日志？如果NIO都会出现这种情况，怀疑是JDK版本问题

**Comment by magicdoom** [comment]
另外检查是否你程序里有事务  没有commit'或者rollback

**Comment by magicdoom** [comment]
aio准备废弃  有bug  不建议用

**Comment by fuzzywy** [comment]
很不好意思，耽搁了这么久。
@ZzzCrazyPig 我看了所有阻塞时的日志，都是没有异常打印的。
用show @@conenction查看阻塞进程，发现NET_OUT一直是一个固定值，大概2000多个字节。
@zhuam @magicdoom 我现在已经换回了NIO了，我发现用show @@connection查看后台链接时会发现后台有这种SCHEMAL为NULL并且存在了超长时间的链接
| Processor10 | 2067 | 127.0.0.1     | 8066 |      41964 | mr   | NULL   | utf8:33 |    173 |     700 |          4350 |       40960 |          0 | 3       | true      
我把这个链接KILL掉，就能够正常查询了。
请问，这种链接是怎么产生的呢

**Comment by fuzzywy** [comment]
暂时解决的办法是自动kill掉某些schemal为NULL或者存在时间超长的connection
