### ISSUE TITLE
1.6 版本, 使用 prepare语句时, 参数使用 无符号整形,  类型解析错误

### ISSUE THREAD

**Issue by playzhangzlm** [MyCATApache/Mycat-Server#1086]
参数 BindValue 类型 解析赋值时 使用  bv.type & 0xff,   而在 使用此bv.type时没有 进行0xff位运算,导致类型找不到.

先由 ExecutePacket.java(120)
public void read(byte[] data, String charset) throws UnsupportedEncodingException 函数中
![image](https://cloud.githubusercontent.com/assets/21661217/18240284/50baf4c2-737d-11e6-910f-1e76759da434.png)
mm.readUB2() 函数解析 参数类型, 通过位运算
![image](https://cloud.githubusercontent.com/assets/21661217/18240384/f7b4728a-737d-11e6-9cdf-84fa9472e170.png)
通过类型对BindValue变量赋值
![image](https://cloud.githubusercontent.com/assets/21661217/18240447/69ac572c-737e-11e6-8d5b-b74074cb4d95.png)

最后 在使用时 没有进行 0xff 位运算
![image](https://cloud.githubusercontent.com/assets/21661217/18240472/a008c148-737e-11e6-8245-fcfb38a17410.png)
------------------------------------------------------------------------------------------------
2016-09-05 15:36:38,018 [WARN ][$_NIOREACTOR-0-RW] caught err: java.lang.NullPointerException
	at io.mycat.server.handler.ServerPrepareHandler.prepareStmtBindValue(ServerPrepareHandler.java:187)
	at io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:93)
	at io.mycat.net.FrontendConnection.stmtExecute(FrontendConnection.java:370)
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:91)
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:462)
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:444)
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
	at java.lang.Thread.run(Unknown Source)

不清楚 此问题 你们是否已修复了, 如果已修复就忽略掉吧

**Comment by ZzzCrazyPig** [comment]
@playzhangzlm 能提供一下测试出错的程序？表结构？或者运行出错的那条sql语句么？

**Comment by playzhangzlm** [comment]
这样的语句执行的
CStatementPtr stmt = conn->prepareStatement("insert into tb_hist_player_money_record(id,player_id,money_type,money_opt,money_action,before,after,`value`,`status`,created_date,last_modified_date) values(?,?,?,?,?,?,?,?,?,?,?)");
		stmt->setUInt64(1,id);
		stmt->setUInt64(2,player_id);
		stmt->setUInt(3,money_type);
		stmt->setUInt(4,money_opt);
		stmt->setUInt(5,money_action);
		stmt->setUInt(6,before);
		stmt->setUInt(7,after);
		stmt->setUInt(8,value);
		stmt->setUInt(9,status);
		stmt->setTimestamp(10,created_date*1000);
		stmt->setTimestamp(11,last_modified_date*1000);
		bool retval = stmt->executeUpdate() > 0;

**Comment by ZzzCrazyPig** [comment]
这个表的这些列定义能给下？这是用C++调用的？

**Comment by playzhangzlm** [comment]
是用 C++调用的,   你是要这个数据表结构的定义?

**Comment by playzhangzlm** [comment]
C++那些函数实现在底层库, 看不到, 
表结构是这样的,  一般整形字段都是用的 无符号的
CREATE TABLE `tb_hist_player_money_record` (
`id`  bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
`player_id`  bigint(20) UNSIGNED NOT NULL ,
`money_type`  tinyint(3) UNSIGNED NOT NULL ,
`money_opt`  tinyint(3) UNSIGNED NOT NULL,
`money_action`  int(10) UNSIGNED NOT NULL,
`before`  int(10) UNSIGNED NOT NULL COMMENT ' 操作之前值 ' ,
`after`  int(10) UNSIGNED NOT NULL ,
`value`  int(10) UNSIGNED NOT NULL,
`status`  tinyint(3) UNSIGNED NOT NULL ,
`created_date`  datetime NOT NULL ,
`last_modified_date`  datetime NOT NULL,
PRIMARY KEY (`id`),
INDEX `index1` (`player_id`) USING BTREE 
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

**Comment by ZzzCrazyPig** [comment]
恩，就要这个表结构而已，上面插入程序的所有字段都是插入非空值对吧？

**Comment by playzhangzlm** [comment]
是的,  全字段都会赋值的.

**Comment by ZzzCrazyPig** [comment]
恩，能顺便提供一下你使用的C++测试代码吗？因为我搞java，很少搞c++，得本地部署C++环境来debug？能打包共享出来么？百度云？

**Comment by playzhangzlm** [comment]
我是在 我们的项目中使用的,   无法给你,  刚才用项目库 试着写个测试程序, 发现不能运行, 没法给你 c++的测试程序, 抱歉.

mycat 的 io\mycat\server\handler\ServerPrepareHandler.java(145)  如下图所示, 加了 & 0xff 就解决了类型找不到的问题了.
private String prepareStmtBindValue(PreparedStatement pstmt, BindValue[] bindValues) {

![image](https://cloud.githubusercontent.com/assets/21661217/18247341/8a7d7802-73a4-11e6-81d0-e2c8d75f9717.png)

**Comment by ZzzCrazyPig** [comment]
嗯，没事，是我没那么快写出一个c++调试程序，而且看你给的片段，至少是封装过的！你确定没问题的话，由你来提pull request?

**Comment by playzhangzlm** [comment]
我本地测试 是OK的,   我还没有 pull request 过,

**Comment by ZzzCrazyPig** [comment]
好的，我大概知道为何要加那个`&0xff`了。我可以用java来测试，应该就是因为你的字段定义为`UNSIGNED`，而我之前没有测试过这种类型。谢谢你提出这个issue！我测试完我来提issue吧。

link : 
```
The type of each parameter is made up of two bytes:

the type as in Protocol::ColumnType

a flag byte which has the highest bit set if the type is unsigned [80]
```

from [mysql protocol document](https://dev.mysql.com/doc/internals/en/com-stmt-execute.html)
