### ISSUE TITLE
有唯一索引情况下，导入多行insert语句会导致丢失数据

### ISSUE THREAD

**Issue by lingniao2000** [MyCATApache/Mycat-Server#1093]
#当mysqldump文件里面包含多行insert，并且有重复行（部分字段），导入到新的包含唯一索引的mycat分表（相同结构),会丢失数据, 重复行有概率能导入进去一行。

**Comment by ZzzCrazyPig** [comment]
mycat什么版本？mysqldump insert数据样式能否给一下？

**Comment by magicdoom** [comment]
给出能重现的数据   不然很难排查

**Comment by lingniao2000** [comment]
好的，我晚点提供，这两天抽不开身


发自我的 iPhone

**Comment by lingniao2000** [comment]
好像比较难抽取，我是一个很大的mysqldump文件里面的数据，一个多行insert，都很大。似乎不好抽取

2016-09-09 12:18 GMT+08:00 Lingniao Li <lingniao@gmail.com>:

**Comment by lingniao2000** [comment]
mycat是1.5

在 2016年9月9日 下午4:49，Lingniao.Li <lingniao@gmail.com>写道：

**Comment by ZzzCrazyPig** [comment]
那能把出错的背景描述一下？这样对我们修复有帮助！比如用的表是否为分片表？分片规则？mycat log是否有出错日志，有给下日志

**Comment by lingniao2000** [comment]
现状：
线上系统有一张表A，里面包含id,
owner_id,owner_type,va_id等，里面发现有若干掉重复记录，也就是除了id，不一样，其他很多字段都一样。
导入到mycat分片表B，分片规则是mod_long 。为了防止重复记录导入到mycat，在mycat分表里面建了包含6个字段的一个唯一索引。
这条语句导出
mysqldump -h127.0.0.1 -uxxx -pxxx -P3306 db A  --single-transaction
--skip-add-locks -c  -t  >A_20160830.sql
这样导入
(echo "set session sql_log_bin=0;"; cat A_20160906.sql) | mysql -f
-h11.1.1..1 -uxxx -pxxx -P3306 db > duplicate.log>&1
然后在重复日志里发现若干重复行的告警，在原表和mycat表对比着几条重复记录，发现部分重复记录导入到mycat一行，部分记录完全就没有了。
debug日志似乎没有看到什么信息(日志太大)
数据类似这样:
id owner_id owner_type user_id bo_id is_vip va_id original_principal
price_principal price_interest price price_punish plan_time success_time
is_pay owner_rate is_lender expect_num ba_transfer ba_is_transfer version
create_time update_time
211593142 816139 2 408979 21699 1 3392 0 4.03 0.42 4.44 0 2014/10/1 2014/10/2
01:25 1 1 0 3 0 0 1 2015/6/1 00:53 2016/8/31 10:18
6456253 408979 1 408979 21699 1 3392 0 4.03 0.42 4.44 0 2014/10/1 2014/10/2
01:25 1 1 0 3 0 0 1 2015/6/1 00:53 2016/8/31 10:18

2016-09-09 17:14 GMT+08:00 CrazyPig <notifications@github.com>:

**Comment by lingniao2000** [comment]
我现在换成了单行insert 语句在导入， 还没有导入完， 检查了一些重复行，看起来是没有丢数据。只是超级慢

在 2016年9月9日 下午5:56，Lingniao.Li <lingniao@gmail.com>写道：

**Comment by lingniao2000** [comment]
hi,各位，我分别用多行insert和单行insert导入数据
唯一索引爆出来的数量差非常多,比如多行insert
ERROR 1105 (HY000) at line 682: Duplicate entry '109540-1-109540-11937-1941-2014-06-08' for key 'uniq_mycat'
ERROR 1105 (HY000) at line 731: Duplicate entry '408979-1-408979-21699-3392-2014-10-01' for key 'uniq_mycat'
ERROR 1105 (HY000) at line 11232: Duplicate entry '1435307-1-1435307-481666-0-2016-03-16' for key 'uniq_mycat'
ERROR 1105 (HY000) at line 37031: Duplicate entry '438506-2-108064-11937-1938-2014-06-08' for key 'uniq_mycat'
ERROR 1105 (HY000) at line 37080: Duplicate entry '776060-2-107851-21723-4825-2016-01-01' for key 'uniq_mycat'
ERROR 1105 (HY000) at line 47667: Duplicate entry '1301552-2-1435307-481666-0-2016-03-16' for key 'uniq_mycat' 

而单行导入的话，duplicate entry比这个数量多很多的。

多行insert情况，我猜测只要报一个duplicate，那么这个多行里面的所有行，可能都导入不进去，导致了数据丢失

**Comment by magicdoom** [comment]
你其中有重复数据  肯定就异常了     这个不算bug

**Comment by lingniao2000** [comment]
是的，我晕了，今天在mysql里面测试了一下，结果也是一样的，有重复数据，整个insert语句都会回滚。

mysql> INSERT INTO travelrecord (id, user_id, traveldate, fee, days) VALUES ('1', '001', '2016-10-10 10:10:10', '1', '1');
Query OK, 1 row affected, 1 warning (0.01 sec)

mysql> INSERT INTO travelrecord (id, user_id, traveldate, fee, days) VALUES ('2', '002', '2016-11-11 11:11:11', '2', '2');
Query OK, 1 row affected, 1 warning (0.01 sec)

mysql> INSERT INTO travelrecord (id, user_id, traveldate, fee, days) VALUES ('3', '003', '2016-11-11 11:11:11', '3', '3'),('1', '001', '2016-10-10 10:10:10', '1', '1');
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
mysql>  select * from travelrecord;
+----+---------+------------+------+------+
| id | user_id | traveldate | fee  | days |
+----+---------+------------+------+------+
|  1 | 001     | 2016-10-10 |    1 |    1 |
|  2 | 002     | 2016-11-11 |    2 |    2 |
+----+---------+------------+------+------+
2 rows in set (0.00 sec)                    

一条重复，4条只能插入两条 .
