### ISSUE TITLE
读写分离环境下，如果主从延迟超出阈值slaveThreshold，现在筛选从库的条件有问题。

### ISSUE THREAD

**Issue by Xing1214** [MyCATApache/Mycat-Server#1111]
读写分离场景下，主从延迟超出阈值slaveThreshold，则从库不参与此次的负载均衡，但是在选择从库的时候判断条件是(SlaveThreshold!=-1&&switchType==2)的情况下才会去筛选从库。但其实，在读写分离场景中本来就跟切换无关，只关心延迟阈值，如果超出阈值则将超出阈值的从库踢出。不知道这样想对不对？

**Comment by magicdoom** [comment]
不对   这有2是根据延迟阈值来切换的       其他的是另外的切换方式   看权威指南

**Comment by Xing1214** [comment]
不切换的状态就不关心主从延迟时间吗？
