### ISSUE TITLE
不切换的情况下，就不关心主从同步延迟时间吗？

### ISSUE THREAD

**Issue by Xing1214** [MyCATApache/Mycat-Server#1114]
如果我的场景是不切换switchType=-1但是slaveThreshold=1，开启读写分离balance=1，现在我主从同步一主两从中其中一个从库S1的secondBehindMaster=20，S2正常那在这个时候我有一条查询语句，s1还参与这次的负载均衡吗？

**Comment by magicdoom** [comment]
切换和读写分离是2马事         都说了有几种切换方式     只有一种是根据延迟时间来的    另外还有集群、直接切等    自己看看指南吧

**Comment by Xing1214** [comment]
@magicdoom,现在就是在说读写分离场景不关心延迟时间吗？
