### ISSUE TITLE
TextParsingException错误

### ISSUE THREAD

**Issue by fuzzywy** [MyCATApache/Mycat-Server#1125]
用mycat入库的时候出现这个错误
09/26 16:01:58.958  ERROR [$_NIOREACTOR-3-RW] (FrontendConnection.java:270) -load data error
com.univocity.parsers.common.TextParsingException: Error processing input: Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096). 

SQL语句是load data local infile into xxx

请问4096这个阀值是怎么 设置的 ？

**Comment by magicdoom** [comment]
新版1.6已经修改大了   如果你还是出错这个错  可能是解析出错了

**Comment by fuzzywy** [comment]
谢谢 ，我使用的版本是1.5.1-RELEASE

**Comment by magicdoom** [comment]
可以通过设置包含字符 分隔字符   转义等选项试试  如果还有问题  去群里找南哥
