### ISSUE TITLE
Error: Could not find or load main class demo.catlets.XmlToYaml

### ISSUE THREAD

**Issue by icloudsun** [MyCATApache/Mycat-Server#1129]
MyCat .16 beta

[root@story-serv-t03-spark-master bin]# pwd
/data/mycat/mycat-1.6-beta/bin
[root@story-serv-t03-spark-master bin]# ./xml_to_yaml.sh
check JAVA_HOME & java
---------set HOME_DIR------------
Error: Could not find or load main class demo.catlets.XmlToYaml
---------finished------------

请问demo.catlets.XmlToYaml这个class在哪里？

**Comment by magicdoom** [comment]
包名改过了
