### ISSUE TITLE
多表配置问题

### ISSUE THREAD

**Issue by yayaw** [MyCATApache/Mycat-Server#113]
如何实现，不分片的表，默认走指定的datanode

**Comment by apachemycat** [comment]
若绝大多数表不分片，可以增加一个Schema（逻辑库），指定dataNode ，里面不配置任何表，则这个Schema就是默认不分片的
	<schema name="mydatabase" checkSQLschema="false" dataNode="dn1"  sqlMaxLimit="100">
         </schema>

server.xml里面增加上述Sechema的授权

<user name="test">
		<property name="password">test</property>
		<property name="schemas">TESTDB,mydatabase</property>
	</user>

此时访问 mydatabase就不走分片
mysql -utest -ptest  -h127.0.0.0  -Dmydatabase

**Comment by yayaw** [comment]
哪我其不是，有二个DATABASE了，前端应用，不是得改了吗？

**Comment by apachemycat** [comment]
HA Datasource这个JDBC连接池可以解决你的问题

**Comment by mycatmerger** [comment]
1.4已经实现配置默认节点
