### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLNoTransientConnectionException:connectionRefused. 

### ISSUE THREAD

**Issue by CCMBChina** [MyCATApache/Mycat-Server#1130]
在1.4 release版本碰见这个错，com.mysql.jdbc.exceptions.jdbc4.MySQLNoTransientConnectionException:connectionRefused，并且经常遇见，请问有已知的应用问题吗？账号密码以及表库权限应该无错

**Comment by magicdoom** [comment]
可能是比如密码配置错了  然后心跳检测一直在跑    触发后端db的拒绝了
