### ISSUE TITLE
测试sequence报错

### ISSUE THREAD

**Issue by dingding2015** [MyCATApache/Mycat-Server#114]
我在dn1上创建自增表MYCAT_SEQUENCE
CREATE TABLE MYCAT_SEQUENCE ( name VARCHAR(50) NOT NULL, current_value INT NOT NULL, increment INT NOT NULL DEFAULT 100, PRIMARY KEY (name) ) ENGINE=InnoDB;
INSERT INTO MYCAT_SEQUENCE(name,current_value,increment) VALUES ('GLOBAL', 0, 100);
按照文档中的设置创建了三个函数
启用了server.xml中的1
sequence_db_conf.properties 中增加了GLOBAL=dn1
schema.xml中增加了table name="MYCAT_SEQUENCE" primaryKey="name" dataNode="dn1"

在mycat中执行SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');报如下错误：
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo7.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo4.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo3.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo5.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo2.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo4.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo3.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
ERROR 1305 (42000): FUNCTION pdinfo2.MYCAT_SEQ_NEXTVAL does not exist
mysql> SELECT MYCAT_SEQ_NEXTVAL('GLOBAL');
+-----------------------------+
| MYCAT_SEQ_NEXTVAL('GLOBAL') |
+-----------------------------+
| 101,100 |
+-----------------------------+
1 row in set (0.05 sec)

**Comment by dingding2015** [comment]
测试版本是1.3.0.2

**Comment by apachemycat** [comment]
参考Mycat IN Action文档，里面有关于数据库方式的Sequence的创建办法，有一个SQL脚本，需要在数据库执行 ，FUNCTION pdinfo7.MYCAT_SEQ_NEXTVAL does not exist 就表明没有执行过SQL

**Comment by linzhiqiang0514** [comment]
请确认是否已经执行SQL?问题是否已解决 ？

**Comment by dingding2015** [comment]
确认该SQL已经在mysql中执行了

**Comment by dingding2015** [comment]
确认那个SQL脚本已经在数据库中执行了，并且有三个function生成

**Comment by Brochen** [comment]
请确认那三个函数是创建在哪个用户下面，文档里是在root用户下面，然后在确认下mycat中配置的用户对这3个函数是否有访问权限

**Comment by dingding2015** [comment]
文档中配置的mycat账户拥有全局权限，使用mycat账户创建的

**Comment by Brochen** [comment]
能否把你的schema.xml贴出来看一下

**Comment by dingding2015** [comment]
可否QQ沟通？

**Comment by dingding2015** [comment]
该问题通过测试正常了，是我的使用方法不正确，查询的时候应该是：
select next value for MYCATSEQ_GLOBAL;
