### ISSUE TITLE
mycat 计算 decimal 精度不稳定

### ISSUE THREAD

**Issue by lingniao2000** [MyCATApache/Mycat-Server#1142]
我们的表字段定义是decimal(18,2) ，但是计算出来的值小数点后面有14位
mysql> SELECT sum(price_principal),sum(price_interest),sum(price_punish) FROM borrows_accept WHERE plan_time='2016-08-10' AND bo_id=712571 AND owner_type=1;
+--------------------+--------------------+--------------------+
| SUM0               | SUM1               | SUM2               |
+--------------------+--------------------+--------------------+
| 236.67999999999995 | 29.719999999999995 | 16.229999999999997 |
+--------------------+--------------------+--------------------+
1 row in set (0.13 sec)

mysql> SELECT sum(price_principal),sum(price_interest),sum(price_punish) FROM borrows_accept WHERE plan_time='2016-08-10' AND bo_id=712571 AND owner_type=1;
+--------------------+--------------------+-------+
| SUM0               | SUM1               | SUM2  |
+--------------------+--------------------+-------+
| 236.67999999999995 | 29.719999999999995 | 16.23 |
+--------------------+--------------------+-------+
1 row in set (0.10 sec)

mysql> SELECT sum(price_principal),sum(price_interest),sum(price_punish) FROM borrows_accept WHERE plan_time='2016-08-10' AND bo_id=712571 AND owner_type=1;
+--------------------+-------+-------+
| SUM0               | SUM1  | SUM2  |
+--------------------+-------+-------+
| 236.67999999999998 | 29.72 | 16.23 |
+--------------------+-------+-------+
1 row in set (0.05 sec)

**Comment by ZzzCrazyPig** [comment]
可以给出在mysql上的计算精度么？还有你的mycat用的什么版本?

**Comment by lingniao2000** [comment]
mycat1.5。mysql就是设定的两位数啊，decimal(18.2)


发自我的 iPhone

**Comment by ZzzCrazyPig** [comment]
你上面的执行的3个sql是在mycat上面执行的么?

**Comment by lingniao2000** [comment]
是的，连续执行


发自我的 iPhone

**Comment by ZzzCrazyPig** [comment]
那给一下单独在mysql上执行的结果吧？我想看看mysql对精度计算的规律是否跟我猜想的一样，最近我们也在修复这个问题。

**Comment by lingniao2000** [comment]
我测过了，mysql就是正常的精度，decimal(18,2) sum后小数就是两位，这个很简单，随便测试一下就能复现


发自我的 iPhone

**Comment by ZzzCrazyPig** [comment]
哦，抱歉，跟avg混了，avg的精度在mysql的实现上应该有一定的规律，据我观察，应该是sum结果的精度 + 4 (指小数点)
