### ISSUE TITLE
使用reload @@config 重新加载配置文件后，但是Mycat不生效

### ISSUE THREAD

**Issue by feiyeWine** [MyCATApache/Mycat-Server#1146]
版本为mycat 1.5
![image](https://cloud.githubusercontent.com/assets/12509102/19269725/c48cbe02-8fee-11e6-9c01-bd75808ee3f5.png)

![image](https://cloud.githubusercontent.com/assets/12509102/19269852/53984346-8fef-11e6-9e59-3ee2d74aa011.png)

并未热加载成功

重启mycat后，配置生效

请问这是什么问题？

**Comment by magicdoom** [comment]
测试下1.6看看

**Comment by zhuam** [comment]
1.5 热更新有BUG， 使用1.6

**Comment by magicdoom** [comment]
请提交具体配置   并验证1.6

**Comment by magicdoom** [comment]
如果跟数据源有关配置改过   需要用reload_all命令
