### ISSUE TITLE
user_id使用的UUID，使用哪种分片规则好？

### ISSUE THREAD

**Issue by shantianxia** [MyCATApache/Mycat-Server#1148]
user_id为UUID，例如0c7f5fb260784ec7a7a3d96232775b90，0dfebc64b04b4251b57bb329d693ac11，0febede57c43450b9c93f58cba69fbfb，这样的字段使用哪种分片规则好？

**Comment by magicdoom** [comment]
支持字符串的都可以 比一致性哈希分片
