### ISSUE TITLE
mycat批量更新

### ISSUE THREAD

**Issue by lakersh3** [MyCATApache/Mycat-Server#1149]
最近遇到的问题，发现1.5和1.6版本都会出现问题。当执行1个批量更新后，例如拼写100个下面的语句update table_1 set column_1 = 1 where 1=1 and condition_1=1  ;然后1条sql发送给mycat，下来当再执行别的查询语句时，就报错Caused by: java.sql.SQLException: ResultSet is from UPDATE. No Data。同一个方法内的调用，spring做的事务管理，后端采用的是mysql。
    当不使用mycat，直接连mysql就不报错

**Comment by magicdoom** [comment]
调用程序  日志等发完整点

**Comment by lakersh3** [comment]
mycat获取连接后,首先开启一个事务（con.setAutoCommit(false)），然后执行批量更新语句，例如一堆update语句，分号隔开，下面再执行查询语句，最后提交（con.commit()）。
发现报错，错误信息。
java.sql.SQLException: ResultSet is from UPDATE. No Data.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6995)
	at test.TestMycat.main(TestMycat.java:40)

**Comment by lakersh3** [comment]
具体代码，如下。使用的是1.6版本，mysql数据库

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class TestMycat {
		// JDBC URL, username and password of MySQL server
	  private static final String url = "jdbc:mysql://127.0.0.1:8066/mycat_data";
	  private static final String user = "hap";
	  private static final String password = "123456";
	  // JDBC variables for opening and managing connection
	  private static Connection con;
	  private static Statement stmt;
	  private static ResultSet rs;
	public static void main(String[] args) {
		
		String tmpSql="update sy_tenant set updated_by=1000 where tenantpk=";
		StringBuffer sql=new StringBuffer();
		for(Long i=20000060001l;i<=20000060050l;i++){
			sql.append(tmpSql).append(i).append(";");
		}
		sql.deleteCharAt(sql.length()-1);
		
		String query = "select count(*) from sy_user";
	    try {
	      // opening database connection to MySQL server
	      con = DriverManager.getConnection(url, user, password);
	      
	      con.setAutoCommit(false);
	      
	      // getting Statement object to execute query
	      stmt = con.createStatement();
	      stmt.executeUpdate(sql.toString());
	      
	      // executing SELECT query
	      rs = stmt.executeQuery(query);
	      while (rs.next()) {
	        int count = rs.getInt(1);
	        System.out.println("Total number of books in the table : " + count);
	      }
	      System.out.println("xxx");
	      con.commit();
	    } catch (SQLException sqlEx) {
	      sqlEx.printStackTrace();
	    } finally {
	      //close connection ,stmt and resultset here
	      try { con.close(); } catch(SQLException se) { /*can't do anything */ }
	      try { stmt.close(); } catch(SQLException se) { /*can't do anything */ }
	      try { rs.close(); } catch(SQLException se) { /*can't do anything */ }
	    }
	}
}

**Comment by lakersh3** [comment]
具体代码如下，使用的是1.6版本，mysql数据库

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class TestMycat {
		// JDBC URL, username and password of MySQL server
	  private static final String url = "jdbc:mysql://127.0.0.1:8066/mycat_data";
	  private static final String user = "root";
	  private static final String password = "123456";
	  // JDBC variables for opening and managing connection
	  private static Connection con;
	  private static Statement stmt;
	  private static ResultSet rs;
	public static void main(String[] args) {
		
		String tmpSql="update test_a set updated_by=1000 where fieldpk=";
		StringBuffer sql=new StringBuffer();
		for(Long i=20000060001l;i<=20000060050l;i++){
			sql.append(tmpSql).append(i).append(";");
		}
		sql.deleteCharAt(sql.length()-1);
		
		String query = "select count(*) from test_b";
	    try {
	      // opening database connection to MySQL server
	      con = DriverManager.getConnection(url, user, password);
	      
	      con.setAutoCommit(false);
	      
	      // getting Statement object to execute query
	      stmt = con.createStatement();
	      stmt.executeUpdate(sql.toString());
	      
	      // executing SELECT query
	      rs = stmt.executeQuery(query);
	      while (rs.next()) {
	        int count = rs.getInt(1);
	        System.out.println("Total number of books in the table : " + count);
	      }
	      System.out.println("xxx");
	      con.commit();
	    } catch (SQLException sqlEx) {
	      sqlEx.printStackTrace();
	    } finally {
	      //close connection ,stmt and resultset here
	      try { con.close(); } catch(SQLException se) { /*can't do anything */ }
	      try { stmt.close(); } catch(SQLException se) { /*can't do anything */ }
	      try { rs.close(); } catch(SQLException se) { /*can't do anything */ }
	    }
	}
}

**Comment by ZzzCrazyPig** [comment]
不要使用拼接，使用`PrepareStatement`的`addBatch`和`executeBatch`来实现批量写

**Comment by ZzzCrazyPig** [comment]
最后发往mycat的批量insert形式应该如下

```sql
insert into tablename(col1,col2,...) values (...) , (...) , (...) , ...;
```

**Comment by lakersh3** [comment]
insert和delete的批量都没有问题，现在是update时会有错，使用PrepareStatement的addBatch和executeBatch时发送到mycat的update语句就是拼接的，所以会出现错误。

**Comment by lakersh3** [comment]
insert和delete的批量都没有问题，现在是update时会有错。我使用了PrepareStatement的addBatch和executeBatch时，但在mysql-connector-java-5.1.39.jar中PreparedStatement类会处理sql，将update sql进行了拼接，然后发送到mycat的update语句就是拼接的，这样出现了错误。这个该怎么解决好？

**Comment by lakersh3** [comment]
如果jdbcUrl如下jdbc:mysql://10.21.17.201:3316/mycat?rewriteBatchedStatements=true，加上rewriteBatchedStatements参数后，批量更新时就会拼写出一长串update语句（以分号分隔），发送到mycat执行后，如果同一事物内还有其他的执行语句，就会报错。java.sql.SQLException: ResultSet is from UPDATE. No Data.

**Comment by magicdoom** [comment]
目前不支持一次发多个语句拼接     所以rewriteBatchedStatements这个参数暂时不支持
