### ISSUE TITLE
1.5mycat不支持savepoint 

### ISSUE THREAD

**Issue by Duntian** [MyCATApache/Mycat-Server#1155]
mycat 为1.5 mysql 为5.7

 begin;  
select update_time from pt_user where id=1;  
update pt_user set update_time = now()  where id=1;  
select update_time from pt_user where id=1;  
SAVEPOINT book1;  
select update_time from pt_user where id=1;  
update pt_user set update_time = now()-1000  where id=1;  
select update_time from pt_user where id=1;  
rollback to book1;  
select update_time from pt_user where id=1;  
rollback;  
select update_time from pt_user where id=1;   

在执行到rollback to book1 时，报错Transaction error, need to rollback. errno:1064

**Comment by magicdoom** [comment]
savepoint应该不支持     特别是后端 涉及到了多个节点

**Comment by magicdoom** [comment]
暂时不考虑支持，如果有志愿者愿意实现也可以
