### ISSUE TITLE
mycat配置一主一从，主停掉以后，select语句都不能执行了

### ISSUE THREAD

**Issue by wdw1206** [MyCATApache/Mycat-Server#116]
问题：mycat配置了一主一从，主使用service mysql stop停掉以后，select语句也无法执行了。

mycat服务端日志不停地报错：
01-26 14:04:11.416   INFO [$_NIOConnector] (AbstractConnection.java:386) -close connection,reason:hearbeat connecterr ,[thread=$_NIOConnector,class=MySQLDetector,host=172.17.209.103,port=3306,localPort=0,schema=null]
01-26 14:04:12.417   INFO [$_NIOConnector] (AbstractConnection.java:386) -close connection,reason:hearbeat connecterr ,[thread=$_NIOConnector,class=MySQLDetector,host=172.17.209.103,port=3306,localPort=0,schema=null]
01-26 14:04:13.417   INFO [$_NIOConnector] (AbstractConnection.java:386) -close connection,reason:hearbeat connecterr ,[thread=$_NIOConnector,class=MySQLDetector,host=172.17.209.103,port=3306,localPort=0,schema=null]

执行select * from travelrecord语句报错
[Err] 1003 - Connection refused: no further information

**Comment by wdw1206** [comment]
目前的机制必须配置M-M才能使用。所以建议：只有两台机器的时候，配置成双主，如下
<dataHost name="dn1_Host" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="native">
        <heartbeat>select user()</heartbeat>
        <writeHost host="dn1_Host_m1" url="172.17.xxx.xxx:3306" user="user1" password="password1"/>	
        <writeHost host="dn1_Host_m2" url="172.17.xxx.xxx:3306" user="user1" password="password1"/>
    </dataHost>

**Comment by linzhiqiang0514** [comment]
原来Mycat的Action文档里面有句话，就是w节点当掉后，它所带的read节点，可能都会认为失效，因为会有数据不一致的风险。
