### ISSUE TITLE
对于生产上的表如果分区字段不是默认的ID,该怎么改写RULE.XML

### ISSUE THREAD

**Issue by aiaix** [MyCATApache/Mycat-Server#1171]

**Comment by aiaix** [comment]
<tableRule name="mod-long">
                <rule>
                        <columns>id</columns>
                        <algorithm>mod-long</algorithm> 比如默认是ID列分区，那么如果我的表有的是ID1 ,有得是ID2，该怎么写？？

**Comment by magicdoom** [comment]
你是什么列  clolumns里面就写什么列名    多个表就配置多个rule
