### ISSUE TITLE
ERROR 3009 (HY000): java.lang.IllegalArgumentException: Invalid DataSource:0 

### ISSUE THREAD

**Issue by terry19850829** [MyCATApache/Mycat-Server#1184]
1.基本信息
CentOS release 6.5 (Final) 虚拟机 和 win7 x64 混合 postgresql作为db的环境
java version "1.7.0_79"
mycat 1.5 部署在宿主机win7上

10.99.9.155:5432 宿主机PG
10.99.8.167:5432 虚拟机PG

2.mycat配置

      <mycat:schema xmlns:mycat="http://org.opencloudb/" >

	<schema name="orderDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="order" dataNode="dn1,dn2" rule="mod-long" /> 
	</schema>

	<dataNode name="dn1" dataHost="host1" database="order_db" />
	<dataNode name="dn2" dataHost="host2" database="order_db" />

	<dataHost name="host1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="mysql" dbDriver="native" switchType="1">
		<heartbeat>select user;</heartbeat>
		<writeHost host="hostM1" url="10.99.9.155:5432" user="postgres" password="123456">
		</writeHost>
	</dataHost>

	<dataHost name="host2" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="mysql" dbDriver="native" switchType="1">
		<heartbeat>select user;</heartbeat>
		<writeHost host="hostM2" url="10.99.8.167:5432" user="postgres" password="123456">
		</writeHost>
	</dataHost>

    </mycat:schema>

3.问题现象

mysql客户端能够正常连接
show databases ；正常 orderDB
use orderDB;正常
建表语句 create table `order`(`id` int(11) not null,primary key(`id`));
直接报错：ERROR 3009 (HY000): java.lang.IllegalArgumentException: Invalid DataSource:0 

今天刚开始玩Mycat， 请大牛帮忙解答下。查了下官网权威指南，没有postgresql的相关解决方案，
postgresql需要有什么特殊的配置，还是说我本身的配置有问题？

**Comment by brotherbin** [comment]
`dbType`和`dbDriver`不应该设置成mysql的，但是权威指南上没具体写postgresql怎么配，可能是对postgresql的支持还在完善中，尝试换成1.6版本改配置dbType="postgresql" dbDriver="jdbc"试试

**Comment by terry19850829** [comment]
@brotherbin 好的，我先尝试下。主要是权威指南上确实没有提到，然后在网上查了些文档发现都是配置了mysql。

**Comment by terry19850829** [comment]
@brotherbin  还有那个测试心态的函数 pg的方法是select user; mysql 是select user(); 这个还是应该按照自己后端使用的具体的数据库吧？

**Comment by terry19850829** [comment]
引述权威指南里面的原话:

    从1.6版本开始支持postgresql的native原始协议。
如果使用JDBC的话需要将符合JDBC 4标准的驱动JAR包放到MYCAT\lib目录下，并检查驱动JAR包中包括如下目录结构的文件：META-INF\services\java.sql.Driver。在这个文件内写上具体的Driver类名，例如：com.mysql.jdbc.Driver。

**Comment by terry19850829** [comment]
@brotherbin  换了1.6 win下装服务貌似不行了。不过可以使用start_nowrapper.bat启动  目前看来在连PG
但是由于我的两台机器数据不同，现在心跳检查一直会报 database "bill" not exist。我一台机器有bill数据库，一台没有。这个是1.6 默认有什么检查嘛？

**Comment by terry19850829** [comment]
@brotherbin  附上前面部分的日志，mycat是启动成功了
`2016-11-02 11:13:19,376 [INFO ][Timer0] create connections ,because idle connection not enough ,cur
is 0, minCon is 10 for hostM2  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.ja
va:299)
MyCAT Server startup successfully. see logs in logs/mycat.log
2016-11-02 11:13:28,379 [WARN ][BusinessExecutor7] JDBCConnection [id=23,autocommit=true,pool=io.myc
at.backend.jdbc.JDBCDatasource@4f801872, schema=order_db, dbType=POSTGRESQL, oldSchema=null, packetI
d=0, txIsolation=0, running=false, borrowed=false, host=10.99.8.167, port=5432, con=null, respHandle
r=null, attachement=null, headerOutputed=false, modifiedSQLExecuted=false, startTime=1478056399377,
lastTime=0, isSpark=false, processor=io.mycat.net.NIOProcessor@10c000b6] connectionError org.postgre
sql.util.PSQLException: FATAL: database "bill" does not exist  (io.mycat.backend.mysql.nio.handler.N
ewConnectionRespHandler:NewConnectionRespHandler.java:37)’`

**Comment by terry19850829** [comment]
@brotherbin 附上连接成功的日志
`2016-11-02 11:13:19,275 [INFO ][BusinessExecutor3] connected successfuly JDBCConnection [id=17,autoc
ommit=true,pool=io.mycat.backend.jdbc.JDBCDatasource@5dc4d0d2, schema=order_db, dbType=POSTGRESQL, o
ldSchema=null, packetId=0, txIsolation=0, running=false, borrowed=true, host=10.99.9.155, port=5432,
 con=org.postgresql.jdbc4.Jdbc4Connection@2fe19787, respHandler=null, attachement=null, headerOutput
ed=false, modifiedSQLExecuted=false, startTime=1478056399172, lastTime=1478056399275, isSpark=false,
 processor=io.mycat.net.NIOProcessor@76e1e924]  (io.mycat.backend.mysql.nio.handler.GetConnectionHan
dler:GetConnectionHandler.java:67)
2016-11-02 11:13:19,279 [INFO ][BusinessExecutor2] connected successfuly JDBCConnection [id=20,autoc
ommit=true,pool=io.mycat.backend.jdbc.JDBCDatasource@5dc4d0d2, schema=order_db, dbType=POSTGRESQL, o
ldSchema=null, packetId=0, txIsolation=0, running=false, borrowed=true, host=10.99.9.155, port=5432,
 con=org.postgresql.jdbc4.Jdbc4Connection@3a338a0, respHandler=null, attachement=null, headerOutpute
d=false, modifiedSQLExecuted=false, startTime=1478056399173, lastTime=1478056399279, isSpark=false,
processor=io.mycat.net.NIOProcessor@418ce895]  (io.mycat.backend.mysql.nio.handler.GetConnectionHand
ler:GetConnectionHandler.java:67)`

**Comment by terry19850829** [comment]
目前建表是不成功的：
`2016-11-02 11:45:23,719 [WARN ][$_NIOREACTOR-1-RW] ServerConnection [id=1, schema=orderDB, host=0:0:
0:0:0:0:0:1, user=test,txIsolation=3, autocommit=true, schema=orderDB]create table `order`(`id` int(
11) not null), route={
   1 -> dn1{create table `order`(`id` int(11) not null)}
   2 -> dn2{create table `order`(`id` int(11) not null)}
} java.lang.IllegalArgumentException: Invalid DataSource:0
        at io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:140)
        at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.execute(MultiNodeQueryHandler.ja
va:184)
        at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:149)
        at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:288)
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136)
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
        at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
        at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
        at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
        at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
        at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
        at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
        at java.lang.Thread.run(Thread.java:745)
 (io.mycat.server.NonBlockingSession:NonBlockingSession.java:153)`

**Comment by terry19850829** [comment]
@brotherbin  目前通过在另外一边新建bill数据库 解决，但是 两边的数据库差异并不止bill，不知道具体原因。 

后端如果是postgresql的话，建表之类的语法需要怎么使用？ 因为连接mycat使用的是mysql的客户端。还是要需要用postgresql的客户端连接？？

**Comment by brotherbin** [comment]
看了源码里作者注释的配置方法是
`dbType="PostgreSQL" dbDriver="native"`
抱歉我给的不对，再这样试试
[https://github.com/MyCATApache/Mycat-Server/blob/1.6/src/main/java/io/mycat/backend/postgresql/package-info.java](https://github.com/MyCATApache/Mycat-Server/blob/1.6/src/main/java/io/mycat/backend/postgresql/package-info.java)

**Comment by brotherbin** [comment]
Mycat只能用MySQL客户端连接

**Comment by terry19850829** [comment]
@brotherbin  这个jdbc的方式也是可以连接的，日志显示已经连接上了。但是没法建表？ 你这边有使用过PG嘛 因为我这边暂时是想试下mycat是否可以作为我们公司的分布式数据库中间件，还没去看过源码。麻烦朋友了 =。=

**Comment by terry19850829** [comment]
@brotherbin  我去，我太蠢了，那个JDBC的连接 我指定了bill库。。。 郁闷了。我再试下native的方式

**Comment by terry19850829** [comment]
@brotherbin  按照你的已经配置成功了。 想问下如果使用PG的话 我msyql客户端连接以后，建表的语法应该按照mysql吧？

`mysql> CREATE TABLE `order`(
    -> `id` int(11) NOT NULL,
    -> `price` varchar(20) NOT NULL,
    -> `gmt_create` timestamp(6) DEFAULT now(),
    -> `gmt_modified` timestamp(6) DEFAULT now(),
    -> `status` varchar(2)
    -> );
ERROR 1105 (HY000): OR C42601 Msyntax error at or near "(" P103 Fscan.l L1005 Rscanner_yyerror`

**Comment by terry19850829** [comment]
@brotherbin 成功建表了，可能和语法有关。我再看看。。。 谢谢朋友帮忙解决了。

`CREATE TABLE `order` 
( `id` INT NOT NULL,
`price` varchar(20) NOT NULL,
`gmt_create` timestamp(6) DEFAULT now(),
`gmt_modified` timestamp(6) DEFAULT now(),
`status` varchar(2)
)`

**Comment by terry19850829** [comment]
贴个正确配置再这里：

`<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="orderDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="order" dataNode="dn1,dn2" rule="mod-long" /> 
	</schema>

	<dataNode name="dn1" dataHost="host1" database="order_db" />
	<dataNode name="dn2" dataHost="host2" database="order_db" />

	<dataHost name="host1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="Postgresql" dbDriver="native" switchType="1">
		<heartbeat>select user</heartbeat>
		<writeHost host="hostM1" url="10.99.9.155:5432" user="postgres" password="123456">
		</writeHost>
	</dataHost>

	<dataHost name="host2" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="Postgresql" dbDriver="native" switchType="1">
		<heartbeat>select user</heartbeat>
		<writeHost host="hostM2" url="10.99.8.167:5432" user="postgres" password="123456">
		</writeHost>
	</dataHost>

</mycat:schema>`
