### ISSUE TITLE
mybatis 连接mycat 中文乱码的问题

### ISSUE THREAD

**Issue by terry19850829** [MyCATApache/Mycat-Server#1185]
1.基本信息
CentOS release 6.5 (Final) 虚拟机 和 win7 x64 混合 postgresql作为db的环境
java version "1.7.0_79"
mycat 1.6 部署在宿主机win7上

10.99.9.155:5432 宿主机PG
10.99.8.167:5432 虚拟机PG

2.mycat配置

    <mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="orderDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="order" primaryKey="id" dataNode="dn1,dn2" rule="mod-long" /> 
		<table name="order_status" primaryKey="id" dataNode="dn1,dn2" type="global" rule="mod-long"/>
	</schema>

	<dataNode name="dn1" dataHost="host1" database="order_db" />
	<dataNode name="dn2" dataHost="host2" database="order_db" />

	<dataHost name="host1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="Postgresql" dbDriver="native" switchType="1">
		<heartbeat>select user</heartbeat>
		<writeHost host="hostM1" url="10.99.9.155:5432" user="postgres" password="123456">
		</writeHost>
	</dataHost>

	<dataHost name="host2" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="Postgresql" dbDriver="native" switchType="1">
		<heartbeat>select user</heartbeat>
		<writeHost host="hostM2" url="10.99.8.167:5432" user="postgres" password="123456">
		</writeHost>
	</dataHost>

     </mycat:schema>

3.问题现象

mysql客户端连接，操作，建表无任何问题。但是用mybatis进行insert报乱码问题。

数据库驱动 *mysql-connector-java-5.1.35*

错误信息如下：

    `2016-11-02 15:29:34.306 ERROR 9552 --- [           main] com.alibaba.druid.pool.DruidDataSource   :   init datasource error, url: jdbc:mysql://localhost:8066/orderDB?useUnicode=true&characterEncoding=utf8

    java.sql.SQLException: 锟斤拷 C42601 M锟斤法锟斤拷锟斤拷 锟斤拷 "WHERE" 锟津附斤拷锟� P177 Fsrc\backend\parser\scan.l L1006 Rscanner_yyerror
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771) ~[mysql-connector-java-5.1.35.jar:5.1.35]`

mycat 端的日志：

```
2016-11-02 16:14:20,527 [WARN ][$_NIOREACTOR-4-RW] execute  sql err : errno:1105 误 C42601 M语法错误
 在 "WHERE" 或附近的 P177 Fsrc\backend\parser\scan.l L1006 Rscanner_yyerror con:PostgreSQLBackendCon
nection [id=20, host=10.99.9.155, port=5432, localPort=63249] frontend host:127.0.0.1/64148/test  (i
o.mycat.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:249)
```

通过客户端查看字符集编码：

mysql> show variables like '%char%';
```
`+--------------------------+---------------------+`
| VARIABLE_NAME            | VALUE               |
+--------------------------+---------------------+
| wait_timeout             | 172800              |
| system_time_zone         | CST                 |
| max_allowed_packet       | 16777216            |
| net_buffer_length        | 8192                |
| tx_isolation             | REPEATABLE-READ     |
| character_set_server     | utf8                |
| query_cache_size         | 0                   |
| net_write_timeout        | 60                  |
| init_connect             |                     |
| time_zone                | SYSTEM              |
| sql_mode                 | STRICT_TRANS_TABLES |
| character_set_results    | utf8                |
| query_cache_type         | OFF                 |
| character_set_client     | utf8                |
| interactive_timeout      | 172800              |
| lower_case_table_names   | 1                   |
| character_set_connection | utf8                |
+--------------------------+---------------------+
17 rows in set (0.00 sec)
```

都为UTF-8

mybatis连接信息：

```
spring.datasource.name=orderDB
spring.datasource.url=jdbc:mysql://localhost:8066/orderDB?characterEncoding=utf8
spring.datasource.username=test
spring.datasource.password=123456
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
```

mybatis mapper代码:

` @Insert("<script>" +
            "insert into `order`(id, status, price, gmt_create,gmt_modified) "
            + "values "
            + "(next value for MYCATSEQ_ORDER,#{order.status},#{order.price},now(),now()) "
            + "</script>") void insertOrder(@Param("order") Order order);`

sequence_conf配置：

```
ORDER.HISIDS=
ORDER.MINID=1
ORDER.MAXID=100000000
ORDER.CURID=0
```

后端posgresql服务器编码 UTF8

哪位朋友可以帮忙看看？

**Comment by magicdoom** [comment]
dbtype配错了

**Comment by terry19850829** [comment]
@magicdoom  这个 贴错了 我改下 。。。不好意思 连接已经成功了。表也能建

**Comment by terry19850829** [comment]
@magicdoom  顺便把 mybatis mapper的代码也附上了

**Comment by terry19850829** [comment]
@magicdoom  将两台PG 都部署到 linux服务器上 解决了乱码的问题。能够正常显示错误信息。
应该是win + linux 混合环境导致的。

目前是这个异常：

`Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: OR C42601 Msyntax error at or near "WHERE" P121 Fscan.l L1002 Rscanner_yyerror`

**Comment by terry19850829** [comment]
@brotherbin 有没有碰到过这个异常？
`java.sql.SQLException: OR C42601 Msyntax error at or near "WHERE" P177 Fscan.l L1005 Rscanner_yyerror`

**Comment by brotherbin** [comment]
@terry19850829 能不能捕捉到发到PG上的sql具体是什么，像是全局序列号没有解析出来导致语法错误，
确认下Mycat Sequence有配置好，`next value for MYCATSEQ_ORDER` 改成 `next value for MYCATSEQ_GLOBAL`试下，我看的文档是用这个标识

**Comment by terry19850829** [comment]
@brotherbin 使用next value for MYCATSEQ_GLOBAL 报同样的错误。感觉这个错误不是执行后端的PG上报出来的，我看看PG能不能查到执行的SQL。

**Comment by terry19850829** [comment]
@brotherbin sequenceHandlerType的配置如下：

`<property name="sequnceHandlerType">0</property>`

本地文件读取，应该没有问题的。。。

**Comment by terry19850829** [comment]
@brotherbin  这个错误是在建立连接的时候报的错，可能和SQL还无关，我在想是不是驱动版本的问题？

**Comment by terry19850829** [comment]
@brotherbin  jdbc 在建立连接的时候，jdbc驱动部分会执行下面这个查询，我这边是这个SQL直接异常了。查询代码如下：

`/* mysql-connector-java-5.1.35 ( Revision: 5fb9c5849535c13917c2cf9baaece6ef9693ef27 ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'license' OR Variable_name = 'init_connect'`

**Comment by brotherbin** [comment]
@terry19850829 这我有点爱莫能助了，不太熟PG

**Comment by terry19850829** [comment]
@brotherbin  大概原因找到了，是不是Postgresql 这块本身native不够成熟，在mysql下直接执行这个query，没有任何问题。在PG下where部分报语法错误。

**Comment by fireflyhoo** [comment]
SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'license' OR Variable_name = 'init_connect'

這個語法的 pg 不支持，請問這個是sql 是怎麽產生的

**Comment by fireflyhoo** [comment]
使用pg native 模式，只能用标准sql语法。

**Comment by terry19850829** [comment]
@fireflyhoo  
mysql-connector-java-5.1.35这个驱动 
com.mysql.jdbc.ConnectionImpl 3771行 private void loadServerVariables() throws SQLException 方法

3820 - 3834行代码入下：

```
if (versionMeetsMinimum(5, 0, 3)) {
                query = versionComment + "SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout'"
                        + " OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client'"
                        + " OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server'"
                        + " OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results'"
                        + " OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone'"
                        + " OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length'"
                        + " OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size'"
                        + " OR Variable_name = 'license' OR Variable_name = 'init_connect'";
            }

            this.serverVariables = new HashMap<String, String>();

            try {
                results = stmt.executeQuery(query);
```

**Comment by fireflyhoo** [comment]
342991688 加我QQ，

**Comment by terry19850829** [comment]
@fireflyhoo  这个SQL 不是我写的，是驱动内部自己拼接调用的，在建立连接的时候，是不是说我需要使用别的版本的驱动？因为没有任何文档说明这个事情。或者说我这边没查到

**Comment by fireflyhoo** [comment]
噢，后续做下适配。

**Comment by terry19850829** [comment]
@fireflyhoo  我在想是不是发到了后端的PG，导致的这个异常。不能确定 因为公司这边环境是我本地在玩。没有debug mycat，而且刚开始弄这个中间件，不熟。所以请各位大牛帮忙下了。
