### ISSUE TITLE
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: OR C42601 Msyntax error at or near "WHERE" P121 Fscan.l L1002 Rscanner_yyerror

### ISSUE THREAD

**Issue by terry19850829** [MyCATApache/Mycat-Server#1190]
1.  基本信息
JDK1.7 
mycat1.6  
PG * 2  版本9.1

使用Postgresql 的native协议

2.mycat配置

```
<mycat:schema xmlns:mycat="http://io.mycat/">

<schema name="orderDB" checkSQLschema="false" sqlMaxLimit="100">
	<table name="order" primaryKey="id" dataNode="dn1,dn2" rule="mod-long" /> <!-- primaryKey type  -->
	<table name="order_status" primaryKey="id" dataNode="dn1,dn2" type="global" rule="mod-long"/>
</schema>

<dataNode name="dn1" dataHost="host1" database="order_db" />
<dataNode name="dn2" dataHost="host2" database="order_db" />

<dataHost name="host1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="Postgresql" dbDriver="native" switchType="1">
	<heartbeat>select user</heartbeat>
	<writeHost host="hostM1" url="10.99.9.155:5432" user="postgres" password="123456">
	</writeHost>
</dataHost>

<dataHost name="host2" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="Postgresql" dbDriver="native" switchType="1">
	<heartbeat>select user</heartbeat>
	<writeHost host="hostM2" url="10.99.8.167:5432" user="postgres" password="123456">
	</writeHost>
</dataHost>

 </mycat:schema>
```

3.现象

mycat正常启动，mysql客户端连接正常，建表正常。
mybatis客户端连接，mysql驱动mysql-connector-java 5.1.35

在jdbc驱动建立与mycat连接的时候，底层会有一个查询：

`/* mysql-connector-java-5.1.35 ( Revision: 5fb9c5849535c13917c2cf9baaece6ef9693ef27 ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'license' OR Variable_name = 'init_connect'
`

导致直接报错。

该查询直接在mysql下执行无任何问题。
在PG下执行，也报相同的语法错误，是不是该查询直接发往了后台的PG？

**Comment by magicdoom** [comment]
这个语句mycat里面我记得是直接拦截到然后返回自己模拟的数据的

**Comment by terry19850829** [comment]
@magicdoom  已经和望舒沟通过，jdbc的方式做了兼容处理的。native目前是有问题的。我现在使用jdbc的方式已经跑起来了 这个issue我关掉吧。
