### ISSUE TITLE
mycat系统崩溃

### ISSUE THREAD

**Issue by rocker100** [MyCATApache/Mycat-Server#121]
系统大概运行了1个礼拜左右，有天晚上凌晨系统突然停止服务，后台所有数据库操作都报错

**Comment by yoyoch1** [comment]
补充版本号？那时具体执行了那些业务？执行的SQL又是啥？异常日志有否？方便伙伴们定位问题吧

**Comment by rocker100** [comment]
版本：Mycat-server-1.3-beta1 
业务：只用到一个读写分离功能，一个主库，一个从库
执行的SQL：主要是查询和插入，插入量还比较大，应该说整个数据库的压力还蛮大的
异常日志：我查看了一下mycat.log日志文件，好像没找到异常信息

![mycat](https://cloud.githubusercontent.com/assets/1681177/5930701/1fb059b2-a6ce-11e4-8a8a-fab40e0998f7.png)

**Comment by apachemycat** [comment]
从这个日志看，早上8点都是正常的，若没有重启Mycat，说明Mycat一直没有问题，另外建议用正式版，不要用比较旧的开发版。
