### ISSUE TITLE
wrapper.log日志输出异常，和mcyat.log日志重复

### ISSUE THREAD

**Issue by chenjing7232** [MyCATApache/Mycat-Server#1237]
【mycat版本信息】
BuildTime  2016-10-12 09:00:27
GitVersion   cacf0e792dc36682dcac849abd8cdef7b82f7c5d
MavenVersion 1.6-RELEASE
【问题描述】
在启动mycat后，发现wrapper.log输出日志很多，且大量日志是和mycat.log内容一样的，以下是wrapper.log的日志截图：
![clipboard](https://cloud.githubusercontent.com/assets/14304247/20509149/abbfcf8a-b0a1-11e6-81fd-462e0b211c0d.png)
![clipboard2](https://cloud.githubusercontent.com/assets/14304247/20509150/abca7ee4-b0a1-11e6-8c1f-3d3f98084b89.png)

**Comment by magicdoom** [comment]
1.6.5已结fix，1.6可以自己把log4j2.xml里面关于console的那行注释掉
