### ISSUE TITLE
Mycat 1.6无法执行mysqlbinlog解析出来的内容

### ISSUE THREAD

**Issue by wuyuanyong** [MyCATApache/Mycat-Server#1238]
#######
环境说明
OS:RHEL 6.4 x66_64
OS Kernal:2.6.32-358.el6.x86_64
MySQL: 5.6.29 社区版
binlog_format=row
mycat:1.6

###### 问题描述：
将5.6.29的binlog通过mysqlbinlog解析出来，然后通过Mycat追加到各个分片出现如下错误：
 [root@rac3 conf]# mysqlbinlog  /data/mysql/mysql3306/logs/mysql-bin.000004 | mysql -utest -ptest -h192.168.10.24 -Dtest -P8066

Warning: Using a password on the command line interface can be insecure.
ERROR 1609 (HY000) at line 36: The BINLOG statement of type `Table_map` was not preceded by a format description BINLOG statement.

##############
是不是通过mysqlbinlog解析出来的binlog不能通过Mycat追加到各个分片里面？？？？

**Comment by magicdoom** [comment]
你如果解析出sql来执行时可以的
