### ISSUE TITLE
postgresql + native

### ISSUE THREAD

**Issue by xinliuswie** [MyCATApache/Mycat-Server#1249]
host配置 
	<dataHost name="localhost" maxCon="100" minCon="10" balance="0" writeType="0" switchType="1" dbType="postgresql" dbDriver="native">
		<heartbeat>select 1</heartbeat>
 		<writeHost host="localhostM1" url="localhost:5432" user="postgres" password="postgres" />
	</dataHost>
启动没有错误
执行心跳sql以及任何sql时报错
    2016-11-30 10:45:11,662 [INFO ][$_NIOREACTOR-2-RW] error response errno:1105, 误 C42704 M未认可的配置参数 "autocommit" Fguc.c L5682 Rset_config_option from of sql :select 1 at con:PostgreSQLBackendConnection [id=2, host=localhost, port=5432, localPort=53953]  (io.mycat.sqlengine.SQLJob:SQLJob.java:132)

**Comment by magicdoom** [comment]
@fireflyhoo 可以跟踪下看看

**Comment by fireflyhoo** [comment]
此问题已经解决,请下载最新代码

**Comment by fireflyhoo** [comment]
![image](https://cloud.githubusercontent.com/assets/3061324/20741973/6c67be66-b708-11e6-9f9c-c178f496d075.png)

**Comment by xinliuswie** [comment]
谢谢，下载了最新的代码，没有报错。
但有个问题就是，连接postgresql后只能看到public schema下的表，其他schema下的看不到。
有可能是配置上的问题，我随后检查检查

**Comment by fireflyhoo** [comment]
![image](https://cloud.githubusercontent.com/assets/3061324/20792053/d715f94c-b7fa-11e6-927c-9cd0449c0317.png)
当前, 默认只是显示 public schema 下的 表,  测试有什么问题可以直接找我, 342991688 ,希望你能帮我们一起完善

**Comment by fireflyhoo** [comment]
因为如果显示其他schema 的话,映射到mysql上不好显示, 毕竟 mysql 没有schema 的概念, 如果要的话 可能会考虑 shema名.xxx表的形式,

**Comment by xinliuswie** [comment]
Mycat 的重点还是分库分表处理大规模关系型数据，多租户技术算是衍生出来的吧。
Postgresql 确实比较特殊，会比别的库多一层，但也是最适合做多租户应用的。


在Mycat中，如果使用jdbc方式连接postgresql，指定到具体的数据库，对应单独的DataHost节点，就可以利用Postgresql
多一层的特性。
有个小问题就是，使用jdbc连接之后在连接工具里看不到表？schema下已经配置了table

当然，如果能做到像 Navicat那样连接数据库就爽了。
