### ISSUE TITLE
SetIgnoreUtil extract config?

### ISSUE THREAD

**Issue by ddatsh** [MyCATApache/Mycat-Server#1254]
如io.mycat.util.SetIgnoreUtil 中注释部分所说
忽略部分 SET 指令, 避免WARN 不断的刷日志
实际使用过程中，还是有许多未在里面定义的set语句会刷warn日志很厉害

感觉需要单独提出来允许自定义忽略哪些

征求一下做法是src\main\resources 里再加一个properties还是什么呢

**Comment by magicdoom** [comment]
可以 考虑，注意兼容性   不配置这个文件也别报错
