### ISSUE TITLE
4台机器做了两个主从，把其中一个主的mysql服务关闭，mycat服务无法继续工作

### ISSUE THREAD

**Issue by suxl** [MyCATApache/Mycat-Server#126]
配置如下：
<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100">
		<table name="base_user" primaryKey="id_" autoIncrement="true" dataNode="dn1" />
		<table name="sam_glucose" primaryKey="id_" autoIncrement="true" dataNode="dn1,dn2" rule="mod-long" />
		<table name="t1" primaryKey="id_" autoIncrement="true" dataNode="dn1" />
		<table name="mycat_sequence" primaryKey="name_" dataNode="dn1" />
	</schema>

	<dataNode name="dn1" dataHost="mainHost" database="sam_test" />
	<dataNode name="dn2" dataHost="submeterHost" database="sam_test" />
	
	<dataHost name="mainHost" maxCon="1000" minCon="10" balance="1"
		writeType="0" dbType="mysql" dbDriver="native">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="hostM1" url="192.168.18.78:3306" user="root" password="root">
			
			<readHost host="hostS1" url="192.168.18.74:3306" user="root" password="123456" />
		</writeHost>
	</dataHost>
	
	<dataHost name="submeterHost" maxCon="1000" minCon="10" balance="1"
		writeType="0" dbType="mysql" dbDriver="native">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="hostM2" url="192.168.18.59:3306" user="root" password="123456">
			
			<readHost host="hostS2" url="192.168.18.81:3306" user="root" password="123456" />
		</writeHost>
	</dataHost>
望能得到哪些高手解答，目前mycat其他各项功能都测试通过了，打算把mycat应用到公司的正式环境下，希望能够搞清楚这个问题就比较放心了！

**Comment by suxl** [comment]
补充：把其中某个主上的mysql服务关闭后，使用mycat查询或新增的操作时总是报：1003 - Connection refused: no further information

**Comment by apachemycat** [comment]
上述配置其实是主从模式，真正的双主模式 是要这样写：

<dataHost name="mainHost" maxCon="1000" minCon="10" balance="1"
    writeType="0" dbType="mysql" dbDriver="native">
    <heartbeat>select user()</heartbeat>
    
    <writeHost host="hostM1" url="192.168.18.78:3306" user="root" password="root">
        
   
    </writeHost>
      <writeHost host="hostM2" url="192.168.18.74:3306" user="root" password="123456" />
</dataHost>

**Comment by suxl** [comment]
感谢您的回答，我之所以这么配置，是因为考虑到以后数据库节点的扩容。我们的项目中有一个sam_glucose这个表数据增长特别快，以后要扩容的时候我还是得增加节点，继续来存储这个表的数据。这样我每增加这样一个节点，为了保证数据的高可用性，同时我又得需要增加一个从节点。那还您这个思路的话，我以后对这个表的数据做100个分区节点，那就是在一个dataHost中配置100个writeHost？
我就是这块有点不太清楚，不知道考虑到以后扩展，这块该怎么配置比较好，目前也也没有看到这方面比较好点的文档。

**Comment by suxl** [comment]
补充一下，其实未来可能不是配置双主的模式，像我的sam_glucose这个表数据增加的特别快，到达一定的数据量后，我还得针对这个增加一个主和一个从节点来扩容。请问，按我这个未来扩容的思路，我应该怎么配置合适呢？

**Comment by apachemycat** [comment]
100个分区节点 其实是100个database，可以在3个dataHost上（一个dataHost 里面有一个writeHost，一个readHost)，也可以在10个dataHost。
sam_glucose这个表数据增加的特别快，可以考虑时间范围或主键范围分片，只是增加database，到某个亦有的dataHost上，而dataHost数量没那么快的变化
