### ISSUE TITLE
order varchar column as  an int

### ISSUE THREAD

**Issue by wengad82** [MyCATApache/Mycat-Server#1260]
[SQL]select * from w_customer order by cust_id+0;
[Err] 1105 - java.lang.IllegalArgumentException: all columns in order by clause should be in the selected column list!cust_id + 0

建议支持id字段为varchar类型，但是排序时希望使用数值方式进行排序。

**Comment by magicdoom** [comment]
建议支持id字段为varchar类型，但是排序时希望使用数值方式进行排序
这个需求也太怪了吧，varchar就应该根据字符排序 ，int就应该数值排序
