### ISSUE TITLE
1.4-1.6 select for update 未锁定链接

### ISSUE THREAD

**Issue by Duntian** [MyCATApache/Mycat-Server#1261]
版本1.4-1.6
Mycat-server-1.4-release-20151019230038-linux.tar  
到
Mycat-server-1.6-RELEASE-20161012170031-linux.tar

在一个事务中
begin
select * from a  where id=1 for update ;
update b set col=1 ;
select * from c;
commit;

其中第二个语句不会锁定连接，导致for update锁不上表。

改成：
begin
update b set col=1 ;
select * from a  where id=1 for update ;
select * from c;
commit;

可以正常锁表

是因为mycat在这些版本中做了优化，开启事务后，直到碰到真正的事务操作才会锁定链接，而不是只要开启事务，就一定锁定链接并走向主库。

但是在select  for update 时未能处理。

相同的问题，还有Oracle的序列，在开启事务后，取序列，由于不是强制走主库，会走到从库取，结果就报错了
例：
begin
select seq_a.nextval from dual ;
insert into xxxx
commit;

建议，是否可以增加一个配置，开启事务后，是强制锁定链接并走主库，还是直到碰到事务语句后才锁定的选择项。

**Comment by HashZhang** [comment]
能不能这样，只对for update语句进行锁表

**Comment by HashZhang** [comment]
能不能这样，只对for update语句开始锁表

**Comment by magicdoom** [comment]
应该解析select for update时当做是更新语句就可以了

2016-12-08 18:45 GMT+08:00 张哈希 <notifications@github.com>:

**Comment by HashZhang** [comment]
已提PR

**Comment by magicdoom** [comment]
楼主可以测试验证下看看
