### ISSUE TITLE
如何使用JPA的persist方法时,使用mycat自带的sequence生成ID主键

### ISSUE THREAD

**Issue by huangpokl** [MyCATApache/Mycat-Server#1262]
如何使用JPA的persist方法时,使用mycat自带的sequence生成ID主键?
表内ID的配置如下：
`    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;`

当这样设置时，调用jpa的persist方法会报一下错误
`ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]:181] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement] with root cause
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: bad insert sql (sharding column:ID not provided,INSERT INTO bas_device (available, create_time, update_time, uuid, device_model
	, device_name, device_serial, device_type, resolution, system_version)
VALUES (1, '2016-12-05 14:11:46', '2016-12-05 14:11:46', 'ce547c0479264c68a96e7aadb7b6a7f4', 'w'
	, 'ss', '23b36bf4bf7e4962b0bbdaeee2ad9138', 'IOS', 'ss', NULL)`

**Comment by HashZhang** [comment]
配置里面检查两个配置：
schemal.xml:table标签是否包含autoIncrement=true
server.xml: 检查是否指定了sequnceHandlerType属性

**Comment by HashZhang** [comment]
示例配置：
```
<schema name="test2">
		<table name="producer" primaryKey="ID" autoIncrement="true" dataNode="dn1,dn4"
			   rule="mod-long-2" />
		<table name="customer" primaryKey="ID" autoIncrement="true" dataNode="dn4,dn3"
			   rule="mod-long-2"/>
	</schema>
```
```
<property name="sequnceHandlerType">2</property>
```

**Comment by HashZhang** [comment]
执行：
```
insert into producer(name)values("张哈希");
select * from producer;
```
结果：
```
+--------------------+--------+
| id                 | name   |
+--------------------+--------+
| 806808430038880256 | 张哈希|
+--------------------+--------+

```

**Comment by HashZhang** [comment]
对于JPA，表内ID不做任何配置，插入时不提供ID，JPA读取时应该会读到ID
