### ISSUE TITLE
MYCAT 1.6 在navicat中执行会抛异常 

### ISSUE THREAD

**Issue by Duntian** [MyCATApache/Mycat-Server#1263]
navicat （版本 10.1.7）在执行完SQL后，会返回SQL执行的过程，但是在连上MYCAT后抛异常

[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID=' at line 1

查看MYCAT代码，有这段处理，但是。。。。

//fix navicat   SELECT STATE AS `State`, ROUND(SUM(DURATION),7) AS `Duration`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ
		if(ServerParse.SELECT == type &&sql.contains(" INFORMATION_SCHEMA.PROFILING ")&&sql.contains("CONCAT(ROUND(SUM(DURATION)/"))
		{
			InformationSchemaProfiling.response(this);
			return;
		}

**Comment by magicdoom** [comment]
1.6.5版本测试看看  应该已经fix
