### ISSUE TITLE
ERROR 1003 (HY000): Reload config failure

### ISSUE THREAD

**Issue by wengad82** [MyCATApache/Mycat-Server#1267]
mysql> reload @@config;
ERROR 1003 (HY000): Reload config failure

但是日志里面都不报错，能否把错误信息写入到日志文件，好分析！

**Comment by HashZhang** [comment]
日志里面不报错，可能是你配置有问题

**Comment by HashZhang** [comment]
日志里面不报错，可能是你配置有问题

**Comment by wengad82** [comment]
哪个配置文件？

**Comment by zhuam** [comment]
reload @@config;  检查 server.xml

reload @@config_all  需要检查  schema.xml 及  server.xml
