### ISSUE TITLE
Mycat 是否支持指定数据节点查询？

### ISSUE THREAD

**Issue by huangpokl** [MyCATApache/Mycat-Server#1269]
场景如下：
[http://geek.csdn.net/news/detail/72973](url)

即将分库分表的信息包含于ID中，通过解析ID定位该条数据位于哪个库表中，以此提供查询效率。
Mycat是否支持此场景？
如支持如何使用，配置？
感谢回答！

**Comment by HashZhang** [comment]
你的意思是某个ID，ID中同时包含这个记录属于哪个库以及那张表对吧。
例如：
001002ACB07842
001就代表库1,002就代表库1的表2对吧。思路不错，但是目前MyCat只支持单列分片字段，可以多库每库一张表，可以单库多张表，但是多库多表还没实现，可以考虑未来实现多列分库，多库多表吗？ @magicdoom

**Comment by magicdoom** [comment]
这个你可以自己写一个分片规则来实现，库内分表不推荐     推荐只分库来分片。也可以利用现有注解来指定
