### ISSUE TITLE
MyCAT 1.6 Firewall问题

### ISSUE THREAD

**Issue by wowkingah** [MyCATApache/Mycat-Server#1275]
**描述**
在firewall的whitehost中只能配置主机，不能配置网段。

**测试配置方法**
<host host="192.168.1.0" user="mycat"/>
<host host="192.168.1.0/24" user="mycat"/>
<host host="192.168.1.%" user="mycat"/>

**建议**
当数据库用户及后端APP较多时，为每个用户指定HOST似乎不可取。
建议，添加可配置网段的功能。

**Comment by HashZhang** [comment]
可以制作下，已在最新的pull request中提交

**Comment by wowkingah** [comment]
神速。
