### ISSUE TITLE
通过pdo连接mycat  ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by isoleo** [MyCATApache/Mycat-Server#1278]
![image](https://cloud.githubusercontent.com/assets/17608877/21001484/87070f48-bd5b-11e6-8f2a-c43e25547f76.png)

pdo 属性设置   ATTR_EMULATE_PREPARES =false

// 封装的方法
		protected function doSql($sql,$params=array()) {
			$result = null;
			if (!empty($params)) {   //判断是否为空  
			   
				$result = $this->getLink()->prepare($sql);
				
				foreach ($params as $key => $val) {
			        if (is_int($val)) {
			            $type = PDO::PARAM_INT;
			        } else if (is_bool($val)) {
			            $type = PDO::PARAM_BOOL;
			        } else if (is_null($val)) {
			            $type = PDO::PARAM_NULL;
			        } else {
			            $type = PDO::PARAM_STR;
			        }
			        
					if (is_int($key)) {
						$key += 1;
					}

					$result->bindValue($key,$val,$type);
				}

				$result->execute();
			} else {   // 当参数为空的时候  执行mycat 就会报ArrayIndexOutOfBoundsException
				//	直接执行sql语句
				$result = $this->getLink()->query($sql);
			}
			return $result;
		}

// 调用上边的方法 
public function test_pdo() {
            $gindex = 900040;
            $gindexVer = 2;
            $gUid = '352e5f69b0675a19df23d3e5ec78fcaa';
            $db = getWmodDb();
            
            //  下边两行，是可以正常执行的
            $sql =" SELECT id FROM t_table WHERE gindex=? and gindex_ver=? and guid=?";
            $list = $db->dosql($sql, array($gindex, $gindexVer, $gUid));
            
            // 下边两行，是会报错的。ArrayIndexOutOfBoundsException
            $sql =" SELECT id FROM t_table ";
            $list = $db->dosql($sql);

            echo 'pdo exis value <br/>';
            dump($list);
            
            
            $sqls =" SELECT id FROM wmod_change_game";
            $lists = $db->vgetData($sqls);
            echo 'pdo empty exis <br/>';
            dump($lists);die;
       }

**Comment by dsphper** [comment]
这个问题的特征简单总结一下就是：使用PHP-PDO链接Mysql，设置成服务器端预处理。
然后使用select * from xxx;进行查询，并不进行绑参操作。Mycat则会爆出上面给出图中的错误。

**Comment by HashZhang** [comment]
这个最好给一下MyCat日志输出报什么错

**Comment by magicdoom** [comment]
@ZzzCrazyPig 看看

**Comment by ZzzCrazyPig** [comment]
@isoleo 上面的程序可以给出完整的方法？里面给的不完整。我用普通的pdo去操作没有测出异常- -。见鬼了

**Comment by ZzzCrazyPig** [comment]
@isoleo  `getWmodDb();`这个方法没给出来。我对php不熟，尽量给全点。还有如果使用不封装的pdo的例子能测试出来更好。

**Comment by ZzzCrazyPig** [comment]
@dsphper 你也遇到同样的问题？

**Comment by ZzzCrazyPig** [comment]
@isoleo @dsphper 两位，我给下我这边测试用的php，你们看下跟你们要模拟出错的有没有什么不一致，采用原始的pdo:

```php
<?php
$host = 'localhost';  
$user = 'root';  
$pwd = 'mysql';  
// sakila数据库是安装mysql时, 系统自带的一个示例数据库  
$dbname = 'TESTDB';  
  
// dsn的具体写法, 在PHP手册中搜索: PDO_MYSQL  
$dsn = "mysql:host=$host;dbname=$dbname;port=8066";  
  
// 连接数据库  
$pdo = new PDO ( $dsn, $user, $pwd );  
$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);  
$sql = "select id from tb_test";    
$stmt = $pdo -> query( $sql );  
// 预编译sql 
// $stmt -> prepare($sql);
// $stmt -> execute();  
  
// 直接取全部出来  
var_dump ( $stmt -> fetchAll () );
$pdo = null;
?>
```

**Comment by ZzzCrazyPig** [comment]
@isoleo @dsphper 成功在linux上模拟到了你们提到的异常，给我点时间debug下，预计今天内修复

**Comment by isoleo** [comment]
我们现在的环境
有点忙，没来的急回复。。。
php 5.4.3 
linux: centos6
mycat 1.6 release版

**Comment by ZzzCrazyPig** [comment]
已经提交fix代码，请南哥@magicdoom merge，还得麻烦两位@isoleo @dsphper协助多测试一下。我这边简单测了一下没问题。

**Comment by zch513430014** [comment]
请问这个问题是否有解决呢，我这边也遇到同样的错误了
