### ISSUE TITLE
mycat1.6在mysql下执行带返回结果集的存储过程时直接卡死

### ISSUE THREAD

**Issue by ywhnicety** [MyCATApache/Mycat-Server#1281]
例如：
CREATE PROCTEST(IN a varchar(20))
BEGIN  
    select * from tablename;
END;

当在mycat上执行：CALL PROCTEST('abc');这个SQL语句时一直卡住，不返回。

**Comment by magicdoom** [comment]
加注解   通过jdbc等程序执行     mysql命令行可能会过滤注释    具体看权威指南
