### ISSUE TITLE
mycat 对prepare 解释错误

### ISSUE THREAD

**Issue by isoleo** [MyCATApache/Mycat-Server#1294]
mysql 代码： 

PREPARE sql1 FROM 'insert into t_test (name) values (?)';
 SET @i=''; -- 参数如果为空串，就报错。
 EXECUTE sql1 USING @i;

很简单，当传入的参数为空串时就报

错误代码： 1064
String index out of range: -1

**Comment by magicdoom** [comment]
mycat版本？

**Comment by isoleo** [comment]
mycat 1.6.5
系统linux 
上边是mysql 代码 。还有个php代码也报错
通过pdo 插入数据时。数据为一个空串。对应的字段not null
这时，返回的错误是 
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null
也就是说，通过mycat 本来的空串，不知道什么原因就能成null ，而数据库设计成了not null
所以报错了
我认为通过pdo 报的这个错。优先级高

**Comment by isoleo** [comment]
php版本 5.4.3
mysql 5.6

**Comment by ZzzCrazyPig** [comment]
@isoleo 两个问题分两个issue来提吧。

对于第一个问题，你所提到的mysql代码是在哪里执行的？mysql客户端？还是PHP？目前应该是不支持prepare这种语法的语句。

第二个问题，请描述清楚一点，我看上面的描述：

> 通过pdo 插入数据时。数据为一个空串。对应的字段not null
这时，返回的错误是
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null

你能给描述复现的场景？格式如下:

```
1. 复现BUG的SQL语句(如果能带上复现BUG的测试程序片段更佳)

...

2. 针对这个BUG，mycat后台的报错日志

...
```

**Comment by isoleo** [comment]
详细描述：
php 5.4.3 扩展pdo
mysql 5.6
mycat 版本 1.6.5
表结构 ：
CREATE TABLE t_test (id INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(10) NOT NULL)

php代码段
public function test_a_pdo() {
           $sql = "inset into  t_test (id,name) values (?,?)";  // 两个参数
           $appName = C('BHWEBSITE_APPNAME')[APPNAME_ENV];
           $db = \PdoMysql::getDB(true,$appName);
           $c = $db->vrunsql($sql,array(1,''));   //参数传数  一个为  1 一个为空串
           dump($db);
           dump($c);die;
       }

mycat 日志：

2016-12-16 10:52:09.371  WARN [$_NIOREACTOR-1-RW] (io.mycat.server.handler.SetHandler.handle(SetHandler.java:159)) - ServerConnection [id=1277, schema=dbbh_website, host=10.171.219.217, user=php_user,txIsolation=3, autocommit=true, schema=dbbh_website]inset into  t_test (id,name) values (NULL,NULL) is not recoginized and ignored

以上为所有日志 ，我已经开了debug模式。可是就是没有详细日志 

wrapper.console.loglevel=debug
wrapper.logfile.loglevel=debug
wrapper.syslog.loglevel=debug
我就看到了这三个开关，全加上了

**Comment by ZzzCrazyPig** [comment]
上面的php代码也是用到了服务端预处理么? 也是打开了`ATTR_EMULATE_PREPARES =false`选项的？

**Comment by isoleo** [comment]
是的，ATTR_EMULATE_PREPARES =false

**Comment by ZzzCrazyPig** [comment]
恩，那等我调试一下

**Comment by ZzzCrazyPig** [comment]
@magicdoom 请南哥合并下
