### ISSUE TITLE
异常  find no Route

### ISSUE THREAD

**Issue by githublaohu** [MyCATApache/Mycat-Server#1297]
`[$_NIOREACTOR-1-RW] ServerConnection [id=1, schema=vp_user, host=172.16.0.180, user=root,txIsolation=3, autocommit=true, schema=vp_user]SELECT * FROM `vp_user_800000001`.`vp_user_info` LIMIT 0 err:java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `vp_user_800000001`.`vp_user_info` LIMIT 0 java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `vp_user_800000001`.`vp_user_info` LIMIT 0
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:437)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:287)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:67)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:84)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.route.RouteService.route(RouteService.java:133)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 1    | 2016/12/14 17:57:47 | 	at java.lang.Thread.run(Thread.java:745)
`
配置文件
**schema.xml**
`
<mycat:schema xmlns:mycat="http://io.mycat/">
	<schema name="vp_user" checkSQLschema="true" sqlMaxLimit="100">
		
		<table name="vp_user_info" primaryKey="app_id" dataNode="dn1,dn2,dn3,dn4,dn5" rule="appId_enumeration" />
	</schema>

	<dataNode name="dn1" dataHost="development" database="vp_user_800000001" />
	<dataNode name="dn2" dataHost="development" database="vp_user_800000002" />
	<dataNode name="dn3" dataHost="development" database="vp_user_800000003" />
	<dataNode name="dn4" dataHost="development" database="vp_user_800000004" />
	<dataNode name="dn5" dataHost="development" database="vp_user_800000005" />
	<dataHost name="development" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" url="172.16.6.201:3306" user="root" password="Ab123@" />
	</dataHost>

</mycat:schema>
`

**rule.xml**
`<mycat:rule xmlns:mycat="http://io.mycat/">
	<tableRule name="appId_enumeration">
		<rule>
			<columns>app_id</columns>
			<algorithm>appId_enumeration_fun</algorithm>
		</rule>
	</tableRule>
	<function name="appId_enumeration_fun" class="io.mycat.route.function.PartitionByFileMap">
		<property name="mapFile">appId_enumeration.txt</property>
	</function>
</mycat:rule>
`

**appId_enumeration.txt**
`800000001=0
800000002=1
800000003=2
800000004=3
800000005=4
DEFAULT_NODE=0
`

**Comment by brotherbin** [comment]
> SELECT * FROM vp_user_800000001.vp_user_info LIMIT 0

这种SQL应该是你使用NAVICATE之类的客户端工具触发的，这个异常不会影响应用

**Comment by githublaohu** [comment]
是的，
