### ISSUE TITLE
如何根据时间范围分片

### ISSUE THREAD

**Issue by bylijinnan** [MyCATApache/Mycat-Server#1306]
按时间范围分片，且时间范围的跨度是不确定的，视业务情况定。。例如，16年1月到5月在分片dn1，6月到8月在分片dn2，9月到12月在分片dn3。

目前想到一个办法是：
表中有一个类型为date的input_time字段，可以把input_time转为long型的时间戳，这样就可以auto-sharding-long.

但是没看到哪里可以做类型转换。

谢谢指导！

**Comment by magicdoom** [comment]
mycat支持日期字段的，想时间范围不确定比较困难    ，规则就是要规范，都不确定了就不好路由了，可以适当去看下日期范围取模分片规则
