### ISSUE TITLE
mycat 1.6版本sql监控统计的管理命令无效果

### ISSUE THREAD

**Issue by yebinjei** [MyCATApache/Mycat-Server#1315]
show @@sql.sum  
show @@sql.slow 
show @@sql.resultset 
show @@sql 
这些命令查询不到结果。无论何时都为空。

**Comment by HashZhang** [comment]
这个我这里看是有效果的，你看看你的日志还有其他输出

**Comment by gaotuan** [comment]
useSqlStat 设置为1
