### ISSUE TITLE
mycat 1.6.5 提示表不存在

### ISSUE THREAD

**Issue by isoleo** [MyCATApache/Mycat-Server#1323]
mysql 真实库名 db3

当schema name 与真实库名不一致时，对表进行查询
，提示表不存在

schema name="db31" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn3"

WARN [$_NIOREACTOR-7-RW] (io.mycat.backend.mysql.nio.handler.SingleNodeHandler.backConnectionErr(SingleNodeHandler.java:248)) - execute  sql err : errno:1146 Table 'db31.sbtest4' doesn't exist con:MySQLConnection [id=55, lastTime=1483526276841, user=lixiaomeng, schema=db3, old shema=db3, borrowed=true, fromSlaveDB=false, threadId=35836165, charset=utf8, txIsolation=2, autocommit=true, attachment=dn3{select * from `db31`.`sbtest4` limit 0, 1000}, respHandler=SingleNodeHandler [node=dn3{select * from `db31`.`sbtest4` limit 0, 1000}, packetId=1], host=101.147.161.185, port=6000, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] frontend host:101.160.19.150/59355/user

**Comment by isoleo** [comment]
这回是我的问题，请忽略。谢谢

**Comment by Crown017** [comment]
是什么问题呢
