### ISSUE TITLE
请教mycat集群的配置细节。

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#135]
mycat是否必须借助于第三方软件才能搭建集群环境？
server.xml中关于cluster的配置是否还可用？

**Comment by songwie** [comment]
貌似不可以用

**Comment by bluoy** [comment]
cobar是有的，查了下代码，好像被mycat阉割掉了。不知何因？

**Comment by songwie** [comment]
看代码本来想通过zk ，统一管理，后来估计作者没开发完

**Comment by bluoy** [comment]
那现在有成熟的集群配置案例吗？想评估生产环境使用的可行性。

**Comment by linzhiqiang0514** [comment]
可以参考，mycat-doc下面的案例文件夹里面，有群里的人共享的文档。
