### ISSUE TITLE
创建了2个schema，使用show tables from database;和use database;show tables;显示结果不一样

### ISSUE THREAD

**Issue by faidev** [MyCATApache/Mycat-Server#1350]
3个db做的galera集群，创建了2个schema，vicidial和vicidial1
MySQL [(none)]> show tables from vicidial1;
+-----------------------------------------+
| Tables_in_vicidial                      |
+-----------------------------------------+
| ajax_chat_bans                          |
| ajax_chat_invitations                   |
| ajax_chat_messages                      |
·······························

MySQL [(none)]> use vicidial1;
Database changed
MySQL [vicidial1]> show tables;
Empty set (0.00 sec)

**Comment by ZzzCrazyPig** [comment]
估计你只配了schema，没有配置table吧。mycat对show tables的处理是返回schema.xml里面这个schema下面的所有表信息，`show tables from vicidial1`估计走了任意的一个节点去执行了。

**Comment by faidev** [comment]
对的，我的应用还不需要做分片，表的数量太多，写起来麻烦，schema里直接配置的dataNode。

**Comment by ZzzCrazyPig** [comment]
可以配置多个schema，但是schema配置表好像是必须的应该

**Comment by faidev** [comment]
我没有配置表一样可以用好像！
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://org.opencloudb/">
        <schema name="vicidial" checkSQLschema="false" sqlMaxLimit="0" dataNode="mariadb_galera"/>
        <schema name="vicidial1" checkSQLschema="false" sqlMaxLimit="0" dataNode="mariadb_galera1">
        </schema>
        <dataNode name="mariadb_galera" dataHost="galera_host" database="vicidial" />
        <dataNode name="mariadb_galera1" dataHost="galera_host" database="vicidial1" />
        <dataHost name="galera_host" maxCon="1000" minCon="3" balance="1" writeType="0" dbType="mysql" dbDriver="native" s
witchType="3" >
                <heartbeat>show status like 'wsrep%'</heartbeat>
                <writeHost host="galera_host1" url="10.201.184.171:3306" user="root" password="123456">
                </writeHost>
</mycat:schema>
