### ISSUE TITLE
关于mycat的批量insert问题

### ISSUE THREAD

**Issue by exhui** [MyCATApache/Mycat-Server#1351]
执行SQL语句：INSERT INTO mycat_test (id, name) VALUES (next value for MYCATSEQ_GLOBAL, '1') , (next value for MYCATSEQ_GLOBAL, '2');
报以下异常：ERROR 1062 (23000): Duplicate entry '822363637564968960' for key 'PRIMARY'
请问下，这个应该如何解决或者还有其他替代办法吗？

**Comment by xjq941219** [comment]
明显的键重复问题吗
