### ISSUE TITLE
单库分表怎么配置

### ISSUE THREAD

**Issue by harry-lianghairui** [MyCATApache/Mycat-Server#1352]
版本：1.6-RELEASE和1.6.5-DEV版本都试过不行
schema.xml配置
`<table name="hairui" subTables="hairui$1-3" dataNode="dn1" rule="sharding-by-murmur" />`
创建表语句：
```
CREATE TABLE `hairui` (
  `tuid` bigint(20) NOT NULL COMMENT '老师id',
  `cls_id` bigint(20) NOT NULL COMMENT '班级id',
  `course_id` bigint(20) NOT NULL COMMENT '课程id',
  PRIMARY KEY (`tuid`,`cls_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
但是创建hairui表的时候，只创建了hairui一张表, 按道理不是应该创建主表hairui和字表hairui1、2、3的吗

**Comment by songwie** [comment]
http://songwie.com/articlelist/202

**Comment by harry-lianghairui** [comment]
替换class(可以用于生产基于1.6release)：classes\io\mycat\route\function, 附件：http://songwie.com/attached/mycat/AbstractPartitionAlgorithm.class
替换jar：lib目录下mycat-server：（基于1.6.5开发板）http://songwie.com/attached/mycat/Mycat-server-1.6.5-DEV.jar

这两个操作都要操作吗，还有classes\io\mycat\route\function这个目录没找到

**Comment by songwie** [comment]
只需要一个，那个目录是在jar里面

**Comment by yuanbs** [comment]
可以用auto-sharding-long嘛？
