### ISSUE TITLE
mycat-server 1.6 版本 server.xml里面设置给用户设置privileges报错

### ISSUE THREAD

**Issue by Yxnt** [MyCATApache/Mycat-Server#1354]
报错截图如下：

![image](https://cloud.githubusercontent.com/assets/10323352/22194277/4fed541e-e17c-11e6-9bfc-1745c70f3370.png)

配置截图如下
![image](https://cloud.githubusercontent.com/assets/10323352/22194301/81141f5a-e17c-11e6-94a8-53a6a84a40d5.png)

只有这段配置，其他的都为默认。当我把privileges删掉后就可以正常使用
```
<user name="test"> 
  <property name="password">111111</property>  
  <property name="schemas">LocationTest</property>  
  <privileges check="true"> 
    <schema name="LocationTest" dml="0110"/> 
  </privileges> 
</user>
```

**Comment by magicdoom** [comment]
这块重构成firewall了

**Comment by Yxnt** [comment]
@magicdoom 意思是要添加到防火墙规则那里吗？ 能否有个具体示例？

**Comment by 007mawenbin** [comment]
> @magicdoom 意思是要添加到防火墙规则那里吗？ 能否有个具体示例？

哥们，解决了吗，我也遇到了这个问题。
