### ISSUE TITLE
mycat-web连接9066受jdbc驱动版本限制

### ISSUE THREAD

**Issue by zhangxs92** [MyCATApache/Mycat-Server#136]
这两天用mycat-web查看mycat监控，用的是5.1.22 mysql的jdbc驱动包，怎么也连不上，之后换成5.1.12版本的才好使，需注意

**Comment by apachemycat** [comment]
目前最新的JDBC驱动是否OK，因为MySQL驱动中有一个地方修改了。

**Comment by linzhiqiang0514** [comment]
请验证，使用最新的代码做验证。

**Comment by Danielle1993** [comment]
好的

**Comment by magicdoom** [comment]
按照新版的来测试  一般5.1.35 36是没问题的
