### ISSUE TITLE
mycat 1.6 show @@sql show @@sql.sum只能记录读操作

### ISSUE THREAD

**Issue by iwasnobody** [MyCATApache/Mycat-Server#1360]
server.xml开启实时统计
<property name="useSqlStat">1</property>"

但是
show @@sql show @@sql.sum
只能看到select的记录，无法看到insert,update的语句，在mycat-web中也是

**Comment by peterxiemin** [comment]
请问时时统计的开关是什么？

**Comment by iwasnobody** [comment]
@peterxiemin 就是在server.xml文件中，设置<property name="useSqlStat">1</property>，开启实时记录sql操作

**Comment by iwasnobody** [comment]
就是在server.xml文件中，设置<property name="useSqlStat">1</property>，开启实时记录sql操作

 

 

Best regards,

Yu Jun

**Comment by peterxiemin** [comment]
好的，谢谢。 我将userSqlStat设置=1后，sql监控里面也全都是select语句。这个问题你解决了吗？

**Comment by iwasnobody** [comment]
没有，我不是做开发的，猜测是bug

发自我的 iPhone

**Comment by ZzzCrazyPig** [comment]
使用最新的1.6代码测试，没有发现该问题，show @@sql 和 show @@sql.sum 可以记录到写记录

**Comment by iwasnobody** [comment]
@ZzzCrazyPig 您好，能否提供你1.6版本下载的路径，我是使用如下路径下载的安装包
http://dl.mycat.io/1.6-RELEASE/Mycat-server-1.6-RELEASE-20161028204710-linux.tar.gz
谢谢

**Comment by ZzzCrazyPig** [comment]
@iwasnobody 我是用的源码debug的，你的版本我周一验证下才能知道了

**Comment by iwasnobody** [comment]
@ZzzCrazyPig 好的，非常感谢！！！

**Comment by ZzzCrazyPig** [comment]
@iwasnobody  已经确定你那个版本确实有你提到的问题，是个BUG，但是后面的源码修复过，所以我用最新的源码没有发现这个问题，你们方便的话可以用下南哥最新发布的BETA版本，如果不方便，拿最新代码编译，然后替换SingleNodeHandler这个class文件即可

**Comment by iwasnobody** [comment]
@ZzzCrazyPig 1.6.5版本实测已经解决了这个问题，多谢多谢！
