### ISSUE TITLE
当使用select for update 时，无法锁定表

### ISSUE THREAD

**Issue by isoleo** [MyCATApache/Mycat-Server#1377]
SET autocommit=0;
SELECT * FROM tablename WHERE id=2 FOR UPDATE ;

以上sql 在两个终端执行，均能查到数据。
并没有起到锁等待的作用

**Comment by ZzzCrazyPig** [comment]
mycat应该是不支持select for update 或者 select lock in share mode的，这两个语句涉及行锁，情况相对复杂，如果涉及关联表的行锁，那就更复杂了
