### ISSUE TITLE
mycat连接超时?

### ISSUE THREAD

**Issue by lic721** [MyCATApache/Mycat-Server#1394]
mycat1.5, 在线上跑的时候, 报错:
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communicatio
ns link failure

The last packet successfully received from the server was **1,800,239** milliseconds
 ago.  The last packet sent successfully to the server was **1,800,254** millisecond
s ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
...

从时间上来看, 应该是connection达到idleTimeout(1800s)后被强制关闭了.
但是, 项目里面已经配置了c3p0数据源的idleConnectionTestPeriod, 每60秒就检查空闲连接, 配置如下:

	<bean id="dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource">
		<property name="driverClass" value="${hibernate.connection.driver_class}" />
		<property name="jdbcUrl" value="${hibernate.connection.url}" />
		<property name="properties">
			<props>
				<prop key="user">${hibernate.connection.username}</prop>
				<prop key="password">${hibernate.connection.password}</prop>
			</props>
		</property>
		<property name="acquireIncrement" value="15" />
		
		<property name="acquireRetryAttempts" value="30"></property>
		
		<property name="acquireRetryDelay" value="1000"></property>
		
		<property name="autoCommitOnClose" value="false"></property>
		
		<property name="idleConnectionTestPeriod" value="60"></property>
		<property name="preferredTestQuery" value="SELECT 1 FROM role"></property>
		
		
		<property name="initialPoolSize" value="50"></property>
		
		<property name="maxIdleTime" value="60"></property>
		

	</bean>

**Comment by huangyiminghappy** [comment]
这种是你mycat连接还是活跃，但是mysql服务器那边把连接关闭（因为超过mysql设置的最大空闲连接时间），导致mycat里的数据库连接去连mysql的时候报这个错误。

**Comment by lic721** [comment]
原因知道了. 但是没有好的解决办法.
数据库是sqlserver, mycat不支持sqlserver的存储过程多结果集, 所以我自己写了段代码, 但是对于buffer的处理有问题, 把数据搞丢了.
