### ISSUE TITLE
Mycat的依赖fastjson存在严重漏洞，需要升级版本

### ISSUE THREAD

**Issue by Ulyssesyi** [MyCATApache/Mycat-Server#1405]
近两天阿里巴巴发出一个通知https://help.aliyun.com/knowledge_detail/51589.html
https://github.com/alibaba/fastjson/wiki/security_update_20170315。
说fastjson在1.2.24以及之前版本存在代码执行漏洞，当用户提交一个精心构造的恶意的序列化数据到服务器端时，fastjson在反序列化时存在漏洞，可导致远程任意代码执行漏洞。那么mycat的这个依赖该怎么升级防止这个漏洞呢？

**Comment by WenTao-Love** [comment]
是直接更新pom依赖版本就可以了吗？
