### ISSUE TITLE
NonBlockingSession.tryExistsCon一处是否有问题？

### ISSUE THREAD

**Issue by kuaikuai** [MyCATApache/Mycat-Server#1406]
public boolean tryExistsCon(final BackendConnection conn, RouteResultsetNode node) {
        if (conn == null) {
            return false;
        }

        boolean canReUse = false;
        // conn 是 slave db 的，并且 路由结果显示，本次sql可以重用该 conn
        if (conn.isFromSlaveDB() && (node.canRunnINReadDB(getSource().isAutocommit())
                && (node.getRunOnSlave() == null || node.getRunOnSlave()))) {
            canReUse = true;
        }

        // conn 是 master db 的，并且路由结果显示，本次sql可以重用该conn
        if (!conn.isFromSlaveDB() && (node.getRunOnSlave() == null || !node.getRunOnSlave())) {
            canReUse = true;
        }
        **//如果一个链接的消息尚未接受完毕，这个重用是否不当？
       // 改成if (canReUse && conn.getAttachment() == null 可以保证消息已处理完**
        if (canReUse) {
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("found connections in session to use " + conn
                        + " for " + node);
            }
            conn.setAttachment(node);
            return true;
        } else {
            // slavedb connection and can't use anymore ,release it
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("release slave connection,can't be used in trasaction  "
                        + conn + " for " + node);
            }
            releaseConnection(node, LOGGER.isDebugEnabled(), false);
        }
        return false;
    }

**Comment by kuaikuai** [comment]
没有问题，理解错了。

**Comment by seair-jzh** [comment]
正确的理解是？我似乎出现了类似问题，后端连接未返回结果就被重用了
