### ISSUE TITLE
select * from t1,t2 where t1.id=t2.tid 查询的结果不正确，其中t2表是按照t1表的id 取模分表的

### ISSUE THREAD

**Issue by suxl** [MyCATApache/Mycat-Server#141]

**Comment by suxl** [comment]
数据划分说明：
我一共用了4台服务器做了双主双从的模式，其中t2表在master1和master2上都有，t1表在master1上。
发现使用select * from t1,t2 where t1.id=t2.tid  只能查询到master1上t2表的数据，master2上t2表的数据查询不到(符合条件的也查不到)。

**Comment by linzhiqiang0514** [comment]
你这是跨分片join，目前应该是不支持的。

**Comment by sohudo** [comment]
此问题已经解决了
