### ISSUE TITLE
java.lang.ClassNotFoundException:demo.catlets.ShareJoin

### ISSUE THREAD

**Issue by if-zz** [MyCATApache/Mycat-Server#1414]
当按照文档执行/*!mycat:catlet=demo.catlets.ShareJoin */ select a.*,b.id, b.name as tit from customer a,company b on a.company_id=b.id;
提示错误ERROR 1064(HY000):java.lang.ClassNotFoundException:demo.catlets.ShareJoin
MyCat版本为1.6
请问一下是哪里出了问题和解决办法

**Comment by fireflyhoo** [comment]
包名改了,在   io.mycat.catlets 下面

**Comment by if-zz** [comment]
嗯，谢谢，解决问题了
