### ISSUE TITLE
不分库不分表时where条件中有多于一个@符时, 会在不同的dataNode间随机查询数据

### ISSUE THREAD

**Issue by rayoo** [MyCATApache/Mycat-Server#1428]
V1.6版本, 不分库不分表时where条件中有多于一个@符时, 会在不同的dataNode间随机查询数据.
比如: 我的schema.xml中有四个dataNode,  有一张不分库不分表的表abc只用了其中一个dataNode1, 
`<table name="abc" dataNode="dn1" />
<dataNode name="dataNode1" dataHost="mysql_115" database="mycat50" />
<dataNode name="dataNode2" dataHost="mysql_115" database="mycat51" />
<dataNode name="dataNode3" dataHost="mysql_117" database="mycat70" />
<dataNode name="dataNode4" dataHost="mysql_117" database="mycat71" />`
在执行: select * from abc where id='xxx@@@aaa'时, 就会随机的在 dataNode1, dataNode2, dataNode3和dataNode4四个注册的dataNode间随机读取数据. 而不是仅在dataNode1上查询, join查询时也是如此.

**Comment by ZzzCrazyPig** [comment]
你好，是用什么工具连接mycat测出来的？普通的mysql client命令行工具？还有，能提供以下命令**在mycat8066端口执行下的结果**？

```sql
explain select * from abc where id='xxx@@@aaa';
```

> 请多执行几次，看路由结果是否真的是随机的

**Comment by rayoo** [comment]
官方release版本有这个问题, 我down的新代码已经没这个问题了
