### ISSUE TITLE
mycat直接执行存储过程，一直处于执行中状态，无法显示结果

### ISSUE THREAD

**Issue by suxl** [MyCATApache/Mycat-Server#143]
在mycat中直接执行mysql中的存储过程，一直处于执行中状态，无法显示结果。
目前可以通过/*!mycat: sql=select * from base_user where id_=1;*/CALL proc_test(); 这个注解的方式正常执行，但是需要把存储过程中的sql写到注解中，感觉有些不是很方便，不知道还有没有其他方式能正常执行！

**Comment by apachemycat** [comment]
目前还找不到更好的办法来确定存储过程路由到那些节点

**Comment by sohudo** [comment]
语句写错误了
/*!mycat: sql=select * from base_user where id_=1 */CALL proc_test();
