### ISSUE TITLE
Avg 函数别名结果不对

### ISSUE THREAD

**Issue by liuhuawu** [MyCATApache/Mycat-Server#1435]
mycat1.6 Avg 函数别名结果不对：

mysql> select avg(cust_id) GG from customer t;

+---------------+
| GG            |
+---------------+
| 2001243655000 |
+---------------+
1 row in set
没有别名结果是正确的：
mysql> select avg(cust_id)  from customer t;
+----------------+
| AVG0           |
+----------------+
| 200124365.5000 |
+----------------+
1 row in set

**Comment by ZzzCrazyPig** [comment]
请提供 `customer` 在 `schema.xml` 的配置信息，还有 `server.xml` 里面 `<system>` 片段的配置信息

**Comment by liuhuawu** [comment]
schema.xml
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
    <schema name="cloudb" checkSQLschema="false" sqlMaxLimit="100">
        <table name="customer" dataNode="dn1,dn2" rule="cust_id" ruleRequired="false" type="rule" indexCol="cust_id"/>
    </schema>
    <dataNode name="dn1" dataHost="mysql1" database="db1"/>
    <dataNode name="dn2" dataHost="mysql2" database="db2"/>
    <dataHost balance="1" maxCon="1000" minCon="5" name="mysql1" writeType="0" switchType="3" slaveThreshold="100" dbType="mysql" dbDriver="native">
        <heartbeat>show status like 'wsrep%'</heartbeat>
        <writeHost host="hostM1" url="192.x.x.x:3306" password="testbpt" user="galera"/>
        <writeHost host="hostR1" url="192.x.x.x:3306" password="testbpt" user="galera"/>
        <writeHost host="hostR2" url="192.x.x.x:3306" password="testbpt" user="galera"/>
    </dataHost>
    <dataHost balance="1" maxCon="1000" minCon="5" name="mysql2" writeType="0" switchType="3" slaveThreshold="100" dbType="mysql" dbDriver="native">
        <heartbeat>show status like 'wsrep%'</heartbeat>
        <writeHost host="hostM1" url="192.x.x.x:4306" password="testbpt" user="galera"/>
        <writeHost host="hostR1" url="192.x.x.x:4306" password="testbpt" user="galera"/>
        <writeHost host="hostR2" url="192.x.x.x:4306" password="testbpt" user="galera"/>
    </dataHost>
</mycat:schema>

**Comment by liuhuawu** [comment]
schema.xml
`<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
    <schema name="cloudb" checkSQLschema="false" sqlMaxLimit="100">
        <table name="customer" dataNode="dn1,dn2" rule="cust_id" ruleRequired="false" type="rule" indexCol="cust_id"/>
    </schema>
    <dataNode name="dn1" dataHost="mysql1" database="db1"/>
    <dataNode name="dn2" dataHost="mysql2" database="db2"/>
    <dataHost balance="1" maxCon="1000" minCon="5" name="mysql1" writeType="0" switchType="3" slaveThreshold="100" dbType="mysql" dbDriver="native">
        <heartbeat>show status like 'wsrep%'</heartbeat>
        <writeHost host="hostM1" url="192.x.x.x:3306" password="testbpt" user="galera"/>
        <writeHost host="hostR1" url="192.x.x.x:3306" password="testbpt" user="galera"/>
        <writeHost host="hostR2" url="192.x.x.x:3306" password="testbpt" user="galera"/>
    </dataHost>
    <dataHost balance="1" maxCon="1000" minCon="5" name="mysql2" writeType="0" switchType="3" slaveThreshold="100" dbType="mysql" dbDriver="native">
        <heartbeat>show status like 'wsrep%'</heartbeat>
        <writeHost host="hostM1" url="192.x.x.x:4306" password="testbpt" user="galera"/>
        <writeHost host="hostR1" url="192.x.x.x:4306" password="testbpt" user="galera"/>
        <writeHost host="hostR2" url="192.x.x.x:4306" password="testbpt" user="galera"/>
    </dataHost>
</mycat:schema>`

**Comment by liuhuawu** [comment]
server.xml
`<!DOCTYPE mycat:server SYSTEM "server.dtd">
<mycat:server xmlns:mycat="http://io.mycat/">
    <system>
        <property name="useHandshakeV10">1</property>
        <property name="useSqlStat">1</property>
        <property name="useGlobleTableCheck">0</property>
        <property name="sequnceHandlerType">1</property>
        <property name="processorBufferPoolType">0</property>
        <property name="handleDistributedTransactions">1</property>
        <property name="useOffHeapForMerge">1</property>
        <property name="memoryPageSize">1m</property>
        <property name="spillsFileBufferSize">1k</property>
        <property name="useStreamOutput">0</property>
        <property name="systemReserveMemorySize">384m</property>
        <property name="useZKSwitch">true</property>
        <property name="idleTimeout">10000</property>
    </system>
    
    <user name="root">
        <property name="password">root</property>
        <property name="schemas">cloudb</property>
        <property name="benchmark">30</property>
    </user>
</mycat:server>`

**Comment by nimei1248** [comment]
版本1.6-releases测试正常

**有别名：**
[104 11:42:26] test@10.1.1.1[mule] >select avg(id) xxx from t_announce;  
+-------------------+
| XXX               |
+-------------------+
| 5.333333333333333 |
+-------------------+
1 row in set (0.26 sec)

**无别名：**
[105 11:42:31] test@10.1.1.1[mule] >select avg(id)  from t_announce;   
+-------------------+
| AVG0              |
+-------------------+
| 5.333333333333333 |
+-------------------+
1 row in set (0.29 sec)

**Comment by wqyxx** [comment]
package io.mycat.sqlengine.mpp 中的UnsafeRowGrouper类中方法processAvgFieldPrecision()中的isAvgField方法写死了。导致avg函数列加别名后结果错误。代码如下：
/**
	 * 处理AVG列精度
	 */
	private void processAvgFieldPrecision() {
		for(String key : columToIndx.keySet()) {
			if(isAvgField(key)) { // AVG列的小数点精度默认取SUM小数点精度, 计算和返回的小数点精度应该扩展4
				ColMeta colMeta = columToIndx.get(key);
				colMeta.decimals += 4;
			}
		}
	}

private boolean isAvgField(String columnName) {
		Pattern pattern = Pattern.compile("AVG([1-9]\\d*|0)SUM");
		Matcher matcher = pattern.matcher(columnName);
		return matcher.find();
	}
修改后的方法为：
private void processAvgFieldPrecision() {
		for (int i = 0; i < mergCols.length; i++) {
			if (mergCols[i].mergeType == MergeCol.MERGE_AVG) {
				for (String key : columToIndx.keySet()) {
					// AVG列的小数点精度默认取SUM小数点精度, 计算和返回的小数点精度应该扩展4
					if (columToIndx.get(key).colIndex == mergCols[i].colMeta.avgSumIndex) {
						ColMeta colMeta = columToIndx.get(key);
						colMeta.decimals += 4;
					}
				}
			}
		}
	}

**Comment by zagnix** [comment]
代码怎么不提交pr？

**Comment by ZzzCrazyPig** [comment]
@wqyxx  分析很到位 当初没考虑到别名的情况，修改后的代码应该如同你上述修改的，然后在最后计算完break就可以:

```java
private void processAvgFieldPrecision() {
    for (int i = 0; i < mergCols.length; i++) {
        if (mergCols[i].mergeType == MergeCol.MERGE_AVG) {
            for (String key : columToIndx.keySet()) {
            // AVG列的小数点精度默认取SUM小数点精度, 计算和返回的小数点精度应该扩展4
                if (columToIndx.get(key).colIndex == mergCols[i].colMeta.avgSumIndex) {
                    ColMeta colMeta = columToIndx.get(key);
                    colMeta.decimals += 4;
                    break;
                }
            }
        }
    }
}
```

**Comment by yanjunli** [comment]
这个问题 解决了吗？
