### ISSUE TITLE
ehcache-core包是否有问题

### ISSUE THREAD

**Issue by andylee1890** [MyCATApache/Mycat-Server#1442]
Description	Resource	Path	Location	Type
The type net.sf.ehcache.CacheManager cannot be resolved. It is indirectly referenced from required .class files	EnchachePooFactory.java	/Mycat-Server/src/main/java/io/mycat/cache/impl	line 1	Java Problem

**Comment by huangyiminghappy** [comment]
请问能把出错场景详细描述一下吗？
