### ISSUE TITLE
这两天在做mycat的技术调研,总结以下问题

### ISSUE THREAD

**Issue by andylee1890** [MyCATApache/Mycat-Server#1451]
这两天在做Mycat的技术调用,考虑可能系统会使用到该中间件,于是做了一些技术调研,总结了以下问题,请问是否准确, 如有不对,请大神们多多指正.

Mycat潜在存在的问题						
						
	1.语法:					
	  Mycat有自定义的一套SQL解析语法规则,如Mycat的注解语法,负责指定查询SQL指向的schema.	兼容性不足,Mycat并不是适合在项目开发中途引入,如果打算使用Mycat建议在项目设计之初将其考虑在内					
						
	2.强一致性查询					
	  在金融系统中,大多数的业务场景需要保证数据的强一致性,当使用数据库层使用Mycat中间件代理是会出现在一个事务当中,前一次的数据库"写"的操作Mycat指向的是主库,而下一次"查"的操作Mycat指向了从库,出现数据不一致,此时须特殊指定,将"查"的操作也要指向主库	.				
						
	3.不支持夸库事务,跨分片的事务,目前只是弱XA模式.					
						
	4.分片的table,目前不能执行lock table 这样的语句,这种语句会随机分发到某个节点,也不会全部分片全锁,	经常导致死锁的问题,此类问题经常出现在dump导入导出过程中。					
						
	5.SQL解析错误导致致命后果,使用时须特别注意					
	  (1).where 写成wher 导致全表数据删除:delete from tablename wher id=x;					
	  (2).where前面没有空格导致全表数据被:upate:update tablename set a=bwhere id=x;					
	  (2).where 前面没有空格导致全表查询:select * from tablename set a=bwhere id=x;					
	  (4).目前sql解析器采用Druid,在某些sql,例order，group，sum，count 条件下,会出现兼容问题:select t.name as name1 from test order by t.name

**Comment by ausky** [comment]
我也是刚研究，一起讨论下； 
1: 这个问题，我觉得不应该吧，我看文档说有 后期引入的案例的；你的问题我没怎么理解；
2: 这个可以通过分片规则解决吧？ 正如 文档说的 80%  的 都可以通过  全局表 + e-r 配置；经测试 当前开启事务或者说 autocommit 为 false 情况， 是不会读 从库的； 
3: 这个我是完全不知道； 正在看
4,5 :  这是我的测试，不知道是不是这个意思
`mysql> explain LOCK TABLES goods  WRITE;
+-----------+-------------------------+
| DATA_NODE | SQL                     |
+-----------+-------------------------+
| dn1       | LOCK TABLES goods WRITE |
| dn4       | LOCK TABLES goods WRITE |
+-----------+-------------------------+
2 rows in set (0.07 sec)

mysql> delete from goods wher id=1;
ERROR 1105 (HY000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'wher id=1' at line 1
mysql> 
`

**Comment by ausky** [comment]
不过 explain 确实会丢弃错误的 sql 部分
`mysql> explain select * from goods2 wher idx=1;
+-----------+-------------------------------------+
| DATA_NODE | SQL                                 |
+-----------+-------------------------------------+
| dn1       | SELECT * FROM goods2 wher LIMIT 100 |
+-----------+-------------------------------------+
1 row in set (0.00 sec)
`

**Comment by andylee1890** [comment]
分片事务确实不支持,写了个springmvc+mybatis的demo,连接的是mycat,用的切面事务,回滚级别是Throwable, 在一个事务中,执行插入后主动抛出异常后,查看数据库,插入成功,并未回滚. 事务没有问题,连接单个mysql数据库试过了

**Comment by andylee1890** [comment]
前两天跟一个近20年的架构师在聊这个中间件, 刚好他们在项目上线前也想将这款中间件引入项目当中,但是到临近上线前,他将这个插件从项目中卸载. 
给出的评价总结如下:
1.老多坑了;
2.这插件根本还是不可用状态;
3.....不可描述.

真事, 他们的项目本月才上线的.

这几天我也是对这个插件做了一些调查, 确实印证了一些说法.

其实我比较希望大家能把各自踩过坑的经历分享一下.

**Comment by ausky** [comment]
坑我觉得应该是有的，不过我很好奇 为啥到上线前才觉得有问题不用？ 还有他们最终选择的什么方案呀，我感觉跨分片本事就是个很复杂的问题

**Comment by andylee1890** [comment]
由项目急着上线,卸载mycat后,自己实现了一套简单jdbc的代理, 将有事务的查询指向主库,将无事务的查询指向从库,利用mysql自带的同步数据功能进行同步. 
这是个临时方案, 这种做法也是有延时问题的,在访问量集中的时候从库的实际利用率也不高,比如客户购买一笔,客户马上去看订单,查订单应该没有事务,就会因延时查不到.
主从分离延时是避免不了的,如果对实时性或者一致性有要求的场景就不适合用读写分离方式来做.
集群模式可以满足强一致的要求,集群模式下也不需要做读写分离了,但是集群的成本有点高,目前来说考虑成本这不是首选方案.
mycat中间件的理念好,但是用作生产使用,一定要弄清楚他的坑,目前我在按照官方文档的作法在测一测弱XA模式

**Comment by ausky** [comment]
我简单的看了下代码，mycat 自身有事务的查询是不会分配到 读库的； 因为我们默认是 autocommit = false 导致没法看到读写分离了； 查看代码看到autocommit=false或者开启事务的时候 是不会分配到 读库的； 读写都是在写库 ； 我做的demo也是基于 mysql 自身的主从同步； 而且我看好像代码里面还有个从库是否同步完成的状态检测当前的从库是否可作读；不知道理解的对不对

**Comment by andylee1890** [comment]
今天写一个完整的Demo测试一下分片及事务
稍后将完整的文档发出来,昨天简单试了一下,数据回滚是正常,等下完整的测一下.
1.分片枚举：sharding-by-intfile 							
2.主键范围：auto-sharding-long 							
3.一致性hash：sharding-by-murmur 							
4.字符串hash解析：sharding-by-stringhash 							
5.按日期（天）分片：sharding-by-date 							
6.按单月小时拆分：sharding-by-hour 							
7.自然月分片：sharding-by-month 							
8.取模分片(ER分片):mod-long

**Comment by andylee1890** [comment]
想看下他的分片这块代码的实现,导入源码报错

**Comment by ausky** [comment]
嗯？我源码下载运行没问题呀 ，你不是下载的完整的mycat-server?

**Comment by rongbo-j** [comment]
已经存在的项目不建议使用mycat，坑比较多，很多简单的sql语法都报错，天天都在改代码

**Comment by ausky** [comment]
那不用mycat用其他类似的框架方案还是自己做呢，或者放弃分片？

**Comment by dearloki** [comment]
使用了读写分离的特性，框架控制的默认是自动提交，事务走主库，非事务走的是读库

**Comment by rongbo-j** [comment]
准备研究下youtube的vitess中间件，比较成熟，官方地址http://vitess.io/

**Comment by andylee1890** [comment]
@dearloki  读写分离满足不了强一致的需求

**Comment by andylee1890** [comment]
这两天写了个demo测了一下mycat 包括分片事务及分片锁
https://github.com/andylee1890/TestWeb.git

**Comment by andylee1890** [comment]
接下来部署一个一个节点的mycat服务,将业务库切到mycat, 所有表暂时设置成全局表, 疏通一下sql是否都正常

**Comment by magicdoom** [comment]
1.语法:					
  Mycat有自定义的一套SQL解析语法规则,如Mycat的注解语法,负责指定查询SQL指向的schema.	兼容性不足,Mycat并不是适合在项目开发中途引入,如果打算使用Mycat建议在项目设计之初将其考虑在内	

**mycat额外引入的注解等你可以不用，其他都是标准的mysql语法，有些是分布式情况下引起，可以通过合理的设计来解决，比如ER、全局表**				
					
2.强一致性查询					
  在金融系统中,大多数的业务场景需要保证数据的强一致性,当使用数据库层使用Mycat中间件代理是会出现在一个事务当中,前一次的数据库"写"的操作Mycat指向的是主库,而下一次"查"的操作Mycat指向了从库,出现数据不一致,此时须特殊指定,将"查"的操作也要指向主库	.	

**mycat默认在事务里读都走主库，你供事务可以解决这个问题，否则你可以用注解**			
					
3.不支持夸库事务,跨分片的事务,目前只是弱XA模式.		

**这个后续会改进，大部分场景够用，需要有个平衡**			
					
4.分片的table,目前不能执行lock table 这样的语句,这种语句会随机分发到某个节点,也不会全部分片全锁,	经常导致死锁的问题,此类问题经常出现在dump导入导出过程中。		

	**尽量避免lock，dump可以加参数跳过，1.6.5有人提交支持了lock table语句**		
					
5.SQL解析错误导致致命后果,使用时须特别注意					
  (1).where 写成wher 导致全表数据删除:delete from tablename wher id=x;					
  (2).where前面没有空格导致全表数据被:upate:update tablename set a=bwhere id=x;					
  (2).where 前面没有空格导致全表查询:select * from tablename set a=bwhere id=x;					
  (4).目前sql解析器采用Druid,在某些sql,例order，group，sum，count 条件下,会出现兼容问题:se

**这个是druid的问题，之前给druid提过pr，不过他们认为这个不是问题，汗。。。你们可以去druid那边请愿**

**Comment by skyesx** [comment]
> mycat默认在事务里读都走主库，你供事务可以解决这个问题，否则你可以用注解

这里的事务指代的是读事务还是写事务？
