### ISSUE TITLE
childTable Insert Error

### ISSUE THREAD

**Issue by plumstar** [MyCATApache/Mycat-Server#1462]
Version:2.0-dev
Log:
find root parent's node sql select table_name.null from table_name where  table_name.null=2
errorResponse 1054 Unknown column 'table_name.null' in 'field list'

It's ok In 1.6-RELEASE version.

**Comment by huangyiminghappy** [comment]
什么表结构以及sql语句是什么样的，配置贴出来，谢谢

**Comment by songwie** [comment]
2.0早就废弃了

**Comment by plumstar** [comment]
@songwie 官网没说明啊，2.0的新特性会实现吗

**Comment by songwie** [comment]
2.0基本不会用了  会从1.6开始递归 慢慢加 2.0的特效会分散到各个版本



songwie2009@163.com
 
From: plumstar
Date: 2017-04-27 18:31
To: MyCATApache/Mycat-Server
CC: 从零开始; Mention
Subject: Re: [MyCATApache/Mycat-Server] childTable Insert Error (#1462)
@songwie 官网没说明啊，2.0的新特性会实现吗

**Comment by plumstar** [comment]
@songwie 好的，多谢~
