### ISSUE TITLE
 register err java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by ucjmh** [MyCATApache/Mycat-Server#1467]
INFO   | jvm 1    | 2017/04/26 22:29:42 | 2017-04-26 22:29:42,391 [ERROR][$_NIOREACTOR-17-RW] register err java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/04/26 22:29:42 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 
INFO   | jvm 1    | 2017/04/26 22:29:48 | 2017-04-26 22:29:48,391 [ERROR][$_NIOREACTOR-18-RW] register err java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/04/26 22:29:48 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 

每隔6s就会打一次这个 这个可以怎么关掉吗？INFO   | jvm 1    | 2017/04/26 22:29:42 | 2017-04-26 22:29:42,391 [ERROR][$_NIOREACTOR-17-RW] register err java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2017/04/26 22:29:42 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/04/26 22:29:42 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 
INFO   | jvm 1    | 2017/04/26 22:29:48 | 2017-04-26 22:29:48,391 [ERROR][$_NIOREACTOR-18-RW] register err java.nio.channels.ClosedChannelException
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:188)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.FrontendConnection.register(FrontendConnection.java:444)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.NIOReactor$RW.register(NIOReactor.java:160)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:92)
INFO   | jvm 1    | 2017/04/26 22:29:48 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/04/26 22:29:48 |  (io.mycat.net.NIOReactor$RW:NIOReactor.java:163) 

每隔6s就会打一次这个 这个可以怎么关掉吗？

**Comment by magicdoom** [comment]
你前面加了lvs之类的负载了吧   用1.6.5

**Comment by ojhtyy** [comment]
我用1.6版本也遇到这问题, 用了1.6.5 或 1.7后, 可以解决以上问题,   但是引入了新的问题 :我做了读写分离 写操作正常, 读操作每10秒会在mysql主从库切换执行 , 并不能把读操作一直分配到从库 , 如下
mysql> select @@server_id,sysdate();
+-------------+---------------------+
| @@server_id | sysdate()           |
+-------------+---------------------+
|           2 | 2017-05-09 18:23:44 |
+-------------+---------------------+
1 row in set (0.00 sec)

mysql> select @@server_id,sysdate();
+-------------+---------------------+
| @@server_id | sysdate()           |
+-------------+---------------------+
|           1 | 2017-05-09 18:23:46 |
+-------------+---------------------+

同时日志报错如下:
2017-05-09 18:23:45.796  WARN [$_NIOREACTOR-1-RW] (io.mycat.backend.heartbeat.MySQLDetector.onResult(MySQLDetector.java:159)) - found MySQL master/slave Replication err !!! DBHostConfig [hostName=hostSlave, url=192.168.2.34:3306], {}
2017-05-09 18:23:45.797  INFO [$_NIOREACTOR-1-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:510)) - close connection,reason:no handler ,MySQLConnection [id=21, lastTime=1494325425789, user=fabaotest, schema=gzsmallroutdb, old shema=gzsmallroutdb, borrowed=false, fromSlaveDB=false, threadId=3714, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=192.168.2.34, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]

**Comment by 1042904326** [comment]
请问，你找到了原因了吗？我也遇到了
