### ISSUE TITLE
用MySQL Connector Python的pooling连接mycat，无法释放connection

### ISSUE THREAD

**Issue by Andsons** [MyCATApache/Mycat-Server#1474]
利用Python的连接池连接MyCat，close时出错，见代码：
cnxpool = mysql.connector.pooling.MySQLConnectionPool()
cnx = cnxpool.get_connection()
cnx.close()   ##这里出错

报错：
在connection.py的line 177, in _auth_switch_request 抛出错误errors.get_exception(packet)
可能是MyCat对连接池状态下cnx.close()解析错误

**Comment by ZzzCrazyPig** [comment]
请提供:

- Mycat的版本
- Mycat后台的异常日志

**Comment by Andsons** [comment]
MyCat版本：Mycat-server-1.6-RELEASE-20161028204710-linux
日志：对于mysql-connector-python连接失败，MyCat后台只是记录登陆与退出，没有报错。
我猜测MyCat对SQL的转义出了问题

2017-05-xx 17:21:49.633  INFO [$_NIOREACTOR-34-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:194)) - [thread=$_NIOREACTOR-34-RW,class=ManagerConnection,id=271,host=192.168.2.62,port=9066,schema=xxxx]'root' login success
2017-05-16 17:21:49.635  INFO [$_NIOREACTOR-34-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:508)) - close connection,reason:quit cmd ,[thread=$_NIOREACTOR-34-RW,class=ManagerConnection,id=271,host=192.168.2.62,port=9066,schema=xxxx]

**Comment by Andsons** [comment]
MyCat版本：Mycat-server-1.6-RELEASE-20161028204710-linux
日志：对于mysql-connector-python连接失败，MyCat后台只是记录登陆与退出，没有报错。
我猜测MyCat对SQL的转义出了问题

2017-05-xx 17:21:49.633  INFO [$_NIOREACTOR-34-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:194)) - [thread=$_NIOREACTOR-34-RW,class=ManagerConnection,id=271,host=192.168.2.62,port=9066,schema=xxxx]'root' login success
2017-05-16 17:21:49.635  INFO [$_NIOREACTOR-34-RW] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:508)) - close connection,reason:quit cmd ,[thread=$_NIOREACTOR-34-RW,class=ManagerConnection,id=271,host=192.168.2.62,port=9066,schema=xxxx]

**Comment by Andsons** [comment]
复现代码
import mysql.connector.pooling
cnxpool = mysql.connector.pooling.MySQLConnectionPool(pool_name = "mypool", pool_size=5, pool_reset_session=True, **config)
cnx = cnxpool.get_connection()
cnx.close()

**Comment by ZzzCrazyPig** [comment]
从你给的Mycat日志，好像看不到报错信息？

**Comment by Andsons** [comment]
确实看不到错误，咨询了另一位committer，好像也看不出什么问题。

**Comment by ZzzCrazyPig** [comment]
噢 我知道了 你连了9066端口- -。不是连的8066么？

**Comment by Andsons** [comment]
不是9066端口，下面是我的连接配置项。结合上面的代码，这个问题可以在自己电脑上复现
config = {
    "user":       "root",
    "password":   "123456",
    "host":       "192.168.2.62",
    "port":       8066,
    "database":   "FPDB",
    "charset":    "utf8"
}

**Comment by ZzzCrazyPig** [comment]
```
2017-05-xx 17:21:49.633 INFO [$_NIOREACTOR-34-RW] (io.mycat.net.handler.FrontendAuthenticator.success(FrontendAuthenticator.java:194)) - [thread=$_NIOREACTOR-34-RW,class=ManagerConnection,id=271,host=192.168.2.62,port=9066,schema=xxxx]'root' login success
2017-05-16 17:21:49.635 INFO [$_NIOREACTOR-34-RW] 
```
上面的 **9066** 是怎么回事

**Comment by Andsons** [comment]
我刚刚复现了一下，除了info连接正确之外，还有warn：SET @@session.autocommit = OFF is not recoginized and ignored ，连接失败并没有报错。
管理端口，是因为装了mycat-web，定时登陆。
上面给的日志和Python的连接错误没关系。
