### ISSUE TITLE
mycat1.6.0版本，分片表的SQL包含聚合函数，返回结果错误

### ISSUE THREAD

**Issue by aboutcode** [MyCATApache/Mycat-Server#1487]
mysql5.6.0版本下，执行如下SQL：
SELECT MAX(create_time) AS maxTime, min(create_time) AS minTime FROM ord_order;

返回结果错误，每次返回的maxTime和minTime都会产生变化。

我怀疑mycat没有执行merge操作，每次返回的是某一个分库的执行结果：
![image](https://cloud.githubusercontent.com/assets/10251367/25892756/00547826-35a8-11e7-8bd1-6d1e34e05553.png)

**Comment by zagnix** [comment]
https://github.com/MyCATApache/Mycat-Server/pull/1518  这个pr修复了该问题
