### ISSUE TITLE
对ORACLE数据库支持不是很好

### ISSUE THREAD

**Issue by vihcle** [MyCATApache/Mycat-Server#1493]
1、想Oracle数据库插入date类型的数据，如果值中带有毫秒的数值，完全无法插入。
2、Oracle语法解析器如何正确匹配？根据语句使用oracleStatementParser?

**Comment by magicdoom** [comment]
1.用to_date函数
2.配置oracle类型

**Comment by vihcle** [comment]
datanode是配置的oracle数据库类型。如果使用to_date()函数，其他数据库就无法执行了吧？
页面发来的时间值，在SQL语句中当成整数操作，导致oracle数据库报类型不匹配。。。

**Comment by magicdoom** [comment]
你后端是oracle就用oracle的sql语法，其他数据库用其他的语法
