### ISSUE TITLE
向oracle数据库插入日期，对字符串不会自动添加to_date()函数

### ISSUE THREAD

**Issue by vihcle** [MyCATApache/Mycat-Server#1495]
插入date值时，不会对值进行处理，添加to_date()函数。。。

**Comment by Fxdemon** [comment]
有2种方式：
1.将Oracle数据库字段类型设置为date类型 
2.在MyBatis 的配置文件中进行相应数据库类型和POJO类型的映射。

**Comment by vihcle** [comment]
Mycat server现在只支持MYSQL驱动连接，使用Oracle驱动无法连接到mycat server! 所以方案二是行不通的啊。。。。。。。。

**Comment by magicdoom** [comment]
mycat是不会自动加to_data函数的  这个要应用程序来加
