### ISSUE TITLE
mycat查询时where条件为子查询会遍历所有节点？

### ISSUE THREAD

**Issue by ccrccr0603** [MyCATApache/Mycat-Server#1497]
版本是1.6，test1 是分片表，CLIENT_NO 是分片key，test2 是全局表，explain时发现会分发到每一个节点执行。
SELECT
	COUNT(1) AS COUNT0
FROM
	test1 T
WHERE
	T.CLIENT_NO = (
		SELECT
			Client_No
		FROM
			test2 c
		WHERE
			c.Card_No = '12345671234567'
		AND c.Card_No_End2 = Substr('12345671234567', - 2, 2)
		LIMIT 1
	)
AND T.TRAN_DATE >= '20160201'
AND T.TRAN_DATE <= '20160810'；

**Comment by yanjunli** [comment]
releases 版本吗？

**Comment by ccrccr0603** [comment]
是releases版本

**Comment by yanjunli** [comment]
最近对这种情况的子查询做了改进.
像你贴的这种情况,子查询会先执行.获取到结果后,与外部主查询合并，再路由。根据路由结果看在哪些分片上执行。
可以下载最新代码验证这个问题。
