### ISSUE TITLE
group by 语句跨分片查询结果不对

### ISSUE THREAD

**Issue by suxl** [MyCATApache/Mycat-Server#150]
select user_id from sam_glucose group by user_id 
实际只能查询出两个结果，但是这个语句查询出了3条结果，没有把两个分片的数据合并；

使用 select user_id,count(*) from sam_glucose group by user_id  这样的写法就自动合并为2条记录了。
跨分片的情况下，必须要加count关键字才可以正确分组，这块最好能优化一下。

**Comment by sohudo** [comment]
已解决
https://github.com/MyCATApache/Mycat-Server/pull/157
