### ISSUE TITLE
使用prepare，出现路由问题 

### ISSUE THREAD

**Issue by Youxrjack** [MyCATApache/Mycat-Server#1501]
mysql> show @@datanode;
+------+-----------------+-------+-------+--------+------+------+---------+------------+----------+---------+---------------+
| NAME | DATHOST         | INDEX | TYPE  | ACTIVE | IDLE | SIZE | EXECUTE | TOTAL_TIME | MAX_TIME | MAX_SQL | RECOVERY_TIME |
+------+-----------------+-------+-------+--------+------+------+---------+------------+----------+---------+---------------+
| dn5  | mysqlab/cash    |     1 | mysql |      0 |    0 | 1000 |       3 |          0 |        0 |       0 |            -1 |
| m01  | mysqlab/month01 |     1 | mysql |      0 |    0 | 1000 |       0 |          0 |        0 |       0 |            -1 |
| m02  | mysqlab/month02 |     1 | mysql |      0 |    0 | 1000 |       0 |          0 |        0 |       0 |            -1 |
| m03  | mysqlab/month03 |     1 | mysql |      0 |    0 | 1000 |       2 |          0 |        0 |       0 |            -1 |
| m04  | mysqlab/month04 |     1 | mysql |      0 |    1 | 1000 |       3 |          0 |        0 |       0 |            -1 |
| m05  | mysqlab/month05 |     1 | mysql |      0 |    0 | 1000 |       1 |          0 |        0 |       0 |            -1 |
| m06  | mysqlab/month06 |     1 | mysql |      0 |    0 | 1000 |       1 |          0 |        0 |       0 |            -1 |
| m07  | mysqlab/month07 |     1 | mysql |      0 |    0 | 1000 |       3 |          0 |        0 |       0 |            -1 |
| m08  | mysqlab/month08 |     1 | mysql |      0 |    8 | 1000 |    5699 |          0 |        0 |       0 |            -1 |
| m09  | mysqlab/month09 |     1 | mysql |      0 |    0 | 1000 |       1 |          0 |        0 |       0 |            -1 |
| m10  | mysqlab/month10 |     1 | mysql |      0 |    0 | 1000 |       0 |          0 |        0 |       0 |            -1 |
| m11  | mysqlab/month11 |     1 | mysql |      0 |    0 | 1000 |       0 |          0 |        0 |       0 |            -1 |
| m12  | mysqlab/month12 |     1 | mysql |      0 |    0 | 1000 |       0 |          0 |        0 |       0 |            -1 |
+------+-----------------+-------+-------+--------+------+------+---------+------------+----------+---------+---------------+

mysql> explain prepare stmt from 'SELECT * FROM cash.mmm;';
+-----------+---------------------------------------------+
| DATA_NODE | SQL                                         |
+-----------+---------------------------------------------+
| m09       | prepare stmt from 'SELECT * FROM cash.mmm;' |
+-----------+---------------------------------------------+
1 row in set (0.00 sec)

mysql> explain prepare stmt from 'SELECT * FROM cash.mmm;';
+-----------+---------------------------------------------+
| DATA_NODE | SQL                                         |
+-----------+---------------------------------------------+
| dn5       | prepare stmt from 'SELECT * FROM cash.mmm;' |
+-----------+---------------------------------------------+
1 row in set (0.00 sec)

mysql> explain prepare stmt from 'SELECT * FROM cash.mmm;';
+-----------+---------------------------------------------+
| DATA_NODE | SQL                                         |
+-----------+---------------------------------------------+
| m09       | prepare stmt from 'SELECT * FROM cash.mmm;' |
+-----------+---------------------------------------------+
1 row in set (0.00 sec)

mysql> explain prepare stmt from 'SELECT * FROM cash.mmm;';
+-----------+---------------------------------------------+
| DATA_NODE | SQL                                         |
+-----------+---------------------------------------------+
| m01       | prepare stmt from 'SELECT * FROM cash.mmm;' |
+-----------+---------------------------------------------+
1 row in set (0.00 sec)

**mmm表没有做切分，按理prepare是在默认节点dn5上执行，但是路由却随机到了各个节点，添加注释后，会选择默认节点dn5，如下，但是添加注释应是对于做了切分的表才使用的！？**

mysql> explain /*!mycat:sql=select 1 from mmm*/prepare stmt from 'SELECT * FROM cash.mmm;';
+-----------+---------------------------------------------+
| DATA_NODE | SQL                                         |
+-----------+---------------------------------------------+
| dn5       | prepare stmt from 'SELECT * FROM cash.mmm;' |
+-----------+---------------------------------------------+
1 row in set (0.00 sec)

**Comment by ZzzCrazyPig** [comment]
不支持prepare语句

**Comment by Youxrjack** [comment]
1.6开始不是支持了吗？

**Comment by ZzzCrazyPig** [comment]
是prepare协议，prepare语句不支持

**Comment by Youxrjack** [comment]
那我要使用就只能通过注解去使用了？

**Comment by huangyiminghappy** [comment]
支持jdbc的preparestatement的访问，但是直接prepare语句是不支持的。

**Comment by ZzzCrazyPig** [comment]
恩 你可以看看注解是否满足你的要求，这个应该很少人用过

**Comment by Youxrjack** [comment]
好的，谢谢
