### ISSUE TITLE
sql取别名和字段名一致时会报找不到table的错误

### ISSUE THREAD

**Issue by zerocc123** [MyCATApache/Mycat-Server#1505]
类似SELECT user_id as USER_ID
FROM E_USER这样的语句运行在mycat下会报错，但是SELECT user_id as USER_ID1
FROM E_USER这样的就不会报错

**Comment by yanjunli** [comment]
可以用下1.6.5 版本

**Comment by yanjunli** [comment]
新版本已经修复了这个问题.
