### ISSUE TITLE
mycat-1.6出现异常同时mycat到mysql的连接数会超过maxCon

### ISSUE THREAD

**Issue by zhaohaolin** [MyCATApache/Mycat-Server#1524]
出现异常的部分日志
`INFO   | jvm 1    | 2017/06/06 19:30:16 | } java.io.IOException: the max activeConnnections size can not be max than maxconnections
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:411)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:134)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.execute(MultiNodeQueryHandler.java:184)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.server.NonBlockingSession.checkDistriTransaxAndExecute(NonBlockingSession.java:185)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:147)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:288)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 1    | 2017/06/06 19:30:16 |       at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2017/06/06 19:30:16 |  (io.mycat.server.NonBlockingSession:NonBlockingSession.java:153) 
INFO   | jvm 1    | 2017/06/06 19:30:16 | 2017-06-06 19:30:16,385 [ERROR][$_NIOREACTOR-6-RW] the max activeConnnections size can not be max than maxconnections  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:410) `

同时连接数会超过配置的maxConn值
schema.xml部分配置如下：
`<mycat:schema xmlns:mycat="http://io.mycat/">
        <schema name="push_log" checkSQLschema="false" sqlMaxLimit="100">
                
                <table name="t_message_info_01" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_02" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_03" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_04" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_05" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_06" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_07" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_08" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_09" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_10" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_11" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_12" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_13" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_14" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_15" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_16" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_17" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_18" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_19" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_20" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_21" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_22" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_23" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_24" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_25" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_26" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_27" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_28" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_29" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_30" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_info_31" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                
                <table name="t_message_push_info_01" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_02" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_03" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_04" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_05" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_06" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_07" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_08" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_09" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_10" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_11" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_12" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_13" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_14" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_15" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_16" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_17" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_18" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_19" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_20" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_21" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_22" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_23" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_24" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_25" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_26" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_27" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_28" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_29" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_30" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
                <table name="t_message_push_info_31" primaryKey="ID" dataNode="dn1,dn2" rule="sharding-by-murmur" />
        </schema>
        <dataNode name="dn1" dataHost="dh1" database="push_log" />
        <dataNode name="dn2" dataHost="dh1" database="push_log2" />
        
        <dataHost name="dh1" maxCon="200" minCon="10" balance="0"
                          writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM1" url="host1:3306" user="xxx" password="xxx">
                	<readHost host="hostS2" url="host2:3306" user="xxx" password="xxx" />
                </writeHost>
        </dataHost>
</mycat:schema>`

**Comment by dingwpmz** [comment]
原因分析：
    PhysicalDatasource的getConnection方法是非线程安全的，是先获取当前活跃的连接数，然后再比较是否超过了最大连接数，这个过程不是一个原子操作，在多线程环境下存在问题；源码如下：
public void getConnection(String schema, boolean autocommit,
			final ResponseHandler handler, final Object attachment)
			throws IOException {
		
		// 从当前连接map中拿取已建立好的后端连接
		BackendConnection con = this.conMap.tryTakeCon(schema, autocommit);
		if (con != null) {
			
			//如果不为空，则绑定对应前端请求的handler
			takeCon(con, handler, attachment, schema);
			return;	
			
		} else {
			int activeCons = this.getActiveCount();// 当前最大活动连接
			if (activeCons + 1 > size) {// 下一个连接大于最大连接数
				LOGGER.error("the max activeConnnections size can not be max than maxconnections");
				throw new IOException("the max activeConnnections size can not be max than maxconnections");
			} else { // create connection
				LOGGER.info("no ilde connection in pool,create new connection for "	+ this.name + " of schema " + schema);
				createNewConnection(handler, attachment, schema);
			}
		}
	}

修复思路：
1、首先引入锁保护连接池中已存在的连接，活跃连接。
2、引入一个超时机制，如果连接池的连接数已达到最大连接数后，有在获取连接的地方等待一段时间（目前默认为30s）,如果30S后还是没有可用连接，将报超过最大连接数。
目前代码提交路径：https://github.com/dingwpmz/Mycat-Server.git
测试情况：已经在本地经过压力测试，并不会带来新的问题。
想进一步与你沟通，测试一下。
我的个人QQ:624324735

**Comment by yanjunli** [comment]
这个问题可以关闭了吗？@zhaohaolin

**Comment by lixiliang** [comment]
经过我的测试，发现maxCons数依然存在不准确的情况

**Comment by messi18** [comment]
这个问题依然存在。

**Comment by zhaohaolin** [comment]
可以关闭了
