### ISSUE TITLE
select a.*,b.a_type from table1 a join table2 b on a.id = b.id where b.time="201706021122"  出现a_type无法识别

### ISSUE THREAD

**Issue by 1042904326** [MyCATApache/Mycat-Server#1525]

**Comment by 1042904326** [comment]
新功能拆分sql为：select *,a_type from table1 a ;可是table1没有a_type这个字段  是不是拆分有问题

**Comment by yanjunli** [comment]
是哪个版本出现的这个问题？
这两个表的分片规则是怎样的

**Comment by 1042904326** [comment]
拉的最新的代码，一个是全局表，一个是分库的，这个应该给分表规则没有关系呀

**Comment by yanjunli** [comment]
可以把配置贴一下吗？
我这边没有再现.

table_0 是 全局表
mysql> select a.*,b.uid from subtest1 a join table_0 b on a.id = b.uid;
+----+-------+------+--------+---------+-----+
| id | name  | age  | depart | account | uid |
+----+-------+------+--------+---------+-----+
|  1 | Jack1 |   21 | IT     |     100 |   1 |
+----+-------+------+--------+---------+-----+
1 row in set (0.02 sec)

这是两个分片规则不一样的表做join.
mysql> select a.*,b.ote from subtest1 a join subtest2 b on a.id = b.id;
+----+------+------+--------+---------+----+------+
| id | name | age  | depart | account | id | ote  |
+----+------+------+--------+---------+----+------+
|  6 | Jack |   21 | IT     |     100 |  6 | NULL |
+----+------+------+--------+---------+----+------+
1 row in set (0.21 sec)

**Comment by 1042904326** [comment]
不好意思，这个可能是我自己修改的原因吧，谢谢
