### ISSUE TITLE
mycat - invalid route in sql, multi tables found but datanode has no interse

### ISSUE THREAD

**Issue by boonyachengdu** [MyCATApache/Mycat-Server#1533]
mycat - invalid route in sql, multi tables found but datanode has no interse

**Comment by yanjunli** [comment]
可以把sql 贴出来吗？
对于多表关联的情况.可以使用catlet.或者使用最新的版本,最新版本对表关联和子查询做了完善.

**Comment by nydsx** [comment]
Hello,
     I met the seem problem  ,Is it solved?
