### ISSUE TITLE
mycat select 1 问题

### ISSUE THREAD

**Issue by changealice** [MyCATApache/Mycat-Server#1537]
explain select 1 看每次返回的data_node都是不同的。
问题：
select 1 是不是mycat-server直接返回了，不在具体data_node执行就返回了?

**Comment by zagnix** [comment]
是随机下发一个datanode执行的

**Comment by changealice** [comment]
如果随机发，数据库连接池在检查连接是否有效就有个问题，用select 1 会随机在mycat 其中一个节点的连接有效，检查连接是不是又不起作用

**Comment by changealice** [comment]
@zagnix 如果随机发，数据库连接池在检查连接是否有效就有个问题，用select 1 会随机在mycat 其中一个节点的连接有效，检查连接是不是又不起作用

**Comment by ZzzCrazyPig** [comment]
@changealice 确实有你说的这个问题，你的本意应该是通过`select 1`这个语句要能够检测到mycat后端链接的所有mysql节点是否有效对吧？

**Comment by ZzzCrazyPig** [comment]
目前所有无表的select语句都会随机下发某个mysql节点执行的

**Comment by yanjunli** [comment]
select 1 应该是客户端发往 mycat 检查 与mycat之间的连接是否有效的。

mycat 与后端数据库有专门的心跳检查.会遍历后端连接.
这个问题应该是不存在的.

**Comment by changealice** [comment]
@ZzzCrazyPig 是的，老的oracle是通过select 1 from dual ，改造成mycat后就按照mycat select 1  来了，后面就遇到mysql八小时连接的问题了。
