### ISSUE TITLE
mysql   now（）函数无法使用

### ISSUE THREAD

**Issue by m949976269** [MyCATApache/Mycat-Server#1548]
插入数据时 ，时间 用now(）函数 ,提示
[SQL]INSERT INTO t_equipment (
 	equipment_id,
 	create_time,
  update_time,
  proversion
)
VALUES
('mc111', NOW(), NOW(), '1.1')

[Err] 1064 - com.alibaba.druid.sql.parser.ParserException: syntax error

**Comment by m949976269** [comment]
- [ ] 

- [1. ](`url`)

**Comment by yanjunli** [comment]
最新源码已经修复了这个问题

**Comment by m949976269** [comment]
但这个问题在1.6.5上依然有啊

**Comment by yanjunli** [comment]
跑下源码。源码应该是已经修复了的

**Comment by m949976269** [comment]
源码是哪个版本····

**Comment by yanjunli** [comment]
1.6.5

**Comment by m949976269** [comment]
![image](https://user-images.githubusercontent.com/13692628/27522823-6a8d102c-5a5b-11e7-90c3-d9c8cc86d2b7.png)
这个好久没更新了啊

**Comment by yanjunli** [comment]
https://github.com/MyCATApache/Mycat-Server
这是官网地址...
