### ISSUE TITLE
 日志报find no Route ，但是前台有结果

### ISSUE THREAD

**Issue by ch-13** [MyCATApache/Mycat-Server#1551]
select * from travelrecord order by id limit 2,2

ServerConnection [id=3, schema=TESTDB, host=192.168.1.5, user=root,txIsolation=3, autocommit=true, schema=TESTDB]SELECT * FROM `db1`.`travelrecord` LIMIT 0 err:java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `db1`.`travelrecord` LIMIT 0 java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `db1`.`travelrecord` LIMIT 0

这个要怎么做？

**Comment by yanjunli** [comment]
用的什么版本？

**Comment by ch-13** [comment]
Mycat-server-1.6-RELEASE.jar

**Comment by yanjunli** [comment]
用 Mycat-server-1.6.5-BETA.jar 看下有没有这个问题？

**Comment by ch-13** [comment]
@yanjunli 1.6.5-DEV  是这个版本？ 
https://github.com/MyCATApache/Mycat-download  这边只看到这个

**Comment by ch-13** [comment]
应该是Mycat-server-1.6-RELEASE.jar这个jar有问题。我现在还是用1.6分支，自己打了个包，就不报错了

**Comment by yanjunli** [comment]
嗯.现在  1.6.5 DEV 版就是在1.6 分支上开发的.
