### ISSUE TITLE
急求 数据查询问题

### ISSUE THREAD

**Issue by lmhfq** [MyCATApache/Mycat-Server#1553]
![image](https://user-images.githubusercontent.com/5369580/27674244-73e3da38-5cd7-11e7-811a-36c91ed5cbcb.png)
![image](https://user-images.githubusercontent.com/5369580/27674275-92c01426-5cd7-11e7-92ab-c301052876c2.png)
![image](https://user-images.githubusercontent.com/5369580/27674328-c84dbc38-5cd7-11e7-8d71-5d5e6632bd07.png)

问题出在哪里

**Comment by yanjunli** [comment]
什么版本.schema 是什么配置.日志有没有报错.

**Comment by lmhfq** [comment]
1.6-RELEASE
first-hash shop_id的 没有报错日志都能查出来 加上shop_id就正常 不加就多条

**Comment by zagnix** [comment]
@lmhfq  log4j.xml 开启debug，贴上详细的log信息.

**Comment by yanjunli** [comment]
建议 升级 1.6.5 版本.
