### ISSUE TITLE
select xxx from table where id='11' for update

### ISSUE THREAD

**Issue by muyl** [MyCATApache/Mycat-Server#1566]
执行语句select xxx from table where id='11' for update 无法正常锁定表【mysql】

**Comment by yanjunli** [comment]
需要使用 update 的注解 锁表

**Comment by muyl** [comment]
注解是这样用吗
/*!mycat:sql=select 1 from table */select * from table where id='xx' for update
我使用上面的没有正常锁住表

**Comment by yanjunli** [comment]
/*!mycat:sql=update table  */select * from table where id='xx' for update
注解中的sql 并不会真正到数据库执行。只是告诉mycat 后面的 select 语句是 for update 语句。
