### ISSUE TITLE
Mycat在抛出double free or corruption (out)后，当尝试重启时如果有查询请求过来会导致后端数据库的连接初始化过程失败

### ISSUE THREAD

**Issue by Ulyssesyi** [MyCATApache/Mycat-Server#1567]
Mycat在抛出double free or corruption (out)后，当尝试重启时如果有查询请求过来会导致后端数据库的连接初始化过程失败。
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] init backend myqsl source ,create connections total 10 for hostM1 index :0  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:303) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,141 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,142 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,142 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,216 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostS1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,220 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostS1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,220 [INFO ][$_NIOREACTOR-0-RW] init backend myqsl source ,create connections total 10 for hostM1 index :0  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:303) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,220 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,222 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,222 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,223 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,223 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,223 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,223 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,224 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,224 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:48:22 | 2017-07-14 11:48:22,224 [INFO ][$_NIOREACTOR-0-RW] no ilde connection in pool,create new connection for hostM1 of schema fastfood  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,188 [INFO ][WrapperSimpleAppMain] init result :finished 0 success 0 target count:10  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:328) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,188 [ERROR][WrapperSimpleAppMain] #!MyCat#posserver3 init failure  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:288) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,188 [INFO ][WrapperSimpleAppMain] init backend myqsl source ,create connections total 10 for hostM1 index :0  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:303) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,188 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,188 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,188 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,189 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,189 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,189 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,189 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,189 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,189 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,189 [INFO ][WrapperSimpleAppMain] no ilde connection in pool,create new connection for hostM1 of schema retail  (io.mycat.backend.datasource.PhysicalDatasource:PhysicalDatasource.java:413) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,271 [INFO ][$_NIOREACTOR-0-RW] init result :finished 0 success 0 target count:10  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:328) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,271 [ERROR][$_NIOREACTOR-0-RW] #!MyCat#posserver3 init failure  (io.mycat.backend.datasource.PhysicalDBPool:PhysicalDBPool.java:288) 
INFO   | jvm 2    | 2017/07/14 11:49:22 | 2017-07-14 11:49:22,272 [WARN ][$_NIOREACTOR-0-RW] ServerConnection [id=3, schema=fastfood, host=10.29.90.215, user=kqlpos,txIsolation=3, autocommit=true, schema=fastfood]SELECT `_id` FROM `t_bpartner` WHERE (`nShopID`='808901') AND (`_id`='1494301830948') AND (`bIsActive`='Y'), route={
INFO   | jvm 2    | 2017/07/14 11:49:22 |    1 -> dn1{SELECT `_id`
INFO   | jvm 2    | 2017/07/14 11:49:22 | FROM `t_bpartner`
INFO   | jvm 2    | 2017/07/14 11:49:22 | WHERE `nShopID` = '808901'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `_id` = '1494301830948'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `bIsActive` = 'Y'
INFO   | jvm 2    | 2017/07/14 11:49:22 | LIMIT 10000}
INFO   | jvm 2    | 2017/07/14 11:49:22 |    2 -> dn2{SELECT `_id`
INFO   | jvm 2    | 2017/07/14 11:49:22 | FROM `t_bpartner`
INFO   | jvm 2    | 2017/07/14 11:49:22 | WHERE `nShopID` = '808901'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `_id` = '1494301830948'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `bIsActive` = 'Y'
INFO   | jvm 2    | 2017/07/14 11:49:22 | LIMIT 10000}
INFO   | jvm 2    | 2017/07/14 11:49:22 |    3 -> dn3{SELECT `_id`
INFO   | jvm 2    | 2017/07/14 11:49:22 | FROM `t_bpartner`
INFO   | jvm 2    | 2017/07/14 11:49:22 | WHERE `nShopID` = '808901'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `_id` = '1494301830948'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `bIsActive` = 'Y'
INFO   | jvm 2    | 2017/07/14 11:49:22 | LIMIT 10000}
INFO   | jvm 2    | 2017/07/14 11:49:22 |    4 -> dn4{SELECT `_id`
INFO   | jvm 2    | 2017/07/14 11:49:22 | FROM `t_bpartner`
INFO   | jvm 2    | 2017/07/14 11:49:22 | WHERE `nShopID` = '808901'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `_id` = '1494301830948'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `bIsActive` = 'Y'
INFO   | jvm 2    | 2017/07/14 11:49:22 | LIMIT 10000}
INFO   | jvm 2    | 2017/07/14 11:49:22 |    5 -> dn5{SELECT `_id`
INFO   | jvm 2    | 2017/07/14 11:49:22 | FROM `t_bpartner`
INFO   | jvm 2    | 2017/07/14 11:49:22 | WHERE `nShopID` = '808901'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `_id` = '1494301830948'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `bIsActive` = 'Y'
INFO   | jvm 2    | 2017/07/14 11:49:22 | LIMIT 10000}
INFO   | jvm 2    | 2017/07/14 11:49:22 |    6 -> dn6{SELECT `_id`
INFO   | jvm 2    | 2017/07/14 11:49:22 | FROM `t_bpartner`
INFO   | jvm 2    | 2017/07/14 11:49:22 | WHERE `nShopID` = '808901'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `_id` = '1494301830948'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `bIsActive` = 'Y'
INFO   | jvm 2    | 2017/07/14 11:49:22 | LIMIT 10000}
INFO   | jvm 2    | 2017/07/14 11:49:22 |    7 -> dn7{SELECT `_id`
INFO   | jvm 2    | 2017/07/14 11:49:22 | FROM `t_bpartner`
INFO   | jvm 2    | 2017/07/14 11:49:22 | WHERE `nShopID` = '808901'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `_id` = '1494301830948'
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	AND `bIsActive` = 'Y'
INFO   | jvm 2    | 2017/07/14 11:49:22 | LIMIT 10000}
INFO   | jvm 2    | 2017/07/14 11:49:22 | } java.lang.IllegalArgumentException: Invalid DataSource:0
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.backend.datasource.PhysicalDBNode.getConnection(PhysicalDBNode.java:140)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.execute(MultiNodeQueryHandler.java:184)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.server.NonBlockingSession.execute(NonBlockingSession.java:149)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:288)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:324)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:344)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:500)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:482)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:323)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:196)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:275)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 2    | 2017/07/14 11:49:22 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 2    | 2017/07/14 11:49:22 |  (io.mycat.server.NonBlockingSession:NonBlockingSession.java:152)

**Comment by yanjunli** [comment]
mycat 是哪个版本？

**Comment by Ulyssesyi** [comment]
2017-03-19 06:31:25
GitVersion   5c00cd0f33cdd0df6e4936c4ea8db7d246a748c0
MavenVersion 1.6.5-BETA
GitUrl https://github.com/MyCATApache/Mycat-Server.git
MyCatSite http://www.mycat.org.cn
QQGroup 106088787

**Comment by Ulyssesyi** [comment]
这是当时我们使用1.5发现在阿里云的负载均衡下会因为负载均衡的心跳导致服务宕机，然后使用了修复了这个问题1.6.5beta版本

**Comment by dengly** [comment]
可以看看[#1545](https://github.com/MyCATApache/Mycat-Server/issues/1545)
