### ISSUE TITLE
当插入的字符串中只含有一个英文状态的双引号的时候，mycat会进入假死状态。

### ISSUE THREAD

**Issue by 694551594** [MyCATApache/Mycat-Server#1569]
sql：INSERT INTO table(column) VALUES ('test"');

经调试代码应该是在io.mycat.route.util.RouterUtil类中的handleBatchInsert方法有问题。

**Comment by yanjunli** [comment]
有意向修复这个问题吗？

**Comment by 694551594** [comment]
。。。。。。我试试。。但是不能保证能修复成功。。 @yanjunli

**Comment by yanjunli** [comment]
应该没问题。加油,期待你的pr。

**Comment by liuweiGit** [comment]
else if ((j == ')' && flag == 1) || (j == ')' && flag == 2)) {

                flag = 0;
                currentValue.append(j);
                handledSQLs.add(currentValue.toString());
                currentValue = new StringBuilder();
                currentValue.append(prefix);
            }

改成这样，上面所描述的问题好像能解决，不知道批量插入会不会有问题，待测试

**Comment by liuweiGit** [comment]
else if ((j == ')' && flag == 1) || (j == ')' && flag == 2)) {

                flag = 0;
                currentValue.append(j);
                handledSQLs.add(currentValue.toString());
                currentValue = new StringBuilder();
                currentValue.append(prefix);
            }

上述问题将源码改成这样好像没问题了，但也不是十分肯定。

**Comment by liuweiGit** [comment]
else if ((j == ')' && flag == 1) || (j == ')' && flag == 2)) {

                flag = 0;
                currentValue.append(j);
                handledSQLs.add(currentValue.toString());
                currentValue = new StringBuilder();
                currentValue.append(prefix);
            } else if (j == ',' && flag == 0) {
                continue;
            } else {
                currentValue.append(j);
            }

仔细测试了一下应该没问题
