### ISSUE TITLE
Mycat-Server日志记录插入操作问题

### ISSUE THREAD

**Issue by dandan32** [MyCATApache/Mycat-Server#1578]
目前使用Mycat-Server1.5做读写分离的测试，公司项目也在Mycat-Server1.5上初步能运行。

但是将log4j.xml中的level调为debug后，打算做sql执行语句的记录分析。发现除了连接相关的日志，select语句日志，set语句日志之外。（insert/update/delete）这三类操作的日志一条都没有，是不是Mycat-Server1.5就不记录这部分的操作呢？

**Comment by classfellow** [comment]
期待有人回复

**Comment by classfellow** [comment]
最近也在考虑用，期待有人回复

**Comment by dandan32** [comment]
没个大神来回复下我么TAT。

**Comment by yanjunli** [comment]
建议换一个更新的版本看看。

**Comment by yanjunli** [comment]
1.6.5 版本已经修复这个问题
