### ISSUE TITLE
版本1.6中 reload @@sqlstat 提示不支持

### ISSUE THREAD

**Issue by zyhui98** [MyCATApache/Mycat-Server#1579]
MySQL [TESTDB]> reload @@sqlstatus;
ERROR 1003 (HY000): Unsupported statement

**Comment by zyhui98** [comment]
可以支持了，但是写sql不显示

**Comment by yanjunli** [comment]
用1.6.5 版本吧。

**Comment by zyhui98** [comment]
5.6.29-mycat-1.6-RELEASE-20161028204710

**Comment by zyhui98** [comment]
MySQL [TESTDB]> reload @@sqlstatus;
ERROR 1003 (HY000): Unsupported statement

还是这个提示，但是我在server.xml 中添加了<property name="useSqlStat">1</property>

**Comment by zyhui98** [comment]
还是不起作用
