### ISSUE TITLE
v1.3.0.2 节点通配符配置优化建议

### ISSUE THREAD

**Issue by yoyoch1** [MyCATApache/Mycat-Server#158]
关于通配符配置，可否改简单点，如：
< table name="..."  type="global" datanode="dn$0~4,dn$5~9"/>
....
< table name="..."  primaryKey="id"  autoIncrement="TRUE"  rule="..."  dataNode="dn$0~4,dn$5~9"/>
....
< table name="..."  type="global" dataNode="dn0"/>
.....
< table name="..."  primaryKey="id"  autoIncrement="TRUE"  rule="..."  dataNode="dn0,dn1"/>
....

< dataNode name="dn$0~4" dataHost="H3306" database="db$01~05" />
< dataNode name="dn$5~9" dataHost="H3307" database="db$06~10" />

数据库就是：db01、db02....db10

这样不受那么多限制，配置也灵活，也不会隐含很多东西在后面，用起来简单

**Comment by magicdoom** [comment]
已经实现，具体可以参考配置文档

**Comment by mycatmerger** [comment]
1.4已经实现
