### ISSUE TITLE
Mycat使用注解可以指定datanode吗？

### ISSUE THREAD

**Issue by zyhui98** [MyCATApache/Mycat-Server#1586]
类似下面的
/*#mycat:db_type=master*/ select * from travelrecord

**Comment by yanjunli** [comment]
/#mycat:datanode=dn1/ select * from travelrecord。

**Comment by zyhui98** [comment]
``        hintHandlerMap.put("sql",new HintSQLHandler());
        hintHandlerMap.put("schema",new HintSchemaHandler());
        hintHandlerMap.put("datanode",new HintDataNodeHandler());
        hintHandlerMap.put("catlet",new HintCatletHandler());
        
        // 新增sql hint（注解）/*#mycat:db_type=master*/ 和 /*#mycat:db_type=slave*/  和 /*mycat:db_type=slave*/
        // 该hint可以和 /*balance*/ 一起使用
        // 实现强制走 master 和 强制走 slave
        hintHandlerMap.put("db_type", new HintMasterDBHandler());
        isInit = true;	// 修复多次初始化的bug

**Comment by zyhui98** [comment]
`        hintHandlerMap.put("sql",new HintSQLHandler());
        hintHandlerMap.put("schema",new HintSchemaHandler());
        hintHandlerMap.put("datanode",new HintDataNodeHandler());
        hintHandlerMap.put("catlet",new HintCatletHandler());
        
        // 新增sql hint（注解）/*#mycat:db_type=master*/ 和 /*#mycat:db_type=slave*/  和 /*mycat:db_type=slave*/
        // 该hint可以和 /*balance*/ 一起使用
        // 实现强制走 master 和 强制走 slave
        hintHandlerMap.put("db_type", new HintMasterDBHandler());
        isInit = true;	// 修复多次初始化的bug`
