### ISSUE TITLE
show @@sql.sum.table 命令的疑问

### ISSUE THREAD

**Issue by 352926** [MyCATApache/Mycat-Server#1589]
show @@sql.sum.table; 这个命令是显示每张表的读写统计

请问，这个执行后，统计的时间范围是什么时间到什么时间？

还有就是怎么指定时间范围内的读写统计呢？

因为mycat-web 那边的统计是不准确的，我一天内只insert 1次，select 1次，但是mycat-web里统计出来的数量却有读写好几百次。

而我用命令在mycat 9066管理端上查询出来的是对的。

但是我想知道我怎么来设定统计的范围，比如我取昨天的读写次数呢？

我翻阅了书本，以及查遍了网络，也没有找到 关于 show @@sql.sum.table 限制时间范围的说明。

有一些命令后面可以带上where，但是我在这边尝试了无效。

请大神指导！

**Comment by zyhui98** [comment]
同遇到这个问题

**Comment by HashZhang** [comment]
没有时间限制的，因为在缓存里面，所以这个数字会一直增长。。。需要自己去定时读取统计记录，并在必要时reload config清除这个缓存

**Comment by 352926** [comment]
知道了，多谢，同时找到mycat-web统计不准的原因了，我看了代码发现，mycat-web那边是每隔3分钟判断show @@sql.sum如果读或写>0就记录show @@sql.sum.table的结果，然后根据时间范围进行SUM(R)，SUM(W)累加，实际上应该取MAX会稍微准确点，但是最准确的应该单独再写个脚本来统计：今天R次数 = 今天最后执行时间R - 昨天最后执行的R   或者用sql  MAX(R) - MIN(R) 来计算范围内的次数
