### ISSUE TITLE
schema.xml 非分片表配置问题及优化建议

### ISSUE THREAD

**Issue by hunter8189** [MyCATApache/Mycat-Server#159]
现在碰到个问题，想请教下：schema.xml 将库里每张表，不管是不是分片，都要每个表都配置下。要是100多张表，只有10来张需要分片，其他90张只是普通表不需要，一一配置太麻烦了。有其他方法将这些90多张表不用配置，这个物理库需要分片的配置，不分片不用配？

我们现在应用较多，有的应用几百张表，有些可能要随时ddl加表什么的，一一个个表配置太麻烦了，有没有有效的方法？比如cobar的schema本身属性有个默认库，普通表不用配置全放在这个默认库里？

如果有这个属性，应用端就可以随意用ddl建普通表了，而schema.xml 无须任何配置。而不是建一张表，就得提前在schema.xml 配置好，这么繁琐了。

**Comment by apachemycat** [comment]
计划增加默认的，目前还未实现，取消的原因是容易引起混乱

**Comment by mycatmerger** [comment]
1.4已经实现，支持schema配置默认节点，未配置的表走默认节点

**Comment by welldone5** [comment]
我像把一个物理数据库中的 users 表在同一个库中分表为 users01,users02,users03 .....  mycat 可以做到么？

**Comment by welldone5** [comment]
这个默认节点怎么配啊，指南里面没有写啊

**Comment by guowang1102** [comment]
我也想问，怎么走默认
