### ISSUE TITLE
mycat如何检测全库扫描

### ISSUE THREAD

**Issue by changealice** [MyCATApache/Mycat-Server#1592]
问题： mycat表会有分片键，线上同事没有按照分片键查询，导致CPU飙高。
问： 
  在mycat或其它层 有没有办法检测出来一个sql语句检索没有带分片键？

**Comment by HashZhang** [comment]
可以考虑在SQL解析结果那里看下发送到的后端链接的size，监控这个

**Comment by changealice** [comment]
@HashZhang 是 查看explain的结果么，目前感觉这种方式可以实现

**Comment by HashZhang** [comment]
不是，可以在SQL解析结果（就是Route结果）那里判断下，打个日志，这样，业务上如果有全表扫描，日志里面就可以看到。不用非得explain。

**Comment by HashZhang** [comment]
你们不是线上定位么

**Comment by changealice** [comment]
@HashZhang 是线上定位问题，这个SQL解析结果是mycat中间件的吧？有关键字就能知道这个是全库扫描？
