### ISSUE TITLE
mycat 1.6 语句中带有`` 区别与mysql关键字时导致转换时匹配不上具体字段?

### ISSUE THREAD

**Issue by huangyuan1113** [MyCATApache/Mycat-Server#1602]
例如:
SELECT `date`,
sum(IF(dtype = 1, detail_performance, 0)) `group`  FROM table_name WHERE done = 1 AND brid = 4  AND `date` LIKE '201708%' GROUP BY `date` ORDER BY `date` ASC

这样在 1.6下会误以为 group列需要 group 操作, date 字段为关键字, 加上`` 括起来会不识别而抛异常

这种情况怎么处理? 只能修改sql 了吗?

**Comment by mycatmerger** [comment]
测试 1.6.5是否还存在

**Comment by huangyuan1113** [comment]
1.6.5-BETA 中不存在了 , 已验证
