### ISSUE TITLE
关于执行存储过程的问题

### ISSUE THREAD

**Issue by 694551594** [MyCATApache/Mycat-Server#1612]
`/*!mycat:sql=SELECT count(1) FROM ess_menu */call `auto_hh_V1.0`(12345678,'00511900200 ','2016','');`

前提是我配置了双主双从，balance=3，然后执行这个条语句，存储过程被随机分到两个读节点执行了。因为他前面的注解SELECT count(1) FROM ess_menu是select类型的，所以选择的是读节点。

但是这个存储过程应该被分到写节点执行吧。。这个是BUG还是有别的写法？

**Comment by yanjunli** [comment]
如果要分到写节点。
就用/*!mycat:sql=update ess_menu set id = id */ call 注解吧.
