### ISSUE TITLE
mycat中引入一个新的关键字

### ISSUE THREAD

**Issue by soforth** [MyCATApache/Mycat-Server#162]
能否引入一个新的关键字，用来处理真正的sql explain。现在的explain显示的是路由信息，每次查真实的explain，还要切到mysqld里面。

**Comment by apachemycat** [comment]
或者扩展explain 指令，增加MySQL Explain的内容，这个有难度，期待有人提供代码

**Comment by magicdoom** [comment]
已经实现explain2指令
