### ISSUE TITLE
后端连接存在无法正确关闭的情况

### ISSUE THREAD

**Issue by Ulyssesyi** [MyCATApache/Mycat-Server#1633]
使用1.6.5的最新版本编译的Mycat运行中发现后端连接数会一直上升，没有正确的关闭空闲连接

**Comment by lllvantis** [comment]
遇到同样问题 请问有后续了吗 @Ulyssesyi

**Comment by Fxdemon** [comment]
JDBC 连接数一直飙升  在高并发情况下 发现后端Oracle数据库 session会话数不释放 导致锁表记录上升

**Comment by Ulyssesyi** [comment]
目前没有办法，我是每天凌晨业务低峰期重启一次服务器解决的 @lllvantis

**Comment by zone7th** [comment]
@Ulyssesyi   现在有好的办法吗？

**Comment by Ulyssesyi** [comment]
@zone7th 没有，还是通过业务低峰期重启服务解决的，主要是不会java，能看懂不会改

**Comment by Fxdemon** [comment]
在MycatStart启动的时候添加定时任务 线程 定时检查是否无效的Session会话 进行释放。

**Comment by Ulyssesyi** [comment]
mycat是不是已经无了？
