### ISSUE TITLE
1.6.5版本 load data报错3009

### ISSUE THREAD

**Issue by garyian168** [MyCATApache/Mycat-Server#1646]
使用load data导入数据时，报错ERROR 3009 (HY000): 

![](http://ww3.sinaimg.cn/large/0060lm7Tly1fjivt7rdctj30r303xaa2.jpg)

@magicdoom

**Comment by garyian168** [comment]
1.6版本下导入是正常的

**Comment by SQkaer** [comment]
请问有人解决了这个问题么？
