### ISSUE TITLE
[Q] 在linux环境如何将mycat设置为服务？

### ISSUE THREAD

**Issue by Hisen158** [MyCATApache/Mycat-Server#167]
目前是通过   mycat/bin  ./startup_nowrap.sh   启动，
mycat 命令无效，如何制作成服务，自启动？

**Comment by songwie** [comment]
./mycat start 启动
./mycat stop 停止
./mycat console  前台运行
./mycat install    添加到系统自动启动
./mycat remove  取消随系统自动启动
./mycat restart  重启服务
./mycat pause 暂停
./mycat status 查看启动状态

**Comment by Hisen158** [comment]
linux下 ./mycat install命令无效，不能创建服务，重启linux无效，vi mycat 文件也可看到无install 命令，应该是其他方式 加入服务？

**Comment by apachemycat** [comment]
是具体报了什么错误，是否与Root权限有关

**Comment by Hisen158** [comment]
[root@localhost bin]# ./mycat install
Usage: ./mycat { console | start | stop | restart | status | dump }
意思是 ./mycat install 和 ./mycat remove 根本就没有这两个命令的。

**Comment by songwie** [comment]
install ,remove 可能真的没有，我试了下提示不支持，可能打包的时候wrap 没处理这个

**Comment by wja513** [comment]
@Hisen158 

1. 创建mycat用户
```bash
groupadd mycat
useradd -M -g mycat -s /sbin/nologin mycat
```
2. 在 /usr/local/mycat/bin/mycat编辑如下行，以mycat用户运行
RUN_AS_USER=mycat
3. 加入开机启动项
```bash
ln -s /usr/local/mycat/bin/mycat /etc/init.d/mycat
chkconfig mycat on
```
