### ISSUE TITLE
单库分表使用表别名查询时执行sql报错：[Err] 1105 - Unknown column 'a.id' in 'field list'

### ISSUE THREAD

**Issue by wangjianwen** [MyCATApache/Mycat-Server#1673]
有一个学生(student)表， 分成2两个表，schema.xml如下：
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="test" checkSQLschema="true" sqlMaxLimit="100">
		<table name="student" subTables="student$1-2" dataNode="dn1" rule="latest-month-calldate"/>
	</schema>
	
	<dataNode name="dn1" dataHost="localhost1" database="test" />
	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="hostM1" url="localhost:3306" user="root"
				   password="111111">
			
		</writeHost>
	</dataHost>
		
</mycat:schema>

执行带表别名的sql:
        select a.id, a.name from student a
报错：
        报错： [Err] 1105 - Unknown column 'a.id' in 'field list'

**Comment by yuanbs** [comment]
请问下单库分表能用auto-sharding-long分片规则嘛？我试了报错please make sure table datanode size = function partition size，难道这个只能多节点适用？用了mod-long设置data-nodes=1可以运行但是每次都插入到同一个表。
