### ISSUE TITLE
表名加双引号 不走分片表 只插入到主节点上

### ISSUE THREAD

**Issue by Fxdemon** [MyCATApache/Mycat-Server#1683]
表名加双引号 不走分片表 只插入到主节点上 
分片表 A 
执行SQL： INSERT INTO "A" ("ID", "B" ) VALUES ( '1','2')  不会插入到对应的分片表中

**Comment by HashZhang** [comment]
你这个表名加双引号，不符合MySQL语句标准吧

**Comment by Fxdemon** [comment]
一般不会添加双引号 主要使用某些工具会出现此类情况
