### ISSUE TITLE
mycat执行复杂的存储过程不成功

### ISSUE THREAD

**Issue by sundystar** [MyCATApache/Mycat-Server#1700]
mycat执行复杂的存储过程不成功

**Comment by HashZhang** [comment]
举个例子

**Comment by sundystar** [comment]
<select id="getDsCarRrcommand" statementType="CALLABLE" parameterType="java.util.HashMap" resultMap="BaseModelMap">
       <![CDATA[
           {call getDsCarRrcommand(
              #{modelMaxPrice,mode=IN},
              #{modelMinPrice,mode=IN},
              #{pageSize,mode=IN,jdbcType=INTEGER},
              #{dsModelCategory,mode=IN,jdbcType=VARCHAR},
              #{dsBrandId,mode=IN,jdbcType=VARCHAR},
              #{salesNationwide,mode=IN,jdbcType=VARCHAR},
              #{mark,mode=IN,jdbcType=INTEGER}
           )}    
       ]]>
    </select>


这样的该怎么用mycat调用啊，入产5个参数

**Comment by sundystar** [comment]
<select id="getDsCarRrcommand" statementType="CALLABLE" parameterType="java.util.HashMap" resultMap="BaseModelMap">
       <![CDATA[
           {call getDsCarRrcommand(
              #{modelMaxPrice,mode=IN},
              #{modelMinPrice,mode=IN},
              #{pageSize,mode=IN,jdbcType=INTEGER},
              #{dsModelCategory,mode=IN,jdbcType=VARCHAR},
              #{dsBrandId,mode=IN,jdbcType=VARCHAR},
              #{salesNationwide,mode=IN,jdbcType=VARCHAR},
              #{mark,mode=IN,jdbcType=INTEGER}
           )}    
       ]]>
    </select>

**Comment by sundystar** [comment]
楼主怎么不回复我啊
