### ISSUE TITLE
一致性哈希分片模式 insert into(xxx) values(xxx),(xxx) 语法不支持

### ISSUE THREAD

**Issue by suxl** [MyCATApache/Mycat-Server#176]
测试了一致性哈希，
INSERT INTO mycat_test(name_) VALUES('s21');   这样ok。
INSERT INTO mycat_test(name_) VALUES('s21'),('s22')；这样的就报错
[Err] 1003 - mycat sequnce err.java.sql.SQLSyntaxErrorException: com.foundationdb.sql.StandardException: Row value size is different

注：配置的是 Druid解析器，mycat_test表的id_ 使用的是sequence方式获取的

**Comment by songwie** [comment]
使用注解方式解决

**Comment by yoyoch1** [comment]
请问注解方式格式像啥样呢？？
如果Druid解析，不用通过注解，类似直接在mysql上执行，那就完美了。

**Comment by songwie** [comment]
http://songwie.com/articlelist/61
看这篇文章，原理就是自己指定路由，前提是你的写批次插入都是一个分片，否则有问题

**Comment by mycatmerger** [comment]
1.4序列已经改成druid解析，请使用1.4测试
