### ISSUE TITLE
执行带错误语法的orderby sql语句，不抛语法错误，能返回结果集。

### ISSUE THREAD

**Issue by wangjild** [MyCATApache/Mycat-Server#177]
![sqlerror](https://cloud.githubusercontent.com/assets/1264866/6593682/b291c276-c815-11e4-8ba8-fea2b7cf3f83.png)

在普通的mysql中执行同样的语句，会抛语法错误：
![mysqlcorrect](https://cloud.githubusercontent.com/assets/1264866/6593707/f1b6e184-c815-11e4-9b1c-0d84d631989c.png)

**Comment by curt001** [comment]
orderby错了，被当成别名了吧，应该是order by,漏了空格

**Comment by wangjild** [comment]
是当成别名了，但是在mycat中能够执行成功且返回不匹配limit条件数目的结果集。这应该是mycat sql语法解析器的问题

**Comment by mycatmerger** [comment]
druid解析把orderby当做别名一直解析下去。如果希望解决，可以提交给druid
