### ISSUE TITLE
调用file @@list命令后会造成lost connection

### ISSUE THREAD

**Issue by kunzeal** [MyCATApache/Mycat-Server#1785]
version：1.6
现象：
链接9066 admin端口，调用file @@list
ERROR 2013 (HY000): Lost connection to MySQL server during query

看了下代码，1.4和1.5版本是没问题的
1.6里，在ConfFileHandler.java:74这里，原本
header.packetId = ++packetId;
改成了
header.packetId = 1;

这个是故意改错的么？

**Comment by apachemycat** [comment]
fixed
