### ISSUE TITLE
reload @@config耗时要60秒左右，如果有事务在处理的话有几率导致事务出错

### ISSUE THREAD

**Issue by curt001** [MyCATApache/Mycat-Server#179]
看了下源码是reload config是全部重载并且清除缓存，怪不得会导致事务出错。
新增表要先配置schema.xml文件，然后mycat服务在运行中又不能停止，只能reload config，但是reload时间长，还有几率导致事务出错，也算是一个bug吧。

**Comment by curt001** [comment]
![reload config success](https://cloud.githubusercontent.com/assets/8361102/6663141/94bf5668-cbfe-11e4-860c-d9a86274579d.png)

**Comment by curt001** [comment]
![mycat reload config](https://cloud.githubusercontent.com/assets/8361102/6663145/a1d67642-cbfe-11e4-9987-c1b72d05417c.png)

**Comment by apachemycat** [comment]
未来版本中预计会改善，不再重新Reload数据源，这是Cobar遗留的问题之一

**Comment by mycatmerger** [comment]
目前1.4已经支持不在reload数据源，如果数据源修改可以用 reload_all指令
