### ISSUE TITLE
关于pom文件依赖sequoiadb-java-driver的问题

### ISSUE THREAD

**Issue by yaojunan** [MyCATApache/Mycat-Server#1792]
在代码（代码分支为1.5）编译打包时，发现构建不通过，报错为：
Failed to execute goal on project Mycat-server: Could not resolve dependencies for project org.opencloudb.mycat:Mycat-server:jar:1.5.1-RELEASE: Failure to find com.sequoiadb.org:sequoiadb-java-driver:jar:1.0-SNAPSHOT 
    在网上看了，没有sequoiadb-java-driver的相关依赖。疑惑如下：
   （1）在release版本中使用SNAPSHOT版本的第三方依赖感觉有些不合适。
  （2）关于sequoiadb-java-driver相关的包，网上找到的是如下，是否可以更改为如下：
          <dependency>
			<groupId>com.sequoiadb</groupId>
			<artifactId>sequoiadb-driver</artifactId>
			<version>1.12</version>
		</dependency>

**Comment by karakapi** [comment]
更新了,愿意帮忙测试一下吗
