### ISSUE TITLE
show @@sql返回限制

### ISSUE THREAD

**Issue by 4linuxfun** [MyCATApache/Mycat-Server#1799]
连接mycat的9066端口，执行show @@sql每次最大只返回50行结果，能超过限制吗？或者有其他获取SQL语句的方式也行。
mycat 版本：5.5.8
PS：有些SQL语句会导致mycat重启，想要搜集SQL语句，进行重放操作，暂时只找到show @@sql这简洁的获取SQL语句的方式，log日志设置为debug返回内容太多，过滤太麻烦。

**Comment by gaotuan** [comment]
最新的版本没这个限制
