### ISSUE TITLE
PhysicalDatasource.conMap 该集合有放连接进去吗？从代码里没看出来

### ISSUE THREAD

**Issue by csgvsjay1000** [MyCATApache/Mycat-Server#1803]
PhysicalDatasource.conMap 该集合有放连接进去吗？从代码里没看出来

**Comment by srmsh** [comment]
PhysicalDatasource的returnCon方法

**Comment by csgvsjay1000** [comment]
@srmsh 知道了，谢谢，后面发现原来releaseConnection释放连接时会往里面增加。
