### ISSUE TITLE
分库分表这种场景保证在一个库的问题

### ISSUE THREAD

**Issue by yangpancode** [MyCATApache/Mycat-Server#1805]
用mycat做分库分表时，我们要做联合查询的join时，为了保证父表和子表在同一个库中，采用子表的外键是父表的主键，分片字段是父表的主键，如果分片的字段不是父表的主键，而是其他的字段，还能保证两个表主键id的信息在同一个库中吗? 
比如订单表有订单id，有订单类型，子表是订单的一些属性，外键是订单的主键id；如果我不用订单的主键id做分片字段，而用订单类型来作为分片字段的时候，能保证同一个订单的主表和子表信息都在同一个库吗？多谢告知

**Comment by cloudufull** [comment]
er 分片 可能能行吧
