### ISSUE TITLE
Mycat连接SQL Server后，采用Navicat for MySQL连接Mycat无法查看到表，且程序报错

### ISSUE THREAD

**Issue by gerogefeng** [MyCATApache/Mycat-Server#181]
原因是Mycat连接SQL Server对SELECT @@character_set_database, @@collation_database指令未做处理，导致指令在数据库上执行而报错。

**Comment by mycatmerger** [comment]
目前后端是jdbc这块对这些指令还不支持，建议直接连实际的sql server，也欢迎提交pull request来支持
