### ISSUE TITLE
schema.xml配置问题

### ISSUE THREAD

**Issue by kiragame** [MyCATApache/Mycat-Server#1810]
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100">
		
		<table name="user_info" primaryKey="id" type="global" dataNode="dn1,dn2" />
	</schema>

	<dataNode name="dn1" dataHost="localhost1" database="test1" />
	<dataNode name="dn2" dataHost="localhost2" database="test2" />

	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="hostM1" url="xxxxx:3306" user="user"
				   password="xxxxx">
	       </writeHost>
	</dataHost>  
	<dataHost name="localhost2" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat></heartbeat>
		<writeHost host="hostM2" url="xxxxx:3306" user="user"
				   password="xxxxx">
	       </writeHost>
		 
        </dataHost>  
</mycat:schema>

如上配置之后，Mycat访问user_info，只能得到<dataNode name="dn1" dataHost="localhost1" database="test1" />内的数据。
有人能指正一下我的错误吗？谢谢！

**Comment by srmsh** [comment]
配置rule 分片规则

**Comment by kiragame** [comment]
你好。因为数据库都是独立的（结构相同，数据没有任何联系，即无hash）。所以没有分片规则，没办法使用Mycat吗？

**Comment by kiragame** [comment]
删掉type="global"可满足自身业务需求
