### ISSUE TITLE
lock tables语句执行不符合预期

### ISSUE THREAD

**Issue by wangjild** [MyCATApache/Mycat-Server#182]
问题描述：

对于正常的mysql服务器

1. mysql command 1 连接上server，执行lock tables 语句
2. mysql command 2 连接上server，执行delete 语句。此时会挂起
3. mysql command 1 执行exit，退出进程，结束与server的连接
4. mysql command 2 会立刻得到delete语句的执行结果

但是如果mysql command 连接的是mycat

那么第4步骤会永远挂起，被阻塞住。看起来是mycat并没有正确地执行回滚操作。

explain lock tables 和 unlock tables，目前1.3 版本中，这2个语句的执行是随机的，会随机挑上一个node来执行

**Comment by apachemycat** [comment]
这个的确存在问题，Lock table这种语句，目前并不合适在Mycat上执行，锁定的表比较多
