### ISSUE TITLE
请问那个testtool.jar的源码在哪里？

### ISSUE THREAD

**Issue by Mount565** [MyCATApache/Mycat-Server#1845]
请问那个testtool.jar的源码在哪里？
文档里关于date类型没讲明白，需要瞧两眼源码啊

**Comment by Mount565** [comment]
找到源码了， 发现日期格式为yyyy-MM-dd时有问题，不能正确生产日期字符串。日期格式定义与值的范围定义是以‘-’分割的，如果日期格式中有‘-’，就有问题了。 

`class DateVarItem extends StringItem {
	String format;
	int[] yearRang = { 1970, 2999 };
	int[] monRang = { 1, 12 };
	int[] dayRang = { 1, 31 };
	int[] hourRang = { 0, 23 };
	int[] minuteRang = { 0, 59 };
	int[] secondRang = { 0, 59 };
	int[] sssRang = { 0, 999 };

	public DateVarItem() {

	}

	public void initString(String content) {
		**int fmtEndPos = content.indexOf('-');**
		if (fmtEndPos == -1) {
			fmtEndPos = content.indexOf(')');
		}
		format = content.substring(5, fmtEndPos);
		int yearP = content.indexOf("]y", fmtEndPos);
		if (yearP > 0) {
			yearRang = getRangeofPattern(content, yearP);
		}

		int monthP = content.indexOf("]M", fmtEndPos);
		if (monthP > 0) {
			monRang = getRangeofPattern(content, monthP);
		}
...
`

**Comment by Mount565** [comment]
随机生产date应该这样写：${date(yyyy/MM/dd HH:mm:ss-[2018-2019]y[1-12]M[1-31]d[0-23]H[0-59]m[0-59]s)}

**不支持日期格式为yyyy-MM-dd , 因为源码中以第一个‘-’ 为日期格式和值范围的分割符.**

**Comment by dcmr** [comment]
我找到jar包，没有源码
