### ISSUE TITLE
这个项目还有人维护么?

### ISSUE THREAD

**Issue by Fanduzi** [MyCATApache/Mycat-Server#1846]
官网的论坛社区都挂了
DBLE在PPT上提到的你们的bug你们修复了吗?
Proxysql现在支持基于GTID的一致性读, MyCAT还打算做么?
MGR的支持, 有计划吗?

**Comment by ustcqb** [comment]
mycat也不修复bug，也不出新版本，搞个QQ群还要收费加入，开源的精神都丢了，mycat迟早被淘汰

**Comment by Fanduzi** [comment]
维护个毛线, 一堆bug不修复. 果然只有DBA for DBA的ProxySQL才靠谱. 国人还是不行

**Comment by lazio579** [comment]
可以加入我们https://github.com/Lede-Inc/cetus，具备开源职业精神

**Comment by peng051410** [comment]
@ustcqb 收费只是为了过滤一些人而已，5元钱对于现在社会来说不是大数目吧！
