### ISSUE TITLE
mycat是停止维护了吗？

### ISSUE THREAD

**Issue by zhoubang85** [MyCATApache/Mycat-Server#1882]
源码都是3年前的了，mycat一直都没有动态了，这让人产生猜测，是不是已经停止维护了！？
如果真的停止维护的话，那就太可惜了。

**Comment by peng051410** [comment]
新版本即将开始，敬请期待！

**Comment by karakapi** [comment]
看看commit?

**Comment by zwyqz** [comment]
一直在维护的亲~可以看下pr的时间

**Comment by 3legcat** [comment]
已经fix的issue维护人员能不能close掉？

**Comment by mousycoder** [comment]
同感~~~现在不知道跑哪去维护了

**Comment by Fxdemon** [comment]
https://github.com/Fxdemon/ClusterDB-Server/blob/master/README.md

**Comment by mousycoder** [comment]
厉害 @Fxdemon

**Comment by 995933447** [comment]
mycat2没有文档了吗 mycat1下载地址都找不到 git上那些1.x版本下载下载直接解压报错
