### ISSUE TITLE
关于mycat表名大小写问题

### ISSUE THREAD

**Issue by wangbingqiong** [MyCATApache/Mycat-Server#1907]
mysql对应的表名时全大写的，使用1.6和1.6.5都是一样，mycat里生成两个表，一个全大写，一个全小写，大写的操作都没问题(配置文件里写的大写),小写的操作都有问题了，找不到，如何跟mysql一一对应，表明大写的mycat里就存在大写的表，不要在生成小写的表

**Comment by yangpancode** [comment]
请问你后来是如何解决的？我的也出了同样的问题。

**Comment by zjswwh** [comment]
请问你怎么解决的啊 我也遇到了这个问题

**Comment by caofei996** [comment]
解决了吗？我也遇到了
