### ISSUE TITLE
1.6.5版本使用多表更新时出现的问题

### ISSUE THREAD

**Issue by lujunGit** [MyCATApache/Mycat-Server#1914]
- **`mycat1.6.5-release`在做两张表同步更新，sql语句添加注解的方式，应用出现sql语句语法错误的问题。**

1. 表A和表B,表A做了枚举值的分库分表，表B做了全局表在每个分库中都存在并在`schame.xml`中配置了，表B 
    的数据要同步更新到表A,
2. sql语句：`update A a inner join B b on a.id=b.id set a.name=b.name, a.status=b.status where a.sid=1`;已经根据sid做了分库分表，
3. 后台持久层用的是springJPA和阿里的数据库连接池包，使用本地sql方式执行，改写的sql是：
   ` /*!mycat: sql=select 1 from a where sid=1*/ update A a inner join B b on a.id=b.id set a.name=b.name, a.status=b.status where a.sid=1`
4. 结果在mycat客户端是可以正确路由到指定数据库的，但是应用却出现不识别：`/*!mycat: sql=select 1 from a where sid=1*/`，认为是不正确的sql语法，仔细看是因为阿里的数据库连接池和springJPA事务有拦截器在进行检查sql的时候认为语法错误，所以就不能用注解了，大家有没有遇到这样的问题？在不能修改持久层的基础上，除了修改mycat源码还有什么好的方法？
5. sql语句改成子查询的不用join的方式我试过，但是没有注解的话，mycat会报不支持多表更新，目前因为这种写法才能保证数据同时更新的时效性没在保证时效性的情况下，如何修改？

**Comment by lujunGit** [comment]
已经试过了，把分库都改成一个个独立的schame也是不行，即sql语句改为：
`/*!mycat: schame=op1;*/ update A a inner join B b on a.id=b.id set a.name=b.name, a.status=b.status where a.sid=1`
应用后台同样报了sql语法错误，不识别，擦，同样的这个语句在mycat客户端执行没有任何问题。

**Comment by zwyqz** [comment]
1.采用先查后更新的办法
2.xml是可以支持mycat注解的
3.mycat客户端如果没有问题 那就是web程序的问题 做对应修改就行.

**Comment by lujunGit** [comment]
看了代码，是因为后端框架使用的是jpa+dried数据库连接池，注解事务时，会检查sql的合法性，结果检查出来添加注解的sql不合法，就出错了，我自己改了mycat这一层，从mycat这边接收sql的入口重新组织sql注解，就可以了。
