### ISSUE TITLE
1.6.5 版本应该不支持io.mycat.route.function.PartitionByCRC32PreSlot 这个算法

### ISSUE THREAD

**Issue by seifeHu** [MyCATApache/Mycat-Server#1916]
使用1.6.5下默认的crc32slot  用作rule 。启动时会被报如下错误。
Caused by: io.mycat.config.util.ConfigException: rule crc32slot is not found

使用其它rule不会有问题。

**Comment by karakapi** [comment]
是的,正在修

**Comment by karakapi** [comment]
现在这个1.6的版本的crc32算法已经修好了
