### ISSUE TITLE
mycat的count()问题

### ISSUE THREAD

**Issue by hanlu09** [MyCATApache/Mycat-Server#1927]
select 1 from transaction_event where service_list_id in ( 46730 );
select count(0) t_count from (select 1 from transaction_event where service_list_id in ( 46730 ) );
两个SQL的查询结果不一致

**Comment by xjq941219** [comment]
最好不要在mycat中用子查询

**Comment by zwyqz** [comment]
改写下你们查分页插件的sql吧.
