### ISSUE TITLE
使用genKeyPair 生成秘钥对，公钥如何提供给mycat？

### ISSUE THREAD

**Issue by baisijian** [MyCATApache/Mycat-Server#1928]
使用genKeyPair 生成秘钥对，公钥如何提供给mycat？

**Comment by zwyqz** [comment]
usingDecrypt 属性
80
是否对密码加密默认0 否 如需要开启配置1，同时使用加密程序对密码加密，加密命令为：
执行mycat jar 程序（1.4.1以后）： java -cp Mycat-server-1.4.1-dev.jar io.mycat.util.DecryptUtil 1:host:user:password Mycat-server-1.4.1-dev.jar 为mycat download 下载目录的jar 1:host:user:password 中 1 为db端加密标志，host为dataHost 的host 名称

**Comment by baisijian** [comment]
这样使用的是默认的私钥，如何使用新生成的秘钥对
