### ISSUE TITLE
1.65在执行大量查询后，内存占用会一直在线性上涨5~6G

### ISSUE THREAD

**Issue by louis319** [MyCATApache/Mycat-Server#1939]
查看堆dump，发现99%都是char[],主要就是查询过程中使用到的SQL；如何能控制内存稳定在某个水平内，不会一直上涨；Statement 和 ResultSet确认都已关闭了的；

**Comment by xadomgreen** [comment]
> 查看堆dump，发现99%都是char[],主要就是查询过程中使用到的SQL；如何能控制内存稳定在某个水平内，不会一直上涨；Statement 和 ResultSet确认都已关闭了的；

老铁你这个问题解决了吗 我最近我遇到了，。。
