### ISSUE TITLE
现在最新release分支还是20180122版本的吗？这个版本单库分表批量保存报错，查主分支在5月5号已修复

### ISSUE THREAD

**Issue by xiaoliufang** [MyCATApache/Mycat-Server#1948]
拉取20180122版本使用单库分表报java.lang.IndexOutOfBoundsException，然后拉取github最新代码，查看源码发现在5月5号这个已经修改好了，但是release版本没有找到5月5号之后的发布，请问这个有计划上线吗？

**Comment by zwyqz** [comment]
拿1.66版本吧。

**Comment by zwyqz** [comment]
http://dl.mycat.io/1.6.6/

**Comment by xiaoliufang** [comment]
好的，谢谢。但是这个好像是test版本，什么时候改成release版本，这个用起来会有影响吗？

**Comment by apachemycat** [comment]
压测过的

**Comment by tanhaihui** [comment]
我想知道单库分表批量插入是加什么注解的？为什么我1.6.6版本不行？
