### ISSUE TITLE
语句解析问题（语句会被截取！！！！！）

### ISSUE THREAD

**Issue by 437865981** [MyCATApache/Mycat-Server#1949]
MySQL [TESTDB]> explain update  t_user_amount set amount = amount-8.8888 where user_id = 10;
+-----------+----------------------------------------------+
| DATA_NODE | SQL                                          |
+-----------+----------------------------------------------+
| node_db01 | UPDATE t_user_amount_1 SET amount = amount-8 |
| node_db01 | UPDATE t_user_amount_2 SET amount = amount-8 |
| node_db01 | UPDATE t_user_amount_3 SET amount = amount-8 |
| node_db01 | UPDATE t_user_amount_4 SET amount = amount-8 |
| node_db01 | UPDATE t_user_amount_5 SET amount = amount-8 |
| node_db01 | UPDATE t_user_amount_6 SET amount = amount-8 |
+-----------+----------------------------------------------+
6 rows in set (0.00 sec)

根据user_id 分表
执行： update  t_user_amount set amount = amount-8.8888 where user_id = 10;
会截取，变成：update  t_user_amount set amount = amount-8  ，所有记录都操作了
！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by zwyqz** [comment]
![image](https://user-images.githubusercontent.com/4454612/43836136-f2bd9458-9b46-11e8-8cfd-b869dc6bb5ed.png)
jia加个空格吧.
