### ISSUE TITLE
最新的1.3 between 问题

### ISSUE THREAD

**Issue by runfriends** [MyCATApache/Mycat-Server#195]
select id from hotspot_nearby  where apid=-1 and mac='0' and (latitude between 39.97523031984604 and 39.993211680153955) and 
         (longitude between 116.30105621163985 and 116.32452378836017)  这个出错

改成>=  <=就不出错

**Comment by mycatmerger** [comment]
master的代码我测试正常，你可以试试

**Comment by runfriends** [comment]
master正常，1.3不正常。latitude longitude在mysql是decimal，java类型是BigDecimal，分片键是id。

**Comment by mycatmerger** [comment]
请使用1.4
