### ISSUE TITLE
分页BUG

### ISSUE THREAD

**Issue by Fxdemon** [MyCATApache/Mycat-Server#1952]
DruidMycatRouteStrategy.java
MySQL分页查询出现结果未合并的异常：
//改写sql：如insert语句主键自增长, 在直接结果路由的情况下,进行sql 改写处理
druidParser.changeSql(schema, rrs, statement,cachePool);
由于上面的SQL导致执行DruidSelectParser changeSql执行了2次 将startSize
设置为 0 ;

修改方法：
DruidMycatRouteStrategy中删除下面代码
//改写sql：如insert语句主键自增长, 在直接结果路由的情况下,进行sql 改写处理
druidParser.changeSql(schema, rrs, statement,cachePool);

**Comment by zwyqz** [comment]
什么意思？

**Comment by Fxdemon** [comment]
意思就是SQL路由解析执行了2次 导致rrs 中startsSize设置为0 查询结果大于limtM,N 中的N
