### ISSUE TITLE
请问下，mycat跑一段时间，cpu居高不下是什么原因，mycat没报错

### ISSUE THREAD

**Issue by 437865981** [MyCATApache/Mycat-Server#1956]
CPU 过一段时间，大概一天，跑到800%左右

**Comment by yinhaibo** [comment]
I have same problem, I can restart mycat to resolve it, but is is dangours for our application.

**Comment by sunzhonghui** [comment]
同样

**Comment by Fxdemon** [comment]
service.xml配置优化
   
    
    <property name="processors">1024</property>
     
	 <property name="processorExecutor">64</property>

**Comment by sunzhonghui** [comment]
> 
> 
> service.xml配置优化
> 
> ```
> 
> <property name="processors">1024</property>
>  
>  <property name="processorExecutor">64</property>
> ```

两行参数是不是反了？我看文档是这样的。
![default](https://user-images.githubusercontent.com/17609963/49349594-4d9f5a00-f6e6-11e8-901e-3008433f5533.png)

**Comment by sunzhonghui** [comment]
> 1024

设置1024真的没问题吗?
