### ISSUE TITLE
murmur hash初始化过程拼接key重复

### ISSUE THREAD

**Issue by loxp** [MyCATApache/Mycat-Server#1962]
io.mycat.route.function.PartitionByMurmurHash类中有一个方法:

`
private void generateBucketMap(){...}
`

该方法拼接出的string key为: 
SHARD-0-NODE-0
SHARD-0-NODE-0-NODE-1
SHARD-0-NODE-0-NODE-1-NODE-2
......

为什么不采用以下方式生成key?
SHARD-0-NODE-0
SHARD-0-NODE-1
SHARD-0-NODE-2
......

**Comment by zwyqz** [comment]
前辈留下来的    不能改这个东西了 不然用的用户升级之后 会有问题
