### ISSUE TITLE
MyCAT 已经和尚未支持的功能,希望大家一起整理下

### ISSUE THREAD

**Issue by wenerme** [MyCATApache/Mycat-Server#197]
## 已经支持

* 分片条件
  * 取模分片
  * 日期分片
* LOAD DATA
* 压缩协议

## 尚未支持
INSERT 多值

根据主键范围查询
二级索引

> 希望大家补充

**Comment by apachemycat** [comment]
INSERT 多值 1.3.0.3版本已经支持，需要改SQL Parser为Druid解析器，参考相关文档。
 主键范围查询 的支持，若主键是自增长类型的（包括整数自增长，日期格式的等），支持Between的范围查询（优化模式），否则仍然支持范围查询，不过需要到所有分片查询一次。

**Comment by apachemycat** [comment]
二级索引 目前没见到有特别大的优势， 但Mycat有特殊的优化，即非主键分片 的情况下，主键相当于一个额外的分片规则，内部有缓存优化带主键参数的查询SQL

**Comment by apachemycat** [comment]
LOAD DATA  目前正在开发中，预计1.4版本正式支持

**Comment by wenerme** [comment]
那可以补充下这个列表么? 以官方的姿态,或者说添加个 WIKI 页面
比较对于 MyCAT 的很多进度和工作都不了解,有个直观的列表或表格比较好
