### ISSUE TITLE
单库分表，有自动新增表的需求怎么解决比较好？

### ISSUE THREAD

**Issue by zz0116** [MyCATApache/Mycat-Server#1970]
单表数据量大，3千万左右，数据量上升快，而且无法预料会有多大增速，新增表得修改配置文件，并重启mycat，感觉比较麻烦，能否有自动新增分表的功能？
若不用mycat自己粗略实现的情况是：按照某字段分表，在插入数据前先查询是否有该分表（由逻辑表名和字段值拼接出来的实际表名，到数据库查是否存在这张表），若没有则新建该分表。
感觉这个应该是能做的，但是sharding-jdbc也没有自动新建表的功能。

**Comment by karakapi** [comment]
使用zk搭建mycat集群,直接更改zk中的配置并保存,可以在线更新mycat集群配置

**Comment by zz0116** [comment]
这个就是所谓的动态扩容嘛，相当于热部署，直接修改配置文件不用重启mycat，我仔细看了这个特性，跟我的需求还是很不一样的，我的想法是，比如说我存每个userid的文章，一个用户一张表，article_1 article_2 article_3...那么一旦来了一个新用户id=23789，而这张article_23789是不存在的，那么我希望在自动创建表的同时不用改各种配置，开发人员在这个过程什么都不用做。

**Comment by karakapi** [comment]
最新的权威指南里面有介绍基于有状态分片算法的数据自动迁移，但是还是与你的需求有偏差

**Comment by zz0116** [comment]
是的，我查了很多，普遍的做法还是一开始建很多表，比如有说见过分64个库，每个库64张表……现在在想是不是这种一开始就建大量表更好。

**Comment by karakapi** [comment]
有离线的数据迁移,但是mycat的表配置还是需要自己修改,mycat eye正在做可视化配置,可以从工具上补充繁琐配置修改
