### ISSUE TITLE
1.6.5 release load data error

### ISSUE THREAD

**Issue by SQkaer** [MyCATApache/Mycat-Server#1979]
待load的数据是csv格式，数据量不大（几百M）
执行load指令，mycat报错：
load data error 
java.lang.NullPointerException

请问有人知道怎么解决吗？

**Comment by zwyqz** [comment]
得指出是哪一行或者更详细的报错

**Comment by nchuxyz** [comment]
sql 贴一下呢

**Comment by SQkaer** [comment]
已经解决了哈，谢谢。实际上问题是之前的schma里面的某些表没有分片规则。老版的mycat这里有个bug

**Comment by cd13486503530** [comment]
换1.6，没问题
mysql -hlocalhost -uroot -P8066 -p123456 -A testDB -e "LOAD DATA LOCAL INFILE '/root/result1.txt'  INTO TABLE test FIELDS TERMINATED BY ','  (plantsn, p1, p5, p4, p3, p2, p6, updatetime, score, date);"

**Comment by cd13486503530** [comment]
换分片表，配置1片，可以导入
