### ISSUE TITLE
当使用预处理语句对mycat执行插入/更新时候，无法向数据库存入一个反斜杠。

### ISSUE THREAD

**Issue by IMWYY** [MyCATApache/Mycat-Server#1980]
mycat对与预处理传来的参数，反斜杠全部会被去除。如"\\\\\\"" ，只会存入一个"。直接连接mysql无问题。
出问题环境：
java通过jdbc连接mysql，预处理模式（useServerPrepStmts=true），使用预处理语句。
go通过gorm连接mysql，使用预处理语句。

**Comment by zwyqz** [comment]
![image](https://user-images.githubusercontent.com/4454612/44844875-94f8f300-ac7e-11e8-940d-01b010cd0450.png)

![image](https://user-images.githubusercontent.com/4454612/44844866-8f9ba880-ac7e-11e8-817d-439df47429b7.png)
试了下是可以的

**Comment by IMWYY** [comment]
@zwyqz jdbc连接里使用参数 useServerPrepStmts=true了么？ 用server的预处理，不用client的预处理。JDBC client的预处理会把sql拼接好扔给mycat执行，server的预处理会把sql和参数分开传递。

**Comment by zwyqz** [comment]
https://github.com/MyCATApache/Mycat-Server/pull/1981

**Comment by webnum** [comment]
已修复！2018年9月8日
