### ISSUE TITLE
mycat1.6.5 远程load文件，出现no such file or directory

### ISSUE THREAD

**Issue by SQkaer** [MyCATApache/Mycat-Server#1983]
load DATA local INFILE 'd:\88\qq.txt' IGNORE INTO TABLE test CHARACTER SET 'gbk' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n'(id,sid,asf) ;

发现mycat无法从远端load文件，只能放在mycat服务器上，才成功。看用户指南，应该支持远端load文件的。请问有人知道问题吗？

**Comment by karakapi** [comment]
不支持远端load文件

**Comment by karakapi** [comment]
2.0会支持,但是还没出正式版

**Comment by SQkaer** [comment]
@karakapi 谢谢
