### ISSUE TITLE
单库分表应该怎么配置？或者多库分表，一个库里存储N个分片怎么配置呢？

### ISSUE THREAD

**Issue by qianyong198765** [MyCATApache/Mycat-Server#2001]
<table name="outtag" subTables="outtag_$0-9" dataNode="userprofile1" rule="mobile_end"/>
使用此方法，mycat启动的时候会报datanode size不匹配的错误，请大神指导一下，谢谢！

**Comment by qianyong198765** [comment]
自己使用错误

**Comment by wenjiajia08** [comment]
麻烦问下怎么解决的，我也遇到了
