### ISSUE TITLE
mycat 连接mysql ，数据插入重复

### ISSUE THREAD

**Issue by zhengshibing** [MyCATApache/Mycat-Server#2004]
mycat 版本 Mycat-server-1.6-RELEASE-20161028204710-linux
mysql 版本 5.7.23

schame.xml 中关键配置如下

### <table name="act_personal_info" dataNode="dn1,dn2,dn3,dn4" rule="auto-sharding-long"/>
	<dataNode name="dn1" dataHost="db1" database="mydbs" />
	<dataNode name="dn2" dataHost="db2" database="mydbs" />
	<dataNode name="dn3" dataHost="db3" database="mydbs" />
	<dataNode name="dn4" dataHost="db1" database="mydbs2" />
	<dataHost name="db1" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="host1" url="192.168.2.65:3306" user="root"
				   password="1">
		</writeHost>
	</dataHost>
	<dataHost name="db2" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="host2" url="192.168.2.66:3306" user="root" password="1" />
		
	</dataHost>
	<dataHost name="db3" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="host3" url="192.168.2.69:3306" user="root" password="1" />
		
	</dataHost>

rule.xml 关键配置如下
### 	<tableRule name="auto-sharding-long">
		<rule>
			<columns>account_no</columns>
			<algorithm>rang-long</algorithm>
		</rule>
	</tableRule>
	<function name="rang-long"
		class="io.mycat.route.function.AutoPartitionByLong">
		<property name="mapFile">autopartition-long.txt</property>
	</function>

文件autopartition-long.txt内容为
### [root@m65 conf]# more autopartition-long.txt
# range start-end ,data node index
# K=1000,M=10000.
0-500M=0
500M-1000M=1
1000M-1500M=2
1500M-20000M=3

表act_personal_info的创建命令为
### CREATE TABLE `act_personal_info` (
  `account_no` INT(11) DEFAULT NULL,
  `u_name` VARCHAR(50) DEFAULT NULL,
  `addr` VARCHAR(100) DEFAULT NULL,
  `age` SMALLINT(6) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8

**现在往act_personal_info中插入数据
 INSERT INTO act_personal_info(account_no, u_name, addr, age) VALUES(8000000, '王五', '龙翔路75号', 21);
INSERT INTO act_personal_info(account_no, u_name, addr, age) VALUES(19000000, '赵六', '龙翔路73号', 21);
会向dn1,dn2中同时插入数据，导致数据重复，但是我的表并不是global类型的
另外 使用explain INSERT INTO act_personal_info(account_no, u_name, addr, age) VALUES(8000000, '王五', '龙翔路75号', 21);
DATA_NODE 也解析出写入dn2，但是dn1也有数据，这个就有问题了**

请大神们帮忙分析一下，困扰一天了

**Comment by zwyqz** [comment]
先换种分片规则试试看 第二使用1.66版本 试试看

**Comment by zhengshibing** [comment]
掉坑里面了，自己把自己坑了，DN1是DN2的slave，所以dn1的数据重复了
