### ISSUE TITLE
Mycat-server-1.6-RELEASE-20161028204710-win.tar.gz 错误的server.dtd

### ISSUE THREAD

**Issue by xuefli** [MyCATApache/Mycat-Server#2032]
the source in  github is : <!ELEMENT user (property+,privileges*)>
the jar in tar.gz include server.dtd is <!ELEMENT user (property+*)>

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.6.1/

**Comment by xuefli** [comment]
1.6.6.1 fix this issue
