### ISSUE TITLE
MYCAT的逻辑库登录不上去，求解答。

### ISSUE THREAD

**Issue by sundong1982** [MyCATApache/Mycat-Server#2037]
C:\Program Files\MySQL\MySQL Server 8.0\bin>mysql -uroot -p123456 -h127.0.0.1 -P8066 -DTESTDB
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (HY000): Access denied for user 'root', because password is error

**Comment by sundong1982** [comment]
日志  ERROR [$_NIOREACTOR-0-RW] (io.mycat.net.handler.FrontendAuthenticator.failure(FrontendAuthenticator.java:240)) - ServerConnection [id=2, schema=null, host=127.0.0.1, user=null,txIsolation=3, autocommit=true, schema=null]Access denied for user 'root', because password is error              

日志记录 user=null,

**Comment by sundong1982** [comment]
物理库3306完全正常

**Comment by sundong1982** [comment]
换成5.7就可以了 哪位大神解答下:)

**Comment by Fxdemon** [comment]
用MyCat Server.xml中配置的用户密码登录 你的貌似用的数据库的登录帐号和密码

**Comment by sundong1982** [comment]
@Fxdemon 是逻辑库的 换成5.7就OK了  估计是8.0太新，mycat更新没跟上

**Comment by liuyuer** [comment]
遇到同样的问题，现在有解决办法吗？

**Comment by sundong1982** [comment]
> 遇到同样的问题，现在有解决办法吗？

用5.7  8.0比较新 mycat更新慢还不兼容

**Comment by HysunHe** [comment]
用Oracle19c数据库也同样问题

**Comment by DaiChongyu** [comment]
我就是5.7啊一样上不去

**Comment by dddygin** [comment]
mysql -uroot -h192.168.1.177 -P 8066 -p --default-auth=mysql_native_password 加上 --default-auth=mysql_native_password 就可以了

**Comment by houhong** [comment]
> mysql -uroot -h192.168.1.177 -P 8066 -p --default-auth=mysql_native_password 加上 --default-auth=mysql_native_password 就可以了

这个是可以的
