### ISSUE TITLE
分库查询关联字段存在null会出现空指针异常

### ISSUE THREAD

**Issue by hhy464591454** [MyCATApache/Mycat-Server#2056]
例如:
select t1.* from t_table_1 t1 left join t_table_2 t2 on t1.name=t2.name ;
此时假如 t1.name 或 t2.name 有null值 则报出空指针异常
请问怎么解决?
version:1.6

**Comment by zwyqz** [comment]
报错贴一下

**Comment by hhy464591454** [comment]
close
