### ISSUE TITLE
1.4-dev版本，使用默认节点配置的会导致走默认节点的建表和删表等sql语句执行2遍

### ISSUE THREAD

**Issue by curt001** [MyCATApache/Mycat-Server#206]
1.4-dev版本，使用默认节点配置的会导致走默认节点的建表和删表等sql语句执行2遍，
配置如下：

![default](https://cloud.githubusercontent.com/assets/8361102/6976959/9a5a9a16-d9e5-11e4-9bc9-fb43d7a1bd71.jpg)

执行结果如下：
![sql](https://cloud.githubusercontent.com/assets/8361102/6976961/a837a78c-d9e5-11e4-96cb-c5ce3d4c8b68.jpg)
不知道是我个人配置问题还是所有人都这样，请大家继续验证下

**Comment by magicdoom** [comment]
我跟踪了下，并未执行2遍，但是最后连接会自动关闭，错误信息：close connection,reason:stream closed，无其他错误信息，具体原因有待进一步查找

**Comment by magicdoom** [comment]
我这个问题是由于返回ok包id被多加了1引起了，我已经提交了pull request，你可以取下来测测。看看是否还会出错

**Comment by curt001** [comment]
的确是这个原因导致的，我这把那行删了后测试了下sql执行正常了

**Comment by magicdoom** [comment]
确认了就把这个问题关闭吧

**Comment by linzhiqiang0514** [comment]
问题已解决。
