### ISSUE TITLE
1.6.6.1 管理端口有问题 9066 运行 Show @@backend 无响应 1.6.5可以使用

### ISSUE THREAD

**Issue by pkingwsd** [MyCATApache/Mycat-Server#2063]
1.6.6.1 管理端口有问题 9066 运行 Show @@backend 无响应 1.6.5可以使用

**Comment by zwyqz** [comment]
测了没问题哦

**Comment by pkingwsd** [comment]
今天又试了一下，没有Mycat-server-1.6.6.1-release-20181031195535-linux.tar.gz,又可以联上了。关闭问题，谢谢
