### ISSUE TITLE
mycat 1.6.5 release版本jdbc错误

### ISSUE THREAD

**Issue by fbbin** [MyCATApache/Mycat-Server#2070]
显示看到了mycat很多错误日志  _client closed_ 然后上issue查了下，有童鞋说dbdriver切换到jdbc就好了，于是尝试试下；发现切换到jdbc之后出现了一个很奇怪的问题，首先环境如下：php用的phalcon的框架，然后mycat是1.6.5 release版本，数据库是mysql5.1。问题描述：本来update一个字段的，但是会把其他字段（类型都是tinyint）的值设置为一个莫名其妙的值 。
` 

       $video = Videos::findFirst($id);
       if ($video) {
                // 这里只更新两个字段
                $video->playCnt = $video->playCnt + 1;
                $video->updatedAt = date('Y-m-d H:i:s');
                $video->save();
            }`
这是php调用的代码，然后报错的内容为：

`
execute  sql err : errno:1264 Data truncation: Out of range value for column 'watermark' at row 1 con:JDBCConnection [id=3391,autocommit=true,pool=io.mycat.backend.jdbc.JDBCDatasource@8672c36, schema=new_videos, dbType=MYSQL, oldSchema=new_videos, packetId=1, txIsolation=0, running=false, borrowed=true, host=10.62.62.102, port=3306, con=com.mysql.jdbc.JDBC4Connection@27cf3327, respHandler=SingleNodeHandler [node=dataNodeNewVideos{UPDATE `video_videos` SET `uid` = '158978', `game.... `watermark` = '14644', `prefr.....}, headerOutputed=false, modifiedSQLExecuted=true, startTime=1543239429173, lastTime=1543239429176, isSpark=false, processor=io.mycat.net.NIOProcessor@5c64d6e2] frontend ...`
中间省略了一部分内容，字段watermark是tinyint类型的，数据库默认是0 ，然后 执行第一次更新是OK的，但是这个watermark字段值却变成了49，按理说要是溢出了也是最大的255才对啊；然后如果这时候继续更新一次，那就报错了，也就是出现上面的错误了。前提是这个在dbdriver为native模式下都是OK的。

**Comment by 437865981** [comment]
看打印出来的日志sql，你设置的  watermark = '14644',  看下代码这个字段的设值是不是哪里有问题

**Comment by fbbin** [comment]
> 看打印出来的日志sql，你设置的 watermark = '14644', 看下代码这个字段的设值是不是哪里有问题
不是的，你看我上面贴的PHP代码，我没有设置这个值，我也不知道这个14644是怎么设置上去的；如果这个PHP代码有问题，那么在native下也应该是有问题的，但是native都是没有问题的。

**Comment by fbbin** [comment]
在JDBC的URL中加入参数：tinyInt1isBit=false即可。
1对应的bit值就是49，2对应的是50以此类推。
