### ISSUE TITLE
distinct 与 常量别名使用时报错，版本1.6.6

### ISSUE THREAD

**Issue by hehuang139** [MyCATApache/Mycat-Server#2081]
发现 select dictinct 1 as alias这种语法时会报错，看了下后台日志，distinct应该是通过group by实现的，但是mycat在解析的时候，并没有把1 as alias 解析成group by 1，而是解析成group by 1 as alias，故报错。初步推断应该是druid解析sql时的问题，因为 field as alias是正常解析成group by field 不会带上alias。并且发现有人之前提过这个问题，希望能解决下

**Comment by Fxdemon** [comment]
升级druid  1.1.11 可以解决

**Comment by hehuang139** [comment]
好的，多谢
