### ISSUE TITLE
Mycat支持多个注解同时使用吗？"/*!mycat:schema=" + schema + " */" /*!mycat:catlet=io.mycat.catlets.ShareJoin */

### ISSUE THREAD

**Issue by jinliang123** [MyCATApache/Mycat-Server#2098]

**Comment by Fxdemon** [comment]
个人建议 
规避法：
1.首先需要对mycat 支持动态部署和动态配置  
2.应用端需要动态支持schema设置  
3.这样跨库查询的时候就可以  /!mycat:catlet=io.mycat.catlets.ShareJoin */ 
改造法：
对MyCat进行二次开发 满足你的需求 。
一个注解解决2中需求 
多注解支持功能开发
实现思路：数组解析 先schema 再 catlet 
如：/!mycat:｛schema，catlet｝=｛schema，io.mycat.catlets.ShareJoin｝ */  支持这样的注解

**Comment by jinliang123** [comment]
@Fxdemon 好的，我试试 谢谢
