### ISSUE TITLE
mycat全局表DML操作阻塞，直到连接超时和后端的mysql断开连接

### ISSUE THREAD

**Issue by blackghost-01** [MyCATApache/Mycat-Server#210]
环境信息：
mycat：centos 6.6 64bit，jdk 1.7.0_75
mysql：mariadb 10.0.15，一主一从

按照mycat默认的配置文件，创建全局表company
CREATE TABLE `company` (
  `id` int(10) NOT NULL,
  `name` char(64) NOT NULL,
  `uptime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

但是，对company表做DML（insert,update,delete），都会被阻塞，直到连接超时，和后端的mysql断开，前台报错为ERROR 2013 (HY000): Lost connection to MySQL server during query。打开mycat debug级别的日志，后台日志如下：
04/07 14:01:10.989  DEBUG [$_AIO1] (NonBlockingSession.java:117) -ServerConnection [id=1, schema=test, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=test]insert into company(`id`,`name`) values(2,'lianjia'), route={
   1 -> dn1{insert into company(`id`,`name`) values(2,'lianjia')}
   2 -> dn2{insert into company(`id`,`name`) values(2,'lianjia')}
   3 -> dn3{insert into company(`id`,`name`) values(2,'lianjia')}
} rrs 
04/07 14:01:10.999  DEBUG [$_AIO1] (MultiNodeQueryHandler.java:78) -execute mutinode query insert into company(`id`,`name`) values(2,'lianjia')
04/07 14:05:52.382   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=6, lastTime=1428386451858, schema=db2, borrowed=false, fromSlaveDB=false, threadId=814255, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.384   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=6, lastTime=1428386451858, schema=db2, borrowed=false, fromSlaveDB=false, threadId=814255, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.384   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=8, lastTime=1428386451858, schema=db2, borrowed=false, fromSlaveDB=false, threadId=814253, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.385   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=8, lastTime=1428386451858, schema=db2, borrowed=false, fromSlaveDB=false, threadId=814253, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.385   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=2, lastTime=1428386470990, schema=db2, borrowed=true, fromSlaveDB=false, threadId=814247, charset=utf8, txIsolation=0, autocommit=true, attachment=dn2{insert into company(`id`,`name`) values(2,'lianjia')}, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.385   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=2, lastTime=1428386470990, schema=db2, borrowed=true, fromSlaveDB=false, threadId=814247, charset=utf8, txIsolation=0, autocommit=true, attachment=dn2{insert into company(`id`,`name`) values(2,'lianjia')}, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.386   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=10, lastTime=1428386451858, schema=db3, borrowed=false, fromSlaveDB=false, threadId=814254, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.387   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=10, lastTime=1428386451858, schema=db3, borrowed=false, fromSlaveDB=false, threadId=814254, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.387   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=4, lastTime=1428386451858, schema=db1, borrowed=false, fromSlaveDB=false, threadId=814250, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.387   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=4, lastTime=1428386451858, schema=db1, borrowed=false, fromSlaveDB=false, threadId=814250, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.388   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=5, lastTime=1428386470990, schema=db3, borrowed=true, fromSlaveDB=false, threadId=814251, charset=utf8, txIsolation=0, autocommit=true, attachment=dn3{insert into company(`id`,`name`) values(2,'lianjia')}, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.388   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=5, lastTime=1428386470990, schema=db3, borrowed=true, fromSlaveDB=false, threadId=814251, charset=utf8, txIsolation=0, autocommit=true, attachment=dn3{insert into company(`id`,`name`) values(2,'lianjia')}, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.389   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=7, lastTime=1428386451858, schema=db1, borrowed=false, fromSlaveDB=false, threadId=814256, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.389   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=7, lastTime=1428386451858, schema=db1, borrowed=false, fromSlaveDB=false, threadId=814256, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.389   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=9, lastTime=1428386451858, schema=db3, borrowed=false, fromSlaveDB=false, threadId=814252, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.390   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=9, lastTime=1428386451858, schema=db3, borrowed=false, fromSlaveDB=false, threadId=814252, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.390   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=1, lastTime=1428386470990, schema=db1, borrowed=true, fromSlaveDB=false, threadId=814249, charset=utf8, txIsolation=0, autocommit=true, attachment=dn1{insert into company(`id`,`name`) values(2,'lianjia')}, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.391   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=1, lastTime=1428386470990, schema=db1, borrowed=true, fromSlaveDB=false, threadId=814249, charset=utf8, txIsolation=0, autocommit=true, attachment=dn1{insert into company(`id`,`name`) values(2,'lianjia')}, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:52.391   INFO [Timer0] (AbstractConnection.java:399) -MySQLConnection [id=3, lastTime=1428386451858, schema=db1, borrowed=false, fromSlaveDB=false, threadId=814248, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] idle timeout
04/07 14:05:52.392   INFO [Timer0] (AbstractConnection.java:386) -close connection,reason: idle  ,MySQLConnection [id=3, lastTime=1428386451858, schema=db1, borrowed=false, fromSlaveDB=false, threadId=814248, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.2.13, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/07 14:05:53.372   INFO [Timer1] (PhysicalDatasource.java:221) -create connections ,because idle connection not enough ,cur is 0, minCon is 10 for hostM1
04/07 14:05:53.374   INFO [Timer1] (PhysicalDatasource.java:221) -create connections ,because idle connection not enough ,cur is 0, minCon is 10 for hostS1

已经按照 @从零开始 的建议，参考https://github.com/MyCATApache/Mycat-Server/issues/73排查问题，但是虚拟机并非单核设置，同时也添加了
&lt;property name="usingAIO"&gt;1&lt;/property&gt;
但是问题依旧，请各位大侠帮忙看看

**Comment by blackghost-01** [comment]
今天换到物理机测试了下，环境完全一样，仍然长时间处于阻塞状态

**Comment by stonelion** [comment]
1.查后端数据库，是不是my.cnf里面设置了autocommit = 0。
2.抓包查看，是不是mycat发出的设置事务隔离级别的包数据库收到后没有response。

**Comment by blackghost-01** [comment]
这个问题和https://github.com/MyCATApache/Mycat-Server/issues/215的问题解决办法一致，参考解决方法
