### ISSUE TITLE
union  功能不完善

### ISSUE THREAD

**Issue by waj89757** [MyCATApache/Mycat-Server#212]
有union的语句，如果查询条件加入group by ，最终查询结果不一致。回调函数没有对结果进行相同行的校验。
sql：
select a, b from talbe1 group by a,b
union 
select c,d from table2 group by c,d

源码有关Union解析的方法被注释了，身为菜鸟的本人想不出比较好的办法解决，求大神们指教～

**Comment by yoyoch1** [comment]
那个版本？

**Comment by waj89757** [comment]
1.3

**Comment by mycatmerger** [comment]
2个group by的字段都不一样，在mycat这边不好做groupby处理
