### ISSUE TITLE
ERROR 1003 (HY000): mycat sequnce err.java.lang.RuntimeException: can't fetch sequnce in db,sequnce :TRAVELRECORD detail:FUNCTION db1.mycat_seq_nextval does not exist

### ISSUE THREAD

**Issue by jianrry** [MyCATApache/Mycat-Server#2133]
已经设置了全局自增ID（数据库方式）

节点1（安装了MySQL和MyCat）：

数据库：db1、mycat（通过root用户导入了dbseq.sql文件）

节点2（仅安装了MySQL）：

数据库：db2

[conf.zip](https://github.com/MyCATApache/Mycat-Server/files/2896523/conf.zip)

往虚拟表里面插入数据，会提示“ERROR 1003 (HY000): mycat sequnce err.java.lang.RuntimeException: can't fetch sequnce in db,sequnce :TRAVELRECORD detail:FUNCTION db1.mycat_seq_nextval does not exist”

**Comment by jianrry** [comment]
所有的配置文件都打包上传了，麻烦各位大佬看一下。

**Comment by zwyqz** [comment]
看下db1里面的函数有木有创建成功

**Comment by Shangege337X** [comment]
请问解决了这个问题了吗 我也遇到了
