### ISSUE TITLE
Mycat对空串处理的BUG

### ISSUE THREAD

**Issue by gerogefeng** [MyCATApache/Mycat-Server#214]
数据库中某字段存储空串，但通过Mycat返回的数据，显示该字段为Null。（数据库为SQL Server)

**Comment by stonelion** [comment]
连接SQL server是使用JDBC，JDBC对空字段为null。

**Comment by magicdoom** [comment]
可以同最新代码测试下看看问题是否解决

**Comment by bluoy** [comment]
RowDataPacket.write()中，将空串和NULL做了等同处理，都转换成NULL(0xfb)了。

**Comment by magicdoom** [comment]
多谢bluoy，已经合并到master

**Comment by laoqiu** [comment]
哪个版本是正常的？
