### ISSUE TITLE
mycat分片表查询不带分片键执行失败，报错为ERROR 2013 (HY000): Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by blackghost-01** [MyCATApache/Mycat-Server#215]
日志报错如下：

04/09 11:47:49.206  DEBUG [$_NIOREACTOR-1-RW] (ServerQueryHandler.java:64) -ServerConnection [id=4, schema=test, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=test]select * from customer
04/09 11:47:49.206  DEBUG [$_NIOREACTOR-1-RW] (EnchachePool.java:76) -SQLRouteCache  miss cache ,key:testselect * from customer
04/09 11:47:49.207  DEBUG [$_NIOREACTOR-1-RW] (EnchachePool.java:59) -SQLRouteCache add cache ,key:testselect * from customer value:select * from customer, route={
   1 -> dn1{SELECT *
FROM customer
LIMIT 100}
   2 -> dn2{SELECT *
FROM customer
LIMIT 100}
   3 -> dn3{SELECT *
FROM customer
LIMIT 100}
}
04/09 11:47:49.207  DEBUG [$_NIOREACTOR-1-RW] (NonBlockingSession.java:117) -ServerConnection [id=4, schema=test, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=test]select * from customer, route={
   1 -> dn1{SELECT *
FROM customer
LIMIT 100}
   2 -> dn2{SELECT *
FROM customer
LIMIT 100}
   3 -> dn3{SELECT *
FROM customer
LIMIT 100}
} rrs 
04/09 11:47:49.212  DEBUG [$_NIOREACTOR-1-RW] (MultiNodeQueryHandler.java:78) -execute mutinode query select * from customer
04/09 11:47:49.214  DEBUG [$_NIOREACTOR-1-RW] (PhysicalDBPool.java:417) -select read source hostS1 for dataHost:lianjia01
04/09 11:47:49.214  DEBUG [$_NIOREACTOR-1-RW] (PhysicalDBPool.java:417) -select read source hostS1 for dataHost:lianjia01
04/09 11:47:49.214  DEBUG [$_NIOREACTOR-1-RW] (PhysicalDBPool.java:417) -select read source hostS1 for dataHost:lianjia01
04/09 11:47:49.218  DEBUG [BusinessExecutor25] (MySQLConnection.java:330) -MySQLConnection [id=20, lastTime=1428551269213, schema=db2, borrowed=true, fromSlaveDB=true, threadId=173, charset=utf8, txIsolation=0, autocommit=true, attachment=dn2{select * from customer}, respHandler=NodeWithLimitHandler [node=dn2{select * from customer}, packetId=0], host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
   need syn txIsolationCmd MySQL Command Packet{length=0,id=0}

04/09 11:47:49.219  DEBUG [BusinessExecutor26] (MySQLConnection.java:330) -MySQLConnection [id=18, lastTime=1428551269213, schema=db3, borrowed=true, fromSlaveDB=true, threadId=171, charset=utf8, txIsolation=0, autocommit=true, attachment=dn3{select * from customer}, respHandler=NodeWithLimitHandler [node=dn3{select * from customer}, packetId=0], host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
   need syn txIsolationCmd MySQL Command Packet{length=0,id=0}

04/09 11:47:49.221   INFO [$_NIOREACTOR-1-RW] (AbstractConnection.java:386) -close connection,reason:stream closed ,ServerConnection [id=4, schema=test, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=test]
04/09 11:47:49.221   INFO [$_NIOREACTOR-1-RW] (AbstractConnection.java:386) -close connection,reason:client closed  ,MySQLConnection [id=18, lastTime=1428551269213, schema=db3, borrowed=true, fromSlaveDB=true, threadId=171, charset=utf8, txIsolation=0, autocommit=true, attachment=dn3{select * from customer}, respHandler=NodeWithLimitHandler [node=dn3{select * from customer}, packetId=0], host=172.30.17.22, port=3306, statusSync=StatusSync [schemaCmd=null, charCmd=null, isoCmd=null, acCmd=null, executed=false], writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.222  DEBUG [$_NIOREACTOR-1-RW] (PhysicalDatasource.java:386) -release channel MySQLConnection [id=18, lastTime=1428551269213, schema=db3, borrowed=true, fromSlaveDB=true, threadId=171, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.222  DEBUG [$_NIOREACTOR-1-RW] (NonBlockingSession.java:279) -realse connection MySQLConnection [id=18, lastTime=1428551269213, schema=db3, borrowed=false, fromSlaveDB=true, threadId=171, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.222   WARN [$_NIOREACTOR-1-RW] (NodeWithLimitHandler.java:173) -execute  sql err : errno:1003 client closed  con:MySQLConnection [id=18, lastTime=1428551269213, schema=db3, borrowed=false, fromSlaveDB=true, threadId=171, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.223   INFO [$_NIOREACTOR-1-RW] (AbstractConnection.java:386) -close connection,reason:client closed  ,MySQLConnection [id=20, lastTime=1428551269213, schema=db2, borrowed=true, fromSlaveDB=true, threadId=173, charset=utf8, txIsolation=0, autocommit=true, attachment=dn2{select * from customer}, respHandler=NodeWithLimitHandler [node=dn2{select * from customer}, packetId=0], host=172.30.17.22, port=3306, statusSync=StatusSync [schemaCmd=null, charCmd=null, isoCmd=null, acCmd=null, executed=false], writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.223  DEBUG [$_NIOREACTOR-1-RW] (PhysicalDatasource.java:386) -release channel MySQLConnection [id=20, lastTime=1428551269213, schema=db2, borrowed=true, fromSlaveDB=true, threadId=173, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.223  DEBUG [$_NIOREACTOR-1-RW] (NonBlockingSession.java:279) -realse connection MySQLConnection [id=20, lastTime=1428551269213, schema=db2, borrowed=false, fromSlaveDB=true, threadId=173, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.223   WARN [$_NIOREACTOR-1-RW] (NodeWithLimitHandler.java:173) -execute  sql err : errno:1003 client closed  con:MySQLConnection [id=20, lastTime=1428551269213, schema=db2, borrowed=false, fromSlaveDB=true, threadId=173, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.223   INFO [$_NIOREACTOR-1-RW] (AbstractConnection.java:386) -close connection,reason:client closed  ,MySQLConnection [id=16, lastTime=1428551269213, schema=db1, borrowed=true, fromSlaveDB=true, threadId=170, charset=utf8, txIsolation=3, autocommit=true, attachment=dn1{select * from customer}, respHandler=NodeWithLimitHandler [node=dn1{select * from customer}, packetId=0], host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.224  DEBUG [$_NIOREACTOR-1-RW] (PhysicalDatasource.java:386) -release channel MySQLConnection [id=16, lastTime=1428551269213, schema=db1, borrowed=true, fromSlaveDB=true, threadId=170, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.224  DEBUG [$_NIOREACTOR-1-RW] (NonBlockingSession.java:279) -realse connection MySQLConnection [id=16, lastTime=1428551269213, schema=db1, borrowed=false, fromSlaveDB=true, threadId=170, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.224   WARN [$_NIOREACTOR-1-RW] (NodeWithLimitHandler.java:173) -execute  sql err : errno:1003 client closed  con:MySQLConnection [id=16, lastTime=1428551269213, schema=db1, borrowed=false, fromSlaveDB=true, threadId=170, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
04/09 11:47:49.224  DEBUG [$_NIOREACTOR-1-RW] (NIOReactor.java:119) -ServerConnection [id=4, schema=test, host=127.0.0.1, user=root,txIsolation=3, autocommit=true, schema=test] socket key canceled
04/09 11:47:49.238  DEBUG [$_NIOREACTOR-0-RW] (NIOSocketWR.java:58) -caught err:
java.nio.channels.AsynchronousCloseException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:478)
	at org.opencloudb.net.NIOSocketWR.write0(NIOSocketWR.java:98)
	at org.opencloudb.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:42)
	at org.opencloudb.net.AbstractConnection.write(AbstractConnection.java:328)
	at org.opencloudb.net.AbstractConnection.write(AbstractConnection.java:313)
	at org.opencloudb.mysql.nio.handler.MultiNodeQueryWithLimitHandler.fieldEofResponse(MultiNodeQueryWithLimitHandler.java:350)
	at org.opencloudb.mpp.MutiDataMergeService.fieldEofResponse(MutiDataMergeService.java:270)
	at org.opencloudb.mysql.nio.handler.NodeWithLimitHandler.fieldEofResponse(NodeWithLimitHandler.java:228)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:177)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:116)
	at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:41)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:80)
	at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:216)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:264)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:226)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:97)
	at java.lang.Thread.run(Thread.java:745)
04/09 11:47:49.238  DEBUG [$_NIOREACTOR-0-RW] (MutiDataMergeService.java:160) -field metadata inf:[ID=ColMeta [colIndex=0, colType=3], PROVINCE_CODE=ColMeta [colIndex=3, colType=3], NAME=ColMeta [colIndex=1, colType=254], PHONE=ColMeta [colIndex=2, colType=253]]
04/09 11:47:49.239  DEBUG [$_NIOREACTOR-0-RW] (NIOReactor.java:119) -MySQLConnection [id=16, lastTime=1428551269213, schema=db1, borrowed=false, fromSlaveDB=true, threadId=170, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=172.30.17.22, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] socket key canceled

**Comment by magicdoom** [comment]
server.xml中的mutiNodeLimitType参数配置为0，或者直接注释掉

**Comment by stonelion** [comment]
NodeWithLimitHandler,不要使用handler，这个已经不怎么使用了。

**Comment by blackghost-01** [comment]
按照2楼的方法，将mutiNodeLimitType参数配置为0，问题解决，问题关闭
