### ISSUE TITLE
mycat自增ID当清空数据并修改步长后的2只种现象

### ISSUE THREAD

**Issue by EthanMR** [MyCATApache/Mycat-Server#2152]
昨天测试发现，用mycat的数据库方法配置分片的自增ID，sequence表的current_value和increment分别为5000和1000，这时重启mycat使用inset into user(id,name)value(null,小王)，这种带ID列的插入语句时，id取到的值会是宕机前没用完的值，比如宕机前用到5500，那这次就会说5501。而使用不带ID列的插入语句就会重6000开始取。
按mycat的文档的接收，应该是后面一种情况才是正确的，可是第一种情况的值是哪儿取得呢？并且取值会重复

**Comment by apachemycat** [comment]
insert into table1(id,name) values(next value for MYCATSEQ_GLOBAL,‘test’);  //next value for xxxx

**Comment by zwyqz** [comment]
id对应的插入值为null 在1.6.7已经可以可的了
