### ISSUE TITLE
mycat 1.6.6.1-release 编译不过

### ISSUE THREAD

**Issue by cocoZwwang** [MyCATApache/Mycat-Server#2154]
mycat 1.6.6.1-release 编译不过，报下面的错误：Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.3:create (default) on project Mycat-server: Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:1.3:create failed: A required class was missing while executing org.codehaus.mojo:buildnumber-maven-plugin:1.3:create: org/apache/maven/scm/command/untag/UntagScmResult

请问有谁能解答一下么？

**Comment by cocoZwwang** [comment]
最上面是报这个错误 Error injecting: org.apache.maven.scm.provider.git.gitexe.GitExeScmProvider

**Comment by apachemycat** [comment]
https://github.com/MyCATApache/Mycat-Server/tree/1.6/ 这个分支吗

**Comment by cocoZwwang** [comment]
@apachemycat 是的

**Comment by BHfeimao** [comment]
同问

**Comment by joyken** [comment]
同问

**Comment by chrissata** [comment]
修改 pom.xml maven-scm-provider-gitexe版本由RELEASE 改成1.11.1 后，编译成功。 猜测是因为3月下旬maven-scm-provider-gitexe 这个发布了最新的1.11.2 缘故
					<dependency>
						<groupId>org.apache.maven.scm</groupId>
						<artifactId>maven-scm-provider-gitexe</artifactId>
						<version>1.11.1</version>
					</dependency>

**Comment by cocoZwwang** [comment]
@chrissata 确实可以了，谢谢

**Comment by whryuuki** [comment]
@chrissata 谢谢，确实是按照你说的来解决的

**Comment by fzng** [comment]
@chrissata 谢谢 可以了 不过我的版本只能使用 1.9.2  

<dependency>
		<groupId>org.apache.maven.scm</groupId>
		<artifactId>maven-scm-provider-gitexe</artifactId>
                
		<version>1.9.2</version>
</dependency>

**Comment by fzng** [comment]
@chrissata 谢谢 可以了 不过我的版本只能使用 1.9.2
![image](https://user-images.githubusercontent.com/23091623/61935969-3fc47f00-afbe-11e9-85f7-573d7c1d7e46.png)
