### ISSUE TITLE
使用JDBC连接出现1049-Unkown database 'attendacne'

### ISSUE THREAD

**Issue by maybewh** [MyCATApache/Mycat-Server#2157]
<schema name="attendance" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1"/>
    <dataNode name="dn1" dataHost="hostS1" database="mytest"/>
    <dataHost balance="0" maxCon="1000" minCon="10" name="hostS1" writeType="0" switchType="1" slaveThreshold="100" dbType="mysql" dbDriver="jdbc">
        <heartbeat>select user()</heartbeat>
        <writeHost host="202.115.16.127" url="jdbc:mysql://202.115.16.127:3306?useSSL=false&amp;serverTimezone=UTC&amp;characterEncoding=utf8" password="Root@123456" user="root"/>
    </dataHost>

当dataNode标签中database和schema标签中的name的名称一致时，能够访问成功。但是，名称若不一样，则访问失败，出现1049-Unkown database 'attendacne'错误（使用navicate时，Mysql8.0出现该错误，mysql5.7能正常使用。但使用sql语句查询，能正常使用）

**Comment by gaotuan** [comment]
应该是你配置没写对， schema中的name定义的是 schema的名字，另一个是数据库的名字。这2个完全没有关系

**Comment by xiaonian0430** [comment]
dbDriver="jdbc"或dbDriver="native"都可以的。关键问题是你需要把checkSQLschema="false"改成checkSQLschema="true"
