### ISSUE TITLE
9066端口reload@@config无效

### ISSUE THREAD

**Issue by zhaoshihua** [MyCATApache/Mycat-Server#217]
基于数据库表的全局序列号, 新加入一个序列号, 配置好schema.xml, sequence_db_conf.properties, 插入数据到mycat_sequence; 然后reload @@config无效, 重启mycat后, 序列号正式生效, 怀疑是load不成功.

**Comment by stonelion** [comment]
reload没有重新载入sequence_db_conf.properties，文件配置的只是测试使用。还行建议使用数据库形式的。

**Comment by zhaoshihua** [comment]
那么, 是不是配置的时候不用配置sequence_db_conf.properties? reload会加载最新的数据库mycat_sequence表吗?



438383939@qq.com
 
发件人： stone_lion
发送时间： 2015-04-15 12:01
收件人： MyCATApache/Mycat-Server
抄送： zhaoshihua
主题： Re: [Mycat-Server] 9066端口reload@@config无效 (#217)
reload没有重新载入sequence_db_conf.properties，文件配置的只是测试使用。还行建议使用数据库形式的。

**Comment by stonelion** [comment]
是的。数据库保存的序列和本地文件无关。
