### ISSUE TITLE
Mycat cpu使用率高

### ISSUE THREAD

**Issue by ktktss** [MyCATApache/Mycat-Server#2175]
两次都是运行一段时间后，Mycat 服务器负载到8,cpu 使用率800%
jstack 的截图

"BusinessExecutor39" daemon prio=10 tid=0x00007fc4f40b8000 nid=0xd670 runnable [0x00007fc42adec000]
   java.lang.Thread.State: RUNNABLE
	at io.mycat.memory.unsafe.Platform.copyMemory(Platform.java:302)
	at io.mycat.memory.unsafe.row.BufferHolder.grow(BufferHolder.java:64)
	at io.mycat.memory.unsafe.row.UnsafeRowWriter.write(UnsafeRowWriter.java:182)
	at io.mycat.memory.unsafe.row.UnsafeRowWriter.write(UnsafeRowWriter.java:175)
	at io.mycat.sqlengine.mpp.DataNodeMergeManager.run(DataNodeMergeManager.java:434)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)

jmp INFO   | jvm 1    | 2019/04/13 19:41:03 | Heap
INFO   | jvm 1    | 2019/04/13 19:41:03 |  PSYoungGen      total 3494912K, used 983094K [0x000000072aa80000, 0x0000000800000000, 0x0000000800000000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |   eden space 3494400K, 28% used [0x000000072aa80000,0x0000000766a65818,0x00000007fff00000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |   from space 512K, 31% used [0x00000007fff80000,0x00000007fffa8000,0x0000000800000000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |   to   space 512K, 0% used [0x00000007fff00000,0x00000007fff00000,0x00000007fff80000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |  ParOldGen       total 6990848K, used 3537297K [0x000000057ff80000, 0x000000072aa80000, 0x000000072aa80000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |   object space 6990848K, 50% used [0x000000057ff80000,0x0000000657de44d0,0x000000072aa80000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |  PSPermGen       total 45568K, used 22811K [0x000000057bf80000, 0x000000057ec00000, 0x000000057ff80000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |   object space 45568K, 50% used [0x000000057bf80000,0x000000057d5c6e18,0x000000057ec00000)
INFO   | jvm 1    | 2019/04/13 19:41:03 |

**Comment by junwen12221** [comment]
<property name="useOffHeapForMerge">0</property>

**Comment by ktktss** [comment]
关闭这个选项没用，最后的原因是  开发写的sql语句有问题,
W] (io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler.handleDataProcessException(MultiNodeQueryHandler.java:814)) - io.mycat.backend.mysql.nio.handler.MultiNodeQueryHandler@39f5353a caught exception 
java.lang.IllegalArgumentException: all columns in order by clause should be in the selected column list!REQ_DATE

所有order by的sql 都必须写到select 字段，不然这个语句执行一次 负载就+1

**Comment by ktktss** [comment]
这个应该是mycat 的bug吧

**Comment by venusdrogon** [comment]
我们也经常 mycat CPU 占用 100%
