### ISSUE TITLE
求助:mycat1.6.5是否支持1主1从标准配置

### ISSUE THREAD

**Issue by freeport0421** [MyCATApache/Mycat-Server#2180]
通过测试发现，mysql-native客户端操作SQL查询语句（select），都分发到了主库。这是什么原因?

**Comment by junwen12221** [comment]
writeType="0", 所有写操作发送到配置的第一个writeHost，第一个挂了切到还生存的第二个writeHost，重新启动后已切换后的为准，切换记录在配置文件中:dnindex.properties .

<heartbeat>show slave status</heartbeat>
switchType="2" slaveThreshold="100" notSwitch="1"(三个同时设置)
根据show slave status结果中的主从同步状态,如果Seconds_Behind_Master大于slaveThreshold,就把请求发往主节点, notSwitch = “1”表示,在switchType="2"的主从切换不开启


或者直接switchType="-1"
即完成主备配置

**Comment by freeport0421** [comment]
问题已解决，thanks!
