### ISSUE TITLE
等了mycat2.0 4年了，也停了leader_us吹了4年了 现在2.0稳定版还没出来

### ISSUE THREAD

**Issue by readazusa** [MyCATApache/Mycat-Server#2195]
等了mycat2.0 4年了，也听了leader_us鼓吹4年了 现在2.0稳定版还没出来  哎

**Comment by kuaikuai** [comment]
不要用了。天天只知道吹牛，原来挺好的代码基础，变得越来越烂。

**Comment by daiwenlong** [comment]
暴躁老哥

**Comment by readazusa** [comment]
就像二楼哥们说的一样，原来很好的一个东西现在搞成什么样了。整天搞培训、吹牛逼。看看后来居上的SS，哎！

**Comment by stonyz** [comment]
> 就像二楼哥们说的一样，原来很好的一个东西现在搞成什么样了。整天搞培训、吹牛逼。看看后来居上的SS，哎！

SS是啥？ 我试下看看。

**Comment by gaotuan** [comment]
项目没什么更新了，主要功能还停留在2016年

**Comment by gaotuan** [comment]
官方首页也是垃圾，什么都放在上面，哎。。

**Comment by readazusa** [comment]
> > 就像二楼哥们说的一样，原来很好的一个东西现在搞成什么样了。整天搞培训、吹牛逼。看看后来居上的SS，哎！
> 
> SS是啥？ 我试下看看。

Apache ShardingSphere
以前是当当的sjdbc,创始人现在在京东，目前已经在apache孵化，哥们应该听过

**Comment by readazusa** [comment]
> 官方首页也是垃圾，什么都放在上面，哎。。

哎，很好的一个东西，搞成这个吊样，天天就知道吹牛逼，只要谁在群里说他不好然后直接把别人踢出群，最主要的是别人进群还需要收费，反正收费就是听他吹牛逼搞培训。
https://www.zhihu.com/question/67895376/answer/306511149  
可以看看知乎的评价 哎！

**Comment by readazusa** [comment]
> 暴躁老哥
我暴躁？ 哎，中国的开源如果都和mycat一样，那就完蛋了。

**Comment by HashZhang** [comment]
没进过那个QQ群，也没接触过leaderus，对他们不加评论。
先开始读过，后来贡献过不少源码，和crazypig，爱国，南哥合作过，都是技术牛逼人也很nice，那时候是1.6刚出。现在看到这样确实有点难过。
不过也是因为没有变现手段，中国的开源没有大公司的支持很难继续下去。
用了ShardingSphere，对比上，感觉有点像拿Pulsar与kafka，rocketMQ对比。ShardingSphere是一个很全面的东西，有很多想在mycat上做的功能，Sharding-Proxy和Sharding-Sidecar上面有体现。还是不错的，希望这个社区一直活跃。
也希望MyCat 2.0能重获新生

**Comment by gaotuan** [comment]
啥也不说了，看看mycat权威指南   错字，标点符号，格式。。。

**Comment by daiwenlong** [comment]
这个项目算是黄了，创始人心思不在这上面，年纪大想着变现

**Comment by readazusa** [comment]
> 没进过那个QQ群，也没接触过leaderus，对他们不加评论。
> 先开始读过，后来贡献过不少源码，和crazypig，爱国，南哥合作过，都是技术牛逼人也很nice，那时候是1.6刚出。现在看到这样确实有点难过。
> 不过也是因为没有变现手段，中国的开源没有大公司的支持很难继续下去。
> 用了ShardingSphere，对比上，感觉有点像拿Pulsar与kafka，rocketMQ对比。ShardingSphere是一个很全面的东西，有很多想在mycat上做的功能，Sharding-Proxy和Sharding-Sidecar上面有体现。还是不错的，希望这个社区一直活跃。
> 也希望MyCat 2.0能重获新生

膜拜大神，就算没有变现手段也不至于这样吧，那还开源什么。

**Comment by HashZhang** [comment]
> > 没进过那个QQ群，也没接触过leaderus，对他们不加评论。
> > 先开始读过，后来贡献过不少源码，和crazypig，爱国，南哥合作过，都是技术牛逼人也很nice，那时候是1.6刚出。现在看到这样确实有点难过。
> > 不过也是因为没有变现手段，中国的开源没有大公司的支持很难继续下去。
> > 用了ShardingSphere，对比上，感觉有点像拿Pulsar与kafka，rocketMQ对比。ShardingSphere是一个很全面的东西，有很多想在mycat上做的功能，Sharding-Proxy和Sharding-Sidecar上面有体现。还是不错的，希望这个社区一直活跃。
> > 也希望MyCat 2.0能重获新生
> 
> 膜拜大神，就算没有变现手段也不至于这样吧，那还开源什么。

过奖，并非大神。
这个是个人意愿吧，当初开源也肯定是想做个好东西出来，后来没有leaderus的宣传，估计mycat也不会太出名，然后之前接触过leaderus培训推荐的一个同事，感觉技术还是很可以的，人也很踏实。
但是现在，可能宣传（chui）的过头了，没实现预期，还有QQ群管理问题和社区运营让很多人觉得看不下去（chi xiang wen ti），所以感觉变味道了。
不过也算是在中国凭个人建立开源社区的一种尝试吧。

**Comment by HashZhang** [comment]
> > > 没进过那个QQ群，也没接触过leaderus，对他们不加评论。
> > > 先开始读过，后来贡献过不少源码，和crazypig，爱国，南哥合作过，都是技术牛逼人也很nice，那时候是1.6刚出。现在看到这样确实有点难过。
> > > 不过也是因为没有变现手段，中国的开源没有大公司的支持很难继续下去。
> > > 用了ShardingSphere，对比上，感觉有点像拿Pulsar与kafka，rocketMQ对比。ShardingSphere是一个很全面的东西，有很多想在mycat上做的功能，Sharding-Proxy和Sharding-Sidecar上面有体现。还是不错的，希望这个社区一直活跃。
> > > 也希望MyCat 2.0能重获新生
> > 
> > 
> > 膜拜大神，就算没有变现手段也不至于这样吧，那还开源什么。
> 
> 过奖，并非大神。
> 这个是个人意愿吧，当初开源也肯定是想做个好东西出来，后来没有leaderus的宣传，估计mycat也不会太出名，然后之前接触过leaderus培训推荐的一个同事，感觉技术还是很可以的，人也很踏实。
> 但是现在，可能宣传（chui）的过头了，没实现预期，还有QQ群管理问题和社区运营让很多人觉得看不下去（chi xiang wen ti），所以感觉变味道了。
> 不过也算是在中国凭个人建立开源社区的一种尝试吧。

还有呢，出发点感觉是好的，开源社区。但是感觉大环境下通过开源社区创业变现，很容易做的浮躁。

**Comment by readazusa** [comment]
> > > > 没进过那个QQ群，也没接触过leaderus，对他们不加评论。
> > > > 先开始读过，后来贡献过不少源码，和crazypig，爱国，南哥合作过，都是技术牛逼人也很nice，那时候是1.6刚出。现在看到这样确实有点难过。
> > > > 不过也是因为没有变现手段，中国的开源没有大公司的支持很难继续下去。
> > > > 用了ShardingSphere，对比上，感觉有点像拿Pulsar与kafka，rocketMQ对比。ShardingSphere是一个很全面的东西，有很多想在mycat上做的功能，Sharding-Proxy和Sharding-Sidecar上面有体现。还是不错的，希望这个社区一直活跃。
> > > > 也希望MyCat 2.0能重获新生
> > > 
> > > 
> > > 膜拜大神，就算没有变现手段也不至于这样吧，那还开源什么。
> > 
> > 
> > 过奖，并非大神。
> > 这个是个人意愿吧，当初开源也肯定是想做个好东西出来，后来没有leaderus的宣传，估计mycat也不会太出名，然后之前接触过leaderus培训推荐的一个同事，感觉技术还是很可以的，人也很踏实。
> > 但是现在，可能宣传（chui）的过头了，没实现预期，还有QQ群管理问题和社区运营让很多人觉得看不下去（chi xiang wen ti），所以感觉变味道了。
> > 不过也算是在中国凭个人建立开源社区的一种尝试吧。
> 
> 还有呢，出发点感觉是好的，开源社区。但是感觉大环境下通过开源社区创业变现，很容易做的浮躁。

如果推广和开发同步也好啊，现在是只推广了，没有看见有什么实质性的进展。原来多好的一个项目，也是无奈。
