### ISSUE TITLE
1.6.7.1或1.7两个版本修改操作不支持BigDecimal类型的0E-8值（原值为0.00000000小数点后面8个0）

### ISSUE THREAD

**Issue by LmingXie** [MyCATApache/Mycat-Server#2205]
1.6.7.1或1.7两个版本修改操作不支持BigDecimal类型的0E-8值（原值为0.00000000小数点后面8个0）。会出现mysql lock锁超时，
当将timeout调整为>300s时会出现，MyCat事务不提交问题（MyCat默认数据库连接300s超时）

mycat.log日志输出异常：found backend connection SQL timeout ,close it MySQLConnection，表现症状为，数据库lock锁超时：
ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction，尝试调整MySQL超时时间，修改my.cnf文件添加innodb_lock_wait_timeout=500，配置等待锁超时时间为500秒，
此时出现回滚异常，异常信息提示说：连接超时，系统尝试回滚时，连接已被断开！这是MyCat的异常，MyCat默认一个数据库连接的超时时间为300s，超过就会断开连接。

**Comment by zwyqz** [comment]
BigDecimal 超时问题 可以直连mysql看下是否是mycat问题 
你们什么事务需要300秒 如果是300秒还未提交 应该先把焦点放到解决300秒未提交的问题上

**Comment by LmingXie** [comment]
是的，BigDecimal 超时问题是因为mycat不支持0E-8值，事务超时并不是我们业务逻辑问题，而是因为MyCat不支持BigDecimal类型的0E-8值，导致更新时，MyCat一致不提交事务，最终导致超过了MyCat默认设定的事务最大超时时间300s
