### ISSUE TITLE
106088787 官方群搜不到

### ISSUE THREAD

**Issue by ZHANGLONG678** [MyCATApache/Mycat-Server#2208]
看github首页的官方群106088787 ,但我从QQ加群搜不到

**Comment by yongzhizh** [comment]
发生了什么事情？？
昨天晚上还正常呢，为什么今天qq群打不开了？

![image](https://user-images.githubusercontent.com/22512750/58073444-20cbfa00-7bd5-11e9-966f-3b7eb21a9dcf.png)

**Comment by yongzhizh** [comment]
![image](https://user-images.githubusercontent.com/22512750/58073485-40632280-7bd5-11e9-9157-6342f9f2485b.png)

**Comment by yongzhizh** [comment]
mycat官网的论坛404
官网github地址不对
？？
http://i.mycat.io/

![图片](https://user-images.githubusercontent.com/22512750/58073605-9d5ed880-7bd5-11e9-8e11-78eb297c1e88.png)

**Comment by yongzhizh** [comment]
![图片](https://user-images.githubusercontent.com/22512750/58073687-d9923900-7bd5-11e9-9030-d875459a7f17.png)

**Comment by yongzhizh** [comment]
star  和 fork那两个链接地址写错了

**Comment by junwen12221** [comment]
qq:332702697

**Comment by junwen12221** [comment]
qq群:332702697
