### ISSUE TITLE
为什么MyCAT 版本停留在1.6 而没有发布新的版本？

### ISSUE THREAD

**Issue by vkingnew** [MyCATApache/Mycat-Server#2210]
为什么MyCAT 版本停留在1.6 而没有发布新的版本？最新的版本好像停留在1.6 版本已经两年了，在国内也有不少用户使用于生产，issue也提交了不少和关闭了不少，两年了 mycat 怎么不见发布新的版本号？社区没有发布新版的权限吗 还是代码审核不过关

**Comment by junwen12221** [comment]
我简单列一下原因:
1.开发主力流失
2.按照leader.us的意思,2.0想要全新编写nio内核,难度太大,新来的开源志愿者没有完成完整功能就离开了(加班各种原因)
3.PR是有处理的,就上年来说,起码有10多个PR是合拼了,但也仅限于小修小补的程度

**Comment by junwen12221** [comment]
要是真有同学愿意参与进来,社区还是很欢迎的

**Comment by vkingnew** [comment]
这个应该是开放的主题讨论帖，怎么被关闭了呢? MyCAT社区确实要找找原因了 对比Apache ShardingSphere ，apache mycat 还没进入孵化阶段。建议开发此issue 让更多的社区人员参与讨论而不是关闭。呈现出一种封闭的心态。
