### ISSUE TITLE
小白求教怎么修改root密码

### ISSUE THREAD

**Issue by KeithTt** [MyCATApache/Mycat-Server#2229]
我修改了server.xml里的password，但是重启就恢复成root了。

![image](https://user-images.githubusercontent.com/15189954/59485059-e0475f80-8ea6-11e9-8ab6-cc4baff45836.png)

**Comment by junwen12221** [comment]
不可能吧,是开发环境吗

**Comment by junwen12221** [comment]
有用zookeeper吗

**Comment by KeithTt** [comment]
@junwen12221 
![image](https://user-images.githubusercontent.com/15189954/59556513-47275e80-8ff6-11e9-87ba-a0fb324d3902.png)
看上去是用了。
我看到conf目录下还有一个 zkconf 目录，里面有一层跟conf下一样的配置文件。
![image](https://user-images.githubusercontent.com/15189954/59556528-92da0800-8ff6-11e9-87b7-7c591be2c563.png)

**Comment by zwyqz** [comment]
![image](https://user-images.githubusercontent.com/4454612/59572855-803cfd00-90e2-11e9-9b84-0d5515fb0bd4.png)

loadZk=false 为false 表示没有zk集群 否则有zk集群

**Comment by KeithTt** [comment]
@zwyqz 请问一下，这个是什么配置文件？

**Comment by junwen12221** [comment]
myid.properties

**Comment by KeithTt** [comment]
![image](https://user-images.githubusercontent.com/15189954/59627710-79110000-9171-11e9-8701-3b854152d85c.png)
@zwyqz @junwen12221 看着是用了，求教如何修改配置...

**Comment by junwen12221** [comment]
没有用到zk,把它关闭了,mycat开启了zk会使用zk的配置,而不是本地的

**Comment by KeithTt** [comment]
@junwen12221 直接改成false吗？如果不关闭zk要怎么改配置？

以及我发现我的 bin/mycat 启动脚本不能正常使用。。。

**Comment by junwen12221** [comment]
不关闭zk就直接用zk客户端连接zk把配置改了.或者改zkconf\的配置,使用XmltoZkMain把配置更新到zk

**Comment by KeithTt** [comment]
@junwen12221 我没有找到这个文件....
