### ISSUE TITLE
mycat诡异出错

### ISSUE THREAD

**Issue by fengsen198698** [MyCATApache/Mycat-Server#2236]
线上遇到以下的问题：
1.通过监控show @@connection连接数在一个小时内从100个左右升到600个，并迅速降到100。
2.后端连接的mysql连接数反而在这一个小时内降了100个左右并恢复。（mycat设置的最大连接数490，最小连接数100）
3.在这一个小时内mycat报的一些错误：
1）.receive rollback,but fond backend con is closed or quit
2）.com.alibaba.druid.sql.parser.ParserException: EOF（应用程序发送sql正常，但是mycat端接收的的数据不正确，比如会收到 select a from b where t in(,123,234),应用程序实际发送select a from b where t in(12,123,234)）
4.应用程序报的一些错误：
1.Packets larger than max_allowed_packet are not allowed.（sql长度未超过ax_allowed_packet）
2. Data too long for column   at row 1
3.Could not find specified column in results（表中含有此字段）
4.数据库本身有数据，返回给应用程序空集合。

**Comment by zwyqz** [comment]
1 检查是否事务有超时的情况 默认5分钟


4 问题首先确保mycat处于最新版本。然后不允许一次发送多条sql 
sql解析异常 这个可以贴一下具体报错

**Comment by fengsen198698** [comment]
多谢。
1.看报错，确实有事务超时情况，但事务超时报错仅在那一个小时内。
4.mycat确实不是最新版本，为1.6.查看日志，确实有程序大批量的一次发送多条sql，类似于：INFO   | jvm 1    | 2019/06/18 18:54:09 | UPDATE ercsubscribe_timer SET SchemeId = ? WHERE PushPeriodType = ? 	AND userid = ?; UPDATE ercsubscribe_timer SET SchemeId = ? WHERE PushPeriodType = ? 	AND userid = ?; UPDATE ercsubscribe_timer SET SchemeId = ? WHERE PushPeriodType = ? 	AND userid = ?
请问这样写会影响到什么？为什么不允许。

sql解析异常，有以下几种：
1.INFO   | jvm 1    | 2019/06/18 19:15:31 | 2019-06-18 19:15:31,554 [ERROR][$_NIOREACTOR-10-RW] DruidMycatRouteStrategyError sql:select * from  Classify where parentid= com.alibaba.druid.sql.parser.ParserException: EOF, parentid=
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.equalityRest(SQLExprParser.java:1192)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:112)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:100)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:527)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:247)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:160)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:62)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:237)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:183)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:70)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.route.RouteService.route(RouteService.java:133)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:478)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:460)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:321)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:190)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:273)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:102)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2019/06/18 19:15:31 | Caused by: com.alibaba.druid.sql.parser.EOFParserException: EOF
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:577)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:120)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:157)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1246)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1274)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1152)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1166)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	at com.alibaba.druid.sql.parser.SQLExprParser.equalityRest(SQLExprParser.java:1190)
INFO   | jvm 1    | 2019/06/18 19:15:31 | 	... 26 more
2.INFO   | jvm 1    | 2019/06/18 19:15:31 | 2019-06-18 19:15:31,960 [ERROR][$_NIOREACTOR-16-RW] DruidMycatRouteStrategyError sql:SELECT t1.AccountCode ,t1.UserName ,t2.Name, t1.ManageArea ,t1.BakContent ,t1.PhoneNum ,t1.EmailName ,t1.SuperManage ,t1.AccountLock ,t1.XMLConfig ,t1.ACCOUNTID  FROM Account t1 ,Classify t2 WHERE t2.ClassifyId=t1.DepartMent and t1.DepartMent in (13,tn0101,tn0201,tn0301,,tn0501,tn0601,tn0701,tn0801,tn0901,tn1001,tn1101,tn1201,tn0102,tn0202,tn0302,,tn0502,tn0602,tn0702,tn0802,tn0902,tn1002,tn1102,tn1202,,,,,,tn0103,tn0203,tn0303,,tn0503,tn0603,tn0703,tn0803,tn0903,tn1003,tn1103,tn1203,,,,,,tn0104,tn0204,tn0304,,tn0504,tn0604,tn0704,tn0804,tn0904,tn1004,tn1104,tn1204) order by t1.accountcode asc com.alibaba.druid.sql.parser.ParserException: ERROR. token : COMMA, pos : 272
这个诡异的是，括号里的内容，是先从mycat中查询出id出来，应该为整型，结果出现tn0101,tn0201,tn0301,,但是13为正确的id
3.DruidMycatRouteStrategyError sql:SELECT Count(*) FROM SmartTaskDevice WHERE TaskId IN ### **(,138,139,140,107,125,83,84,4,2,126,49,127,111,112,113,72,73,74,69,75,76,77,78,79,80,70,71,61,68**) AND State>0 AND DeviceState IN (0,1,2) AND ChannelId IN () AND LastCommState IN (1,2) com.alibaba.druid.sql.parser.ParserException: ERROR. token : COMMA, pos : 55
这个诡异的是，与开发一再确认，不可能出现括号内“,”作为开始符，另一个佐证是，查看其它时间段并没有报错。

**Comment by fengsen198698** [comment]
补充：应用程序用c#，驱动程序是否有问题

**Comment by zwyqz** [comment]
多sql确实不予允许 并发会有问题 
然后sqlin里面错误应该是应用程序问题  查询语句一般不会去改写in里面的

**Comment by fengsen198698** [comment]
多sql确实不予允许 并发会有问题
请问具体会发生什么问题？
这段时间确实对一个表进行了大量的insert和update，并且都是这么写的，是一个程序的刷库操作。
这个操作会影响到其它的查询吗？
应用程序其它的查询出现了诡异，从数据库中查询一串整型数据，会返回以下情况吗？
13,tn0101,tn0201,tn0301,,tn0501,tn0601,tn0701,tn0801,tn0901,tn1001,tn1101,tn1201,tn0102,tn0202,tn0302,,tn0502,tn0602,tn0702,tn0802,tn0902,tn1002,tn1102,tn1202,,,,,,tn0103,tn0203,tn0303,,tn0503,tn0603,tn0703,tn0803,tn0903,tn1003,tn1103,tn1203,,,,,,tn0104,tn0204,tn0304,,tn0504,tn0604,tn0704,tn0804,tn0904,tn1004,tn1104,tn1204

**Comment by zwyqz** [comment]
是啊 因为你的多sql导致的

**Comment by fengsen198698** [comment]
我的理解对吗，多sql并发量大，会导致其它查询查串的现象？本来查询A返回的结果a，同一时刻，查询B，可能B得到的结果是a对吗？

**Comment by zwyqz** [comment]
程序上做修改就行

**Comment by fengsen198698** [comment]
太感谢了，那我在测试环境上看看能不能重现。多sql的问题，肯定要让应用程序修改。

**Comment by fengsen198698** [comment]
@zwyqz 我们在测试环境上复现了这个问题，真是太感谢了，请问一下最新版本的mycat是否支持？

**Comment by zwyqz** [comment]
目前只能修改应用程序
