### ISSUE TITLE
Mycat's problem with sub-database sub-tables with complex table structure of primary key and foreign key

### ISSUE THREAD

**Issue by eloen1998** [MyCATApache/Mycat-Server#2245]
The attribute x of the table A is used as the primary key of the table B, so that after the data tables A and B are divided into two databases, since the table B in a certain library cannot obtain all the information of the table A, the insertion and deletion operation of the table B is caused. Limited or wrong.

**Comment by junwen12221** [comment]
should not have foreign keys, and subtable does not support cross-datanode queries.
