### ISSUE TITLE
can't find table define in schema VALUE schema:fp

### ISSUE THREAD

**Issue by xxy123456** [MyCATApache/Mycat-Server#2254]
配置文件如下

	<schema name="fp" checkSQLschema="true" sqlMaxLimit="100">
		
		<table name="users" dataNode="dn3,dn4" ruleRequired="true" autoIncrement="true" primaryKey="id" rule="mod-long" type="global">

		</table>
	</schema>

配置完全局自增id后，插入后出现如下问题
mysql> insert into value users(name) values('22');
can't find table define in schema VALUE schema:fp

**Comment by zwyqz** [comment]
sql 写错了吧
