### ISSUE TITLE
取模分片后，insert可以正常分片，而select 报错

### ISSUE THREAD

**Issue by xxy123456** [MyCATApache/Mycat-Server#2256]
有俩分片，id去模分片。配置文件如下
<schema name="fp" checkSQLschema="true" sqlMaxLimit="100">
		
		<table name="users" dataNode="dn3,dn4" ruleRequired="true" autoIncrement="true" primaryKey="id" rule="mod-long">

		</table>
	</schema>

执行select * from users是报错 route rule for table USERS is required

mycat    | jvm 1    | 2019-07-17 01:16:35,231 [WARN ][$_NIOREACTOR-1-RW] ServerConnection [id=7, schema=fp, host=172.29.0.1, user=fenpian,txIsolation=3, autocommit=true, schema=fp]select* from users err:java.lang.IllegalArgumentException: route rule for table USERS is required: select* from users java.lang.IllegalArgumentException: route rule for table USERS is required: select* from users
mycat    | jvm 1    |   at io.mycat.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:1064)
mycat    | jvm 1    |   at io.mycat.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:947)
mycat    | jvm 1    |   at io.mycat.route.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:412)
mycat    | jvm 1    |   at io.mycat.route.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:287)
mycat    | jvm 1    |   at io.mycat.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:67)
mycat    | jvm 1    |   at io.mycat.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:84)
mycat    | jvm 1    |   at io.mycat.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:81)
mycat    | jvm 1    |   at io.mycat.route.RouteService.route(RouteService.java:133)
mycat    | jvm 1    |   at io.mycat.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:273)
mycat    | jvm 1    |   at io.mycat.server.ServerConnection.execute(ServerConnection.java:222)
mycat    | jvm 1    |   at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:136)
mycat    | jvm 1    |   at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)

**Comment by xxy123456** [comment]
有没有人？帮忙看看啊

**Comment by xxy123456** [comment]
使用docker部署，版本1.6

**Comment by xxy123456** [comment]
这是配置文件
<schema name="fp" checkSQLschema="true" sqlMaxLimit="100">
		
		<table name="users" dataNode="dn3,dn4" ruleRequired="true" autoIncrement="true" primaryKey="id" rule="mod-long">

		</table>
	</schema>

	<dataNode name="dn3" dataHost="fenpianServer" database="fenpian"></dataNode>
	<dataNode name="dn4" dataHost="fenpianServer1" database="fenpian"></dataNode>

	<dataHost name="fenpianServer" maxCon="1000" minCon="100" balance="0" writeType="0" dbDriver="native" dbType="mysql">
		<heartbeat>select user()</heartbeat>
		<writeHost host="masterM1" url="192.168.50.143:3306" user="laravel" password="laravel">
		</writeHost>
	</dataHost>
	<dataHost name="fenpianServer1" maxCon="1000" minCon="100" balance="0" writeType="0" dbDriver="native" dbType="mysql">
		<heartbeat>select user()</heartbeat>
		<writeHost host="masterM1" url="192.168.50.143:3307" user="root" password="xuehua_root">
		</writeHost>
	</dataHost>

**Comment by xxy123456** [comment]
这是配置文件
<schema name="fp" checkSQLschema="true" sqlMaxLimit="100">
		<table name="users" dataNode="dn3,dn4" ruleRequired="true" autoIncrement="true" primaryKey="id" rule="mod-long">

		</table>
	</schema>

	<dataNode name="dn3" dataHost="fenpianServer" database="fenpian"></dataNode>
	<dataNode name="dn4" dataHost="fenpianServer1" database="fenpian"></dataNode>

	<dataHost name="fenpianServer" maxCon="1000" minCon="100" balance="0" writeType="0" dbDriver="native" dbType="mysql">
		<heartbeat>select user()</heartbeat>
		<writeHost host="masterM1" url="192.168.50.143:3306" user="laravel" password="laravel">
		</writeHost>
	</dataHost>
	<dataHost name="fenpianServer1" maxCon="1000" minCon="100" balance="0" writeType="0" dbDriver="native" dbType="mysql">
		<heartbeat>select user()</heartbeat>
		<writeHost host="masterM1" url="192.168.50.143:3307" user="root" password="xuehua_root">
		</writeHost>
	</dataHost>

**Comment by junwen12221** [comment]
select 写上字段和分片条件

**Comment by xxy123456** [comment]
已解决，在table上不要加ruleRequired属性
