### ISSUE TITLE
mycat +postgre中字段和表名都是大写,但是一直都提示我找不到关系表

### ISSUE THREAD

**Issue by zjswwh** [MyCATApache/Mycat-Server#2258]

**Comment by junwen12221** [comment]
贴一下报错日志

**Comment by zjswwh** [comment]
WARN [BusinessExecutor15] (io.mycat.backend.mysql.nio.handler.MultiNodeHandler.errorResponse(MultiNodeHandler.java:137)) - error response from JDBCConnection    错误: 关系 "tb_student3" 不存在

**Comment by junwen12221** [comment]
后端数据库设置大小写不敏感？

**Comment by zjswwh** [comment]
我尝试过 但是不行 postgre 好像没有这个设置规则，我知道mysql有这个 就是我把数据库中表改成了 大写就不行，

**Comment by junwen12221** [comment]
是不是表名加引号了

**Comment by zjswwh** [comment]
我的实体类里面 的确是加了双引号，并且用了转义字符 在配置文件里面 需要也这样吗

**Comment by junwen12221** [comment]
pg 表名加了引号就是区分大小写？？mycat可以在向后端pg连接发送sql时候处理一下sql的大小写，你觉得怎么处理比较好

**Comment by zjswwh** [comment]
其实我不明白我们项目中为啥非要用大写，但是现在项目都做得差不多了，不可能说把大写改成小写，可是我现在的确如果都是大写的话，mycat就会一直提示我找不到相关的表，这个问题可以在mycat里面配置吗，因为pg里面配置不了 忽略大小写，谢谢
