### ISSUE TITLE
版本1.6.7.1-release存在多节点重复插入数据BUG

### ISSUE THREAD

**Issue by PrudenceI** [MyCATApache/Mycat-Server#2259]
配置如下图：
![图片](https://user-images.githubusercontent.com/29862299/61377561-06ad5000-a8d6-11e9-933c-9f4a1b7775d3.png)
测试数据如下图：
![图片](https://user-images.githubusercontent.com/29862299/61377674-42481a00-a8d6-11e9-9b0f-dd35cc7dd3ae.png)
运行结果如下图：
![图片](https://user-images.githubusercontent.com/29862299/61377854-9a7f1c00-a8d6-11e9-9e8c-dc7fb7a24111.png)
其中dn1是正常插入1~5，我就不放图了，BUG在dn2节点重复插入数据

**Comment by junwen12221** [comment]
重复插入数据是指dn2的数据插入两次？
![image](https://user-images.githubusercontent.com/11361391/61422830-034eae80-a940-11e9-8b39-5ba641b284d0.png)
这些SQL在dn2执行了两次？

**Comment by zwyqz** [comment]
你配置的是全局表  全局表就是每个节点都插入

**Comment by PrudenceI** [comment]
> 你配置的是全局表 全局表就是每个节点都插入
谢谢，我明白了~

**Comment by PrudenceI** [comment]
> 重复插入数据是指dn2的数据插入两次？
> ![image](https://user-images.githubusercontent.com/11361391/61422830-034eae80-a940-11e9-8b39-5ba641b284d0.png)
> 这些SQL在dn2执行了两次？
在dn1和dn2中分别插入了一次，没有问题，是我弄错了，我没有搞清楚global的设置是全局插入，不好意思了，实在是抱歉~是我自己的失误~
