### ISSUE TITLE
Mycat 如何自定义分片规则？

### ISSUE THREAD

**Issue by Sunyelw** [MyCATApache/Mycat-Server#2261]
比如我想加下自己的逻辑，对分片字段的前四位做枚举判断，然后入库。

是否可以自己写jar包放到 lib 文件夹下？

jar包的创建有什么要求？

先谢谢各位大佬指点。

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat-Server/blob/1.6/src/main/java/io/mycat/route/function/PartitionDirectBySubString.java

**Comment by junwen12221** [comment]
是否可以自己写jar包放到 lib 文件夹下？
可以

jar包的创建有什么要求？
没有

rule.xml配置类加载路径

**Comment by Sunyelw** [comment]
1、下载源码；
2、在同样的目录下，加上我自己的路由分片处理类；
3、打成jar包替换原来的jar；
4、修改 rule.xml 配置文件，指定处理类
5、重启mycat。

--我理解的处理开发流程对吗？

**Comment by Sunyelw** [comment]
分片规则可以传入一些参数或文件，这种参数传递和文件读取是在哪实现的呢？

**Comment by Sunyelw** [comment]
thx, it had been resolved.
