### ISSUE TITLE
通过MyCat分表之后，如果我想查询总的一个数据，如何实现？

### ISSUE THREAD

**Issue by xll970211** [MyCATApache/Mycat-Server#2264]
如果我通过mycat分了十二张表之后，如果我想查询这十二张表的总数据，我只能分别select这这十二张表吗？
![image](https://user-images.githubusercontent.com/43258690/62182313-c1cef200-b388-11e9-8bb5-e485ac0c24cd.png)

**Comment by junwen12221** [comment]
直接查询不行?

**Comment by xll970211** [comment]
你好，是这样的，现在直接select的话，不可以，提示不存在，因为通过mycat去插入的，后面对应的是RecordSlotPool1-12这12张表，插入是可以直接指定RecordSlotPool的，因为我看mycat说是有一个路由机制，这样是没问题，但是select的话，就不行 @junwen12221

**Comment by xll970211** [comment]
![image](https://user-images.githubusercontent.com/43258690/62186858-25ade680-b39a-11e9-94b6-f7447e5f4c24.png)
直接select的话，会提示这样的信息

**Comment by junwen12221** [comment]
可以贴详细配置吗,没有复现

**Comment by xll970211** [comment]
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
	<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100" >
		<table name="Recharge" primaryKey="OrderID" subTables="Recharge$0-9"  dataNode="dn1" rule="mod-long-1" />
		<table name="RecordCatchFish" primaryKey="UserID" subTables="RecordCatchFish$0-9" dataNode="dn1"  rule="mod-long-2" />
		<table name="RecordTicketGet" primaryKey="RecordID" autoIncrement="true" subTables="RecordTicketGet$0-9" dataNode="dn1" rule="mod1-long" />
		<table name="lxRecordSysBankerScoreChange" primaryKey="RecordID" autoIncrement="true" subTables="lxRecordSysBankerScoreChange$1-12" dataNode="dn1" rule="sharding-by-month" />
		<table name="RecordChiProfitOrLoss" primaryKey="RecordID" autoIncrement="true" subTables="RecordChiProfitOrLoss$1-12"  dataNode="dn1" rule="sharding-by-month1" />
		<table name="RecordChiProfitCost" primaryKey="RecordID" autoIncrement="true" subTables="RecordChiProfitCost$1-12" dataNode="dn1" rule="sharding-by-month1" />
		<table name="RecordGameProfitOrLoss" primaryKey="RecordID" autoIncrement="true" subTables="RecordGameProfitOrLoss$1-12"  dataNode="dn1" rule="sharding-by-month1" />
		<table name="PropUseRecord" primaryKey="RecordID" autoIncrement="true" subTables="PropUseRecord$0-9" dataNode="dn1" rule="mod1-long" />
		<table name="SkiAddRecord" primaryKey="ID" autoIncrement="true" subTables="SkiAddRecord$0-9"  dataNode="dn1" rule="mod3-long" />
		<table name="TorpAddRecord" primaryKey="ID" autoIncrement="true" subTables="TorpAddRecord$0-9"  dataNode="dn1" rule="mod3-long" />
		<table name="PropBuyRecord"  primaryKey="ID" autoIncrement="true" subTables="PropBuyRecord$0-9"  dataNode="dn1" rule="mod3-long"/>
		<table name="PropGiveRecord" primaryKey="ID" autoIncrement="true" subTables="PropGiveRecord$0-9"  dataNode="dn1" rule="mod3-long"/>
		<table name="PropRecoveryRecord" primaryKey="ID" autoIncrement="true" subTables="PropRecoveryRecord$0-9" dataNode="dn1" rule="mod3-long"/>
		<table name="RecordSendPresent" subTables="RecordSendPresent$1-12" dataNode="dn1" rule="sharding-by-month2" />
		<table name="AccountsLastVersion" dataNode="dn1" />
		<table name="RecordGameTotalProfitOrLoss" dataNode="dn1"  />
		<table name="RecordGrantExperience"  dataNode="dn1" />
		<table name="RecordGrantGameScore"  dataNode="dn1" />
		<table name="RecordGrantMember"  dataNode="dn1" />
		<table name="RecordGrantTreasure"  dataNode="dn1" />
		<table name="RecordGameReward"  dataNode="dn1" />
		<table name="RecordSendProperty"  dataNode="dn1" />
        	<table name="RecordSysAdminSend"  dataNode="dn1" />
		<table name="AndroidJettonStatic" primaryKey="ID" autoIncrement="true" subTables="AndroidJettonStatic$1-12"  rule="sharding-by-month1"  dataNode="dn1" />
		<table name="TempScoreGive"  dataNode="dn1" />
		<table name="RecordDrawInfo" primaryKey="DrawID" autoIncrement="true" subTables="RecordDrawInfo$1-12"  dataNode="dn2" rule="sharding-by-month1" />
		<table name="RecordDrawScore" primaryKey="DID" autoIncrement="true" subTables="RecordDrawScore$1-12"  dataNode="dn2" rule="sharding-by-month1" />
		<table name="RecordYYBF" primaryKey="ID" autoIncrement="true" subTables="RecordYYBF$1-12" dataNode="dn2" rule="sharding-by-month1" />
        	<table name="RecordSlotPool" primaryKey="ID" autoIncrement="true" subTables="RecordSlotPool$1-12" dataNode="dn2" rule="sharding-by-month1" />
		<table name="RecordInsure" subTables="RecordInsure$0-9" dataNode="dn2" rule="mod2-long" />
		<table name="RecordTurnOver" primaryKey="RecordID" autoIncrement="true" subTables="RecordTurnOver$0-9" dataNode="dn2" rule="mod1-long" />
		<table name="RecordUserInout" primaryKey="RecordID" autoIncrement="true" subTables="RecordUserInout$0-9" dataNode="dn2" rule="mod1-long" />
		<table name="RecordHitLoop" primaryKey="RecordID" autoIncrement="true" subTables="RecordHitLoop$0-9" dataNode="dn2" rule="mod1-long" />
		<table name="SignInRecord" primaryKey="ID" autoIncrement="true" subTables="SignInRecord$0-9" dataNode="dn3" rule="mod3-long" />
		<table name="HallSharing" subTables="HallSharing$0-9" dataNode="dn3" rule="mod-long" />
		<table name="RechargeRecord" subTables="RechargeRecord$0-9" dataNode="dn3" rule="mod-long" />
		<table name="RecordScoreInfo" subTables="RecordScoreInfo$0-9" dataNode="dn3" rule="mod-long" />
		<table name="ReliefRecord" primaryKey="RID" autoIncrement="true" subTables="ReliefRecord$0-9" dataNode="dn3" rule="mod-long-3" />
		<table name="ScoreChange" primaryKey="RecordID" autoIncrement="true" subTables="ScoreChange$0-9" dataNode="dn3" rule="mod1-long" />
		<table name="Withdrawals" subTables="Withdrawals$0-9" dataNode="dn3" rule="mod1-long" />
		<table name="ProfitDetails" primaryKey="ID" autoIncrement="true" subTables="ProfitDetails$0-9" dataNode="dn3" rule="mod3-long" />
		<table name="RecordNovicePack" primaryKey="ID" autoIncrement="true" subTables="RecordNovicePack$0-9" dataNode="dn3" rule="mod3-long" />
		<table name="LuckyDrawRecord" primaryKey="ID" autoIncrement="true" subTables="LuckyDrawRecord$0-9" dataNode="dn3" rule="mod3-long" />
		<table name="BoxBuyRecord" primaryKey="ID" autoIncrement="true" subTables="BoxBuyRecord$0-9" dataNode="dn3" rule="mod3-long" />
		<table name="OnlineNumber" primaryKey="RecordID" autoIncrement="true" subTables="OnlineNumber$0-9" dataNode="dn3" rule="mod1-long" />
		<table name="RedPacketRecord" primaryKey="ID" autoIncrement="true" subTables="RedPacketRecord$0-9" dataNode="dn3" rule="mod3-long" />
		<table name="RecordTicktInfo" primaryKey="ID" autoIncrement="true" subTables="RecordTicktInfo$0-9" dataNode="dn3" rule="mod3-long" />

**Comment by xll970211** [comment]
@junwen12221 麻烦大佬帮忙看一下了，十分感谢，如果您方便的话，想加您一下VX或者QQ

**Comment by xll970211** [comment]
没事了，我这边通过命令行查看的话，是没有问题，因为之前是通过navicat看的，可能这个软件有点问题

**Comment by xll970211** [comment]
很感谢您的回答，我现在关闭这个问题。
