### ISSUE TITLE
Mycat查询information_schema相关会返回空

### ISSUE THREAD

**Issue by whybean** [MyCATApache/Mycat-Server#2273]
我在连接到mycat查询schemata时，会出现查询为空的情况，但在任一库下去查询时，就会有值，同样，直接去连mysql查询时，也能查询出数据库的信息。
select * from information_schema.schemata;

**Comment by whybean** [comment]
![1](https://user-images.githubusercontent.com/26714102/63150178-b3dfc900-c038-11e9-882e-418ffceea658.png)

**Comment by whybean** [comment]
![2](https://user-images.githubusercontent.com/26714102/63150218-cd811080-c038-11e9-824a-457bf188efb9.png)

**Comment by junwen12221** [comment]
mycat会话中的schema为information_schema 会返回自定义信息(做了PhpAdmin's的适配),不会发送到后端mysql

**Comment by whybean** [comment]
但是，对于phpmyadmin来说，连接会报错：
![image](https://user-images.githubusercontent.com/26714102/63154716-d3302380-c043-11e9-9c77-dcd0ce4fa572.png)

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.7.3/Mycat-server-1.6.7.3-remove-curSchemaIsinfomata-def-response-20190816170122-linux.tar.gz 使用这个版本测试

**Comment by whybean** [comment]
这个版本正常了，还未发现其他的问题。非常感谢！
但我想知道，这个版本目前只是说是一个测试版本，还是说是一个稳定的可以应用在生产环境的版本？

**Comment by junwen12221** [comment]
在当前release的版本上去掉了information_schema 的拦截,这个功能如果后面没有发现问题就提交代码合拼到主分支

**Comment by whybean** [comment]
另外还有一个问题，Mycat支持ssl连接的吗？
使用phpmyadmin会发现SSL未被使用，而正常情况下直接连接mysql不会有这个提示。
![image](https://user-images.githubusercontent.com/26714102/63160042-602caa00-c04f-11e9-8b77-5d1819160072.png)

**Comment by junwen12221** [comment]
不支持

**Comment by whybean** [comment]
了解，非常感谢解答！
