### ISSUE TITLE
1.6.5之后的版本，非分片表不配置在schema.xml中，无法查询

### ISSUE THREAD

**Issue by stevepomp** [MyCATApache/Mycat-Server#2275]
在版本号0e42f27中，将io.mycat.route.util.RouterUtil的tryRouteForTables方法中判断非分片表走默认节点的逻辑删除了。
![TIM截图20190819125135](https://user-images.githubusercontent.com/28881426/63240402-08c25000-c282-11e9-8c03-871b5ee6503e.png)

**Comment by junwen12221** [comment]
```
    if(schema.isNoSharding()||(tables.size() >= 1&&isNoSharding(schema,tables.get(0)))) {
            return routeToSingleNode(rrs, schema.getDataNode(), ctx.getSql());
        }
```
这一段对吧

**Comment by junwen12221** [comment]
fix

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.7.3/Mycat-server-1.6.7.3-%e5%af%b9%e9%9d%9e%e6%8b%86%e5%88%86%e9%94%ae%e4%b8%bb%e9%94%ae%e4%bd%9c%e4%b8%ba%e6%9d%a1%e4%bb%b6%e4%bd%9c%e4%b8%ba%e4%bf%ae%e6%94%b9%e6%9d%a1%e4%bb%b6%e5%ba%94%e8%af%a5%e8%b7%af%e7%94%b1%e6%89%80%e6%9c%89%e8%8a%82%e7%82%b9-20190828215749-linux.tar.gz

可以测试一下
