### ISSUE TITLE
mycat怎么插入schema未定义的表

### ISSUE THREAD

**Issue by JarryFeng** [MyCATApache/Mycat-Server#2290]
mycat怎么插入schema未定义的表，一定要先修改schema才能插入未定义的表吗

**Comment by junwen12221** [comment]
schema上配置datanode

**Comment by JarryFeng** [comment]
> schema上配置datanode

配置datanode？没明白

**Comment by junwen12221** [comment]
你用的mycat那个版本?

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.7.3/Mycat-server-1.6.7.3-fix-datanode-on-schema.tar.gz
