### ISSUE TITLE
Mycat-server-1.6.7.3-release-20190809210613不能读取schema默认数据节点表

### ISSUE THREAD

**Issue by 804e** [MyCATApache/Mycat-Server#2295]
schema.xml内容如下
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="msedu_sale" checkSQLschema="true" sqlMaxLimit="100" dataNode="msedu_sale_1">
        <table name="saas_test" primaryKey="ID" type="global" dataNode="msedu_sale_1,msedu_sale_2" />
	</schema>
    
	<dataNode name="msedu_sale_1" dataHost="172.16.100.21" database="msedu_sale" />
    <dataNode name="msedu_sale_2" dataHost="172.16.100.22" database="msedu_sale" />
    
    <dataHost name="172.16.100.21" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="172.16.100.21" url="172.16.100.21:3306" user="root"
				   password="root" />
	</dataHost>
	<dataHost name="172.16.100.22" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="172.16.100.22" url="172.16.100.22:3306" user="root"
				   password="root@22" />
	</dataHost>
</mycat:schema>
发现读取msedu_sale的时候，除了表saas_test均无法读取，回退版本到1.5后正常，1.6.7不再支持默认数据节点了吗？

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.7.3/Mycat-server-1.6.7.3-fix-datanode-on-schema.tar.gz

**Comment by junwen12221** [comment]
1.6.7.2/1.6.7.1都行
