### ISSUE TITLE
支持表名改写路由吗？

### ISSUE THREAD

**Issue by M-make** [MyCATApache/Mycat-Server#2296]
你好，请问下，mycat支持表名改写路由吗？
比如数据库A和数据库B，库A和库B分别有test1表和test2表，客户端访问A.test1可以将这个sql路由到A库的test1表

**Comment by junwen12221** [comment]
可以,sql不带schema

**Comment by M-make** [comment]
> 可以,sql不带schema

好的，谢谢，mycat是支持 oracle pg mysql 的吗？我看那个支持里面写的是伪装成mysql的服务器，那么mycat连oracle，我的客户端需要的是mysql的jdbcDriver吗？还有mycat支持hive吗
