### ISSUE TITLE
双主切换

### ISSUE THREAD

**Issue by 635099891** [MyCATApache/Mycat-Server#2297]
`<dataHost name="db1" maxCon="1000" minCon="10" balance="1"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="2"  slaveThreshold="100">

		
		<heartbeat>show slave status</heartbeat>

		
		<writeHost host="hostM1" url="172.18.0.4:3306" user="root" password="123456">
			<readHost host="hostS1" url="172.18.0.8:3306" user="root" password="123456" />
		</writeHost>

		<writeHost host="hostM2" url="172.18.0.10:3306" user="root" password="123456">
			<readHost host="hostS2" url="172.18.0.9:3306" user="root" password="123456" />
		</writeHost>

</dataHost>`

hostM1挂掉后 mycat无法切换到hostM2

**Comment by zwyqz** [comment]
配置对应的switchtype

**Comment by 635099891** [comment]
> 配置对应的switchtype

```
<dataHost name="db1" maxCon="1000" minCon="10" balance="1"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="2"  slaveThreshold="100">
		<!-- 心跳检测方式 -->
		<heartbeat>show slave status</heartbeat>
		<!-- host标签 url实例地址 user用户名 password密码 -->
		<writeHost host="hostM1" url="172.18.0.4:3306" user="root" password="123456">
			<readHost host="hostS1" url="172.18.0.8:3306" user="root" password="123456" />
		</writeHost>
		<writeHost host="hostM2" url="172.18.0.10:3306" user="root" password="123456">
			<readHost host="hostS2" url="172.18.0.9:3306" user="root" password="123456" />
		</writeHost>
	</dataHost>
```
