### ISSUE TITLE
单库分表join查询的问题

### ISSUE THREAD

**Issue by pscj** [MyCATApache/Mycat-Server#2313]
我使用的是通过subTitles做的单库分表，分表是通过一个字段hash进行的。我打算进行的操作是两个分表的表join，这样不知道是否支持。我看说明上好像是说一个分表和一个没分表的可以join，都是分过表的可以join吗？保证是同一个分区节点里的。

	<schema name="inn912" checkSQLschema="true" sqlMaxLimit="100">		
		<table name="checkin"   primaryKey="id" dataNode="dn1" subTables="ts_checkin,bj_checkin" rule="area-intfile" />		
		<table name="roomlist"  primaryKey="id" dataNode="dn1" subTables="ts_roomlist,bj_roomlist" rule="area-intfile" />
		
		<table name="user" 	 	dataNode="dn1"/>
		<table name="sessions"  dataNode="dn1"/>
	</schema>
	
	<dataNode name="dn1" dataHost="restserver" database="inn912" />	

我要执行的查询是： select * from checkin as a inner join roomlist as b on a.roomId=b.id
在navicat里的执行结果是，只能查询到checkin表中的字段。无法看到roomlist中的数据

**Comment by ermao1577973673** [comment]
我也遇到了这个问题，不知道怎么解决，有解决的大神吗

**Comment by 17602541404** [comment]
+1,不过我出现的是拆分的表和未拆分的表 join会出错, 表现为用别名时, 提示表不存在, 或这查询的字段不存在

**Comment by 17602541404** [comment]
请问是已解决吗? 有解决方案分享么
