### ISSUE TITLE
mycat set@变量后获取变量为null

### ISSUE THREAD

**Issue by 804e** [MyCATApache/Mycat-Server#2326]
使用变量的时候，无法读取变量的值
`set @num=1;select @num`
返回结果是null。
但是文档里面“第 11 章 MyCAT 对存储过程的支持”，里面是有对变量的使用的，不知道哪里用的不对
`/*#mycat: sql=SELECT * FROM test */ set @pin=111;call p_test(@pin,@pout);select @pout`

**Comment by junwen12221** [comment]
开启事务再操作看看

**Comment by 804e** [comment]
开启handleDistributedTransactions开关吗？
mysql事务控制没效果
```
MySQL [(none)]> set autocommit = 0;
Query OK, 0 rows affected (0.00 sec)

MySQL [(none)]> start transaction;
Query OK, 0 rows affected (0.00 sec)

MySQL [(none)]> begin;
Query OK, 0 rows affected (0.00 sec)

MySQL [(none)]> set @num=1;select @num;
Query OK, 0 rows affected (0.00 sec)

+------+
| @num |
+------+
| NULL |
+------+
1 row in set (0.00 sec)
```

**Comment by 804e** [comment]
我看源代码io.mycat.server.handler.SetHandler里面是禁止使用set @variable这种语句的，不知道指南里面的存储过程调用是怎么成功的

**Comment by junwen12221** [comment]
https://blog.csdn.net/qq_31183071/article/details/102653151
