### ISSUE TITLE
mycat 连接mongoDB 4.0 只能查询,不能增删改

### ISSUE THREAD

**Issue by linhai123** [MyCATApache/Mycat-Server#2339]
我使用的mycat最新1.6版本,mongo-java-driver 版本为 3.11.0 , 连接mongodb 4.0 后只能执行查询语句,其它语句会报空指针异常,异常信息如下(这个是delete 语句)
![image](https://user-images.githubusercontent.com/18415927/68206889-c6024f80-0008-11ea-9054-d9b609b5dfa8.png),使用navicat执行语句如下
![image](https://user-images.githubusercontent.com/18415927/68206956-e6caa500-0008-11ea-8632-c0c6e28edf4a.png),当查询语句带有条件的时候有时会返回空,有时又正常返回,数据是存在的,不加条件的情况下没问题,我配置了三个分片库,每个库里只有一条记录,id为别为1,2,3,如下为不加条件查询
![image](https://user-images.githubusercontent.com/18415927/68207202-6b1d2800-0009-11ea-94de-ac7a51d1e6b9.png),以下为加条件查询返回空
![image](https://user-images.githubusercontent.com/18415927/68207301-9869d600-0009-11ea-91cd-7088dc4e299e.png),以下为加条件查询正常返回
![image](https://user-images.githubusercontent.com/18415927/68207240-838d4280-0009-11ea-991e-cad19bf733c7.png)

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat-Server/commit/b46a7362499a4da181f940944daab9509a54e2ef
