### ISSUE TITLE
使用全局序列报语法错误

### ISSUE THREAD

**Issue by linhai123** [MyCATApache/Mycat-Server#2340]
我使用的是数据库方式全局序列,数据库表和方法都按照文档创建完成,在执行插入语句时报语法错误,如图
![image](https://user-images.githubusercontent.com/18415927/68272862-e16c6980-009f-11ea-93a0-f944dc588996.png),这是我的sql语句,错误如下
![image](https://user-images.githubusercontent.com/18415927/68272903-03fe8280-00a0-11ea-8232-55a3210d7ed6.png),server.xml配置如下
![image](https://user-images.githubusercontent.com/18415927/68272960-27c1c880-00a0-11ea-8cce-ddba7cc3ea3d.png)

**Comment by junwen12221** [comment]
修复全局序列号druid解析问题('NEXT VALUE FOR MYCATSEQ_GLOBAL' 使用字符串语法)

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.7.3/update-log.txt

**Comment by linhai123** [comment]
谢谢,已解决
