### ISSUE TITLE
多租户，使用注释找不到指定的库

### ISSUE THREAD

**Issue by cugb-suerwei** [MyCATApache/Mycat-Server#2345]
已经在查询语句之前添加了/*! mycat:schema=CatPaint1 */ 这样的注释。但是报出 No MyCAT Database selected 这样的错误。

**Comment by junwen12221** [comment]
需要有一个默认的schema，在此基础上才可以只用注解指定schema，如果没有默认的schema，则会报 No MyCAT Database selected

**Comment by junwen12221** [comment]
设置默认schema可以是jdbc连接字符串的属性或者use database语法指定

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.7.4/Mycat-server-1.6.7.4-test-20191113141017-update-log.txt

**Comment by cugb-suerwei** [comment]
问题已经解决，多谢指教
