### ISSUE TITLE
close connection,reason:quit cmd

### ISSUE THREAD

**Issue by cysnet** [MyCATApache/Mycat-Server#2348]
通过mycat操作数据，一次操作成功，下一次操作失败。日志如下：

`[INFO ][$_NIOREACTOR-2-RW] close connection,reason:quit cmd ,ServerConnection [id=2, schema=test1, host=192.168.137.1, user=root,txIsolation=3, autocommit=true, schema=test1]  (io.mycat.net.AbstractConnection:AbstractConnection.java:508)`

**Comment by junwen12221** [comment]
什么版本，是通过什么操作

**Comment by cysnet** [comment]
> 什么版本，是通过什么操作

1.6，通过dotnet core 的orm框架EF core操作的

**Comment by junwen12221** [comment]
什么sql

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat-Server/commit/df0214982707d4181f86f83aad3910fa793941e7
