### ISSUE TITLE
golang 可以连接mycat吗

### ISSUE THREAD

**Issue by xuefengyuan** [MyCATApache/Mycat-Server#2350]
看了文档都是基于怎么操作的，golang可以通过什么样的方式连接mycat，或者有什么示例之类的？这方面的资料一直没找到。

**Comment by junwen12221** [comment]
mysql客户端连接

**Comment by xuefengyuan** [comment]
> mysql客户端连接



> mysql客户端连接

**Comment by xuefengyuan** [comment]
> mysql客户端连接

mysql客户端连接指的是在终端还是在golang的代码里，有如果是golang的代码里，有示例提供下么
