### ISSUE TITLE
No dataNode found ,please check tables defined in schema:ins0

### ISSUE THREAD

**Issue by ethanxzw** [MyCATApache/Mycat-Server#2364]
部署的1.6.7.4，启动未报错，但客户端连接后，打开schema报“No dataNode found ,please check tables defined in schema:ins0”

**Comment by junwen12221** [comment]
就是schema配置有问题，贴一下配置文件schema.xml

**Comment by ethanxzw** [comment]
schema配置如下：
`<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
<schema name="ins0" checkSQLschema="false" sqlMaxLimit="100">
<table name="ins_user" primaryKey="USER_ID" dataNode="dn0"/>
<table name="ins_user_ext" primaryKey="INS_USER_EXT_ID" dataNode="dn0"/>
<table name="ins_user_os_state" primaryKey="USER_ID" dataNode="dn0"/>
 </schema>
  <dataNode name="dn0" dataHost="localhost1" database="ins2" />
  <dataHost name="localhost1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="mysql" dbDriver="native" switchType="1" slaveThreshold="100"> 
    <heartbeat>select 1 from ins_user</heartbeat> 
    <writeHost host="hostM1" url="10.21.33.97:31306" user="INS1" password="cRNYi19t+A7E14DrxdStZzHkipwB2mVW/9ySROvEiA+u3H7X1NcVBwhsq38nFFfWC8aYenQd7Lm8+tJdnxr2Qg==" usingDecrypt="1"> 
    </writeHost>  
  </dataHost> 
</mycat:schema>`

**Comment by ethanxzw** [comment]
上面错误是客户端问题，之前用的是HeidiSQL，换其他客户端就没报错了。

**Comment by xiaomaixu** [comment]
我部署的1.6.7.5，启动未报错，但客户端连接后，打开schema报“No dataNode found ,please check tables defined in schema:”
