### ISSUE TITLE
1.6.7.4代码哪里可以找到，github没有看到下载

### ISSUE THREAD

**Issue by alexliu123456** [MyCATApache/Mycat-Server#2379]
1.6分支就是现在的1.6.7.4吗，以下这几个版本都是1.6分支是吗，现在branch 1.6就是最新的1.6.7.4，之前的1.6.7.3和1.6.7已经没有了。所有1.6版本现在都在1.6分支是吗
Mycat-server-1.6.7.4-test版本发布
Mycat-server-1.6.7.3-release 版本发布
Mycat-server-1.6.7-release 版本发布
Mycat-server-1.6.6-test 版本发布

**Comment by alexliu123456** [comment]
现在1.6 分支，有2019-12-20号的代码提交，1.6.7.4没有单独的分支，怎么找到代码

**Comment by junwen12221** [comment]
1.6分支按日期找
