### ISSUE TITLE
mycat变量信息写死导致批量插入获取的主键错误

### ISSUE THREAD

**Issue by hj819748949** [MyCATApache/Mycat-Server#2400]
mycat变量值写死mysql驱动读取的auto_increment_increment值永远为1，如果多台写入的数据库步长不是1，步长是2，那么在批量插入数据库的时候，获取到的id值，从第二个开始是错误的。

mysql驱动初始化的时候，查询一些变量信息，查询的sql如下：
/* mysql-connector-java-8.0.13 (Revision: 66459e9d39c8fd09767992bc592acd2053279be6) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout

mycat接收到请求后直接查询mycat写死的缓存变量信息，导致查询到的变量信息与实际数据库的变量值不一致，auto_increment_increment值这里直接返回了1。
io.mycat.server.handler.SelectHandler.handle
        case ServerParseSelect.SELECT_VAR_ALL:
                SelectVariables.execute(c,stmt);
                break;

mysql驱动(当批量插入数据，获取每一个自增的id时，mysql驱动包是通过，前面的id值, 加上步长值获取到后续的id值，但是由于mycat将步长值写死了，直接返回，没有到数据库中动态查询，导致数据错误)
     com.mysql.cj.jdbc.StatementImpl.getGeneratedKeysInternal(long)
                  long beginAt = getLastInsertID();
                  .........
                  beginAt += this.connection.getAutoIncrementIncrement();

解决办法:
      原代码:
      io.mycat.server.handler.SelectHandler.handle
        case ServerParseSelect.SELECT_VAR_ALL:
                SelectVariables.execute(c,stmt);
                break;

     调整后:
           io.mycat.server.handler.SelectHandler.handle
             case ServerParseSelect.SELECT_VAR_ALL:
                c.execute(stmt, ServerParse.SELECT);
                break;
           
          或者直接将 case ServerParseSelect.SELECT_VAR_ALL  这个case去掉, 默认就是直接走查询，最
          好的办法应该是在这里第一次查询，并将查询结果缓存。

**Comment by junwen12221** [comment]
http://dl.mycat.io/1.6.7.5/
