### ISSUE TITLE
使用native driver 无法连接上阿里云数据库

### ISSUE THREAD

**Issue by longzhihun** [MyCATApache/Mycat-Server#2409]
程序版本：1.6.7.4

`<dataHost name="plus_uat_test" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select 1</heartbeat>
		<writeHost host="hostM1" url="domainurl:3306" user="ddddd"
				   password="xxxxx">
		</writeHost>
	</dataHost>`

报错信息：

> 2020-01-15 20:42:47.788  INFO [$_NIOREACTOR-1-RW] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError

**Comment by junwen12221** [comment]
后端数据库没连上

**Comment by longzhihun** [comment]
@junwen12221 使用jdbc可以连接上  但是native 无法连接上
