### ISSUE TITLE
最新版本中：ER分片，如果子表的关联父表的非分区字段时，无法找到正确的Node

### ISSUE THREAD

**Issue by longzhihun** [MyCATApache/Mycat-Server#2410]
建表脚本：

`create table dept(deptno int,dname varchar(10),datanode varchar(10));

create table emp(empno int,dept_no int,datanode varchar(10));`

Table Rule:
`<tableRule name="sharding-by-intfile">
                <rule>
                        <columns>dname</columns>
                        <algorithm>hash-int</algorithm>
                </rule>
        </tableRule>`

Function:

`<function name="hash-int"
                class="org.opencloudb.route.function.PartitionByFileMap">
                <property name="mapFile">partition-hash-int.txt</property>
                <property name="type">1</property>
        </function>`

File:
`cat partition-hash-int.txt 
accounting,research=0
sales=1
operations=2`

Schema:

`<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100">
		<table name="dept" primaryKey="deptno" dataNode="dn1,dn2,dn3"
			   rule="sharding-by-intfile">
			<childTable name="emp" primaryKey="empno" joinKey="dept_no"
						parentKey="deptno">
			</childTable>
		</table>
	</schema>`

Insert SQL:
`mysql> insert into dept(deptno,dname,datanode) values(10,'accounting',database());
Query OK, 1 row affected (0.14 sec)
mysql> insert into emp(empno,dept_no,datanode) values(1234,10,database());`

报错信息：

`can't find (root) parent sharding node for sql:insert into emp(empno,dept_no,datanode) values(1234,10,'uuu1')`

使用native driver的时候可以，但是使用JDBC driver的时候就不可以了，是配置的不正确吗？

**Comment by junwen12221** [comment]
#2411
