### ISSUE TITLE
1.6.7.1 请求补齐版本jar包和sources包，对镜像仓库给予更好的支持

### ISSUE THREAD

**Issue by pencilkill** [MyCATApache/Mycat-Server#2414]
1.6.7.1版本下载仅提供了安装包，没有jar包和sources包单独下载地址。

1.6.7.4包含jar包和sources包，测试显示1.6.7.4对批量插入报只读事务异常。

请求对1.6.7.1版本提供jar包和sources包下载地址，感谢。

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat-Server/commit/738757c133cad7a06a690cb35196e00b37db2eab
