### ISSUE TITLE
Mycat 操作blob字段引发的问题

### ISSUE THREAD

**Issue by feidian036** [MyCATApache/Mycat-Server#2419]
用mycat操作（读和写）mysql的blob字段过程不报错，但是最终生成的文件无法打开。那么直连mysql操作blob字段后，发现使用mycat方式存储的大小明显比操作mysql的大，说明写入的二进制数据已经存在问题，所以再从数据库中读取并写成文件肯定会有问题。
解决方式： 采用mycat server端的预编译功能，在database.url加入useServerPrepStmts=true 。blob处理正常
引发的问题：加入useServerPrepStmts=true 后 在操作元数据发现为null。哪位大神知道如何处理
PreparedStatment pst = conn.prepareStamement(sql);
ResultSet rst = pst.executeQuery();
ResultSetMetaData rstmd = pst.getMetaData()  //rstmd 为null。不加useServerPrepStmts=true是正常的

**Comment by junwen12221** [comment]
useServerPrepStmts=false的时候,观察mycat接收到了什么sql,往mysql发送了什么sql,尝试在mycar 使用explain查看

**Comment by feidian036** [comment]
useServerPrepStmts=false 能给数据插入数据，但是blob内容大小明显比直连mysql要大的多。说明二进制转换有问题。 改为mycat 服务端预编译，blob字段内容大小和直连mysql一样，blob正常。 但是预编译机制导致无法获取数据库元数据。预编译不支持元数据吗？

**Comment by junwen12221** [comment]
89774536caccfc5916c1c2bd3f3f32a0d3327db7 已修复
