### ISSUE TITLE
使用MySQL8.0.11客户端登陆Mycat1.6-RELEASE失败

### ISSUE THREAD

**Issue by XiaoleLee** [MyCATApache/Mycat-Server#2437]
系统是mac，使用Navicat可以登陆，但是在命令行里使用mysql客户端登陆显示“Access denied for user 'root', because password is error”。
然后查看日志，发现user为null
![image](https://user-images.githubusercontent.com/9973801/76974067-b3f7cc80-696b-11ea-8382-728f3b36c4eb.png)
但是使用Navicat可以登陆，而且user也正常显示了
![image](https://user-images.githubusercontent.com/9973801/76974215-e4d80180-696b-11ea-89fc-02475eff0bf0.png)

**Comment by junwen12221** [comment]
mysql客户端设置native协议登录,或者mycat设置忽略密码

**Comment by XiaoleLee** [comment]
密码协议问题，已解决
