### ISSUE TITLE
fastjson安全漏洞的问题

### ISSUE THREAD

**Issue by xiateapu** [MyCATApache/Mycat-Server#2440]
大佬们，fastjson考虑升级到1.2.67吗，阿里云发布漏洞公告了：
https://help.aliyun.com/noticelist/articleid/1060253179.html?spm=5176.2020520154.sas.5.56831e43xfiwY1

**Comment by junwen12221** [comment]
最新分支已经升级了,或者把旧版本的fastjson jar替换就行

**Comment by xiateapu** [comment]
最新分支指的是哪个？我看Mycat-server-1.6.7.5-test分支好像fastjson好像还是1.2.58  
替换jar包的方式可以弄，但还是希望官方可以修复~

**Comment by junwen12221** [comment]
哦,我记错了,fastjson之前出现漏洞升级了一次,这次又是另一个,现在我改一下

**Comment by xiateapu** [comment]
辛苦了~
