### ISSUE TITLE
MySQL Connector Python连接MyCAT无法commit

### ISSUE THREAD

**Issue by kenlee1988** [MyCATApache/Mycat-Server#2444]
利用MySQL Connector Python连接MyCat，MyCAT最终无法commit
Mycat的版本：Mycat-server-1.6.7.4-release

python代码：
mydb = mysql.connector.connect(host=xx, port=xx, user=xx, passwd=xx, database=xx)
cursor = mydb.cursor()
curosor.execute(sql, val)
mydb.commit()

查看源码发现 mysql.connector 会发送 set @@session.autocommit = off;请求
而server/handler/SetHandler.java 无法正确解析该语句，导致最后的commit请求没有正确处理。

**Comment by junwen12221** [comment]
最新分支fix 需要jar包可以联系我
