### ISSUE TITLE
当视图数据超过20条后通过mycat查询不到结果集，但是重启应用程序就可以查询到

### ISSUE THREAD

**Issue by chengwengao** [MyCATApache/Mycat-Server#2445]
问题描述：当查询的视图数据超过20条时，通过mycat查询不到结果集，但是直接查询可以查询到。
mycat.log中的报错日志如下：
`respHandler=io.mycat.backend.mysql.nio.handler.RollbackNodeHandler@60d0fcea, host=*, port=*, statusSync=null, writeQueue=0, modifiedSQLExecuted=true] bound by ServerConnection [id=132816, schema=*, host=*, user=*,txIsolation=1, autocommit=false, schema=*]: field's eof
2020-03-25 14:31:04.188 ERROR [$_NIOREACTOR-6-RW] (io.mycat.backend.mysql.nio.handler.RollbackNodeHandler.rowResponse(RollbackNodeHandler.java:156)) - unexpected packet for MySQLConnection [id=622, lastTime=1585117864177, user=*, schema=*, old shema=*, borrowed=true, fromSlaveDB=false, threadId=1779567, charset=utf8, txIsolation=1, autocommit=false, attachment=db{select * from a_view
        where id = '123'
        and delete = 0
        and num in
         (  
           '1', '2', ..., '20'
         )},`
数据做了一些脱敏处理，其中a_view是一个视图，只要服务不重启，反复执行一直查询不到，但是重启应用程序（不是重启mycat）就能查询到结果集，请问这个是什么原因？

**Comment by chengwengao** [comment]
mycat版本Mycat-server-1.6.5-release.jar

**Comment by chengwengao** [comment]
> mycat版本Mycat-server-1.6.5-release.jar

折腾了一圈最后把版本升级到1.6.7.1就解决了，暂时不知道是啥原因，可能是新版本修复了已知bug解决了一些问题。

**Comment by chengwengao** [comment]
测试环境可以了，但是上了生产环境问题还是存在

**Comment by junwen12221** [comment]
可能返回了mycat不支持的报文

**Comment by chengwengao** [comment]
> 可能返回了mycat不支持的报文

如果不支持应该一直处理不了才对，但是重启了应用程序后，返回就正常了。应用程序运行一段时间后，就又回返回不正常的结果集。

**Comment by dcmr** [comment]
这么多问题，说实话我看到以后怕怕的。 公司已经准备上mycat了，我是要劝退吗？ 用sharding，大家觉得性能不错，但是要配置的全在程序员

**Comment by chengwengao** [comment]
> 这么多问题，说实话我看到以后怕怕的。 公司已经准备上mycat了，我是要劝退吗？ 用sharding，大家觉得性能不错，但是要配置的全在程序员

说实话，这个看运气吧。我们线上用了1年多都没出问题，但是最近遇到的这个问题真的把我们搞得焦头乱额。我们尝试过升级mycat版本，根据mycat报错日志调整相关参数，但是最终都没有解决问题，可能一方面还是对mycat不够了解，另一方面mycat的确存在一些问题。如果确实要用，建议还是用新不用旧，遇到了问题多分析日志，如果确实是mycat尚未解决的bug导致的问题，可能得从mycat源码层面寻找原因了，但是从目前该项目的开源活跃程度和解决bug的效率来看，这一点基本无望。如果有兴趣，你们也可以参考一下另外一个中间件dble，据说是mycat的增强版，在mycat的基础上修复了mycat的一些bug，也做了一些优化，其开源社区目前来看比较活跃，重要的是因为是在mycat的基础上做的，所以许多配置性的东西和mycat都是相通的，可以举一反三，官网的文档也比较全，我当时只花了大概半天到一天左右的时间就将dble作为mycat的替代品启动成功，迁移和学习成本比较低，在测试环境稳定运行2天后，切到了线上，目前来看已经解决了线上的bug，现在还在持续观察中。

**Comment by chrissata** [comment]
怀疑是因为autocommit的问题导致事务未关闭。
业务执行commit或rollback的时候 mycat没有将autocommit 置为true，而是继续保持false状态。
