### ISSUE TITLE
推荐一款分库分表项目 : Apache ShardingSphere

### ISSUE THREAD

**Issue by thicv** [MyCATApache/Mycat-Server#2472]
调研了几个分库分表的产品，发现国内 star 数比较多的就是 mycat 和 Apache ShardingSphere。

给大家介绍一下Apache Shardingsphere，它的 proxy 功能跟 mycat 的是一样的，但是 Apache ShardingSphere 的起步靠的是Sharding-JDBC，比mycat提供了更灵活的接入端。他还支持分布式事务（XA、BASE）注册中心（ZooKeeper、Etcd），数据脱敏，数据迁移，opentracing 监控等能力。

看Roadmap，Apache ShardingSphere未来还会支持自研的分布式事务（JDTX）、多副本、以及数据库内核端的能力。

Apache ShardingSphere已经是标准的 [Apache基金会的顶级项目了](https://www.infoq.cn/article/EgR36ml79wYdBxzsUq7B?utm_source=tuicool&utm_medium=referral)，社区运作很标准，而且基本涵盖了mycat的全部能力（就算有不支持的，提交社区，应该马上就会有反馈）。

mycat社区现在这样子大家都看到了，基本已经停滞了。看了一下 Apache ShardingSphere创始人 [对项目和社区的见解](https://www.oschina.net/question/4489239_2316036)，还是很靠谱的。

建议大家有空可以去看看 [Apache ShardingSphere](https://github.com/apache/shardingsphere)

![image](https://user-images.githubusercontent.com/64291865/80357331-6c8b2700-88ad-11ea-98e2-880121f33242.png)

**Comment by thicv** [comment]
@zwy
干嘛无缘无故 close 掉，社区是这么玩的吗

**Comment by ExDevilLee** [comment]
@thicv 你推荐的Apache ShardingSphere我也了解过，各方面确实比Mycat要好的多，不管是代码质量、应用场景，还是社区活跃度、响应度等等。但是你这个issue等于是来砸场子的，如果能删issue的话，这个issue估计都要被删掉。

**Comment by thicv** [comment]
@ExDevilLee 不是砸场子，两种技术我最近都调研了一下，只是诚心推荐而已。现在mycat社区基本停滞是事实，所以想让关注分库分表的人多了解一下生态而已。搞开源，何必把自己装在瓶子里。

**Comment by thicv** [comment]
开源是技术的交流，不是宗教

**Comment by thicv** [comment]
做得好，或做的不好都没关系，社区本身就是透明的，没必要不让人说话

**Comment by ExDevilLee** [comment]
赞成你的说法，其实我也只是路人~

**Comment by HashZhang** [comment]
兄嘚，Insight does not crack wise

**Comment by thicv** [comment]
看破不说破是对信息对称的人，很多同学信息不对称，所以想分享下

**Comment by HashZhang** [comment]
兄嘚，你在 vertx，jdon 社区提Issue推荐 spring，或者在RocketMQ社区发帖子推荐Pulsar等等，或者像FastJson那些issue喷jackson比FastJson严谨多了，也一样会被关闭的，哈哈。你可以提升自身影响力，在自媒体宣传 ShardingSphere。或者是ShardingSphere有那些MyCat可以借鉴的地方，总结出来，提Issue，你可以参考这个：

[LoadBalancer: Add ability to eagerly create ReactiveLoadBalancerClient contexts](https://github.com/spring-cloud/spring-cloud-commons/issues/729)

另外，贡献过MyCat，读过ShardingSphere源码，ShardingSphere源码写的严谨很多很多，值得学习。MyCat 没有稳定的大佬一直引导方向，有明确的roadmap，总是这边做一点，那边做一点，代码质量也不稳定，导致现在的局面。

**Comment by thicv** [comment]
开源就是应该充分沟通，没必要隔着一堵墙。mycat现在做的不好，可以参照别的项目。如果做的不好，还禁止讨论别的项目，未免就不合适了，毕竟很多用户都是刚需，mycat停止更新，这些刚需的用户总是要知道有什么产品可以替代的，藏着掖着不仅不能阻止用户知道 Shardingsphere，反而显得太小气

**Comment by thicv** [comment]
@zwy reopen 一下这个 issue 吧，让大家讨论讨论，也互相学习下。

**Comment by ericthecouch** [comment]
好项目，山穷水尽疑无路，柳暗花明又一村，对mycat彻底失望的同时，发现了这么好的替代品

**Comment by ericthecouch** [comment]
@haocao 看大佬去了京东，看来这个项目未来可期啊。

**Comment by githubyong** [comment]
MyCATApache是什么，有没有路过的大佬介绍下：）

**Comment by yanjingfan** [comment]
你们还在用中间件mycat和sharding伪分布式数据库？我司都准备用TiDB分布式关系数据库了

**Comment by HashZhang** [comment]
TiDB还是挺好的，就是有点吃资源，并且TiDB目前还是需要优化一下SQL分析器，我们用的时候，对于表上面有多重index和复合索引的，每次select都要强制force index才保险

**Comment by HashZhang** [comment]
> 你们还在用中间件mycat和sharding伪分布式数据库？我司都准备用TiDB分布式关系数据库了

TiDB还是挺好的，就是有点吃资源，并且TiDB目前还是需要优化一下SQL分析器，我们用的时候，对于表上面有多重index和复合索引的，每次select都要强制force index才保险，否则有时候可能一个普通的按用户查询的SQL，给优化的走按照创建时间过滤的全扫描，吃掉集群整个资源。
