### ISSUE TITLE
给mycat社区的建议

### ISSUE THREAD

**Issue by ericthecouch** [MyCATApache/Mycat-Server#2473]
公司很久前用了 mycat，一直到现在遇到了很多问题，但是目前的社区基本上是停滞状态。
同事提的 issue，基本上都没人修复。
看到了一个 issue #2472 ，深有同感，咱们 mycat 社区不能停滞不前啊，就不能向他们好好学习学习吗。
提问题不修，提建议直接 close，这样很容易让大家弃坑。
希望 mycat 社区能加油。

**Comment by junwen12221** [comment]
为什么不看看2.0呢

**Comment by ericthecouch** [comment]
2.0 进展相对缓慢，完全没有公司背景，不可能有人直接上线。口碑不是说重来就能重来的。一个全新的东西，没有积累，很难被选择了

**Comment by thicv** [comment]
唉，他们就这样了，根本听不进去任何建议。

**Comment by ExDevilLee** [comment]
作者并没有正面回复题主的建议啊，还把issue直接close掉，这种做法并不是太好啊

**Comment by ericthecouch** [comment]
唉，失望。闭关锁国，不思进取。粉丝转路人了。
业精于勤，荒于嬉。不景气怕是会淘汰不争气
