### ISSUE TITLE
mycat1.6.5版本：插入语句的value中出现了,(符号，导致插入数据被篡改

### ISSUE THREAD

**Issue by wwhworkspace** [MyCATApache/Mycat-Server#2477]
原始sql：
`INSERT INTO mail_send (
    createTime,
    updateTime,
    flag,
    accountId,
    messageID,
    sender,
    senderName,
    fromer,
    replyTo,
    toer,
    ccer,
    bccer,
    SUBJECT,
    text,
    STATUS,
    costTime,
    seperated,
    marketed,
    readCount,
    uid,
    uidValidity,
    uidBatchNum,
    attached,
    needDownloadAttach,
    syncFromMailServer,
    messageNum,
    folder,
    sentTime,
    contentSummary
)
VALUES
    (
        NOW(),
        NULL,
        0,
        1115,
        '2222000000',
        NULL,
        NULL,
        '9999',
        '9999',
        NULL,
        NULL,
        NULL,
        NULL,
        '<html><p style=\\"margin: 0px;\\">it will soon be on wuwanhua2908 vacation now,(Labor Day，01/05-05/05)</p><img style=\\"display:none\\" class=\\"just-for-mail-none-lys\\"></html>',
        0,
        NULL,
        0,
        0,
        0,
        NULL,
        NULL,
        0,
        0,
        NULL,
        0,
        0,
        NULL,
        NULL,
        NULL
    )`

执行结果：(这个问题已经在mycat1.7版本中修复了)
text字段的value中出现了不该存在的自增ID和逗号：1255754334583525376,
`<html><p style=\\"margin: 0px;\\">it will soon be on wuwanhua2908 vacation now,(1255754334583525376,Labor Day，01/05-05/05)</p><img style=\\"display:none\\" class=\\"just-for-mail-none-lys\\"></html>`

源码：
RouterUtil.handleBatchInsert方法
values =Pattern.compile(",\\s*\\(").matcher(values).replaceAll(","+mycatSeqPrefix);

原因：
因为原语句没有主键字段，所以mycat要补充主键字段，在补充主键字段的时候考虑到批量插入语句的情况，在批量替换,(的时候没有排除value中的内容，因为value中的内容里面也包含了,(，这样mycat补充主键字段时就发生错误，导致value中的内容多出了一个不该出现的自增ID和逗号，mycat补充主键后的结果如下（应该只会有一个next value for MYCATSEQ_MAIL_SEND，但是出现了两个！）：
`INSERT INTO mail_send (
    ID,
    createTime,
    updateTime,
    flag,
    accountId,
    messageID,
    sender,
    senderName,
    fromer,
    replyTo,
    toer,
    ccer,
    bccer,
    SUBJECT,
    text,
    STATUS,
    costTime,
    seperated,
    marketed,
    readCount,
    uid,
    uidValidity,
    uidBatchNum,
    attached,
    needDownloadAttach,
    syncFromMailServer,
    messageNum,
    folder,
    sentTime,
    contentSummary
)
VALUES
    (
          next value for MYCATSEQ_MAIL_SEND,
            NOW(),
            NULL,
            0,
            1115,
            '2222000000',
            NULL,
            NULL,
            '9999',
            '9999',
            NULL,
            NULL,
            NULL,
            NULL,
            '<html><p style=\\"margin: 0px;\\">it will soon be on wuwanhua2908 vacation now,(next value for MYCATSEQ_MAIL_SEND,Labor Day，01/05-05/05)</p><img style=\\"display:none\\" class=\\"just-for-mail-none-lys\\"></html>',
            0,
            NULL,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            NULL,
            0,
            0,
            NULL,
            NULL,
            NULL
    )`

**Comment by junwen12221** [comment]
这个问题好像被修复过,可以使用1675试试
#2477 
#2476
