### ISSUE TITLE
1.6.7.4升级到1.6.7.5-release，不修改server.xml，全局自增id会有问题

### ISSUE THREAD

**Issue by xmabul** [MyCATApache/Mycat-Server#2480]
在不改变数据库、mycat的conf配置，将1.6.7.5-release的bin和lib目录替换到1.6.7.4后，插入全局自增id会提示ERROR 1003 (HY000): mycat sequnce err.java.lang.NumberFormatException: null。

```
mysql> select version();
+---------------------------------------------+
| VERSION()                                   |
+---------------------------------------------+
| 5.6.29-mycat-1.6.7.4-release-20200105164103 |
+---------------------------------------------+
1 row in set (0.02 sec)

mysql> insert into t_user(name,user) values('a','xx');
Query OK, 1 row affected (0.04 sec)

mysql> select version();
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql> select version();
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: test

+---------------------------------------------+
| VERSION()                                   |
+---------------------------------------------+
| 5.6.29-mycat-1.6.7.5-release-20200422133810 |
+---------------------------------------------+
1 row in set (0.20 sec)

mysql> 
mysql> 
mysql> 
mysql> select version();
+---------------------------------------------+
| VERSION()                                   |
+---------------------------------------------+
| 5.6.29-mycat-1.6.7.5-release-20200422133810 |
+---------------------------------------------+
1 row in set (0.00 sec)

mysql> insert into t_user(name,user) values('a','xx');
ERROR 1003 (HY000): mycat sequnce err.java.lang.NumberFormatException: null
```

server.xml：  sequnceHandlerType=1
sequence_db_conf.properties：  T_USER=dn1
schema.xml部分配置：   <table name="t_user" primaryKey="id" type="global" autoIncrement="true" dataNode="dn1" />
mycat_sequence表：  T_USER             16         1

**Comment by junwen12221** [comment]
没有复现

**Comment by xmabul** [comment]
1.6.7.4版本的[server.xml](https://github.com/MyCATApache/Mycat-Server/blob/Mycat-server-1.6.7.4-release-20200105164103/src/main/resources/server.xml)，第21行sequnceHandlerType
1.6.7.5版本的[server.xml](https://github.com/MyCATApache/Mycat-Server/blob/Mycat-server-1.6.7.5-test/src/main/resources/server.xml)，第21行sequenceHandlerType
控制变量法才找到这两个版本哪里不一致，也间接说明mycat的git管理有点混乱，说实在的。
一开始用1.6.7.4版本，配置sequnceHandlerType=1，升级到5的时候没替换conf目录，结果5版本命名改了，读取配置找不到，估计就用默认值0了吧。修改命名为sequenceHandlerType=1就正常了
