### ISSUE TITLE
mysql-connector-java-8.0.11 Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by tom055** [MyCATApache/Mycat-Server#2491]
![20200603154832](https://user-images.githubusercontent.com/17687356/83610662-62e29680-a5b2-11ea-98fb-17cde2ad100b.png)

mysql版本是8.0.20
已经替换了mycat/lib/mysql-connector-java-5.1.35.jar 为 mysql-connector-java-8.0.11.jar
navicat可以连接上mycat数据库
![666](https://user-images.githubusercontent.com/17687356/83610970-de444800-a5b2-11ea-89ac-00de1138547f.png)

**Comment by junwen12221** [comment]
检查一下是后端数据库没有这个变量?

**Comment by tom055** [comment]
@junwen12221 mysql5.7就没问题了 mysql8不行 mycat版本1.6.7.5 以后版本会支持mysql8吗？

**Comment by Qka6666** [comment]
有没有办法解决，我也是同样的问题，mysql 8.0.20 ,mycat 1.6.5， navicat可以正常连接使用
但是服务报Unknown system variable 'query_cache_size'

**Comment by tom055** [comment]
@Qka6666 换mysql5点几就行 或者 使用mycat2

**Comment by Qka6666** [comment]
> @Qka6666 换mysql5点几就行 或者 使用mycat2

Mycat-server-1.6.7.3-release-20190927161129-linux.tar.gz  换到1.6.7.3版本mycat,没有此问题了
