### ISSUE TITLE
使用Hibernate启动更新表结构时：Table found：adAdmin.ip_tb

### ISSUE THREAD

**Issue by jaceding** [MyCATApache/Mycat-Server#2496]
mycat版本：1.6.7.4-release
Hibernate版本 4.1.6-Final
MySQL版本：5.7

Hibernate 更新表结构时，Table not found：ip_tb
但Hibernate 会创建表，创建表时，Table 'ip_tb' already exists。

**Comment by funnyAnt** [comment]
mycat不支持这种schema.table的语法。 如果adAdmin是mycat上面的逻辑库，可以通过在schema.xml里面配置 checkSQLschema="true"来规避，如果是mysql上面的物理库，不支持。 具体可参考下1.6.5的使用手册
