### ISSUE TITLE
客户端对mycat的支持情况怎么样，比如Navicat

### ISSUE THREAD

**Issue by xiaomaixu** [MyCATApache/Mycat-Server#2503]
客户端对mycat的支持情况怎么样，比如Navicat，对表和虚拟表视图区分的好吗等等

**Comment by xiaomaixu** [comment]
用Navicat查看mycat下的表和虚拟表好像混一起了，表和视图下面显示的一样多，都是显示表和视图的总数，视图下面不是视图表的点击报错如下：
![image](https://user-images.githubusercontent.com/20907534/84111753-2dc6c000-aa5a-11ea-9a62-6545da17af13.png)
表下面不是表的点击报错如下：
![image](https://user-images.githubusercontent.com/20907534/84111946-71b9c500-aa5a-11ea-8f23-aef647032235.png)
用Navicat查看mysql节点下的表和视图下面显示的都正确，表显示在表下面，视图显示在视图下面，没有两边都有，谢谢帮忙解决。

**Comment by funnyAnt** [comment]
mycat不支持view的。客户端仅仅支持navicat，并且建议使用版本10
