### ISSUE TITLE
CLIENT_PLUGIN_AUTH is required

### ISSUE THREAD

**Issue by WindRush** [MyCATApache/Mycat-Server#2519]
用1.6的版本，mysql版本是5.7
用terminal可以连接上，但是用springboot+mybatis老连不上，总是报CLIENT_PLUGIN_AUTH is required，又遇到的吗，咋解决啊

**Comment by WindRush** [comment]
mysql-connector-java是5.1.38

**Comment by junwen12221** [comment]
5.1.35

**Comment by WindRush** [comment]
解决了，mysql装了两次，导致数据乱了，把mysql卸载干净，又重新装了下可以连上了
