### ISSUE TITLE
[优化]非DDL的修改语句insert,update,delete，自动开启事务功能

### ISSUE THREAD

**Issue by funnyAnt** [MyCATApache/Mycat-Server#2528]
#### 需求来源
 未开启事务的情况下， update 一个全局表customer，假定customer有2个节点dn1,dn2。 因mycat不会主动开启事务，当下面情况发生时会出现数据不一致情况：
   - 1）dn1节点上面update成功
   - 2）dn2节点上面update失败

#### 优化方案
  当业务侧没有开启事务时，如果涉及到多节点修改类操作，mycat自动开启事务，保证多个节点的数据一致性。

**Comment by funnyAnt** [comment]
已经完成代码初步编写工作

**Comment by junwen12221** [comment]
1.6的ok包状态应该是没有设置事务标记,一些客户端会利用此标记检查事务状态或者发送sql查询事务的sql检查

如果客户端与mycat的事务状态发生不一致,会导致客户端发送一些sql,比如mycat实际上已经开启了事务,但是mycat里面没有体现,或者随机发送到后端数据库.如果不提供这些事务的标记供客户端正确查询,就会导致客户端状态混乱.

**Comment by funnyAnt** [comment]
> 1.6的ok包状态应该是没有设置事务标记,一些客户端会利用此标记检查事务状态或者发送sql查询事务的sql检查
> 
> 如果客户端与mycat的事务状态发生不一致,会导致客户端发送一些sql,比如mycat实际上已经开启了事务,但是mycat的报文与查询事务sql里面没有体现,或者随机发送到后端数据库.如果不提供这些事务的标记供客户端正确查询,就会导致客户端状态混乱.

那返回客户端的OK包事务状态位：是以客户端是否开启事务为准，还是mycat实际到底开启事务为准。
