### ISSUE TITLE
全局表一致性保证

### ISSUE THREAD

**Issue by xiaomaixu** [MyCATApache/Mycat-Server#2531]
您好，我们使用的是1.6.7.3版本mycat已经有全局表一致性的检查了吧？最近有用户反应全局表数据不一致，有没有保证全局表数据一致性的方法啊？谢谢帮忙解答。

**Comment by funnyAnt** [comment]
#### 问题
- 原来的版本是会有这样的问题，参考#2528 里面的修复。修复后会大大减少全局表数据不一致的情况

- 但是因为全局表的修改涉及到多节点分布式事务问题，依然会存在commit时候出现部分commit成功部分commit失败的情况。

#### 解决思路
- 搞一个定时job，定期检查下全局表的在每个节点的数据量是否一致。

**Comment by xiaomaixu** [comment]
好嘞，修复后的稳定包是哪个？mycat官网上发布出来了没

**Comment by funnyAnt** [comment]
> 好嘞，修复后的稳定包是哪个？mycat官网上发布出来了没

代码提交到了1.6.76-test分支。至于什么时候发版本，要问 @junwen12221 ，或者qq群里面咨询下。
