### ISSUE TITLE
配置多个schema时，同一个sql执行多次，会跑到不通的datanode上面

### ISSUE THREAD

**Issue by zhanglei-1231** [MyCATApache/Mycat-Server#2533]
![image](https://user-images.githubusercontent.com/67528918/85936291-d49cce80-b92b-11ea-93e8-69cac265dbc6.png)
![image](https://user-images.githubusercontent.com/67528918/85936306-fc8c3200-b92b-11ea-9204-aebb1e800f7b.png)
配置多个schema，对应多个datanode时，同一个sql执行多次，会跑到不通的datanode上面。
请教如何解决？

**Comment by funnyAnt** [comment]
先看看你这个表是不是全局表。全局表为了负载均衡每次会随机选择一个节点的。

**Comment by zhanglei-1231** [comment]
这个不是全局表

**Comment by funnyAnt** [comment]
要根据配置文件和SQL具体分析了，最好找官方客服看看。

**Comment by zhanglei-1231** [comment]
升级版本后没有出现过此现象
