### ISSUE TITLE
session transaction

### ISSUE THREAD

**Issue by xiaomaixu** [MyCATApache/Mycat-Server#2550]
mycat日志报错set session transaction read only is not recoginized and ignored
![image](https://user-images.githubusercontent.com/20907534/87149483-e6df1b00-c2e2-11ea-9147-eb62fd194dc6.png)

**Comment by junwen12221** [comment]
不影响

**Comment by xiaomaixu** [comment]
好嘞，谢谢您呵！问一下全局表一致性优化有发布稳定版本吗？
https://github.com/MyCATApache/Mycat-Server/issues/2531



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat-Server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月14日(星期二) 下午4:13
收件人:&nbsp;"MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;;
抄送:&nbsp;"小麦"<1647178091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] session transaction (#2550)





 
不影响

**Comment by funnyAnt** [comment]
1676 版本。 如果要定期检查各个分片上面全局表的数据一致性，请使用第三方工具pt-table-checksum定期跑.
