### ISSUE TITLE
SHOW FULL TABLES FROM 数据名 LIKE '表名' 找不到 但是 SHOW FULL TABLES FROM 数据名 LIKE '%表名' 可以找的到 这么简单语句都执行有问题么

### ISSUE THREAD

**Issue by zhanghengdashuaibi** [MyCATApache/Mycat-Server#2570]
2020-08-07 16:59:51.354 ERROR [$_NIOREACTOR-3-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=37, schema=CSBR_Platform_Manage, host=218.106.118.42, user=root,txIsolation=3, autocommit=true, schema=CSBR_Platform_Manage, executeSql=SHOW FULL TABLES FROM `CSBR_Platform_Manage` LIKE 'mf_user']not found table : mf_user in schema CSBR_Platform_Managejava.lang.Thread .getStackTrace1559
io.mycat.net.FrontendConnection .getStack224
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.server.ServerConnection .routeEndExecuteSQL309
io.mycat.server.ServerConnection .execute241
io.mycat.server.response.ShowFullTables .response58
io.mycat.server.handler.ShowHandler .handle51
io.mycat.server.ServerQueryHandler .query92
io.mycat.net.FrontendConnection .query376
io.mycat.net.FrontendConnection .query396
io.mycat.net.handler.FrontendCommandHandler .handle76
io.mycat.net.FrontendConnection .rawHandle570
io.mycat.net.FrontendConnection .handle552
io.mycat.net.AbstractConnection .onReadData327
io.mycat.net.NIOSocketWR .asynRead216
io.mycat.net.AbstractConnection .asynRead279
io.mycat.net.NIOReactor$RW .run113
java.lang.Thread .run748
 write errorMsg:{} error

**Comment by junwen12221** [comment]
设置mysql忽略大小写

**Comment by zhanghengdashuaibi** [comment]
已经设置过了,但是还是没有用 数据库可以执行的语句 mycat执行不了

**Comment by funnyAnt** [comment]
@zhanghengdashuaibi SHOW FULL TABLES FROM 数据名 LIKE '%表名' ---里面的“数据名” 是物理库的还是mycat逻辑库名称？

**Comment by Bretterman** [comment]
我也遇到了这个问题，mycat执行不了这个语句。是mycat逻辑库名称。

> @zhanghengdashuaibi SHOW FULL TABLES FROM 数据名 LIKE '%表名' ---里面的“数据名” 是物理库的还是mycat逻辑库名称？

**Comment by funnyAnt** [comment]
@Bretterman  问题待确认

**Comment by zwyqz** [comment]
需要进行命令的实现,欢迎commit

**Comment by funnyAnt** [comment]
@Bretterman  @zhanghengdashuaibi  已经修复，请验证。

 @zwyqz 请帮忙走查下代码
