### ISSUE TITLE
mycat事务不支持repeateable read吗？

### ISSUE THREAD

**Issue by waj89757** [MyCATApache/Mycat-Server#258]
试了一下，两个事务，如果第一个事务commit了，第二个事务再次读取数据会变化，现在的版本不支持可重复读吗？

**Comment by zhouwenbin2000** [comment]
是否可重复读是跟数据库的隔离级别有关吧。应该设置下就可以了吧？

**Comment by mycatmerger** [comment]
事务隔离级别支持的，请在应用端连接池属性中配置
