### ISSUE TITLE
查询时会丢数据

### ISSUE THREAD

**Issue by wjzxc123** [MyCATApache/Mycat-Server#2581]
正确的数据：
![image](https://user-images.githubusercontent.com/32690579/91268288-a4e13a00-e7a7-11ea-93f0-07835c5486d7.png)

在查询几次：
![image](https://user-images.githubusercontent.com/32690579/91268330-b9bdcd80-e7a7-11ea-8436-af31b9254734.png)

请求怎么解决

**Comment by funnyAnt** [comment]
请提供相关的mycat配置信息，和详细的操作流程。

**Comment by allstar2012** [comment]
遇到了一样的问题。直接连接数据库没有问题，连接Mycat，哪怕只设置一个写库，不配置读库，也是一会有数据，一会没有数据。
用的都是最简单的配置。
schema.xml配置如下：
<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="1000" randomDataNode="dn1">
<table name="test" dataNode="dn1"/>
</schema>
<dataNode name="dn1" dataHost="localhost1" database="TESTDB" />
<dataHost name="localhost1" maxCon="1000" minCon="10" balance="3"
                          writeType="0" dbType="mysql" dbDriver="jdbc" switchType="-1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM1" url="jdbc:mysql://127.0.0.1:3306" user="sa" password="sa123">
                </writeHost>
        </dataHost>
-----------------------------------------------------
server.xml

**Comment by wjzxc123** [comment]
> 遇到了一样的问题。直接连接数据库没有问题，连接Mycat，哪怕只设置一个写库，不配置读库，也是一会有数据，一会没有数据。
> 用的都是最简单的配置。
> schema.xml配置如下：
> select user() ----------------------------------------------------- server.xml

> 新开个issue吧，我之前配置丢了，你问下作者，可以邮件问他
