### ISSUE TITLE
Bug: ERROR 1064 (HY000): multi insert not provided

### ISSUE THREAD

**Issue by amoa400** [MyCATApache/Mycat-Server#259]
当我执行下面的SQL的时候：

    INSERT INTO hx_privilege(`item_id`,`value`,`name`) VALUES(1,'PRIVILEGE_PROMOTION_SELECT','');
报了`ERROR 1064 (HY000): multi insert not provided`错误

表结构如下：
+---------+-------------+------+-----+---------+----------------+
| Field   | Type        | Null | Key | Default | Extra          |
+---------+-------------+------+-----+---------+----------------+
| item_id | int(10)     | NO   | PRI | NULL    | auto_increment |
| value   | varchar(40) | NO   |     | NULL    |                |
| name    | varchar(60) | NO   |     | NULL    |                |
+---------+-------------+------+-----+---------+----------------+

**Comment by amoa400** [comment]
版本：1.3.0.3-release

**Comment by amoa400** [comment]
1.4-dev也存在这个情况

**Comment by magicdoom** [comment]
master代码已经修复这个问题
