### ISSUE TITLE
权威指南购书登记

### ISSUE THREAD

**Issue by songwie** [MyCATApache/Mycat-Server#260]
回复登记，格式：QQ，邮箱，截图。

**Comment by liongovip** [comment]
5284794
liongo@yeah.net
![11](https://cloud.githubusercontent.com/assets/12029199/7405311/878dc662-ef23-11e4-93d2-1755f564bb9c.jpg)

**Comment by da091314** [comment]
QQ：36959793  邮箱：36959793@qq.com 
![qq 20150430102911](https://cloud.githubusercontent.com/assets/10664635/7405329/cee94eb4-ef23-11e4-870a-762be2b00762.png)

**Comment by float-ant** [comment]
1064536737
float_ant@163.com
![image](https://cloud.githubusercontent.com/assets/12179373/7405334/d1e450b4-ef23-11e4-9783-d6610a92c260.png)

**Comment by dadait** [comment]
qq:3345233 邮箱：web3.0@qq.com 
![Uploading 20150430102856.png…]()

**Comment by pengqiuyuan** [comment]
370020694
pengqiuyuanfj@gmail.com
![image](https://cloud.githubusercontent.com/assets/4953205/7405372/2c2d2d0c-ef24-11e4-988b-780d2bc4c8f8.png)

**Comment by yinaxiong** [comment]
QQ:1978945630
Email:develop.api@qq.com
![20150430103611](https://cloud.githubusercontent.com/assets/7835924/7405436/014c9f04-ef25-11e4-9eca-b4f2c1559505.jpg)

**Comment by zdx86** [comment]
QQ：878432898
Email：chnzhn@126.com
![qq 20150430103858](https://cloud.githubusercontent.com/assets/11739491/7405450/3a7ca4cc-ef25-11e4-91c4-957d90d822f2.png)

**Comment by 87439247** [comment]
QQ 87439247
87439247@qq.com

![image](https://cloud.githubusercontent.com/assets/11268163/7405490/c821a35e-ef25-11e4-93f8-01010e08cb79.png)

**Comment by aStonegod** [comment]
QQ:250721835   邮箱：250721835@qq.com
订单号：908637262553497 
![screenshot_2015-04-30-10-44-44](https://cloud.githubusercontent.com/assets/11386110/7405507/fef38a1e-ef25-11e4-85b6-9f5d31fb7625.png)

**Comment by kizzyang** [comment]
qq:519870018
邮箱519870018@qq.com
![yang-mycat](https://cloud.githubusercontent.com/assets/1642217/7405544/b2b21372-ef26-11e4-8608-5d913482256c.png)

**Comment by zzcclp** [comment]
QQ: 441586683
email: 441586683@qq.com
订单号：897889433826981

**Comment by 330937205** [comment]
qq：330937205  330937205@qq.com   订单号1028310915360243

**Comment by fenglichun** [comment]
QQ：461460941
Email：fenglichun@sina.com
订单号：998740035216511

**Comment by goldcity** [comment]
qq:1276897435
email:1276897435@qq.com
order:910659905958290 

![orderno](https://cloud.githubusercontent.com/assets/12179595/7405624/d58f690c-ef27-11e4-8bc9-5fcc073641f2.JPG)

**Comment by wuqiangxjtu** [comment]
QQ:14217392
邮箱：14217392@qq.com
![2015-04-30 11 03 36](https://cloud.githubusercontent.com/assets/1294373/7405689/dd0c6b98-ef28-11e4-9b07-a477c50ec063.png)

**Comment by datepecker** [comment]
qq：171733933 邮箱：171733933@qq.com

订单号：1037227137346127

**Comment by seasail** [comment]
qq: 940178747
email: miaoyh1981@163.com
订单编号: 905581675182760
![order](https://cloud.githubusercontent.com/assets/1905360/7405719/45eeed16-ef29-11e4-8b5b-c2430cf9d5b1.png)

**Comment by biocy** [comment]
QQ:248457486      
邮箱：248457486@qq.com
订单号：935007342813467

**Comment by JasonWoC** [comment]
qq: 925063400
email ：925063400@qq.com
bill_id: 1038143202608724
![book](https://cloud.githubusercontent.com/assets/9067167/7405885/ac31558a-ef2b-11e4-9168-4809a8b34474.png)

**Comment by biocy** [comment]
QQ:248457486      
邮箱：248457486@qq.com
订单号：935007342813467

**Comment by liuhr** [comment]
QQ:308816459
邮箱:liuhanran5@163.com
订单号：921323982861259

**Comment by hongzhenglin** [comment]
QQ:307185292
邮箱:307185292@qq.com
订单号：1004855950262818

**Comment by onlylove** [comment]
QQ：317053123
邮箱：317053123@qq.com
订单号：1025130331953716

![20150430114712](https://cloud.githubusercontent.com/assets/1539235/7406069/2037e5b8-ef2f-11e4-8f24-c616ff7441c9.png)

**Comment by liuxudong-yonyou** [comment]
qq:334267502 
mail:334267502@qq.com
订单号：935050144364956

![Uploading QQ截图20150430115631.png…]()

**Comment by fxk2006** [comment]
QQ:463045403
邮箱:463045403@qq.com
订单号：917058128636957
![qq 20150430115737](https://cloud.githubusercontent.com/assets/5274925/7406132/18fc8d66-ef30-11e4-89ac-132073842bcc.png)

**Comment by romanticode** [comment]
QQ:
邮箱：acsebt@qq.com
订单号：1001323361066238
![image](https://cloud.githubusercontent.com/assets/11530766/7406229/7385780a-ef31-11e4-8e02-72b68db69a94.png)

**Comment by romanticode** [comment]
QQ:1526330277
邮箱：acsebt@qq.com
订单号：1001323361066238
![image](https://cloud.githubusercontent.com/assets/11530766/7406243/b06c4622-ef31-11e4-9e30-394742af9736.png)

**Comment by billmingchen** [comment]
QQ:1691732490
邮箱：chenming@tes-sys.com
订单号：1000602099930115
![image](https://cloud.githubusercontent.com/assets/12179494/7406309/fc637bf8-ef32-11e4-9daa-ab1435f7c2b5.png)

**Comment by xiech419** [comment]
QQ:512167324
邮箱：512167324@qq.com
订单号：1032898010963349
![Uploading 1.jpg…]()

**Comment by wpw708wpw** [comment]
QQ: 55298304
邮箱：55298304@qq.com
订单号：1030257143018431

**Comment by houhuijian** [comment]
QQ:290075997
邮箱：290075997@qq.com
订单号：1001021444714909

**Comment by weiyh1102** [comment]
QQ: 642721346
邮箱: 642721346@qq.com
订单号：1015088081205320
![qq 20150430133359](https://cloud.githubusercontent.com/assets/5728751/7406920/aa9ccecc-ef3d-11e4-9d93-0a1bc81ecda7.png)

**Comment by Tsuiwiki** [comment]
QQ:584274971
邮箱:584274971@qq.com
![image](https://cloud.githubusercontent.com/assets/8910013/7406926/cfe2b214-ef3d-11e4-8a8e-ffea9165d043.png)

**Comment by mission008** [comment]
QQ:540654726
邮箱：nietaooldman@126.com
订单号：999290184339611 
![mycat](https://cloud.githubusercontent.com/assets/4986398/7406984/b0daf948-ef3e-11e4-9b18-f9c278f40a23.jpg)

**Comment by 57299116** [comment]
57299116@qq.com
![qq 20150430141345](https://cloud.githubusercontent.com/assets/10276139/7407325/3cefe30e-ef43-11e4-8e87-e4254aa36c51.png)

**Comment by naxiwer** [comment]
QQ:190259626
邮箱:naxiwer@126.com
订单号:898252155180491
![qq 20150430141608](https://cloud.githubusercontent.com/assets/10301387/7407343/7444f9fc-ef43-11e4-8595-571425a20f90.jpg)

**Comment by suSe7en** [comment]
qq:296500802
email:suwen001@163.com
订单号：899017817027388
![qq 20150430142331](https://cloud.githubusercontent.com/assets/5078811/7407450/c14fc0dc-ef44-11e4-8b2f-bc1f71337848.png)

**Comment by mxp5270400** [comment]
qq:420224769
email:mengxiaopeng_java@163.com
订单号：929022779409157
![Uploading mycat.png…]()

**Comment by mxp5270400** [comment]
qq:420224769
email:mengxiaopeng_java@163.com
订单号：929022779409157


![Uploading mycat.png…]()
看订单好吧，又失败了

**Comment by mxp5270400** [comment]
qq:420224769
email:mengxiaopeng_java@163.com
订单号：929022779409157
![mycat](https://cloud.githubusercontent.com/assets/12181708/7407839/93c0aed4-ef48-11e4-90ce-7b8b7efff5ca.png)

**Comment by bandhzh** [comment]
qq:763518276
email:763518276@qq.com
订单号：927439485829383

**Comment by lvxiang639** [comment]
qq:601816857
email :  601816857@qq.com
订单号： 100601938378426

**Comment by sunflowerlb** [comment]
qq:825345469
email:sunflowerlb@126.com
订单号：1025243533535242

**Comment by gerogefeng** [comment]
QQ：441543325
email：441543325@qq.com
订单号：897822472147651
![qq 20150430152936](https://cloud.githubusercontent.com/assets/10845481/7408265/a4db17fe-ef4d-11e4-99e3-9cb7e0443f76.png)

**Comment by blackghost-01** [comment]
QQ:891128702
Email:891128702@qq.com
订单号:899847961418157

**Comment by haohan007008** [comment]
订单号：1030243307603501
QQ:49007952
Email:49007952@qq.com

**Comment by zhutoudan** [comment]
QQ: 75333089
Email: 75333089@qq.com
![1111](https://cloud.githubusercontent.com/assets/1203485/7410064/1715f8ba-ef5e-11e4-8e50-495d88be28d8.png)

**Comment by maochongz** [comment]
订单编号 999302027048147
QQ 79938131
Email: 79938131@qq.com

**Comment by coolcooller** [comment]
订单号：935519505820464
QQ：32693199
Email:32693199@qq.com

**Comment by wendyzhao** [comment]
QQ:251344600
Email:251344600@qq.com
订单号：926865748839068

**Comment by songwie** [comment]
以上已发qq离线或油箱

**Comment by hbhly** [comment]
QQ：36959793 邮箱：36959793@qq.com 
![qq 20150501090016](https://cloud.githubusercontent.com/assets/11534955/7425292/ac16e654-efe0-11e4-8c87-a34ac81f15b7.png)

**Comment by hbhly** [comment]
QQ:1078689049      Email:1078689049@qq.com

![qq 20150501090016](https://cloud.githubusercontent.com/assets/11534955/7425319/068d0e9c-efe1-11e4-87e3-4473c0448c29.png)

**Comment by weism123** [comment]
QQ:442440561  email:442440561@qq.com

**Comment by weism123** [comment]
图片传不了，谢谢
订单号：1020710887382516
QQ:442440561 email:442440561@qq.com

**Comment by yaloo** [comment]
qq：476041189
邮箱：yaloo_yang@189.cn
订单号：1016178830441840
![image](https://cloud.githubusercontent.com/assets/11406425/7429905/c8e6d3d2-f03c-11e4-92a0-be2950aba649.png)

**Comment by nm-cmd** [comment]
qq:7887697
mail:7887697@qq.com
![mycat](https://cloud.githubusercontent.com/assets/11674872/7439590/2380194e-f0b4-11e4-81b5-27d0767b1524.png)

**Comment by zouyu1987** [comment]
qq:865518458
mail:865518458@qq.com
![qq 20150502125929](https://cloud.githubusercontent.com/assets/12206289/7439977/1af566be-f0cb-11e4-9359-abc0b08b0ffb.png)

**Comment by gujiachun** [comment]
QQ：767724839
QQ邮箱: 767724839@qq.com
订单号：898897343567899
图片上传不了

**Comment by Timxuhj** [comment]
订单信息
订单编号898262954972077 支付宝交易号2015031821001001500281676246 成交时间2015-03-18 16:00:21 发货时间2015-04-27 18:15:17付款时间2015-03-18 16:01:36    
宝贝 宝贝属性  状态 服务 单价(元) 数量 优惠 商品总价(元) 
查看宝贝详情 
Mycat权威指南 

qq:21445251

**Comment by tinkerdba** [comment]
qq:84439349
mail:tinkerdba@qq.com
![image](https://cloud.githubusercontent.com/assets/10413637/7444746/cbac4712-f1c4-11e4-8634-cfc22d783d28.png)

**Comment by fengbo102** [comment]
qq:396732354
mail:fengbo102@163.com
订单编号 899707884218085

**Comment by tdgithub2013** [comment]
qq:576553416
mail: 576553416qq.com
订单编号： 898393504517474

**Comment by merek** [comment]
QQ:2355535788    email:xiaoshansong@51book.com
939242936566884

**Comment by songwie** [comment]
以上已发

**Comment by fanyongwei** [comment]
qq:1249119842  email:1249119842@qq.com
订单号：899331729109282

**Comment by Alan810** [comment]
qq:5879472 email:5879472@qq.com
订单号:1010346666199443

**Comment by 99937272** [comment]
qq:99937272 email:99937272@qq.com
订单号：1000227930058912

**Comment by focus031** [comment]
QQ:76043900
email: huangfu31@qq.com
![1111](https://cloud.githubusercontent.com/assets/2740933/7486810/79968a1c-f3dd-11e4-94b2-604d3014d900.png)

**Comment by wangdangpeng** [comment]
93126762
93126762@qq.com
订单号：1043878490017611

**Comment by gf0067** [comment]
122415338
122415338@qq.com
订单号：1001526730552315
![qq 20150508121539](https://cloud.githubusercontent.com/assets/503386/7530497/1bd69f66-f57c-11e4-9d9f-34f2068fb486.png)

**Comment by songwie** [comment]
HAVE SAET

**Comment by zhandao1986** [comment]
459553597
459553597@qq.com
订单号：1001170643309624
![qq 20150514180121](https://cloud.githubusercontent.com/assets/10543183/7629908/52c5042c-fa63-11e4-9bad-ffcece8f05f8.png)

**Comment by lidejun** [comment]
QQ：278627026  mail：278627026@qq.com
订单号：999682583736211
![image](https://cloud.githubusercontent.com/assets/9824063/7763816/4a611610-0079-11e5-9e80-0411c2c1678c.png)
