### ISSUE TITLE
mycat1.6.7.5

### ISSUE THREAD

**Issue by lambertlei** [MyCATApache/Mycat-Server#2600]
取值bit存在问题，数据库里面是 0，但是取出来变成了 true 
登入控制台是正常的
+--------------------+
| check_in           |
+--------------------+
| 0x00               |
+--------------------+

通过程序查询到该字段为48，变成了true

请问是哪个地方存在问题吗

**Comment by junwen12221** [comment]
可以试试native方式连接后端,这个错估计是后端使用jdbc方式导致的

**Comment by lambertlei** [comment]
@junwen12221 是的，驱动更换成native就可以了，jdbc方式出来的数据bit是乱的
