### ISSUE TITLE
最新版1.6.5已fix

### ISSUE THREAD

**Issue by mawenbin666** [MyCATApache/Mycat-Server#2609]
最新版1.6.5已fix

好像没有解决，1.6.6.1还有再报这个错误，偶然有
Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 401943, active 20, maxActive 20, creating 0, createErrorCount 2266

**Comment by funnyAnt** [comment]
- 原因：这个错误是你的druid连接池里面最大连接数配置的20个，已经被用完了。然后新的连接请求过来，无法获取连接一直等待，等待超过400000ms后报错。
- 解决方法：请调整druid连接池最大连接数

**Comment by mawenbin666** [comment]
好的，谢谢，

**Comment by FootyMan** [comment]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:  ### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 1160, active 66, maxActive 80, creating 0, runningSqlCount 1
