### ISSUE TITLE
mycat写入数据会存在时区差问题如何解决

### ISSUE THREAD

**Issue by WhaleKids** [MyCATApache/Mycat-Server#2614]
使用mycat设置好读写分离之后，我这边需求写入的时间和实际写入的时间相差13个小时整，想知道哪些参数可以控制这些。之前直连主库写入的时候是没有这个问题的。
##数据库的时区设置
![image](https://user-images.githubusercontent.com/18114217/95823290-e5007a00-0d5f-11eb-87b8-0e6b0f0d8b5f.png)
##使用mycat出现的时间差
![image](https://user-images.githubusercontent.com/18114217/95823455-3dd01280-0d60-11eb-99cc-7c3f48de97c5.png)

**Comment by funnyAnt** [comment]
2020-10-13 11:17:51这个时间是哪里产生的？

**Comment by WhaleKids** [comment]
> 2020-10-13 11:17:51这个时间是哪里产生的？

问题解决了，不是mycat的问题，是java程序端设置的问题，你说的那个时间是使用binlog2sql工具从binlog中解析出来的。
