### ISSUE TITLE
Mycat 1.6.7.4版本，使用ZK全局序号模式异常(sequnceHandlerType=4)

### ISSUE THREAD

**Issue by VodkaAddict** [MyCATApache/Mycat-Server#2615]
主键未按照sequence_conf.properties中配置的MINID-MAXID的区间内增长1，而是增长步数为(Max-Min + 1)
对应注册在ZK中节点/mycat/{cluster_id}/sequences/incr_sequence/{table}/seq 也会异常

查看源码发现每次调用nextId方法时，tableParaValMap都为null，需要重加载sequence_conf.properties配置
![image](https://user-images.githubusercontent.com/23044809/96430818-3a8fc780-1235-11eb-8f22-6d20d579f398.png)
![image](https://user-images.githubusercontent.com/23044809/96430749-24820700-1235-11eb-9bba-145a11b4262e.png)
重载配置的handler方法则直接更新一次seq的数值，seq = now  + period + 1，并且now赋值为当前seq的数值
![image](https://user-images.githubusercontent.com/23044809/96431073-99edd780-1235-11eb-9367-94138b942a46.png)
![image](https://user-images.githubusercontent.com/23044809/96431188-be49b400-1235-11eb-8e8a-9e7f3ea3ae06.png)
由上最终导致下一次获取全局序号时，主键增加(Max-Min + 1)

**Comment by funnyAnt** [comment]
@VodkaAddict  这边核对下，如果存在你说的问题，本周内修复。

**Comment by funnyAnt** [comment]
@VodkaAddict 看代码里面的逻辑，这个ZK算法对配置文件里面的maxValue不是你所认为的最大值作用，而是一个从ZK上面取值周期的最大值，或者可认为max-min是一个从zk取值的序列段range。例如min 100, max 200：

 - 线程1，第一次取获取到100-200这个区间段； 然后在内存中对nextSeqId递增，不会再从zk取值和更新zk上面的值。直到用完这段值后才会再次从zk上面取下一段。这样设计是为了减少ZK的交互，性能考虑。

 - 线程2，第一次取获取到201-300这个区间段；
 - 线程1，第二次取获取到301-400这个区间段；
 - 线程2，第二次取获取到401-500这个区间段；
