### ISSUE TITLE
show slave status，连续查询多次后报错

### ISSUE THREAD

**Issue by LGX93** [MyCATApache/Mycat-Server#2641]
版本1676，一开始可以成功查询，然后连续查询同一条语句之后报错，重启mycat，又正常查询。

配置：
`
<dataHost name="localhost1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="native" switchType="2" slaveThreshold="100">
	<heartbeat>show slave status</heartbeat>
	<writeHost host="hostM1" url="127.0.0.1:3306" user="test" password="123456">
		<readHost host="hostS1" url="192.168.0.110:3306" user="test" password="123456" />
		<readHost host="hostS2" url="192.168.0.111:3306" user="test" password="123456" />
	</writeHost>
</dataHost>
`
日志：
2020-11-05 13:43:36.720  WARN [$_NIOREACTOR-1-RW] (io.mycat.sqlengine.SQLJob.errorResponse(SQLJob.java:140)) - error response errno:1227, Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation from of sql :show slave status at con:MySQLConnection@222142113 [id=1, lastTime=1604555016718, user=test, schema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=703240, charset=utf8, txIsolation=3, autocommit=true, txReadonly=false, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=test,sql=show slave status,  jobHandler=io.mycat.sqlengine.OneRawSQLQueryResultHandler@65bceb93], host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2020-11-05 13:43:36.720  WARN [$_NIOREACTOR-1-RW] (io.mycat.backend.heartbeat.MySQLDetector.onResult(MySQLDetector.java:209)) - heart beat error: hostM1/localhost1 retry=10 tmo=30000
2020-11-05 13:43:36.720 ERROR [$_NIOREACTOR-1-RW] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]

**Comment by funnyAnt** [comment]
127.0.0.1, port=3306, show slave status,   you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s). 确认下test用户是否有权限执行show slave status

**Comment by LGX93** [comment]
> * 127.0.0.1, port=3306, show slave status,   you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s). 确认下test用户是否有权限执行show slave status
> * 提供表配置；你操作的方式，命令行还是代码，请提供详细样例。

`
mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 3     |
+-------+
1 row in set (0.04 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 1     |
+-------+
1 row in set (0.03 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 1     |
+-------+
1 row in set (0.03 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 3     |
+-------+
1 row in set (0.03 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 3     |
+-------+
1 row in set (0.03 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 1     |
+-------+
1 row in set (0.03 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 1     |
+-------+
1 row in set (0.03 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 111   |
+-------+
1 row in set (0.00 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 111   |
+-------+
1 row in set (0.00 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 111   |
+-------+
1 row in set (0.00 sec)

mysql> select title from article where id=1;
+-------+
| title |
+-------+
| 111   |
+-------+
1 row in set (0.00 sec)
`
title=1和3是从库，title=111是主库，按mycat配置正常是不会读取到主库的，一旦查询了主库的数据就报错了，之后要重新mycat才能正常。

是手动命令行运行的，连续运行相同语句产生的，大概连续运行次数是30次

**Comment by junwen12221** [comment]
有部分sql会随机路由的,	`<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100" randomDataNode="dn1">`
randomDataNode="dn1 这个属性加上,指向有权限的库

**Comment by LGX93** [comment]
> 有部分sql会随机路由的, `<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100" randomDataNode="dn1">`
> randomDataNode="dn1 这个属性加上,指向有权限的库

`
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
	<schema name="test" checkSQLschema="true" sqlMaxLimit="100" dataNode="dn1" randomDataNode="dn1">
	</schema>
	<dataNode name="dn1" dataHost="localhost1" database="test" />
	
	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="1" writeType="0" dbType="mysql" dbDriver="native" switchType="2" slaveThreshold="100"> 
		<heartbeat>show slave status</heartbeat>
		<writeHost host="hostM1" url="127.0.0.1:3306" user="test" password="123456">
			<readHost host="hostS1" url="192.168.0.110:3306" user="test" password="123456" />
			<readHost host="hostS2" url="192.168.0.111:3306" user="test" password="123456" />
		</writeHost>
	</dataHost>
</mycat:schema>
`
加上了效果一样。

**Comment by junwen12221** [comment]
explain show slave status 多试几次看看路由

**Comment by LGX93** [comment]
> explain show slave status 多试几次看看路由

感觉和运行语句次数没关，重启mycat后，前30秒左右是正常的，然后大概30秒后就不行了。
这种情况一般和什么配置有关？

**Comment by junwen12221** [comment]
可能是心跳

**Comment by LGX93** [comment]
> 可能是心跳,查询的节点执行不了心跳语句,导致判断节点挂了

嗯嗯，是心跳，问题解决了，谢谢哈

**Comment by zhaozw1984** [comment]
是如何解决的啊？我配置 switchType="2" 心跳show slave status 为什么是空，没有数据返回呢？
