### ISSUE TITLE
WrapperSimpleApp: Unable to locate the class io.mycat.MycatStartup:

### ISSUE THREAD

**Issue by mkerj** [MyCATApache/Mycat-Server#2643]
版本号：Mycat-server-1.6.7.6-release
jdk:jdk1.8.0_202

启动报这个错误：
WrapperSimpleApp: Unable to locate the class io.mycat.MycatStartup:

1.6.7.6版本最低jdk支持哪个版本？

**Comment by funnyAnt** [comment]
@mkerj  mycat官网取下最新的版本。之前打包有点问题。
