### ISSUE TITLE
想咨询一下，table表名是否能够支持*匹配算法

### ISSUE THREAD

**Issue by qifengzhang007** [MyCATApache/Mycat-Server#2645]
### 问题描述 
>   一个项目数据量超大大的核心表的数量反而会很少，很多表其实是不需要进行进行切分的，这些不需要的切分的表是否支持*匹配语法？ 	 
>  针对不需要数据切分的table表，1.6.7.4版本的项目能否更新一下，  设置属性   primary key ="id"   auto_increment=true  这两个属性能不能首先支持一下？ 只需要自动生成主键id就行。

```code
<schema name="db_test_mycat_write" checkSQLschema="false" sqlMaxLimit="100" >
		<!-- auto sharding by id (long) -->
		<!--splitTableNames 启用<table name 属性使用逗号分割配置多个表,即多个表使用这个配置-->

		<table name="tb_users_mycat" dataNode="dn1,dn2" rule="mod-long" splitTableNames ="true"/>

		<!--  一个项目数据量超大大的核心表的数量反而会很少，很多表其实是不需要进行进行切分的，这些不需要的切分的表是否支持*匹配语法？ ，例如以下的  t_order_0  等直接用*代替就行 -->
		<table name="t_order_0" dataNode="dn1" rule="auto-sharding-long" splitTableNames ="true"/>
	</schema>

	
	<dataNode name="dn1" dataHost="database1" database="db_goskeleton" />	

```

**Comment by funnyAnt** [comment]
- 1、mycat目前不支持模糊匹配表
- 2、你这个需求，不分片表量大不想在schema.xml里面一一配置，可以通过在schema设置默认节点达到，形如
`<schema name="db_test_mycat_write" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1" >`

 添加属性 dataNode="dn1"，这样dn1节点里面所有的物理表都能正常路由访问。
 你说的auto_increment=true这个属性，感觉没有必要，直接用mysql自身的自增序列好啦。 @qifengzhang007

**Comment by qifengzhang007** [comment]
> * 1、mycat目前不支持模糊匹配表
> * 2、你这个需求，不分片表量大不想在schema.xml里面一一配置，可以通过在schema设置默认节点达到，形如
>   `<schema name="db_test_mycat_write" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1" >`
> 
> 添加属性 dataNode="dn1"，这样dn1节点里面所有的物理表都能正常路由访问。
> 你说的auto_increment=true这个属性，感觉没有必要，直接用mysql自身的自增序列好啦。 @qifengzhang007


多谢作者，
表使用mysql自增的id主键的话，使用insert 语句不写id字段，会报错啊。
此外，请作者检查一下官方提供的qq群，无法付费，无法进群，想进去和大家一起使用、讨论

**Comment by funnyAnt** [comment]
@qifengzhang007  微信搜索下  Mycat技术交流
