### ISSUE TITLE
mysql 数据库 存储php json_encode()处理过的数组时,中文编码的\会丢失

### ISSUE THREAD

**Issue by haozhi6** [MyCATApache/Mycat-Server#2655]
mycat版本: Mycat-server-1.6.7.4-release-20200105164103-linux.tar.gz
Mysql版本: 5.7.31-log 社区版

mycat日志执行的sql语句; 2020-11-13 15:06:15.737 DEBUG [$_NIOREACTOR-0-RW] (io.mycat.server.handler.ServerPrepareHandler.execute(ServerPrepareHandler.java:162)) - execute prepare sql: UPDATE `cmf_option`  SET `option_value` = '{\"site_name\":\"\u4e07\u5cb3\u8bfe\u5802\u96c6\u7fa4\u642d\u5efa\",\"site_url\":\"\",\"copyright\":\"\",\"site_phone\":\"\",\"wx_url\":\"\",\"site_seo_title\":\"\u4e07\u5cb3\u8bfe\u5802\u96c6\u7fa4\",\"site_seo_keywords\":\"\u4e07\u5cb3\u8bfe\u5802\u96c6\u7fa4\",\"site_seo_description\":\"\u4e07\u5cb3\u8bfe\u5802\u96c6\u7fa4\",\"apk_ver\":\"\",\"apk_url\":\"\",\"apk_des\":\"\",\"ipa_ver\":\"\",\"ios_shelves\":\"\",\"ipa_url\":\"\",\"ipa_des\":\"\",\"qr_url\":\"\"}'  WHERE  `option_name` = 'site_info'  

实际数据库中插入的数据:
{"site_name":"u4e07u5cb3u8bfeu5802u96c6u7fa4u642du5efa","site_url":"","copyright":"","site_phone":"","wx_url":"","site_seo_title":"u4e07u5cb3u8bfeu5802u96c6u7fa4","site_seo_keywords":"u4e07u5cb3u8bfeu5802u96c6u7fa4","site_seo_description":"u4e07u5cb3u8bfeu5802u96c6u7fa4","apk_ver":"","apk_url":"","apk_des":"","ipa_ver":"","ios_shelves":"","ipa_url":"","ipa_des":"","qr_url":""}

问题: "\\" 丢失 汉字无法正常显示

**Comment by funnyAnt** [comment]
这个我来处理下

**Comment by funnyAnt** [comment]
@18815385963  这个问题已经在2020/1/7号修复，请使用1.6.7.5 或1.6.7.6测试下

**Comment by 18815385963** [comment]
非常感谢!
