### ISSUE TITLE
mycat通过mysql客户端查询数据翻20倍问题

### ISSUE THREAD

**Issue by xiaohanlin888** [MyCATApache/Mycat-Server#2658]
你好，
      我发现我有一个表分了20个表，然后通过mysql客户端连接8066查询这个表，select * from table;  结果集有20倍，刚好和分表的数量一样。但是select count(*) from table；返回的记录数量是正常的。请问是怎么回事呢谢谢

**Comment by funnyAnt** [comment]
@xiaohanlin888  请提供mycat版本号，schema.xml里面的表配置信息，rule里面的路由规则

**Comment by junwen12221** [comment]
旧的1.6分表查询会有查询数量翻倍的问题,1.66之后没有
