### ISSUE TITLE
mycat插入重复主键未报错及查询出来有重复数据！

### ISSUE THREAD

**Issue by 007akuan** [MyCATApache/Mycat-Server#2659]
Mycat版本：5.6.29-mycat-1.6.7.4-release-20200105164103
MySQL版本：5.7.32

schema.xml配置：
![image](https://user-images.githubusercontent.com/74766271/99784421-bcd21b00-2b56-11eb-85b6-96be46021f90.png)
![image](https://user-images.githubusercontent.com/74766271/99786548-9bbef980-2b59-11eb-897d-6bc17a420d03.png)

rule.xml配置：
  
![image](https://user-images.githubusercontent.com/74766271/99784643-133f5980-2b57-11eb-85e5-78cd4fe859b3.png)
![image](https://user-images.githubusercontent.com/74766271/99784653-176b7700-2b57-11eb-865a-c37822799ea3.png)

表结构：
![image](https://user-images.githubusercontent.com/74766271/99784742-3964f980-2b57-11eb-8e9b-98f640498f20.png)

现象1->插入重复数据未报错：
![image](https://user-images.githubusercontent.com/74766271/99784179-6238bf00-2b56-11eb-9b9c-0bd828a5bc3e.png)

现象2->通过Mycat登录查询会有重复数据：
![image](https://user-images.githubusercontent.com/74766271/99784982-89dc5700-2b57-11eb-8bdd-f9113ce2ac4f.png)

**Comment by 007akuan** [comment]
通过Mycat登录查询（再查询前重启过Mycat server）,但是总记录还是有翻倍情况且查询主键总数和去重后总数一致！神奇
![image](https://user-images.githubusercontent.com/74766271/99789062-ff96f180-2b5c-11eb-959e-7e1d6073a09d.png)
![image](https://user-images.githubusercontent.com/74766271/99789363-66b4a600-2b5d-11eb-9998-05a6f45a273b.png)

**Comment by funnyAnt** [comment]
@007akuan  因为你的表虽然设置了primaryKey="id"， 但是没有使用mycat的全局序列方式生成id， insert into依然使用你自己的设置的id, 这样id的唯一性只能是mysql分库级别的。 从mycat全局视觉看所有分库数据，就可能有重复的id.

比如你的例子里面问题原因，(id,create_time)=(3,2020-02-01),(3, ,2020-03-01）分别路由到2月份和3月份的分库，mysql不会报主键冲突。

**Comment by 007akuan** [comment]
> e)=(3,2020-02-01),(3, ,2020-03-01）分别路由到2月份和3月份的分库，

谢谢解答，还有两个问题请教一下：1、怎么解释根据相同主键id查询多次返回结果不一致 2、select count(id),count(distinct id)返回结果相同的问题

**Comment by funnyAnt** [comment]
- 2、select count(id),count(distinct id)返回结果相同的问题，看执行计划，mycat是单库distinct聚合，并没用全局distinct。 mycat约束，distinct，count这类聚合函数，不能混用

- 1、怎么解释根据相同主键id查询多次返回结果不一致，贴下explain select * from warehouse where id=5的执行结果

**Comment by 007akuan** [comment]
> * 2、select count(id),count(distinct id)返回结果相同的问题，看执行计划，mycat是单库distinct聚合，并没用全局distinct。 mycat约束，distinct，count这类聚合函数，不能混用
> * 1、怎么解释根据相同主键id查询多次返回结果不一致，贴下explain select * from warehouse where id=5的执行结果

![image](https://user-images.githubusercontent.com/74766271/99952098-171ee600-2dba-11eb-9bcb-174e5f3cc2bd.png)
![image](https://user-images.githubusercontent.com/74766271/99952125-20a84e00-2dba-11eb-8b60-ef9e9366c23d.png)
![image](https://user-images.githubusercontent.com/74766271/99952173-3584e180-2dba-11eb-8d31-f095a3120a31.png)

**Comment by funnyAnt** [comment]
mysql> explain select * from warehouse where id = 5;
+-----------+--------------------------------------+
| DATA_NODE | SQL |
+-----------+--------------------------------------+
| dw6 | select * from warehouse where id = 5 |
+-----------+--------------------------------------+

直连dw6 这个mysql，执行 select * from warehouse where id = 5看下多少条记录数。

**Comment by 007akuan** [comment]
**<dataNode name="dw6" dataHost="mycat" database="dw06" />**


> mysql> explain select * from warehouse where id = 5;
> +-----------+--------------------------------------+
> | DATA_NODE | SQL |
> +-----------+--------------------------------------+
> | dw6 | select * from warehouse where id = 5 |
> +-----------+--------------------------------------+
> 
> 直连dw6 这个mysql，执行 select * from warehouse where id = 5看下多少条记录数。

mysql> use dw06;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+----------------+
| Tables_in_dw06 |
+----------------+
| warehouse      |
+----------------+
1 row in set (0.00 sec)

mysql> 
mysql> select * from warehouse;
+----+-------+------+---------------------+
| id | name  | pty  | createtime          |
+----+-------+------+---------------------+
|  5 | spark |   55 | 2020-05-01 00:00:00 |
| 11 | mongo |   60 | 2020-11-01 00:00:00 |
+----+-------+------+---------------------+
2 rows in set (0.00 sec)

**Comment by funnyAnt** [comment]
路由感觉有问题，因为没有用id字段分片，explain select * from warehouse where id = 5; 这个语句应该路由到所有分片，而不是dw06节点。 @junwen12221

**Comment by funnyAnt** [comment]
@007akuan  explain select * from warehouse where id = 5;  路由错误问题已经复现，这周修复。
#### 问题原因 
> 配置了primaryKey="id"，主键缓存引起的后续路由计算错误

#### 修复方法：

**Comment by 007akuan** [comment]
> @007akuan explain select * from warehouse where id = 5; 路由错误问题已经复现，这周修复。
> 
> #### 问题原因
> > 配置了primaryKey="id"，主键缓存引起的后续路由计算错误
> 
> #### 修复方法：

去掉primaryKey=“id”配置属性后
<table name="warehouse"  dataNode="dw$1-13" rule="sharding-by-month" />
<dataNode name="dw1" dataHost="mycat" database="dw01" />
<dataNode name="dw2" dataHost="mycat" database="dw02" />
<dataNode name="dw3" dataHost="mycat" database="dw03" />
<dataNode name="dw4" dataHost="mycat" database="dw04" />
<dataNode name="dw5" dataHost="mycat" database="dw05" />
<dataNode name="dw6" dataHost="mycat" database="dw06" />
<dataNode name="dw7" dataHost="mycat" database="dw01" />
<dataNode name="dw8" dataHost="mycat" database="dw02" />
<dataNode name="dw9" dataHost="mycat" database="dw03" />
<dataNode name="dw10" dataHost="mycat" database="dw04" />
<dataNode name="dw11" dataHost="mycat" database="dw05" />
<dataNode name="dw12" dataHost="mycat" database="dw06" />
<dataNode name="dw13" dataHost="mycat" database="dw01" />

重启Mycat服务
结果还是不正确：

mysql> select * from warehouse where id = 5;
+----+-------+------+---------------------+
| id | name  | pty  | createtime          |
+----+-------+------+---------------------+
|  5 | spark |   55 | 2020-05-01 00:00:00 |
|  5 | spark |   55 | 2020-05-01 00:00:00 |
+----+-------+------+---------------------+
2 rows in set (0.04 sec)

mysql> explain select * from warehouse where id = 5;
+-----------+------------------------------------------------+
| DATA_NODE | SQL                                            |
+-----------+------------------------------------------------+
| dw1       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw10      | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw11      | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw12      | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw13      | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw2       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw3       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw4       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw5       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw6       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw7       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw8       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
| dw9       | SELECT * FROM warehouse WHERE id = 5 LIMIT 100 |
+-----------+------------------------------------------------+
13 rows in set (0.00 sec)

登录节点查询结果为：
mysql> use dw01;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+----------------+
| Tables_in_dw01 |
+----------------+
| warehouse      |
+----------------+
1 row in set (0.00 sec)

mysql> select * from warehouse;
+----+--------+------+---------------------+
| id | name   | pty  | createtime          |
+----+--------+------+---------------------+
|  1 | java   |   46 | 2019-12-01 00:00:00 |
|  6 | hadoop |   58 | 2020-06-01 00:00:00 |
+----+--------+------+---------------------+
2 rows in set (0.00 sec)

mysql> use dw02;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from warehouse;
+----+-------+------+---------------------+
| id | name  | pty  | createtime          |
+----+-------+------+---------------------+
|  2 | c#    |   40 | 2020-01-01 00:00:00 |
|  7 | mysql |   60 | 2020-07-01 00:00:00 |
+----+-------+------+---------------------+
2 rows in set (0.00 sec)

mysql> use dw03;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from warehouse;
+----+--------+------+---------------------+
| id | name   | pty  | createtime          |
+----+--------+------+---------------------+
|  3 | python |   49 | 2020-02-01 00:00:00 |
|  8 | pg     |   60 | 2020-08-01 00:00:00 |
+----+--------+------+---------------------+
2 rows in set (0.00 sec)

mysql> use dw04;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from warehouse;
+----+-----------+------+---------------------+
| id | name      | pty  | createtime          |
+----+-----------+------+---------------------+
|  3 | golang    |   51 | 2020-03-01 00:00:00 |
|  9 | sqlserver |   60 | 2020-09-01 00:00:00 |
+----+-----------+------+---------------------+
2 rows in set (0.00 sec)

mysql> use dw05;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from warehouse;
+----+------+------+---------------------+
| id | name | pty  | createtime          |
+----+------+------+---------------------+
|  4 | ruby |   53 | 2020-04-01 00:00:00 |
| 10 | tidb |   60 | 2020-10-01 00:00:00 |
+----+------+------+---------------------+
2 rows in set (0.00 sec)

mysql> use dw06;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from warehouse;
+----+-------+------+---------------------+
| id | name  | pty  | createtime          |
+----+-------+------+---------------------+
|  5 | spark |   55 | 2020-05-01 00:00:00 |
| 11 | mongo |   60 | 2020-11-01 00:00:00 |
+----+-------+------+---------------------+
2 rows in set (0.00 sec)

**Comment by funnyAnt** [comment]
你想说明select * from warehouse where id = 5; 物理库只有1条，但是mycat查询出来2条吗？

你仅仅查询了6个物理库的数据，另外7个物理库都没有看，不能说明物理库就1条记录。

**Comment by 007akuan** [comment]
> 你想说明select * from warehouse where id = 5; 物理库只有1条，但是mycat查询出来2条吗？
> 
> 你仅仅查询了6个物理库的数据，另外7个物理库都没有看，不能说明物理库就1条记录。 @007akuan

13个节点，6个物理库，是这样吗？另外7个物理库是指什么?

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| dw01               |
| dw02               |
| dw03               |
| dw04               |
| dw05               |
| dw06               |
| grace              |
| innodb             |
| kevin              |
| mycattest          |
| mydatabase         |
| mysql              |
| performance_schema |
| sys                |
| test               |
| test01             |
+--------------------+

**Comment by funnyAnt** [comment]
![20201126103022457](https://user-images.githubusercontent.com/73138/100301116-70616200-2fd2-11eb-95ba-a00ac7b115b8.png)
你配置了13个节点，1个物理库被配置到2个逻辑节点上面。 物理库上面有1条记录，对应逻辑库就是2条记录，当然会有你说的重复记录了。 @007akuan

**Comment by 007akuan** [comment]
> ![20201126103022457](https://user-images.githubusercontent.com/73138/100301116-70616200-2fd2-11eb-95ba-a00ac7b115b8.png)
> 你配置了13个节点，1个物理库被配置到2个逻辑节点上面。 物理库上面有1条记录，对应逻辑库就是2条记录，当然会有你说的重复记录了。 @007akuan

好的，谢谢耐心的解答！

**Comment by yanjingfan** [comment]
查询出来有重复数据，也有可能是没有默认排序字段。
