### ISSUE TITLE
使用navicat批量插入数据,分片错乱且数据丢失

### ISSUE THREAD

**Issue by jxtp051811** [MyCATApache/Mycat-Server#2662]
1.mycat 版本:1.6-RELEASE
2.使用navicat导入 456192条数据.autocommit = false,批量提交
![image](https://user-images.githubusercontent.com/35753265/99949963-d5d90700-2db6-11eb-9072-ca260abde297.png)
3.分片规则如下:枚举分片
<mycat:rule xmlns:mycat="http://io.mycat/">
        <tableRule name="fiscal-year-rule">
                <rule>
                        <columns>fiscal_year</columns>
                        <algorithm>fiscal-year-long</algorithm>
                </rule>
        </tableRule>

        <function name="fiscal-year-long" class="io.mycat.route.function.PartitionByFileMap">
                <property name="mapFile">fiscal-year-long.txt</property>
        </function>
</mycat:rule>

fiscal-year-long.txt内容如下:
2019=0
2020=0
2021=0
2022=1
2023=1

schema部分内容:
<table name="表名" primaryKey="ID" rule="fiscal-year-rule" dataNode="dn1,dn2"/>

  <dataNode name="dn1" dataHost="localhost1" database="数据库名" />
   <dataNode name="dn2" dataHost="localhost2" database="数据库名" />

 <dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
                          writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                
                <writeHost host="hostM1" url="jdbc:mysql://XXXXXX:3306/XXXXXX?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true" user="XXXXXX"
                                   password="XXXXXX">
                </writeHost>
        </dataHost>
        <dataHost name="localhost2" maxCon="1000" minCon="10" balance="0"
                          writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                
                <writeHost host="hostM1" url="jdbc:mysql://XXXXXX:3306/XXXXXX?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true" user="XXXXXX"
                                   password="XXXXXX">

批量导入后:
mycat 查询 SELECT count(1) FROM 表名; 总数为 456088
A分片
fiscal_year | count(1)
-- | --
2019 | 79787
2020 | 114048
2021 | 102538
2022 | 12589
B分片
fiscal_year | count(1)
-- | --
2019 | 893
2021 | 11510
2022 | 101459
2023 | 33264

问题1:数据丢失 预期 456192 实际:456088
问题2:没有按照fiscal_year字段严格 分片

**Comment by jxtp051811** [comment]
schema.xml
```xml
<table name="XXXXXX" primaryKey="ID" rule="fiscal-year-rule" dataNode="dn1,dn2"/>

        <dataNode name="dn1" dataHost="localhost1" database="XXXXX" />
        <dataNode name="dn2" dataHost="localhost2" database="XXXXX" />
        
        <dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
                          writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <!-- can have multi write hosts -->
                <writeHost host="hostM1" url="jdbc:mysql://XXXXX:3306/ifrs17_per_biz?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true" user="XXXXX"
                                   password="XXXXX">
                </writeHost>
        </dataHost>
        <dataHost name="localhost2" maxCon="1000" minCon="10" balance="0"
                          writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM1" url="jdbc:mysql://XXXXX:3306/ifrs17_per_biz?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true" user="XXXXX" password="XXXXX">
                </writeHost>
```

**Comment by junwen12221** [comment]
@jxtp051811 可以测试一下最新版的mycat 1675/1676 有没有这个问题

**Comment by jxtp051811** [comment]
@junwen12221 1675/1676 这2个版本 是否正式发布？

**Comment by jxtp051811** [comment]
@junwen12221 更新为1.6.7.5版本，问题解决.3q~!
