### ISSUE TITLE
java.sql.SQLException: The statement is unsafe SQL, reject for user 'octer'

### ISSUE THREAD

**Issue by sunxq86** [MyCATApache/Mycat-Server#2666]
mycat版本：MavenVersion 1.6.7.1-release
为什么加了黑名单配置，mycat+mybatis连接的时候就会报错，只有把blacklist check="true"改为false才没问题，我本地用navicat连接就没问题，但用程序就报错呢？
java.sql.SQLException: The statement is unsafe SQL, reject for user 'octer'

配置为：
<firewall>
           <whitehost>
              <host host="192.168.0.*" user="octer"/>
              <host host="192.168.22.*" user="octer"/>
              <host host="127.0.0.1" user="octer"/>
           </whitehost>
       <blacklist check="true">
                <property name="truncateAllow">false</property>
                <property name="createTableAllow">false</property>
                <property name="alterTableAllow">false</property>
                <property name="dropTableAllow">false</property>
       </blacklist>
        </firewall>

        <user name="octer" defaultAccount="true">
                <property name="password">octer</property>
                <property name="schemas">TESTDB</property>

                
                
        </user>

**Comment by sunxq86** [comment]
` <firewall>
           <whitehost>
              <host host="192.168.0.*" user="octer"/>
              <host host="192.168.22.*" user="octer"/>
              <host host="127.0.0.1" user="octer"/>
           </whitehost>
       <blacklist check="false">
                <property name="truncateAllow">false</property>
                <property name="createTableAllow">false</property>
                <property name="alterTableAllow">false</property>
                <property name="dropTableAllow">false</property>
       </blacklist>
        </firewall>


        <user name="octer" defaultAccount="true">
                <property name="password">octer</property>
                <property name="schemas">TESTDB</property>

                
                
        </user>


        <user name="reader">
                <property name="password">reader</property>
                <property name="schemas">TESTDB</property>
                <property name="readOnly">true</property>
        </user>
`

**Comment by sunxq86** [comment]
《firewall》
           <whitehost>
              <host host="192.168.0.*" user="octer"/>
              <host host="192.168.22.*" user="octer"/>
              <host host="127.0.0.1" user="octer"/>
           </whitehost>
       <blacklist check="false">
                <property name="truncateAllow">false</property>
                <property name="createTableAllow">false</property>
                <property name="alterTableAllow">false</property>
                <property name="dropTableAllow">false</property>
       </blacklist>
        《/firewall》

**Comment by zwyqz** [comment]
对应的sql日志贴出来

**Comment by sunxq86** [comment]
配置文件详见：https://github.com/sunxq86/test/blob/master/123.png

SQL日志我要等开发给我才行

**Comment by funnyAnt** [comment]
无后续日志，关闭。
