### ISSUE TITLE
Queries on global table and shard table

### ISSUE THREAD

**Issue by coolboyPT** [MyCATApache/Mycat-Server#2668]
Hi guy !
 I'm new in MyCAT. I have a question:
Can I perform data queries from global tables and shard tables in the same query by MyCAT ?
For example:
I have database with 2 table t1 (a,b,c ) and t2(d,e,a). In which t1 is global table and t2 is sharding table by key d.
I want to:
SELECT * from t1 where a in ( SELECT a from t2 where d >5);
I tried, the error reported program and request modify schema.xml:  T1 as a sharding table, but I don't want to be like that.
Is there a way to solve?
Thank you, Sincerely.

**Comment by zwyqz** [comment]
SELECT * from t1 where a in ( SELECT a from t2 where d >5);
这样的sql需要分成两个sql分别进行查询

1.SELECT a from t2 where d >5   放入 list中
2.select * from t1 where a in ( list)

**Comment by coolboyPT** [comment]
谢谢
