### ISSUE TITLE
the max activeConnnections size can not be max than maxconnections

### ISSUE THREAD

**Issue by zhoufeilongjava** [MyCATApache/Mycat-Server#2669]
版本 Mycat-server-1.6.7.4-release

错误日志
`2020-12-04 14:07:00.077 ERROR [$_NIOREACTOR-17-RW] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - ServerConnection [id=27786, schema=emc_user, host=47.98.33.199, user=root,txIsolation=3, autocommit=true, schema=emc_user, executeSql=SELECT count(0) FROM point_list WHERE 1 = 1 AND client_id = 10910 AND dtime = 0]backend connect: java.io.IOException: the max activeConnnections size can not be max than maxconnectionsjava.lang.Thread .getStackTrace1559`

server.xml

` 
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mycat:server SYSTEM "server.dtd">
<mycat:server xmlns:mycat="http://io.mycat/">
	<system>
		<property name="nonePasswordLogin">0</property> 
		<property name="ignoreUnknownCommand">0</property>
		<property name="useHandshakeV10">1</property>
		<property name="removeGraveAccent">1</property>
		<property name="useSqlStat">0</property>  
		<property name="useGlobleTableCheck">0</property>  
		<property name="sqlExecuteTimeout">300</property>  
		<property name="sequnceHandlerType">1</property>
		
		
		<property name="sequnceHandlerPattern">(?:(\s*next\s+value\s+for\s*MYCATSEQ_(\w+))(,|\)|\s)*)+</property>
		<property name="subqueryRelationshipCheck">false</property> 
		<property name="sequenceHanlderClass">io.mycat.route.sequence.handler.HttpIncrSequenceHandler</property>
		 
		 
		
		
		
		<property name="processorBufferPoolType">0</property>
		
		
		
		
		
		

		<property name="serverPort">3306</property> <property name="managerPort">9066</property>
		<property name="idleTimeout">300000</property> <property name="bindIp">0.0.0.0</property>
		<property name="dataNodeIdleCheckPeriod">300000</property>
		<property name="frontWriteQueueSize">4096</property> <property name="processors">32</property>
		
		<property name="handleDistributedTransactions">0</property>

		
		<property name="useOffHeapForMerge">0</property>

		
		<property name="memoryPageSize">64k</property>

		
		<property name="spillsFileBufferSize">1k</property>

		<property name="useStreamOutput">0</property>

		
		<property name="systemReserveMemorySize">384m</property>

		
		<property name="useZKSwitch">false</property>

		
		

		
		
		
		<property name="strictTxIsolation">false</property>

		<property name="useZKSwitch">true</property>
		
		<property name="parallExecute">0</property>
	</system>

	
	
	
	
	
	
	
	

	<user name="root" defaultAccount="true">
		<property name="password">000000</property>
		<property name="schemas">user</property>
		<property name="defaultSchema">user</property>
		

		
		
	</user>

	
</mycat:server>
`

**Comment by junwen12221** [comment]
与schema.xml的连接数有关系

`<dataHost name="localhost1" maxCon="1000" minCon="10" `

**Comment by wf0206** [comment]
1. 

- 

- [ ] 

> ### 

- `[](url)`
