### ISSUE TITLE
Mycat 1.5路线图

### ISSUE THREAD

**Issue by apachemycat** [MyCATApache/Mycat-Server#267]
1.5 首先配置用ZK管理
MySQL智能优化
MySQL自动运维
Storm等实时流框架纳入解决大数据的SQL运算
Mycat内嵌负载均衡机制

**Comment by magicdoom** [comment]
扩容缩容数据自动迁移
XA完全支持

**Comment by songwie** [comment]
多表join要不要支持

**Comment by golangpkg** [comment]
管理界面，监控界面要优化下。

**Comment by runfriends** [comment]
使用JDK8

**Comment by stonelion** [comment]
使用JDK8,改善collections迭代。

**Comment by magicdoom** [comment]
如果没有用到jdk8的重要新特性的话，建议先不要jdk8

**Comment by dirihf** [comment]
1、支持自动产生xml配置文件，方便复杂生产环境部署，最好有个类似的gui工具能够实现所有的配置选项；
2、支持insert selec语法；
3、多表join个人觉得无需实现，关系dbmysql支持的都不大好；
4、简化扩容和迁移流程；
5、无需增加haproxy+keepalived即可实现mycat高可用；

**Comment by coderjiang2013** [comment]
如果没有用到jdk8的重要新特性的话，推荐jdk7， 个人认为 lambda 一定程度提高了代码的阅读成本。

**Comment by 408511471** [comment]
把xml文件存到数据里去！

**Comment by yuwentao** [comment]
Storm等实时流框架纳入解决大数据的SQL运算
这条为啥不用spark sql?

**Comment by apachemycat** [comment]
Spark实时流框架也算，但不是完整的Spark SQL，

**Comment by zzcclp** [comment]
使用mycat作为前端，通过配置sparksql把sql路由到spark sql的cli，通过spark sql做大数据join，可否

**Comment by yuwentao** [comment]
那人家会问：为啥不直接用sparksql,而用你的mycat前端，多了一层，有什么好处。

**Comment by zzcclp** [comment]
作为统一的数据入口，对于开发者/DBA来说，就是连接写SQL，获取数据，不需要去关心是mycat连单机mysql，或者分片数据，或者是通过大数据join而来，这不是mycat作为中间件的一个好处吗？又不是只是单纯的使用mycat作为sparksql的前端，吃饱了撑着

**Comment by runfriends** [comment]
增强自动化运维

**Comment by root2000xyz** [comment]
关于MYCAT_SEQUENCE，很对情况下并不需要绝对的自增值，我们需要的只是有序不重复唯一的Long，推荐增加全局唯一ID生成支持，比较简单，使用twitter的算法，64位ID (42(毫秒)+5(机器ID)+5(业务编码)+12(重复累加)) ，相比UUID占用字节少，java实现类参考http://polim.iteye.com/blog/2005680，我在公司的DAL层已集成，结合Mycat使用10000取模分区，目前效果不错，生成唯一ID分布在了各个Mycat或者app上，不会出现读取文件自增或者数据库自增冲突问题。

**Comment by magicdoom** [comment]
Support both zookeeper and etcd

**Comment by songwie** [comment]
root2000xyz  要求的主键生成方式已经支持，代码在master

**Comment by root2000xyz** [comment]
@songwie  ，赞！

**Comment by curt001** [comment]
同样建议把配置的xml文件内容都写入到数据库中，细化权限控制

**Comment by apachemycat** [comment]
Mycat 1.5的规划功能，增加Elasticserach 搜索到 Mycat集群日志中 ，方便快速查找日志的错误问题 ，同时业务系统也可以把日志纳入，统一管理，便于快速定位分析问题
