### ISSUE TITLE
mycat 表水平分片的时候，如果其中某台分片主机挂掉了，就会报错

### ISSUE THREAD

**Issue by 0x33b** [MyCATApache/Mycat-Server#2671]
如题，对表进行水平分片的时候，如果其中有一台分片主机挂掉了，当下次写到这个片区的时候会报错，有没有某种方案可以在我这个分片主机挂掉之后不影响正常使用。

**Comment by zwyqz** [comment]
可以给节点配置读写分离.

**Comment by 0x33b** [comment]
是每个片区都要配置一个读写分离吗？我测试过，给每个节点都建了一个主主复制，当某个片区宕机的时候，备用主机会顶上来，但是那样的话配设备成本会很高。

**Comment by 0x33b** [comment]
> 可以给节点配置读写分离.

是每个片区都要配置一个读写分离吗？我测试过，给每个节点都建了一个主主复制，当某个片区宕机的时候，备用主机会顶上来，但是那样的话配设备成本会很高。

**Comment by zwyqz** [comment]
这样的话是好的 可以分担读压力

**Comment by funnyAnt** [comment]
@0x33b 现在大家都用普通的X86，因为过保或者电源网络的原因，虚机或者物理机挂掉是很正常的现象，需要做好mysql灾备。
1、磁盘采用raid10，多备份一份数据安全保障。
2、mysql做好主从架构，master挂掉不可修复后，slave切换成master顶上。master和slave要部署在不同的网络分区或机架。
3、定期做好mysql数据备份到oss存储，以防止机房级别故障。
4、如果mysql跑在虚机上面，要有一套快速弹出拉去的能力。mysql的master挂掉后并且slave也无法拉起，快速从oss拉起数据重新弹出。 待老的master修复后，还得用flashback功能，找出新旧master间的数据差异，人工决定是否redo还是undo。
