### ISSUE TITLE
mycat查询带参数，偶发参数丢失空指针异常

### ISSUE THREAD

**Issue by mingchengdada** [MyCATApache/Mycat-Server#2676]
**生产偶发问题，重新执行一遍确实正常的
mycat版本BuildTime 2016-10-28 12:47:06
GitVersion 460930b
MavenVersion 1.6-RELEASE
**
异常截图：
![cf5f8d203a4b16d15fe1185c365f2d9](https://user-images.githubusercontent.com/35555403/101477467-360ca300-398a-11eb-9731-b277b0865710.png)

**Comment by junwen12221** [comment]
贴mycat的日志,调整日志debug级别

**Comment by funnyAnt** [comment]
无进一步回复，关闭
