### ISSUE TITLE
MyCat 进行表水平分片时，已有的数据能不能自动分片

### ISSUE THREAD

**Issue by 0x33b** [MyCATApache/Mycat-Server#2677]
1.在使用的数据库因为数据量较大，准备使用mycat进行水平分表，mycat是否可以把之前已存在的数据按照规则分片呢？
2.在数据扩容的时候，新增的节点是否可以将之前的数据根据规则分摊过来？

**Comment by funnyAnt** [comment]
1、数据不会自动重分布，需要自己人工调整。比如导出所有的数据，然后重新通过mycat导入。

2、 选择分布规则很重要，建议超量分片，既能节省资源又能减少后面的数据搬移。 做法是开始的时候就设置好分片个数，比如开始仅仅需要dn1,dn2, 但是为了扩展设置成dn1,dn2,dn3,dn4，其中dn1,dn3在mysql1上，dn2,dn4在mysql2上面。 随着数据增大，mysql压力增大，可以把mysql1：dn3--->迁移到新的mysql3，同理迁移mysql2:dn4-->迁移到mysql4上面。

**Comment by 0x33b** [comment]
> 1、数据不会自动重分布，需要自己人工调整。比如导出所有的数据，然后重新通过mycat导入。
> 
> 2、 选择分布规则很重要，建议超量分片，既能节省资源又能减少后面的数据搬移。 做法是开始的时候就设置好分片个数，比如开始仅仅需要dn1,dn2, 但是为了扩展设置成dn1,dn2,dn3,dn4，其中dn1,dn3在mysql1上，dn2,dn4在mysql2上面。 随着数据增大，mysql压力增大，可以把mysql1：dn3--->迁移到新的mysql3，同理迁移mysql2:dn4-->迁移到mysql4上面。

好的，感谢解答
