### ISSUE TITLE
navicat 客户端卡死

### ISSUE THREAD

**Issue by mawenbin666** [MyCATApache/Mycat-Server#2681]
### 版本:
mycat-1.6.7.1-release-20200209222254

### 问题描述：
`navicat 客户端连接mycat的时候，如果客户端隔10分钟不操作，下次再运行这条SQL的时候就会卡住，有人遇到过吗？`
![image](https://user-images.githubusercontent.com/22042460/102036884-f0732e80-3dfe-11eb-9ced-b018831c970c.png)

**Comment by funnyAnt** [comment]
1、直接发你的SQL文本吧，图片被墙看不到。
2、能稳定复现吗，你的navicat版本号是小于等于10吗

**Comment by qiqsa** [comment]
1、可以通过stack查看mycat
2、可以用抓包工具抓下报文分析

**Comment by funnyAnt** [comment]
无进一步回复，关闭
