### ISSUE TITLE
错误: 找不到或无法加载主类 io.mycat.performance.TestSelectPerf

### ISSUE THREAD

**Issue by a8254692** [MyCATApache/Mycat-Server#2682]
有大佬遇到过执行测试脚本报这个的问题吗？百度搜不出关键词求解

**Comment by funnyAnt** [comment]
这个类在Mycat-server-1.6.*-release-tests.jar 这个包里面

**Comment by a8254692** [comment]
> 这个类在Mycat-server-1.6.*-release-tests.jar 这个包里面

谢谢大佬

**Comment by a8254692** [comment]
> 这个类在Mycat-server-1.6.*-release-tests.jar 这个包里面

大佬我看现在好像官方的下载里已经没有这个包了呀，能指个地址吗

**Comment by funnyAnt** [comment]
自己下载特定版本的源码，然后mvn install, 在target目录下面会有。 附上最新的1.6.7.6的包

[Mycat-server-1.6.7.6-release-tests.zip](https://github.com/MyCATApache/Mycat-Server/files/5693236/Mycat-server-1.6.7.6-release-tests.zip)

**Comment by a8254692** [comment]
> 自己下载特定版本的源码，然后mvn install, 在target目录下面会有。 附上最新的1.6.7.6的包
> 
> [Mycat-server-1.6.7.6-release-tests.zip](https://github.com/MyCATApache/Mycat-Server/files/5693236/Mycat-server-1.6.7.6-release-tests.zip)

好哒，谢谢大佬了

**Comment by a8254692** [comment]
> 自己下载特定版本的源码，然后mvn install, 在target目录下面会有。 附上最新的1.6.7.6的包
> 
> [Mycat-server-1.6.7.6-release-tests.zip](https://github.com/MyCATApache/Mycat-Server/files/5693236/Mycat-server-1.6.7.6-release-tests.zip)

大佬太爱你了~
