### ISSUE TITLE
MyCAT自动配置writeHost和readHost

### ISSUE THREAD

**Issue by LiTeng51** [MyCATApache/Mycat-Server#2685]
MyCAT能否根据多节点（3节点以上）的主从切换（MHA），来自动配置writeHost和readHost。

**Comment by junwen12221** [comment]
不能

**Comment by LiTeng51** [comment]
> 不能

MyCAT可以获取到后端节点的主从状态吗？

**Comment by junwen12221** [comment]
定时器检查主从延迟

**Comment by LiTeng51** [comment]
> 定时器检查主从延迟

MyCAT可以获取到后端数据库是主库库还是从库吗？
MyCAT怎么配置才能实现 writeHost是Master，readHost是Slave。

**Comment by iamif3000** [comment]
> > 定时器检查主从延迟
> 
> MyCAT可以获取到后端数据库是主库库还是从库吗？
> MyCAT怎么配置才能实现 writeHost是Master，readHost是Slave。

我觉得，可以考虑使用类似mha脚本的方式，去更新zookeeper配置。

**Comment by funnyAnt** [comment]
### 通用做法1：
##### 核心思想：
 mycat里面仅仅配置vip（读写VIP和只读VIP）,底层的mysql发生主从切换后，VIP是不变化的，mycat配置无需感知。但是，主从切换后，原来mycat里面的mysql会发生异常，引发mycat内部自动被动关闭连接。

##### 实施方法：
1、writehost 里面配置一个读写vip，对应master的vip
2、readhost里面配置一个只读vip，对应slave的vip

### 通用做法2：
自动服务发现（需要额外开发）：
#### 核心思想：
-  mysql底层维护集群信息（master-slave）到ZK或ETCD, 发生主从切换或者down掉时，自动更新ZK或ETCD
-  mycat里面仅仅配置集群id，通过该集群ID到ZK或ETCD查询到writeHos和readHost。ZK或ETCD数据变更时通知mycat。

@LiTeng51
