### ISSUE TITLE
用Workbench连不上Mycat  

### ISSUE THREAD

**Issue by stargazer1sdh** [MyCATApache/Mycat-Server#2687]
在linux上部署好Mycat-server-1.6.7.1-release-20190627191042-linux，从局域上的一台windows主机上尝试连接。直接敲命令 ： `mysql -uroot -proot -P8066 -h192.168.1.200 -p ` 可以连上去。但是用相同的用户名密码，Mysql自带的Workbench工具怎么也连不上：
![image](https://user-images.githubusercontent.com/24764272/102505709-483ebd80-40bd-11eb-8faa-a5d8ab371a97.png)

**Comment by stargazer1sdh** [comment]
[](url)
![image](https://user-images.githubusercontent.com/24764272/102505933-8d62ef80-40bd-11eb-8640-1615c29bf528.png)

**Comment by junwen12221** [comment]
之前测试过Workbench对报文字段比较严格.一般对mycat兼容性比较好的是sqlyog
