### ISSUE TITLE
分片使用PartitionByMod函数插入非int类型数据时报数组下标越界异常

### ISSUE THREAD

**Issue by iwhalecloud-platform** [MyCATApache/Mycat-Server#2689]
插入insert语句：  分片键为HASH_ID
```` 
insert into INROAM(HASH_ID,FILE_NM,CDR_ITEM,CALL_START_TM) values("00#454120414114526#20201019003159#200599330#CB8E7C60","IG20201019008.200",1,"20201019000000" );    
````
插入时报异常：ArrayIndexOutOfBoundsException

**Comment by iwhalecloud-platform** [comment]
问题现象：  
int类型的数值范围刚好是 -2^31——2^31-1,即-2147483648——2147483647  
报错insert语句中HASH_ID的值取其String.hashCode(),刚好为-2147483648，对其math.abs(-2147483648)结果依旧为负数，即计算hashCode后取绝对值时可能会发生位数溢出  
解决方案 ：  
因此使用math.abs(long)来求绝对值，然后使用long来接收字符串的hashCode()的值

**Comment by iwhalecloud-platform** [comment]
@funnyAnt

**Comment by funnyAnt** [comment]
感谢贡献，期待更多commit
