### ISSUE TITLE
[优化] load data语句支持set语法设置变量

### ISSUE THREAD

**Issue by iwhalecloud-platform** [MyCATApache/Mycat-Server#2691]
问题：  
比如分片表的情况下执行语句：  
LOAD DATA INFILE 'file.txt'
              INTO TABLE t1
              (column1, @var1,@var2)
             SET column2 = @var1/100,columns=100/(@var2/200));
load data过程中报错：java.lang.NullPointException  
方案：  
`load data infile使用set子句时将用户变量改成真实的列名`  

`上述最后真实的列应该是{column1,column2,columns}`

**Comment by funnyAnt** [comment]
@iwhalecloud-platform 年底又到了提交业绩的时候了吧，也搞点大功能提交下反馈下社区，制造点彩蛋给大家。
