### ISSUE TITLE
如下查询，无法根据分片识别具体节点，导致全库查询：

### ISSUE THREAD

**Issue by wamdy** [MyCATApache/Mycat-Server#2694]
如下查询，无法根据分片识别具体节点，导致全库查询：
**SELECT
	a,
	b,
	shard_id
FROM
	test
WHERE
	TRUE
-- AND shard_id = '012'
AND (
	a= '1'
	OR a= '2' 
) 
AND shard_id = '012'**
![image](https://user-images.githubusercontent.com/2725226/102879862-6de51180-4485-11eb-9781-4c1e17089713.png)

**Comment by zwyqz** [comment]
把true去掉看看路由结果

**Comment by funnyAnt** [comment]
`-- AND shard_id = '012'` 映像中druid解析器不支持注释，把这段注释去掉。

**Comment by wamdy** [comment]
> 把true去掉看看路由结果
无影响，分片条件shard_id=‘012’ 放在AND（ x=1 OR x=2）后，就会导致这个问题

**Comment by wamdy** [comment]
> `-- AND shard_id = '012'` 映像中druid解析器不支持注释，把这段注释去掉。

不是，这段无影响

**Comment by funnyAnt** [comment]
##### 问题已确认，系带or的子句解析问题，
![QQ图片20201226175345](https://user-images.githubusercontent.com/73138/103149321-5b2f4d00-47a3-11eb-9d66-978dadbb26e1.png)

#### 原因：
（name=1 or name=2） and id=2 语句，解析whereUnit的时候会把id=2丢掉。

**Comment by funnyAnt** [comment]
@wamdy  已经修复

**Comment by wamdy** [comment]
666
