### ISSUE TITLE
win10+mysql+mycat :java.lang.IllegalArgumentException: Invalid DataSource:1

### ISSUE THREAD

**Issue by xwyzsn** [MyCATApache/Mycat-Server#2696]
# win10+mysql+mycat 错误3009:java.lang.IllegalArgumentException: Invalid DataSource:1
# 版本信息:
** mycat:1.4   mysql:8.0.22 **
#  描述
我在win10单机上使用mysql+mycat想尝试学习分片,在配置好文件之后使用sqlyog连接到8066端口,可以看到TESTDB数据库,但是进行相应得操作就会出现上述错误。
schema.xml文件配置如下
<?xml version="1.0"?>

<!DOCTYPE mycat:schema SYSTEM "schema.dtd">

<mycat:schema xmlns:mycat="http://org.opencloudb/">

	<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100">

		<table name="table_comment" primaryKey="ID" dataNode="dn1,dn2,dn3" rule="auto-sharding-long" />

	</schema>

	<dataNode name="dn1" dataHost="root" database="db1" />

	<dataNode name="dn2" dataHost="root" database="db2" />

	<dataNode name="dn3" dataHost="root" database="db3" />

	<dataHost name="root" maxCon="1000" minCon="10" balance="0"

		writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">

		<heartbeat>select user()</heartbeat>

		

		<writeHost host="hostM1" url="localhost:3306" user="root"

			password="">

		</writeHost>

		<writeHost host="hostS1" url="localhost:3316" user="root"

			password="" />

	</dataHost>

</mycat:schema>

server.xml配置如下

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mycat:server SYSTEM "server.dtd">

<mycat:server xmlns:mycat="http://org.opencloudb/">

	<system>

	<property name="defaultSqlParser">druidparser</property>

	</system>

	<user name="root">

		<property name="password"></property>

		<property name="schemas">TESTDB</property>

	</user>

	<user name="user">

		<property name="password">user</property>

		<property name="schemas">TESTDB</property>

		<property name="readOnly">true</property>

	</user>

</mycat:server>

rule.xml是原来得没有改过;
在Google上找了好久,没有类似得错误出现过,有人告知一下吗?

**Comment by funnyAnt** [comment]
初步看是mycat连接后端的mysql有问题，确认下localhost:3306，localhost:3316都能连接上吗，启动mycat的时候没有报错？

**Comment by zwyqz** [comment]
mysql:8.0.22 需要  改一下mysql设置,把授权改成mysql_native_password,可能要更换用户或者重起才生效 ,可以找下issue

**Comment by xwyzsn** [comment]
> mysql:8.0.22 需要 改一下mysql设置,把授权改成mysql_native_password,可能要更换用户或者重起才生效 ,可以找下issue

谢谢您得帮助,将授权改了之后确实能够连接上了。

**Comment by xwyzsn** [comment]
> 初步看是mycat连接后端的mysql有问题，确认下localhost:3306，localhost:3316都能连接上吗，启动mycat的时候没有报错？

检查了两个端口，重新改了授权重启了mysql解决了问题，谢谢您得帮助。
