### ISSUE TITLE
mycat server 关闭不掉

### ISSUE THREAD

**Issue by jiangbinbin-code** [MyCATApache/Mycat-Server#2701]
一直显示  Waiting for Mycat-server to exit。。。好久了

**Comment by funnyAnt** [comment]
@jiangbinbin-code  通过什么命令关闭的，详细错误日志截图下

**Comment by jiangbinbin-code** [comment]
./mycat stop 关闭&nbsp; &nbsp;起因是因为昨天晚上使用python插入数据，然后今早发现python连接到mycat已经断了，被拒绝。今天用sqlyog也进入不了mycat。mysql -uroot =p -h xxx.xxx.xx.xx -P 8806也进不去mycat，但是mycat一直显示运行状态，然后 就打算关闭重启。 ./mycat stop&nbsp; 然后就一直打印&nbsp;Waiting for Mycat-server to exit。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "momo"<notifications@github.com&gt;; 
发送时间: 2020年12月28日(星期一) 中午11:51
收件人: "MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;; 
抄送: "蓝猫"<712041476@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MyCATApache/Mycat-Server] mycat server 关闭不掉 (#2701)





 
@jiangbinbin-code  通过什么命令关闭的，详细错误日志截图下

**Comment by jiangbinbin-code** [comment]
最后也没关掉。ctrl+c 退出命令了。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat-Server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 中午11:51
收件人:&nbsp;"MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;;
抄送:&nbsp;"蓝猫"<712041476@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] mycat server 关闭不掉 (#2701)





 
@jiangbinbin-code  通过什么命令关闭的，详细错误日志截图下

**Comment by jiangbinbin-code** [comment]
1.mycat.log日志
2.python执行报错，共两个python代码 连接mycat 一个代码执行一段时间后被拒绝，一个代码直接被拒绝连接



3.这是sqlyog客户端那个
   
强行退出之后 mycat状态现在还是显示运行

**Comment by funnyAnt** [comment]
这里面有2个进程，一个是wrapper的守护进程，一个是mycat自身，怀疑mycat已经挂了，但是守护进程依然存在。
<img width="363" alt="无标题" src="https://user-images.githubusercontent.com/73138/103226229-9e85e900-4966-11eb-9dce-f9229c73704a.png">

下次遇到，还是ps -ef|grep mycat， 然后telnet ip 8066 看看Mycat自身的情况。
