### ISSUE TITLE
指定dataNode查询出现错误

### ISSUE THREAD

**Issue by montecristoo** [MyCATApache/Mycat-Server#2704]
版本1.6.7.4

`/*!mycat:dataNode=emc_user_26970 */

-- explain 
SELECT 
    from_unixtime(document_list.ctime),
    -- ,from_unixtime(document_goods.ctime),
    -- document_list.*,
    document_goods.*
  -- goods_list.*,
  -- goods_sku.*,
  -- 1  
FROM
    document_list
        left JOIN
    document_goods ON document_list.db_id = document_goods.db_Id
        AND document_list.id = document_goods.doc_id
        left JOIN
    goods_sku ON document_goods.db_id = goods_sku.db_Id
        AND document_goods.sku_id = goods_sku.id
        left join goods_list ON (goods_sku.db_id = goods_list.db_Id
        AND goods_sku.goods_id = goods_list.id)
        left join client_list on (client_list.db_id = goods_list.db_Id
        AND client_list.id = document_list.client_id)
        where 
        1=1
        -- and document_list.id=1017380
        and document_list.`type`=1
        and document_list.trans_id = 0
        and document_list.dtime =0 
        and document_list.db_id =  26970
        
        -- and document_goods.id=102492
        -- and goods_list.`disable` = 1 -- 根据商品状态筛选
        -- and document_list.db_id between 1 and 100
        -- and number = ''
        and document_list.ctime > unix_timestamp('2020-11-01')
        and document_list.ctime < unix_timestamp('2020-12-05')
        
		-- and quantity>shipped_quantity
		-- and client_id = 10013
        -- and mask_code='2ux02QZDGE'
        -- and document_list.id=1000081
        -- and document_goods.goods_id=408
        -- and document_list.client_id=10034
        -- and goods_list.supplier_id = 19912`

去掉 `-- explain ` 就可以查询出来

**Comment by funnyAnt** [comment]
![20210101114109450](https://user-images.githubusercontent.com/73138/103433117-4715a080-4c26-11eb-8ed8-ba8b9545116c.png)
@montecristoo 测试1676版本没有这个问题，请升级版本后验证。

**Comment by funnyAnt** [comment]
无进一步反馈，先关闭。
