### ISSUE TITLE
can not get column count java.lang.Exception: unsupport * in select items:select * from `user_purchase` where `id` = ? and `is_deleted` = ? limit 1

### ISSUE THREAD

**Issue by JesseGift** [MyCATApache/Mycat-Server#2705]
说明：使用的是mycat 的主从读写模式

**Comment by junwen12221** [comment]
给出Mycat版本

这个问题可能是某个版本的预处理语句在mycat里面不支持导致的(1676某个小版本),可以在客户端关闭服务器预处理看看.

**Comment by funnyAnt** [comment]
@JesseGift  mycat目前的所有版本都不支持prepare情况下面的select *这种语句，因为mycat本身没有存储表的元数据信息，于是 * 是无法在mycat内部替换成真实的字段，直接报错。 

#### 解决方法：
1、客户端关闭Prepare, 设置url里面的useServerPrepStmts=false
2、* 替换成真实的字段。
