### ISSUE TITLE
mycat分片后的表 join关联查询limit返回数据量错误

### ISSUE THREAD

**Issue by qczrzl** [MyCATApache/Mycat-Server#2706]
mycat版本：1.6.7.4-release
分表配置：
```
<schema name="sharding_test" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn6"> 
		<table name="device_message_point_data" subTables="device_message_point_data_$0-6" dataNode="dn6" rule="sharding-by-date">
		</table>
		<table name="device_message_alarm_data" dataNode="dn6"></table>
</schema>
```
查询sql：`select a.message_log_id, d.alarm_level from device_message_point_data a INNER JOIN device_message_alarm_data d on a.device_code=d.device_code LIMIT 40, 20;`
预期应该是20条数据，结果返回了60条； 单独对分片表limit查询返回结果正常，join关联查询后就出现问题
![image](https://user-images.githubusercontent.com/30763852/103337393-275f6a80-4ab6-11eb-948a-434fb80635fe.png)

**Comment by junwen12221** [comment]
用explain语句看看执行计划,单库分表join任意一个物理表应该是可以的.可以试试1676版本

**Comment by funnyAnt** [comment]
@qczrzl  1676版本验证过没有你说的问题。 请检查你的表device_message_alarm_data，device_code是不是有多条重复记录，看你的截图里面，一个记录重复出现了10次。

**Comment by qczrzl** [comment]
@funnyAnt @junwen12221 谢谢解答，版本升级到1.6.7.6后，没有这个问题了
