### ISSUE TITLE
mycat执行查询操作出现SQL结果返回卡死的情况

### ISSUE THREAD

**Issue by yinhuanyi** [MyCATApache/Mycat-Server#2708]
**1、bug描述** 
 MySQL分片使用的是PXC5.7版本，在Mycat执行SQL的时候，会出现概率性的卡死现象

**2、版本号(非常重要)**
 v 1.6.7-release

**3、相关表的配置信息**
  schema.xml (mysql的连接驱动是native方式)
  rule.xml (未使用路由函数)
  server.xml(无)

**4、操作步骤**
1：执行SQL操作

**5、期望结果**
 正常返回

**6、实际结果**
会概率性出现卡死

**7、额外信息**
mysql的连接驱动修改为JDBC后问题解决

**Comment by yinhuanyi** [comment]
使用新版本 Mycat-server-1.6.7.6-test，mysql的连接驱动是native方式，没有出现卡死问题。

**Comment by funnyAnt** [comment]
通过和 沟通发现，使用Mycat-server-1.6.7-release版本，native驱动的时候，出现 no handler报错，使用新版本1.6.7.6后解决。
`2021-01-02 23:31:23.162  WARN [$_NIOREACTOR-6-RW] (io.mycat.backend.mysql.nio.MySQLConnectionHandler.closeNoHandler(MySQLConnectionHandler.java:219)) - no handler bind in this con io.mycat.backend.mysql.nio.MySQLConnectionHandler@2c33dfba client:MySQLConnection@1090471269 [id=6, lastTime=1609601483160, user=root, schema=test, old shema=test, borrowed=false, fromSlaveDB=false, threadId=151, charset=utf8, txIsolation=2, autocommit=true, attachment=null, respHandler=null, host=192.168.100.231, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2021-01-02 23:31:23.162 ERROR [$_NIOREACTOR-3-RW] (io.mycat.backend.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:197)) - receive FieldEofPacket but no handler`
