### ISSUE TITLE
session会话长时间不操作，会出现【MySQL server has gone away】

### ISSUE THREAD

**Issue by yinhuanyi** [MyCATApache/Mycat-Server#2709]
**1、bug描述** 
 session会话长时间不操作，会出现如下提示：
MySQL server has gone away, No connection. 
Trying to reconnect...
Connection id:    1

**2、版本号(非常重要)**
 v 1.6.7-release

**3、相关表的配置信息**
  schema.xml (mysql的连接驱动是JDBC方式)
  rule.xml (无)
  server.xml(无)

**4、操作步骤**
1.  SQL操作

**Comment by funnyAnt** [comment]
参考： https://github.com/MyCATApache/Mycat-Server/wiki/%E5%BC%80%E5%8F%91%E7%AF%87%EF%BC%9A1.0-%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BF%9E%E6%8E%A5%E9%85%8D%E7%BD%AE， 配置下驱动和连接池参数。

**Comment by yinhuanyi** [comment]
好的
