### ISSUE TITLE
mycat 1671版本设置主键和unique key 依然插入重复数据

### ISSUE THREAD

**Issue by cheungfeifu** [MyCATApache/Mycat-Server#2715]
mycat 1671版本

schema.xml <table name="table" dataNode="node$1-10" rule="DEAL_DATE"/>

rule.xml

<tableRule name="DEAL_DATE">
<rule>
        <columns>DEAL_DATE</columns>
        <algorithm>mod-long</algorithm>
</rule>

show create table
PRIMARY KEY (`DR_TYPE`,`FILE_NAME`),
UNIQUE KEY `idx_u` (`DR_TYPE`,`FILE_NAME`)

根据主键和唯一约束 依然查的2条相同的数据，请问mycat的uniquekey 和主键的唯一约束作用只可以到单个节点吗？那在insert的时候不会做一次冲突的检查吗？

**Comment by cheungfeifu** [comment]
schema 文件 <table name="table" dataNode="node$1-10" rule="DEAL_DATE"/>

**Comment by funnyAnt** [comment]
uniquekey 和主键的唯一约束作用只可以到单个节点吗
        ---是的，唯一性由底层的单个数据库来保障。

**Comment by cheungfeifu** [comment]
哎 那这就麻烦了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "momo"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 下午4:33
收件人: "MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;; 
抄送: "张飞虎"<915401550@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MyCATApache/Mycat-Server] mycat 1671版本设置主键和unique key 依然插入重复数据 (#2715)





 
uniquekey 和主键的唯一约束作用只可以到单个节点吗
 ---是的，唯一性由底层的单个数据库来保障。

**Comment by funnyAnt** [comment]
为了保障唯一，可以用mycat自带的sequence功能，具体看使用手册。
