### ISSUE TITLE
reload @@config_all 报错 ERROR 1003 (HY000): Reload config failure （mycat 1671）

### ISSUE THREAD

**Issue by cheungfeifu** [MyCATApache/Mycat-Server#2718]
1.在schema中新增了datanode和schema reload @@config；成功
2.在server 中admin的
 <property name="schemas">data1,data2</property>
新增了2个schema 并执行  reload @@config_all就报错

**3.想询问在一个已经运行的mycat上新增逻辑库步骤是否为如下？：**

1.修改schema文件，增加datanode标签，该标签关联datahost
2.修改schema文件，增加schema标签，里面有table name标签
3.修改server文件，对admin用户增加如上新逻辑库的权限，或者新增用户，来查询新增的逻辑库
4.使用9066管理端口登录reload @@config_all；
5.使用9066管理端口登录，创建表，因为我在上一步就看到逻辑库已经创建了。

**Comment by funnyAnt** [comment]
-  reload @@config 仅仅重载逻辑库和表到内存
-  reload @@config_all 除了重载逻辑库和表， 还多了重载dataHost和dataNode到内存。  这步为什么失败，还需要看具体的mycat报错日志。

**Comment by cheungfeifu** [comment]
您好：
    请问是否有文档来解释如何新增逻辑库的步骤，因为我对于在schema文件中编辑完后，剩下的步骤不是很清楚。

**Comment by funnyAnt** [comment]
没有文档写这么详细的，大概步骤是：
1、修改schema.xml配置文件，添加逻辑表
2、执行reload @@config
3、把schema.xml里面所有的逻辑表元数据信息重载到内存

**Comment by cheungfeifu** [comment]
我有如下疑问：
1.修改schema.xml文件后，使用管理端口9066可以查看新增的database，但是无法use&nbsp;
2.使用8066端口无法查看新增的database
3.在server文件中的schema中新增如上新的database后 reload @@config_all 直接报错，reload @@config 则没有问题，我的schema文件没问题，server文件仅仅是在原来的基础上加了一个database信息，就无法reload @@config_all
<property name="schemas"&gt;js4,bs4,cbbs_rst4,cp4,jf4,psms_rst4,cp,balance,cbbs_cdr4,bs9,cp9</property&gt;
4.在schema文件中，创建逻辑库和逻辑表后，还需要手动去create database吗？假如需要 是在9066管理端口创建还是在8066数据端口创建？假如需要create table 则也是需要在9066端口创建？还是8066数据端口创建？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "momo"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 中午11:47
收件人: "MyCATApache/Mycat-Server"<Mycat-Server@noreply.github.com&gt;; 
抄送: "张飞虎"<915401550@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MyCATApache/Mycat-Server] reload @@config_all 报错 ERROR 1003 (HY000): Reload config failure （mycat 1671） (#2718)





 
没有文档写这么详细的，大概步骤是：
 1、修改schema.xml配置文件，添加逻辑表
 2、执行reload @@config
 3、把schema.xml里面所有的逻辑表元数据信息重载到内存

**Comment by funnyAnt** [comment]
1.修改schema.xml文件后，使用管理端口9066可以查看新增的database，但是无法use&nbsp;
    ---提供下能查看到database的命令

2.使用8066端口无法查看新增的database  
  ---正确现象
  
3.在server文件中的schema中新增如上新的database后 reload @@config_all 直接报错，reload @@config 则没有问题，我的schema文件没问题，server文件仅仅是在原来的基础上加了一个database信息，就无法reload @@config_all
<property name="schemas"&gt;js4,bs4,cbbs_rst4,cp4,jf4,psms_rst4,cp,balance,cbbs_cdr4,bs9,cp9</property&gt;
    ---提供下reload @@config_all报错的相关日志信息

4.在schema文件中，创建逻辑库和逻辑表后，还需要手动去create database吗？假如需要 是在9066管理端口创建还是在8066数据端口创建？假如需要create table 则也是需要在9066端口创建？还是8066数据端口创建？
    ---reload @@config/ reload @@config_all后，无需手工create database.  但是需要在8066端口，执行create table创建物理表，因为配置文件中仅仅是逻辑表，无物理表。

**Comment by cheungfeifu** [comment]
> 1.修改schema.xml文件后，使用管理端口9066可以查看新增的database，但是无法use 
> ---提供下能查看到database的命令
> **查看database命令 :show databases;**
> 2.使用8066端口无法查看新增的database
> ---正确现象
> 3.在server文件中的schema中新增如上新的database后 reload @@config_all 直接报错，reload @@config 则没有问题，我的schema文件没问题，server文件仅仅是在原来的基础上加了一个database信息，就无法reload @@config_all
> <property name="schemas">js4,bs4,cbbs_rst4,cp4,jf4,psms_rst4,cp,balance,cbbs_cdr4,bs9,cp9</property>
> ---提供下reload @@config_all报错的相关日志信息
> 日志如下：
**2021-01-13 14:16:20.767 DEBUG [BusinessExecutor32] (io.mycat.net.FrontendConnection.writeErrMessage(FrontendConnection.java:210)) - [thread=BusinessExecutor32,class=ManagerConnection,id=50093,host=10.248.51.144,port=9066,schema=null]Reload config failurejava.lang.Thread .getStackTrace1556
io.mycat.net.FrontendConnection .getStack227
io.mycat.net.FrontendConnection .writeErrMessage210
io.mycat.manager.response.ReloadConfig$ReloadCallBack .onFailure277
com.google.common.util.concurrent.Futures$6 .run1764
java.util.concurrent.ThreadPoolExecutor .runWorker1142
java.util.concurrent.ThreadPoolExecutor$Worker .run617
java.lang.Thread .run745
 write errorMsg:{} error**
> 4.在schema文件中，创建逻辑库和逻辑表后，还需要手动去create database吗？假如需要 是在9066管理端口创建还是在8066数据端口创建？假如需要create table 则也是需要在9066端口创建？还是8066数据端口创建？
> ---reload @@config/ reload @@config_all后，无需手工create database. 但是需要在8066端口，执行create table创建物理表，因为配置文件中仅仅是逻辑表，无物理表。

**Comment by funnyAnt** [comment]
@cheungfeifu  有没有更详细的日志，上面的日志看不出来哪里有问题

**Comment by cheungfeifu** [comment]
> @cheungfeifu 有没有更详细的日志，上面的日志看不出来哪里有问题

不需要了，这个事情已经处理了，建议在文档或者其他地方写一下生产环境使用mycat的一些信息

**Comment by a394023466** [comment]
![image](https://user-images.githubusercontent.com/39642052/121457496-54effe80-c9da-11eb-8939-d4ecfd210933.png)
When you run Reload @@configo_all, you will retest the connection of the DataNode. If one of the DataNodes fails to connect, an exception will be thrown

**Comment by yueMaa** [comment]
@cheungfeifu 麻烦问下这个1003的错误最后是如何解决的？

**Comment by cheungfeifu** [comment]
> @cheungfeifu 麻烦问下这个1003的错误最后是如何解决的？

重启mycat
