### ISSUE TITLE
dataHost的mincon和maxcon配置下放到writeHost和readHost配置

### ISSUE THREAD

**Issue by AdomXiong** [MyCATApache/Mycat-Server#2720]
**问题描述**
目前碰到有场景在读写分离下，需要writeHost和readHost单独配置minCon和maxCon参数，目前只有权重配置。

**描述您想要的结果及解决方案**
希望把minCon和maxCon参数下放到writeHost和readHost，同时dataHost的minCon和maxCon依然保留。在writeHost和readHost没有配置minCon和maxCon就继承dataHost配置，如果有配置就使用单独配置的参数。

**额外内容**

**Comment by funnyAnt** [comment]
@AdomXiong  要不你自己修改下源码，提供个PR。

**Comment by junwen12221** [comment]
记得商业的分库分表服务只有权重配置
