### ISSUE TITLE
测试发现count(distinct 字段)  与distinct 字段结果不一致

### ISSUE THREAD

**Issue by MyGarfield** [MyCATApache/Mycat-Server#2723]
**问题描述**

**描述您想要的结果及解决方案**

**额外内容**

**Comment by junwen12221** [comment]
不支持count(distinct

**Comment by MyGarfield** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        请教一下，如果对这个字段去重统计，mycat应该怎么写？
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                shenzzhuang
                            
                    
                        
                            
                                    shenzzhuang@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年1月19日 16:14，lightfish<notifications@github.com> 写道： 




不支持count(distinct



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zwyqz** [comment]
用mycat执行distinct 然后web总自己进行count操作

**Comment by MyGarfield** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    非常感谢您的回答，祝您生活愉快。
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                shenzzhuang
                            
                    
                        
                            
                                    shenzzhuang@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年1月19日 20:10，zwyqz<notifications@github.com> 写道： 




用mycat执行distinct 然后web总自己进行count操作



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
