### ISSUE TITLE
mycat like语法问题

### ISSUE THREAD

**Issue by AdomXiong** [MyCATApache/Mycat-Server#2730]
**1、bug描述** 
 mycat中存在show tables like 语法匹配值必须带%的bug，与mysql和mariadb的语法不兼容。

**2、版本号(非常重要)**
 v 1.6.7.4

**3、相关表的配置信息**
驱动方式native

**4、操作步骤**
show tables like 'test';

**5、期望结果**
+-----------------------+
| Tables_in_data (test) |
+-----------------------+
| test                  |
+-----------------------+

**6、实际结果**
ERROR 1064 (HY000): not found table : test in schema CLOUD

**7、额外信息**

**Comment by funnyAnt** [comment]
@AdomXiong 用最新的版本v 1.6.7.6测试下，我这边测试没有出现你说的问题。

**Comment by funnyAnt** [comment]
无进一步回复，关闭
