### ISSUE TITLE
可以直接从1.6-RELEASE升级到1.6.7.1-RELEASE版本吗

### ISSUE THREAD

**Issue by TChange** [MyCATApache/Mycat-Server#2741]
从1.6-RELEASE升级到1.6.7.1-RELEASE版本有哪些需要注意的地方？配置是否有需要调整的地方

**Comment by funnyAnt** [comment]
- 配置不需要改变，请注意看中间版本的changelog，防止新特性对原来的功能有影响。
-  做好功能回归测试。
