### ISSUE TITLE
mycat 导出数据cpu 一直100%

### ISSUE THREAD

**Issue by huyang19881115** [MyCATApache/Mycat-Server#2742]
**描述你使用过程中遇到的问题: **
导出数据mycat cpu一直100%，无法导出数据，服务是120G 内存，5T 硬盘，就安装了mycat，mysql,不知道如何调优 让数据可以导出，数据是按月分区，一个月数据20W 条左右。

**Comment by junwen12221** [comment]
请给出mycat版本

**Comment by huyang19881115** [comment]
mycat 是1.6.7 版本的~
 
发件人： lightfish
发送时间： 2021-02-26 13:19
收件人： MyCATApache/Mycat-Server
抄送： 胡洋; Author
主题： Re: [MyCATApache/Mycat-Server] mycat 导出数据cpu 一直100% (#2742)
请给出mycat版本
―

**Comment by junwen12221** [comment]
你把堆外合拼关闭看看

**Comment by funnyAnt** [comment]
@huyang19881115  看看机器CPU是几核的。 问题排查方法，dump 出线程堆栈，看看线程都忙于啥

**Comment by huyang19881115** [comment]
谢谢~我自己再研究下~~不过机器内存是够的，120G， CPU是16核的，数据量其实也不大，大几百万，就是按月分区的数据多一些，有2亿左右，我再研究下dump看线程处理的问题~


 
发件人： momo
发送时间： 2021-03-02 09:06
收件人： MyCATApache/Mycat-Server
抄送： 胡洋; Mention
主题： Re: [MyCATApache/Mycat-Server] mycat 导出数据cpu 一直100% (#2742)
@huyang19881115 看看机器CPU是几核的。 问题排查方法，dump 出线程堆栈，看看线程都忙于啥

**Comment by xiaoliu10** [comment]
应该是 Platform.copyMemery 这个方法吧 我这边也遇到cpu 时常异常爆满的情况， 定位到是这个方法， 我看之前有改过
![image](https://user-images.githubusercontent.com/28430309/155050329-99a753a6-4cbf-453b-b43c-dedfb5ff694b.png)
但是 是不是上面那个while 循环也要改一下？
