### ISSUE TITLE
2020年4月份Seata从1.2.0支持XA协议,Mycat支持XA分布式事务,是不是说明Seata和Mycat可以一起用？

### ISSUE THREAD

**Issue by ZongjieWu** [MyCATApache/Mycat-Server#2743]
**描述你使用过程中遇到的问题: **

**Comment by funnyAnt** [comment]
Seata从1.2.0支持XA协议
 --- 需要明确下它的XA协议是不是mysql的XA协议，还是自定义的私有协议。

一般情况下不建议使用XA，性能慢，出问题后数据回滚麻烦，异常场景多。请考虑好处于什么考虑使用XA。
