### ISSUE TITLE
使用ROUND 和SUM函数时,查询结果没有求和

### ISSUE THREAD

**Issue by zqmax** [MyCATApache/Mycat-Server#2747]
**1、bug描述** 
 使用ROUND 和SUM函数时,查询结果没有求和

**2、版本号(非常重要)**
 docker自动安装: longhronshens/mycat-docker   latest              f9a4ece7c742        3 years ago         793MB

**3、相关表的配置信息**
  schema.xml 配置
`	<schema name="OLMGSDB" checkSQLschema="true" sqlMaxLimit="100" dataNode="dn5">
		
		<table name="oil_info" dataNode="dn1,dn2,dn3,dn4,dn5" rule="sharding-by-date"/>

	</schema>

	<dataNode name="dn1" dataHost="dh1" database="olmgs" />
	<dataNode name="dn2" dataHost="dh2" database="olmgs" />
	<dataNode name="dn3" dataHost="dh3" database="olmgs_oil_info_1" />
	<dataNode name="dn4" dataHost="dh4" database="olmgs_oil_info_2" />
	<dataNode name="dn5" dataHost="dh5" database="olmgs" />

	<dataHost name="dh1" maxCon="1000" minCon="10" balance="1"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="-1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="m1" url="172.17.0.1:3306" user="root" password="123456"/>
		
	</dataHost>
	<dataHost name="dh2" maxCon="1000" minCon="10" balance="1"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="-1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="m2" url="172.17.0.2:3306" user="root" password="123456"/>
		
	</dataHost>
	<dataHost name="dh3" maxCon="1000" minCon="10" balance="1"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="-1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="m3" url="172.17.0.1:3306" user="root" password="123456"/>
		
	</dataHost>
	<dataHost name="dh4" maxCon="1000" minCon="10" balance="1"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="-1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="m4" url="172.17.0.2:3306" user="root" password="123456"/>
		
	</dataHost>
	<dataHost name="dh5" maxCon="1000" minCon="10" balance="1"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="-1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		
		<writeHost host="m5" url="172.17.42.1:3306" user="root" password="root@tomsung"/>
		
	</dataHost>`

  rule.xml 
`
<tableRule name="sharding-by-date">
		<rule>
			<columns>time</columns>
			<algorithm>sharding-by-date</algorithm>
		</rule>
	</tableRule>
<function name="sharding-by-date" class="io.mycat.route.function.PartitionByDate">
		<property name="dateFormat">yyyy-MM-dd</property>
		<property name="sBeginDate">1999-01-01</property>
		<property name="sEndDate">1999-04-30</property>
		<property name="sPartionDay">24</property>
	</function>`
  server.xml(可选)

**4、操作步骤**
1.  '执行sql语句'
SELECT
	ROUND(
		SUM(
			cast(
			AES_DECRYPT( UNHEX( oil.oil_flow ), '解密字符串' ) AS DECIMAL ( 10, 2 )))) total_oil_volume,
	ROUND(
		SUM(
			cast(
				AES_DECRYPT( UNHEX( oil.unit_price ), '解密字符串' ) AS DECIMAL ( 10, 2 )) * cast(
			AES_DECRYPT( UNHEX( oil.oil_flow ), '解密字符串' ) AS DECIMAL ( 10, 2 )))) total_amount 
FROM
	oil_info oil
2.  '....'
3.  ...

**5、期望结果**
1行数据

**6、实际结果**
5行数据

**7、额外信息**
mysql数据库版本为5.7.23, 使用jdbc和navicat工具结果一样

**Comment by funnyAnt** [comment]
1.6 版本不支持多个聚合函数联合使用的，只能用1个。 更高要求请使用2.0版本。

**Comment by funnyAnt** [comment]
已知问题，暂时不考虑支持，请用2.0版本。 此单关闭。
