### ISSUE TITLE
提两个使用问题，有劳解答

### ISSUE THREAD

**Issue by a6one** [MyCATApache/Mycat-Server#2751]
**描述你使用过程中遇到的问题: **
问题一：DDL语句问题
   连接mycat的8066端口然后执行DDL的create table建表语句，是否会广播到所有的真实物理节点上去创建表？

问题二：mycat的schema.xml、rule.xml、server.xml配置文件是否可以动态配置？
    例如像create table xxx 创建表一样来创建配置文件中的配置信息

以上两个有问题希望有人解答，谢谢

**Comment by junwen12221** [comment]
1.明确配置的表是可以使用create table的分库表创建物理表
2.使用zk作为配置中心可以动态更新配置

**Comment by funnyAnt** [comment]
也可以不用zk配置中心，连接9066端口，执行reload @@config可以重载 schema.xml,rule.xml里面的配置到内存，server.xml里面的需要重启mycat才能生效。
