### ISSUE TITLE
navicat 不显示逻辑表

### ISSUE THREAD

**Issue by hebaodanroot** [MyCATApache/Mycat-Server#2753]
**1、bug描述** 
 简单清晰描述下bug现象.
使用navicat 连接mycat，只显示后端数据库的分表，不显示逻辑表。使用mysql 命令行却显示正常的逻辑表
**2、版本号(非常重要)**
 v 1.6.7.5

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)
![image](https://user-images.githubusercontent.com/45256479/111409718-78284c00-8712-11eb-8563-43498659576b.png)

  rule.xml (涉及到的路由函数)
  server.xml(可选)

**4、操作步骤**
1.  '...'
2.  '....'
3.  ...

**5、期望结果**
navicat显示正确的逻辑表

**6、实际结果**
navicat15只显示分表，navicat11显示逻辑表，但打不开表，提示不存在表

**Comment by funnyAnt** [comment]
元数据处理的问题，需要完善。近期支持。

**Comment by diwenzheng** [comment]
@funnyAnt 我通过navicat连接mycat 不显示 数据库博主 遇到和我一样的问题 1.6.7.6

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/111561043-c438c680-87ce-11eb-933b-a3c6493bfaa6.png)
![Uploading image.png…]()

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/111561085-db77b400-87ce-11eb-9b53-aead81523d5a.png)
 执行sql语句 是可以查询到 但是不显示数据库

**Comment by diwenzheng** [comment]
数据库 是13个 但是 只显示了一个 
![image](https://user-images.githubusercontent.com/60613511/111591046-e0099000-8801-11eb-8fcb-a280e702bc09.png)
nav 的版本是 12.1 麻烦帮忙看看 谢谢

**Comment by funnyAnt** [comment]
@diwenzheng 目前测试支持较好的是10.0 这个版本，请用这个版本试试

**Comment by diwenzheng** [comment]
> @diwenzheng 目前测试支持较好的是10.0 这个版本，请用这个版本试试

我的朋友 使用 windows 12 就可以看到所有的库 为什么 mac 环境 的mac 12 不行 ？
