### ISSUE TITLE
采用注解形式，sql中的limit报错

### ISSUE THREAD

**Issue by ctyctt** [MyCATApache/Mycat-Server#2758]
**1、bug描述** 
/*!mycat:sql = select 标识码 from tt WHERE 所属公司缩写 IN ('SHRQ002') */
select *
from tt  ORDER BY OBJECTID LIMIT 1,10

总是报limit附近语法错误
**2、版本号(非常重要)**
 v 1.6.7.3

3.数据库为sqlserver

**Comment by ctyctt** [comment]
自查下原因

**Comment by funnyAnt** [comment]
@ctyctt 报错信息发下 

另外，执行下explain /*!mycat:sql = select 标识码 from tt WHERE 所属公司缩写 IN ('SHRQ002') */
select * from tt ORDER BY OBJECTID LIMIT 1,10 看执行计划， 执行计划里面SQL到SQLSERVER里面执行是否报错

**Comment by ctyctt** [comment]
嗯，我知道了sqlserver不支持limit。采用注解就只能自己写分页了
