### ISSUE TITLE
咨询一下mycat的设置

### ISSUE THREAD

**Issue by diwenzheng** [MyCATApache/Mycat-Server#2760]
我使用的是垂直分库,并没有利用水平,考虑到50W+数据量的原因 没必要垂直分,所以我的配置 在针对逻辑数据库那里,并没有配里面的表,应该无影响吧? 还有一个就是 我没有标识表的主键,通过软件访问mycat,数据库里的每一个表都显示没有主键,但是选中设计表里又是有主键的,所以这个算我设置问题,还是bug？

**Comment by diwenzheng** [comment]
@magicdoom

**Comment by diwenzheng** [comment]
另外一个发现 mycat 针对apollo的查询 有一定的影响,即我在使用 apollo创建多个项目的时候,如果项目过多,会导致数据显示不全.但是用数据库节点,会显示全.
![image](https://user-images.githubusercontent.com/60613511/112084035-190b8100-8bc3-11eb-84d1-5ae7d1d847ec.png)  而且出现重复现象

**Comment by diwenzheng** [comment]
这是什么原因导致的?是否有人出现过这种问题

**Comment by diwenzheng** [comment]
这里的逻辑 就是单纯的分页查询.在进行分页查询的时候,出现问题

**Comment by diwenzheng** [comment]
mycat 针对 jpa 分页查询 有bug？

**Comment by diwenzheng** [comment]
版本是1.6.7.6

**Comment by diwenzheng** [comment]
![Uploading image.png…]()

**Comment by diwenzheng** [comment]
我利用主从关系的数据库 不知道为什么 任务修改操作都没有办法成功啊

**Comment by junwen12221** [comment]
mycat1.x没有完全实现show语句,可能会出错的

**Comment by diwenzheng** [comment]
> mycat1.x没有完全实现show语句,可能会出错的

现在有哪个版本能支持？这快的问题

**Comment by funnyAnt** [comment]
1、limit 1,10,这种分页，数据重复的问题。这个SQL语句里面需要加 order by ，形如order by id limit 1,10， 让结果有序的。没有order by，单个库数据出现的顺序是row_id顺序，如果涉及到多个库，顺序会多节点交叉。

2、垂直分库，把多个小表放到默认库下面，也就说分到到mycat schema上面的默认dataNode节点，这样这些表就不需要再一一配置，它们之间没有跨库查询，分布式事务问题，这样划分没有问题。

3、读不到主键问题，怀疑是读取元数据的SQL支持的不是太好，请改成debug模式，提供下读取主键时刻的日志。 或者提供读取主键的样例代码，近期提供。
