### ISSUE TITLE
mycat 不支持 mysqldump吗

### ISSUE THREAD

**Issue by diwenzheng** [MyCATApache/Mycat-Server#2761]

**Comment by diwenzheng** [comment]
我在服务内部原生使用 mysqldump 备份数据库到远程,但通过mycat 报错

**Comment by diwenzheng** [comment]
在问一个问题,当主的数据库挂了,切换到下一个节点后,主的恢复了 还会切回来吗

**Comment by zwyqz** [comment]
> 不会的

**Comment by diwenzheng** [comment]
> > 不会的

那要怎么办啊？ 我这个业务必须来回切换的 不能设置权重?

**Comment by diwenzheng** [comment]
确实 我以为可以的 刚我通过关闭主 然后之后查看后端连接状态确实一直成备了 这时候该怎么办

**Comment by diwenzheng** [comment]
有没有办法 通过java 访问 mycat 9066端口 获取到数据啊

**Comment by diwenzheng** [comment]
jdbc 访问mycat 9066 并使用 show @@datasource 没用啊

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/112416887-81906480-8d61-11eb-9977-9594e47e3a72.png)

![image](https://user-images.githubusercontent.com/60613511/112416874-7b01ed00-8d61-11eb-8dd3-897d908d1486.png)


麻烦能不能提供一下帮助 这就是jdbc 访问 执行 show @@datasource 的结果

**Comment by funnyAnt** [comment]
1、mysqldump  mycat 报错，详细报错信息提供下
2、show @@datasource，
  - 先用mysql -h -P9066 -u -p这种方式登录上去，然后执行show @@datasource，看是否报错
  - 如果不报错，把prepare语句改成非prepare语句试试。

**Comment by diwenzheng** [comment]
> 1、mysqldump mycat 报错，详细报错信息提供下
> 2、show @@Datasource，
> 
> * 先用mysql -h -P9066 -u -p这种方式登录上去，然后执行show @@Datasource，看是否报错
> * 如果不报错，把prepare语句改成非prepare语句试试。

thanks 我咨询了很多人 最终确定问题是 因为 mysql-connector 驱动版本的问题 我们项目用的8所以 不支持 show语句
