### ISSUE TITLE
请问用两台配置完全一样的mycat做双活，不用zookeeper搭建集群是否可行？

### ISSUE THREAD

**Issue by happywzy** [MyCATApache/Mycat-Server#2767]
类似于下面这个架构
![image](https://user-images.githubusercontent.com/26290710/114004329-21d1a780-9891-11eb-9115-058b5c2e7975.png)

PS：使用zookeeper那套太麻烦，还得搭建一套zookeeper集群。

**Comment by junwen12221** [comment]
可以,测试一下其中一个mysql挂得情况
