### ISSUE TITLE
Mycat-server-1675-release 包，shell脚本换行符使用CRLF，导致执行出错

### ISSUE THREAD

**Issue by Vastxiao** [MyCATApache/Mycat-Server#2769]
**1、bug描述** 
 简单清晰描述下bug现象.
![image](https://user-images.githubusercontent.com/26339656/114806009-99925b80-9dd6-11eb-888d-1f608469760e.png)

![image](https://user-images.githubusercontent.com/26339656/114806216-f4c44e00-9dd6-11eb-85e2-75d393d7f751.png)

**2、版本号(非常重要)**
 v 1.6.7.5

请打包时更换 sh 脚本换行符为 LF 格式。

**Comment by funnyAnt** [comment]
@Vastxiao  提个pr，更改下init_zk_data.sh文件。 
文件目录：https://github.com/MyCATApache/Mycat-Server/tree/https/github.com/MyCATApache/Mycat-Server/tree/Mycat-server-1.6.76-test/src/main/assembly/bin

**Comment by Vastxiao** [comment]
检查了 1.6.76分支的这个路径的文件，已经修复了这个错误
