### ISSUE TITLE
mycat-server出现异常的时候，客户端就会等待，卡死。

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#279]
分析原因是由于客户端没有拿到服务器的响应包，一直处于等待状态。是否能够加一个统一的处理，如果出现异常，回应客户端一个error响应。不应该不给客户端任何提示。

**Comment by magicdoom** [comment]
master的代码里DataMergeService和jdbc这块我已经做过异常处理，会返回错误包，客户端会自动断开连接。其他可能还有遗漏，如果发现，请把日志错误信息发上来。
