### ISSUE TITLE
源码编译问题

### ISSUE THREAD

**Issue by Peterppan** [MyCATApache/Mycat-Server#2791]
**描述你使用过程中遇到的问题: **
druid 包中的 visitor.getAliasMap() 方法找不到，pom文件写的是1.3的版本，我降级到1.0.18解决。
不过还有DefaultDruidParser.java 文件下 ctx.addTables(visitor.getTables()); 此方法找不到，只有一个两个参数的方法，请问这个怎么解决？

**Comment by funnyAnt** [comment]
把你本机的druid相关老包删除掉，下载最新的包； 下载最新的分支代码，参考https://github.com/MyCATApache/Mycat-Server/issues/2778

**Comment by Peterppan** [comment]
我这边一开始是在Mycat-server-1.6.76-test，换了druid 1.2.6也还是有问题。
现在切换到1.6分支之后，可以了，感谢回答。

**Comment by funnyAnt** [comment]
@Peterppan  漏传文件，刚刚已经补上，参考#2778
