### ISSUE TITLE
mycat Communications link failure

### ISSUE THREAD

**Issue by LayJustDoIt** [MyCATApache/Mycat-Server#2800]
**描述你使用过程中遇到的问题: **
mycat启动后立即访问一个后台接口报连接超时，要是等十几秒在访问接口的话一般不会报错， 不稳定。请问怎么做才能一启动完mycat立即访问接口不报这个连接超时的错。
![image](https://user-images.githubusercontent.com/29298951/120831370-0bdf1b00-c592-11eb-8f7e-382248c257a9.png)
Mycat版本：1.6.7.5
MySQL：5.7
MySQL中的my.cnf超时时间：wait_timeout=86400
项目中的druid配置如下
![image](https://user-images.githubusercontent.com/29298951/120831607-4d6fc600-c592-11eb-834c-3f5b44c85389.png)

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat-Server/wiki/%E5%BC%80%E5%8F%91%E7%AF%87%EF%BC%9A1.0-%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BF%9E%E6%8E%A5%E9%85%8D%E7%BD%AE

**Comment by LayJustDoIt** [comment]
这个早就看过了， 最开始的时候我就这么设置的。。。。 mycat的server.xml以及项目中的配置文件的超时都是按照这个文档的第三条的建议去设置的， 但是设置完后启动mycat看到startup successfully后马上就访问接口就会得到上面的错， 然后再次访问的话才算稳定！！

**Comment by LayJustDoIt** [comment]
补充一下原始的参数设置图，不知道这个算不算是细节问题，startup successfully后马上访问解决就会get这个错误信息。
![image](https://user-images.githubusercontent.com/29298951/120892869-d0505980-c642-11eb-8c27-f7fcf34832ca.png)
![image](https://user-images.githubusercontent.com/29298951/120892899-ec53fb00-c642-11eb-832d-7bb65796149b.png)
![image](https://user-images.githubusercontent.com/29298951/120892983-6ab09d00-c643-11eb-82b7-ecfde24ebbf4.png)

**Comment by funnyAnt** [comment]
我看你的客户端jdbc连接池，配置的检查周期是60000ms,也就是60s，这个期间如果mycat出现了重启操作，连接池肯定没法立马感知到。 如果你想快速感知，把这个时间调整小一点。

**Comment by LayJustDoIt** [comment]
调小后可以，没有连接问题了，已解决，感谢。
