### ISSUE TITLE
No dataNode found ,please check tables defined in schema:null

### ISSUE THREAD

**Issue by xinge-1** [MyCATApache/Mycat-Server#2807]
**描述你使用过程中遇到的问题: **

**Comment by junwen12221** [comment]
贴一下配置,schema上设置datanode属性看看?

**Comment by 373270091** [comment]
@junwen12221 帮忙看下
`
<mycat:schema xmlns:mycat="http://io.mycat/">
    <schema name="xiankan" checkSQLschema="true" sqlMaxLimit="100">
        <table name="xk_statistic_video_file" dataNode="dn1" rule="sharding-by-month" primaryKey="svf_gmt_create" autoIncrement="false"/>
    </schema>
    <dataNode name="dn1" dataHost="localhost1" database="ph_xiankan_dev" />
    <dataHost name="localhost1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        
        <writeHost host="192.168.2.181" url="192.168.2.181:3306" user="root" password="Pinghang@123" />
    </dataHost>
</mycat:schema>
`
