### ISSUE TITLE
 Cannot execute statement in a READ ONLY transaction.

### ISSUE THREAD

**Issue by yanpingLi-0121** [MyCATApache/Mycat-Server#2808]
**1、bug描述** 
 使用HeidiSQL工具连接mycat进行新增/更新数据时,都会出现只读事务的问题

**2、版本号(非常重要)**
 v 1.6.7.4

**3、相关表的配置信息**
  schema.xml :
	<schema name="myCats" checkSQLschema="false" sqlMaxLimit="100" randomDataNode="dn1" dataNode="dn1">
		
		
		<table name="test_table" primaryKey="id" dataNode="dn1" subTables="test_table$1-3" rule="test_rule" 
                  splitTableNames ="true"/>
	</schema>
	<dataNode name="dn1" dataHost="localhost1" database="mycattest" />
	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="mysql" 
                  dbDriver="native" switchType="1"  slaveThreshold="100">
		
		
		<heartbeat>select user()</heartbeat> 
		<writeHost host="hostM" url="192.168.1.40:33061" user="gd_dics" password="gd_dics"></writeHost>
	</dataHost>

  rule.xml (涉及到的路由函数)
  server.xml(可选)

**4、操作步骤**
1.  配置完毕启动mycat
2.  使用HiediSQL连接mycat
3.  进行新增或更新操作,会出现只读事务错误,次数还很频繁

**Comment by yanpingLi-0121** [comment]
贴上去的schema的配置被吞了.

`<schema name="myCats" checkSQLschema="false" sqlMaxLimit="100" randomDataNode="dn1" dataNode="dn1">
		
		
		<table name="test_table" primaryKey="id" dataNode="dn1" subTables="test_table$1-3" rule="test_rule" splitTableNames ="true"/>
	</schema>
	<dataNode name="dn1" dataHost="localhost1" database="mycattest" />
	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="0" writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		
		
		<heartbeat>select user()</heartbeat> 
		<writeHost host="hostM" url="192.168.1.40:33061" user="gd_dics" password="gd_dics"></writeHost>
	</dataHost>`

**Comment by zwyqz** [comment]
使用版本1.6.75   
可以看看
https://blog.csdn.net/qq_31183071/article/details/104828626
