### ISSUE TITLE
java.sql.SQLException: Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by realchencom** [MyCATApache/Mycat-Server#2818]
在mycat/lib中替换了mysql-connector-java-8.0.21.jar
在启动mycat也看到如下提示：
jvm 1    | Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
使用idea连接时，出现java.sql.SQLException: Unknown system variable 'query_cache_size'
-------------------------------------------------------------------感谢回复！

**Comment by junwen12221** [comment]
旧的驱动没有删除 

query_cache_size

通过更改mycat的mysql版本(新版本支持,server.xml)和连接mycat的客户端,mycat连接mysql的客户端的版本相同才可以解决

**Comment by realchencom** [comment]
我使用的是mycat mycat-server-1.6.7.6
通过更改mycat的mysql版本(新版本支持,server.xml) --意思是在server.xml 中可以更改mysql的版本吗？
我现在idea是mysql-connector-java-8.0.21.jar，mycat/lib下的类库mysql-connector-java-8.0.21.jar，老的类库已经删除？

**Comment by junwen12221** [comment]
客户端会查询mycat模拟的mysql版本,不同的客户端不同的行为

**Comment by realchencom** [comment]
我现在用的是8.0.21意思是我如果要使用mycat1.6.7.6需要把mysql的版本降为5.7或5.8吗？

**Comment by junwen12221** [comment]
客户端与服务器版本对应

**Comment by realchencom** [comment]
ok，thanks very much！
问题已经解决！

**Comment by jiang-kang** [comment]
按照上面说的还是解决不掉，我用版本是Mycat-Server-Mycat-server-1675-release
mysql-connector-java版本是8.0.18
还是报java.sql.SQLException: Unknown system variable 'query_cache_size'

**Comment by BigSnake1989** [comment]
我的MySQL版本是 8.0.26 ，按照上面的也做了修改，同样的没有生效 @jiang-kang

**Comment by BigSnake1989** [comment]
@realchencom 麻烦问下，你的问题解决了吗

**Comment by realchencom** [comment]
我的解决了，修改配置文件，就解决了发自我的荣耀手机-------- 原始邮件 --------发件人： Jason Zhang ***@***.***>日期： 2021年9月18日周六 21:10收件人： MyCATApache/Mycat-Server ***@***.***>抄送： real ***@***.***>, State change ***@***.***>主    题： Re: [MyCATApache/Mycat-Server] java.sql.SQLException: Unknown system variable 'query_cache_size' (#2818)

我的MySQL版本是 8.0.26 ，按照上面的也做了修改，同样的没有生效 @jiang-kang
