### ISSUE TITLE
mycat批量更新连接丢失

### ISSUE THREAD

**Issue by LayJustDoIt** [MyCATApache/Mycat-Server#2819]
**1、bug描述** 
 简单清晰描述下bug现象.
批量更新数据库，报连接丢失的情况；批量更新sql如图
![image](https://user-images.githubusercontent.com/29298951/127246627-960d6f31-c93a-443c-b8d5-38f05286159f.png)

**2、版本号(非常重要)**
 v 1.6.7.5 & 1.6.7.6都有 

**3、异常信息**
![image](https://user-images.githubusercontent.com/29298951/127246811-c0832bfa-2848-49b3-b002-ea5aa62b9d47.png)

**Comment by junwen12221** [comment]
需要mycat的日志

**Comment by zwyqz** [comment]
不要用多语句,改为单语句,在java代码中for循环
