### ISSUE TITLE
源码怎么自己打包使用

### ISSUE THREAD

**Issue by jiang-kang** [MyCATApache/Mycat-Server#2824]
源码怎么自己打包使用

**Comment by junwen12221** [comment]
maven环境
控制台,Mycat根目录
package -Dmaven.test.skip=true

**Comment by jiang-kang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat-Server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat-Server] 源码怎么自己打包使用 (#2824)





 
maven环境
 控制台,Mycat根目录
 package -Dmaven.test.skip=true
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiang-kang** [comment]
版本是Mycat-Server-1.6.5-RELEASE
按照你说的打包会报错
java.lang.NoClassDefFoundError: org/apache/maven/scm/command/untag/UntagScmResult
Caused by: java.lang.ClassNotFoundException: org.apache.maven.scm.command.untag.UntagScmResult
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.3:create (default) on project Mycat-server: Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:1.3:create failed: A required class was missing while executing org.codehaus.mojo:buildnumber-maven-plugin:1.3:create: org/apache/maven/scm/command/untag/UntagScmResult
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:buildnumber-maven-plugin:1.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/soft/program/mvn_repo/org/codehaus/mojo/buildnumber-maven-plugin/1.3/buildnumber-maven-plugin-1.3.jar
[ERROR] urls[1] = file:/D:/soft/program/mvn_repo/org/apache/maven/scm/maven-scm-provider-gitexe/1.11.2/maven-scm-provider-gitexe-1.11.2.jar
[ERROR] urls[2] = file:/D:/soft/program/mvn_repo/commons-io/commons-io/2.6/commons-io-2.6.jar
[ERROR] urls[3] = file:/D:/soft/program/mvn_repo/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[4] = file:/D:/soft/program/mvn_repo/org/apache/maven/scm/maven-scm-provider-git-commons/1.11.2/maven-scm-provider-git-commons-1.11.2.jar
[ERROR] urls[5] = file:/D:/soft/program/mvn_repo/org/tmatesoft/svnkit/svnkit/1.10.3/svnkit-1.10.3.jar
[ERROR] urls[6] = file:/D:/soft/program/mvn_repo/de/regnis/q/sequence/sequence-library/1.0.4/sequence-library-1.0.4.jar
[ERROR] urls[7] = file:/D:/soft/program/mvn_repo/org/tmatesoft/sqljet/sqljet/1.1.14/sqljet-1.1.14.jar
[ERROR] urls[8] = file:/D:/soft/program/mvn_repo/org/antlr/antlr-runtime/3.4/antlr-runtime-3.4.jar
[ERROR] urls[9] = file:/D:/soft/program/mvn_repo/net/java/dev/jna/jna-platform/5.6.0/jna-platform-5.6.0.jar
[ERROR] urls[10] = file:/D:/soft/program/mvn_repo/com/trilead/trilead-ssh2/1.0.0-build222/trilead-ssh2-1.0.0-build222.jar
[ERROR] urls[11] = file:/D:/soft/program/mvn_repo/com/jcraft/jsch.agentproxy.connector-factory/0.0.7/jsch.agentproxy.connector-factory-0.0.7.jar

**Comment by jiang-kang** [comment]
是需要修改什么配置吗？

**Comment by junwen12221** [comment]
先

mvn install

等待库依赖下载完毕

**Comment by jiang-kang** [comment]
已经解决
