### ISSUE TITLE
预编译语句执行

### ISSUE THREAD

**Issue by Melody1216** [MyCATApache/Mycat-Server#2825]
MySQL客户端执行prepare语句时，抓包和测试发现MySQL包的标记是0x03，包为COM_QUERY类型，那么Mycat中是如何实现预编译的，看代码实现的过程中是需要识别出包类型为COM_STMT_PREPARE才会执行预编译的逻辑。
MySQL客户端版本：MySQL  Ver 14.14 Distrib 5.7.33, for Win64 (x86_64)

**Comment by junwen12221** [comment]
客户端开启服务器预处理同时使用预处理语句,比如JDBC客户端或者Golang的MySQL客户端
