### ISSUE TITLE
分片表自增id问题

### ISSUE THREAD

**Issue by jjf3904** [MyCATApache/Mycat-Server#2826]
**1、bug描述** 
 我用mycat实现分片表，用的是取模的方案，自增id使用全局自增id，运行了半年多，系统比较平稳，前天开始出现出现问题，经过排查，在insert写入分片表数据的时候，发现需要5-6s，经排查发现是全局自增ip的问题，

**2、版本号(非常重要)**
 v 1.6.7.4-release

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)
<schema name="fanqie_global" checkSQLschema="true" sqlMaxLimit="200" dataNode="dn1">
		<table name="table_name" primaryKey="id" autoIncrement="true" dataNode="dn2" rule="mod-long-by-userid" subTables="table_name_$1-512" />
</schema>
sequence_db_conf.properties配置
TABLE_NAME=dn1
sequence_conf.properties 配置
table_name.MINID=1001
table_name.MAXID=2000
table_name.CURID=1000

**4、操作步骤**
将autoIncrement 改成false，insert写入就正常

**5、期望结果**

**6、实际结果**
请问是全局自增id有出问题了吗？

**Comment by zwyqz** [comment]
数据库设置的步长是不是太小了

**Comment by jjf3904** [comment]
> 数据库设置的步长是不是太小了

sequence_conf.properties 配置
table_name.MINID=1001
table_name.MAXID=2000
table_name.CURID=1000 
是这个配置吗？

**Comment by junwen12221** [comment]
步长是数据库的全局序列号的表里设置的

**Comment by jjf3904** [comment]
> 步长是数据库的全局序列号的表里设置的

步长设置的是1

**Comment by jjf3904** [comment]
> 步长是数据库的全局序列号的表里设置的

步长设置的是1

**Comment by zwyqz** [comment]
設置大一點10000

**Comment by jjf3904** [comment]
> 設置大一點10000

设置大的原理是什么？

**Comment by zwyqz** [comment]
批量獲取的多，減少數據庫的并發的壓力。
