### ISSUE TITLE
mycat只分表，不分库，怎么查询到对应的表

### ISSUE THREAD

**Issue by jiang-kang** [MyCATApache/Mycat-Server#2828]
只分表不分库，数据在user_1,user_2,user_3中，但是每次
查询select＊from user where id='234';  id是primary key
都是查询user_1内的数据,
但是id=234的是在user_2中，
查询这么对应到对应的表中

**Comment by junwen12221** [comment]
分片键是哪个

**Comment by jiang-kang** [comment]
已经解决了
