### ISSUE TITLE
版本是mycat1.6.76，分片规则有哪些

### ISSUE THREAD

**Issue by jiang-kang** [MyCATApache/Mycat-Server#2829]
能给一个对应版本的所有规则的rule.xml吗

**Comment by jiang-kang** [comment]
我想按照uuid字符串分片的，不知道有没有合适的分片规则

**Comment by zwyqz** [comment]
http://www.mycat.org.cn/document/mycat-definitive-guide.pdf 官方文档中有具体的分片规则,可以了解一下
