### ISSUE TITLE
DataGrip连接后报错：[HY000][3000] Unknown MyCAT Database 'information_schema'.

### ISSUE THREAD

**Issue by nemowang** [MyCATApache/Mycat-Server#2830]
**描述你使用过程中遇到的问题: **
连接是成功的，在终端中使用命令行直接连接mycat也是没问题的，但是在datagrip中双击查看库的时候报错：**[HY000][3000] Unknown MyCAT Database 'information_schema'.**
schema.xml配置中的dbDriver用native和jdbc都试过，报同样的错。

#### Mycat版本
1.6.7.4-release

#### DataGrip版本
2019.3

#### schema.xml配置
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="TESTDB" checkSQLschema="true" sqlMaxLimit="100">
		<table name="t_user" primaryKey="id" dataNode="dn1"/>
		<table name="t_order" primaryKey="id" dataNode="dn2"/>
		<table name="t_product" primaryKey="id" dataNode="dn2"/>
	</schema>
	<dataNode name="dn1" dataHost="host1" database="db_mall_user" />
	<dataNode name="dn2" dataHost="host2" database="db_mall_order" />
	
	<dataHost name="host1" maxCon="1000" minCon="10" balance="3"
			  writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" url="jdbc:mysql://172.20.0.7:3306/" user="root"
				   password="123456">
		</writeHost>
	</dataHost>

	<dataHost name="host2" maxCon="1000" minCon="10" balance="3"
                          writeType="0" dbType="mysql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                
		<writeHost host="hostM2" url="jdbc:mysql://172.20.0.8:3306/" user="root"
                                   password="123456">
                </writeHost>
                
        </dataHost>

</mycat:schema>

**Comment by nemowang** [comment]
用navicat试了一下是没问题的。现在不支持使用datagrip吗？

**Comment by junwen12221** [comment]
客户端兼容性不好,sqlyog比较好,你可以把information_schema配置成逻辑库试一下

**Comment by nemowang** [comment]
> 客户端兼容性不好,sqlyog比较好,你可以把information_schema配置成逻辑库试一下

好的，谢谢
