### ISSUE TITLE
the max activeConnnections size can not be max than maxconnections

### ISSUE THREAD

**Issue by DarkLand-Chen** [MyCATApache/Mycat-Server#2831]
**1、bug描述** 
偶尔会出现
the max activeConnnections size can not be max than maxconnectionsjava.lang.Thread .getStackTrace1559

**2、版本号(非常重要)**
 v 1.6.7.6

**3、相关表的配置信息**
  schema.xml (maxCon="8000" minCon="10")
mysql 的最大连接数也是 max_connections = 8000

想问一下 连接数这块配置

**Comment by zwyqz** [comment]
出現這個問題一般是大大結果集, 或者有慢sql導致鏈接占用

**Comment by DarkLand-Chen** [comment]
Mycat does not support the allowMultiQueries value to be true, maybe occur some error.   出现这个报错 是什么问题呢

**Comment by zwyqz** [comment]
一次执行执行一条sql,不允许多条一起执行.

**Comment by DarkLand-Chen** [comment]
![image](https://user-images.githubusercontent.com/51595132/130215065-7f072a51-45f1-4803-9320-ee2aa4338fc0.png)
出现  the max activeConnnections size can not be max than maxconnectionsjava.lang.Thread .getStackTrace1559 报错,  可有优化哪些配置来降低这个报错。
