### ISSUE TITLE
mycat 支持基于 binlog的增量恢复 吗

### ISSUE THREAD

**Issue by Macintosh-c** [MyCATApache/Mycat-Server#2837]
**问题描述**
老的单机mysql 无法支持数据量，现基于mycat 做分库分表，搭建了新的 mysql集群。 在做数据迁移时，首先通过mysqldump做了全量的数据迁移，成功。但是在做 基于 老mysql的binlog 恢复增量 数据时，总是失败，想请教下，mycat支持这样的增量恢复吗？

**Comment by Macintosh-c** [comment]
基于mycat的增量数据迁移，有好的方案吗？谢谢

**Comment by zwyqz** [comment]
如果id递增可以用阿里的愚公https://blog.csdn.net/w329636271/article/details/119767667
