### ISSUE TITLE
使用数据库端主键自增策略时，有一个不算是bug的bug。

### ISSUE THREAD

**Issue by 2218032645a** [MyCATApache/Mycat-Server#2866]
**1、bug描述** 
 当我的数据库名称里带有横杠时，比如（xxx-xxx-dabase）,此时使用数据库端自增策略时，会报sql语法错误。对应到mycat上是一个空值异常，因为获取序列值时没有获取到。通过调试源码发现是use 数据库时出现了错误，当数据库名称里带有横杠时，如果直接use xxx-xxx-database,会报错。如果数据库名称加上``号比如use`xxx-xxx-database`就可以了。因为获取自增序列的数据库函数只有一个数据库里有，所以获取序列值时，首先要切换到这个数据库，由此源码里有了这样一段代码。源码里是这样的----- 
   String useDB = "use " + mysqlDN.getDatabase() + ";";    -------所以碰到带横杠的数据库名称，这里就会报错。虽然说创建数据库时不建议名称里带横杠，但是保不准会有人就是要创建这样的名称的数据库，所以建议源码里也加上``这个引号。这样无论数据库名称怎样，都不会出错了。我已测试，问题得以解决。
**2、版本号(非常重要)**
 v 1.6.*.*

**3、相关表的配置信息**
跟配置表没有关系

**4、操作步骤**
1.  '...'
2.  '....'
3.  ...

**5、期望结果**

**6、实际结果**
A clear and concise description of what  actually happened.

**7、额外信息**

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/1.6.7.6/20211016233725/
