### ISSUE TITLE
怎么设置mycat 连接的默认sql_mode

### ISSUE THREAD

**Issue by cusele** [MyCATApache/Mycat-Server#2879]
**描述你使用过程中遇到的问题: **
数据库设置为 
sql_mode=NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

mycat 1.6.7.5-release-20200422133810

SHOW SESSION VARIABLES  LIKE '%sql_mode%'
IGNORE_SPACE,STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION

执行sql报错如下
INSERT INTO `maxwell_master`.`user_member_ext`(`uid`,`user_number`,`nickname`,`avatar`,`devicetoken`,`sex`,`birthday` )
 VALUES ( '5','2451','','','','0','0000-00-00');

Incorrect date value: '0000-00-00' for column 'birthday' at row 1

**Comment by junwen12221** [comment]
sql_mode在1.6源码里面没有特殊处理过,应该从mysql设置里更改

**Comment by cusele** [comment]
> sql_mode在1.6源码里面没有特殊处理过，应该从mysql设置里更改

我的数据库中设置为NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
但在mycat 中添加了NO_ZERO_DATE

**Comment by cusele** [comment]
> sql_mode在1.6源码里面没有特殊处理过,应该从mysql设置里更改

使用mysql_upgrade升级一下
发现不报错了，暂时先关闭了
