### ISSUE TITLE
插入0000-00-00日期字段错误

### ISSUE THREAD

**Issue by cusele** [MyCATApache/Mycat-Server#2881]
**1、bug描述** 
插入日期字段0000-00-00值时报错，报Incorrect date value: '0000-00-00' for column 'dt' at row 1
直接数据库，可以插入成功

**2、版本号(非常重要)**
Mycat-server-1.6.7.5-release-20200422133810-linux.tar.gz

**3、相关表的配置信息**
  schema.xml (非分区表，后台四台PXC集群)
 

**4、操作步骤**
Server version: 5.6.29-mycat-1.6.7.5-release-20200422133810 MyCat Server (OpenCloudDB)

Copyright (c) 2009-2021 Percona LLC and/or its affiliates
Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use monitor
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from test1;
+----+------------+
| id | dt         |
+----+------------+
|  1 | 0000-00-00 |
|  2 | 0000-00-00 |
|  6 | 0000-00-00 |
| 10 | 0000-00-00 |
| 14 | 0000-00-00 |
| 18 | 0000-00-00 |
| 22 | 0000-00-00 |
| 26 | 0000-00-00 |
| 29 | 0000-00-00 |
| 33 | 0000-00-00 |
+----+------------+
10 rows in set (0.00 sec)

mysql> INSERT INTO test1(dt) VALUES( '0000-00-00');
ERROR 1292 (HY000): Incorrect date value: '0000-00-00' for column 'dt' at row 1
mysql> show session variables like 'sql_mode';
+---------------+-------------------------------------------------------------------------+
| Variable_name | Value                                                                   |
+---------------+-------------------------------------------------------------------------+
| sql_mode      | IGNORE_SPACE,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------+
1 row in set (0.00 sec)

直接数据库，可以插入成功
Server version: 5.7.35-38-57-log Percona XtraDB Cluster (GPL), Release rel38, Revision 5c9f299, WSREP version 31.53, wsrep_31.53

Copyright (c) 2009-2021 Percona LLC and/or its affiliates
Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use monitor
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> INSERT INTO test1(dt) VALUES( '0000-00-00');
Query OK, 1 row affected (0.00 sec)

mysql> select * from test1;
+----+------------+
| id | dt         |
+----+------------+
|  1 | 0000-00-00 |
|  2 | 0000-00-00 |
|  6 | 0000-00-00 |
| 10 | 0000-00-00 |
| 14 | 0000-00-00 |
| 18 | 0000-00-00 |
| 22 | 0000-00-00 |
| 26 | 0000-00-00 |
| 29 | 0000-00-00 |
| 33 | 0000-00-00 |
| 37 | 0000-00-00 |
+----+------------+
11 rows in set (0.00 sec)

mysql> show session variables like 'sql_mode';
+---------------+------------------------------------------------------------+
| Variable_name | Value                                                      |
+---------------+------------------------------------------------------------+
| sql_mode      | STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION |
+---------------+------------------------------------------------------------+
1 row in set (0.00 sec)

**5、期望结果**
能正常插入

**6、实际结果**
无法插入

**7、额外信息**

**Comment by junwen12221** [comment]
数据源配置成native模式看看,如果是jdbc,则添加zeroDateTimeBehavior=convertToNull属性

**Comment by cusele** [comment]
> 数据源配置成原生模式看看，如果是jdbc，则添加zeroDateTimeBehavior=convertToNull属性

我修改了这个参数，可以正常使用了 <property name="fakeMySQLVersion">5.7.35</property>
