### ISSUE TITLE
INSERT 后马上SELECT有时候会查不到数据

### ISSUE THREAD

**Issue by yzmking** [MyCATApache/Mycat-Server#2886]
**1、bug描述** 
INSERT 后马上SELECT有时候会查不到数据

**2、版本号(非常重要)**
1.6-RELEASE

**3、相关表的配置信息**
![1639986818(1)](https://user-images.githubusercontent.com/44563730/146732889-68766f3d-f9ec-46f5-a02d-78edbaee1d0e.jpg)

**4、操作步骤**
链接的是mycat
![1639987442(1)](https://user-images.githubusercontent.com/44563730/146733226-b1c72b76-85fa-4ec6-a992-0d4ce4a85fa7.jpg)

**5、期望结果**
正常查询

**6、实际结果**
查询不到

**7、额外信息**

**Comment by yzmking** [comment]
是只能通过事务去处理吗？

**Comment by yzmking** [comment]
是只能通过事务去处理吗？

**Comment by junwen12221** [comment]
slaveThreadold设置为0同时使用注释指定主节点
```
/*!mycat:db_type=master*/select*from travelrecord
/*#mycat:db_type=master*/select*from travelrecord
/*!mycat:db_type=slave*/select*from travelrecord
```

**Comment by yzmking** [comment]
好的
