### ISSUE TITLE
execute sql err : errno:1023 idle con

### ISSUE THREAD

**Issue by eason2eason** [MyCATApache/Mycat-Server#2893]
**1、bug描述** 
 通过mycat日志拿到报错sql，重新执行没问题，语法正确；
属于偶发现象，SQL场景：根据主键及部分字段字段查询报错:execute sql err : errno:1023 idle con:MySQLConnection
![image](https://user-images.githubusercontent.com/97500881/148891958-5885c3d1-d706-4c0b-b95f-c5b71db84853.png)

**2、版本号(非常重要)**
 v 1.5.*.*

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)
  rule.xml (涉及到的路由函数)
  server.xml(可选)

**4、操作步骤**
1.  '...'
2.  '....'
3.  ...

**5、期望结果**

**6、实际结果**
A clear and concise description of what  actually happened.

**7、额外信息**

**Comment by junwen12221** [comment]
可能是mycat连接的mysql的闲置连接被断开了

**Comment by eason2eason** [comment]
OK
