### ISSUE TITLE
表名增加标识符后，describe 命令不可用

### ISSUE THREAD

**Issue by flypig2002** [MyCATApache/Mycat-Server#290]
没有标识符的SQL，返回正常；
[SQL] DESCRIBE tablename;

增加标识符后，返回错误如下；
[SQL] DESCRIBE \`tablename\`;
[Err] 1046 - No dataNode found ,please check tables defined in schema:db_test

补充：select不受影响，返回结果正常
[SQL] select count(*) from \`tablename\`;

**Comment by magicdoom** [comment]
master已经修复，请验证后关闭

**Comment by linzhiqiang0514** [comment]
请验证？

**Comment by mycatmerger** [comment]
已经修复
