### ISSUE TITLE
mycat 清理空闲连接时会导致某些正常连接变得很慢甚至中断

### ISSUE THREAD

**Issue by mynewzone** [MyCATApache/Mycat-Server#2906]
**1、bug描述** 
mycat 每次清理空闲连接时，会导致正常连接变得异常，包括正在发起建立连接的操作，变得很慢甚至中断，提示mysql server has gone away!  
感觉mycat在清理空闲连接时会误杀正常的连接

**2、版本号(非常重要)**
v 1.6.5-release

**3、具体情况**
**客户端应用描述：**
应用服务器为apache 2.4.34 ，应用框架采用thinkphp 5.1.31 ，内置php的版本为5.6，数据库连接方式 pdo，短连接，没有开启持久连接

![image](https://user-images.githubusercontent.com/37644362/161264614-fc843307-c30e-4307-aedf-68917116d661.png)
![image](https://user-images.githubusercontent.com/37644362/161265604-607a543d-bffb-4ca2-809a-bab10025b4bc.png)
![image](https://user-images.githubusercontent.com/37644362/161265123-45a8754f-17ab-41e4-96c3-97725cd8a4da.png)

频繁出现清理空闲连接的同时，会导致大量正常接口的sql查询变慢，甚至大量出现 mysql server has gone away
![image](https://user-images.githubusercontent.com/37644362/161265831-c04f1a72-62cd-4927-b28b-8b29b9ed856f.png)
![image](https://user-images.githubusercontent.com/37644362/161266408-80f19af8-68fe-47c6-a4ad-4a8da3120b52.png)

**Comment by junwen12221** [comment]
先用最新版看看有没有这个问题
http://dl.mycat.org.cn/1.6.7.6/20220221174943/

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/1.6.7.6/20220419132943/
