### ISSUE TITLE
如果不开启useOffHeapForMerge=1 查询返回数据量为实际个数*物理表个数

### ISSUE THREAD

**Issue by xiaoliu10** [MyCATApache/Mycat-Server#2912]
**1、bug描述** 
 简单清晰描述下bug现象.
 如题， 如果设置这个参数，则线上经常cpu爆满

**2、版本号(非常重要)**
 v 1.6.*.*

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)
  rule.xml (涉及到的路由函数)
  server.xml(可选)

**4、操作步骤**
1.  '...'
2.  '....'
3.  ...

**5、期望结果**

**6、实际结果**
A clear and concise description of what  actually happened.

**7、额外信息**

**Comment by junwen12221** [comment]
#686

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat2/issues/686
