### ISSUE TITLE
Mycat1.6 连接mysql8.0启动报错

### ISSUE THREAD

**Issue by zhangptang** [MyCATApache/Mycat-Server#2923]
**1、bug描述** 
 启动报错，无法连接mysql

**2、版本号(非常重要)**
 Mycat-server-1.6-RELEASE-20161028204710-linux

**3、相关表的配置信息**
  schema.xml (需包含表的配置信息，mysql的连接驱动是JDBC还是native方式)  native方式
  rule.xml (涉及到的路由函数)
  server.xml(可选)

**5、期望结果**
启动成功

**6、实际结果**
启动报错，连接不上mysql

**7、额外信息**
错误日志：
connect eror MySQLConnection java.lang.RuntimeException: Unkown charsetIndex:255

**Comment by zwyqz** [comment]
使用1.6的最新版本http://dl.mycat.org.cn/1.6.7.6/
