### ISSUE TITLE
mycat2是否支持公网数据库读写分离？

### ISSUE THREAD

**Issue by lianrou** [MyCATApache/Mycat-Server#2924]
**描述你使用过程中遇到的问题: **
本人在3台公网ubuntu上通过mycat2去实现读写分离（一主两从），部署完后启动不了mycat服务。（同样方式，同样配置在局域网3台ubuntu上测试正常）。疑问：mycat2是否支持公网数据库读写分离？

**Comment by zwyqz** [comment]
支持；
