### ISSUE TITLE
mycat连接mysql错误，Could not create connection to database server.

### ISSUE THREAD

**Issue by 110jiangnan** [MyCATApache/Mycat-Server#2935]
![image](https://github.com/MyCATApache/Mycat-Server/assets/87222759/d3c2ed55-8f89-4310-b86d-a77ed202df70)
![image](https://github.com/MyCATApache/Mycat-Server/assets/87222759/391fc428-0f33-4f23-91a2-c3acc8347154)
![image](https://github.com/MyCATApache/Mycat-Server/assets/87222759/3196ce21-350f-4cde-a6d4-b49f35d8bbea)
![image](https://github.com/MyCATApache/Mycat-Server/assets/87222759/cffb4a9e-6410-4eea-a45a-6be491e162aa)
我的配置信息
![image](https://github.com/MyCATApache/Mycat-Server/assets/87222759/6ac9c6c6-ff1a-4673-9b13-585f70b07004)
![image](https://github.com/MyCATApache/Mycat-Server/assets/87222759/5532dc9a-ad75-4c9f-8073-52b34feb3efd)
navicat连接这两台MySQL无误，密码没有错误。就是显示mycat初始化MySQL连接错误。navicat操作mycat还显示
![image](https://github.com/MyCATApache/Mycat-Server/assets/87222759/869cf0ee-71ac-4926-9eb6-480716e994e6)

**Comment by 110jiangnan** [comment]
我的mycat是1.6.7.6版本，mysql驱动我换成了8.0.23

**Comment by ilaotan** [comment]
> 我的mycat是1.6.7.6版本，mysql驱动我换成了8.0.23

你报错信息里还是5.1.35的mysql呀  http://dl.mycat.org.cn/1.6.7.6/20220524101549/  官网最新版已经是mysql8.0驱动了

**Comment by 110jiangnan** [comment]
搞错了，已经解决了
