### ISSUE TITLE
Table 'work_log' was not locked with LOCK TABLES

### ISSUE THREAD

**Issue by zhanghqGit** [MyCATApache/Mycat-Server#306]
work_log配置为全局表，配置了三个数据库实例以及三个datanode分别对应,使用spring-data-jpa以及hibernate-jpa进行DAO层操作，总是会出现这种情况。这是为啥？另外，配置的所有全局表(按照快速上手指南配置)都会有这个问题。

**Comment by linzhiqiang0514** [comment]
问题重复，请确认。
https://github.com/MyCATApache/Mycat-Server/issues/307
