### ISSUE TITLE
关于JDBC方式连接后端连接占满数据库的问题

### ISSUE THREAD

**Issue by zhouwenbin2000** [MyCATApache/Mycat-Server#312]
经过跟进代码，发现当前mycat在处理jdbc方式连接后端数据库在管理连接方面有些问题
1. JDBCHeartBeat 中 heartBeat方法没有进行连接关闭，每一个连接来了，都去一个新的连接，执行完之后，没有对连接进行关闭。
2. NIOProcessor中维护的BackendConnection中，没有JDBCConnection的连接，同样通过9066端口，show @@backend, 没有jdbc方式的连接。
3. 由于2的原因，在PhysicalDatasource.heatBeatCheck 动态创建连接的时候，会多创建连接，有可能会大于配置的最大连接数

**Comment by zhouwenbin2000** [comment]
1. 可以修复为下面
@Override
    public void heartbeat() {
        if (isStop.get())
            return;

        lock.lock();
        Connection c = null;
        Statement s = null;
        try {
            isChecking.set(true);
            c = source.getConnection();
            s = c.createStatement();
            s.execute(heartbeatSQL);
            s.close(); // 连接要释放掉
            c.close(); // 连接要释放掉
            logger.info("close jdbcHeartbeat connection.");
            status = OK_STATUS;

        } catch (SQLException ex) {

            status = ERROR_STATUS;
            try {
                if (s != null) {
                    s.close();
                }
                if (c != null) {
                    c.close();
                }
            } catch (SQLException e) {
                logger.error("close jdbc connection error",e);
            }

        } finally {
            lock.unlock();
            this.isChecking.set(false);
        }
    }

2. 在建立JDBC连接的时候也将其放在processor中

3. 2修改好了3也不会有问题

**Comment by magicdoom** [comment]
jdbc心跳异步化导致的计数问题，已经修复，你取最新代码试试

**Comment by zhouwenbin2000** [comment]
我看代码，只是把justForHeartbeat异步调用，改成同步调用就好了吗？

**Comment by magicdoom** [comment]
是的

**Comment by mycatmerger** [comment]
zhouwenbin2000已经提交了修复代码

**Comment by Fxdemon** [comment]
JDBC连接Oracle 存在大量会话不释放
