### ISSUE TITLE
强烈建议

### ISSUE THREAD

**Issue by oldshipmaster** [MyCATApache/Mycat-Server#313]
各位贡献者你们好，发现在mycat中每次加表，要改schema.xml，并且需要重启。在生产环境中，重启这段时间数据库服务不可用？这个太不友好了，强烈建议在这个强大的数据库中间件上加上这个“动态加表，删表，改表结构的功能！”请各位贡献者考虑下这个功能！

**Comment by runfriends** [comment]
mysql -h127.0.0.1 -uroot -ppassword -P9066
reload @@config;



runfriends@126.com
 
发件人： captain
发送时间： 2015-05-22 19:56
收件人： MyCATApache/Mycat-Server
主题： [Mycat-Server] 强烈建议 (#313)
各位贡献者你们好，发现在mycat中每次加表，要改schema.xml，并且需要重启。在生产环境中，重启这段时间数据库服务不可用？这个太不友好了，强烈建议在这个强大的数据库中间件上加上这个“动态加表，删表，改表结构的功能！”请各位贡献者考虑下这个功能！

**Comment by oldshipmaster** [comment]
好的，明白了，thank you
