### ISSUE TITLE
mycat1.4使用JDBC连接mongodb插入数据报错

### ISSUE THREAD

**Issue by john625** [MyCATApache/Mycat-Server#325]
ERROR 1105 (HY000): can't serialize class com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr

**Comment by john625** [comment]
ERROR 1105 (HY000): can't serialize class com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr

**Comment by sohudo** [comment]
mysql> insert into mongo (name,age) values(‘cs’,22);
ERROR 1105 (HY000): can't serialize class com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr

**Comment by sohudo** [comment]
改为
insert into mongo (name,age) values('cs',22);
单引号是全角

**Comment by mycatmerger** [comment]
请验证是否可以关闭
