### ISSUE TITLE
Mycat 主机挂了心跳检测异常

### ISSUE THREAD

**Issue by focussky** [MyCATApache/Mycat-Server#343]
环境：
-------------------------------------------------------------------------------------------------------
OS CentOS 6.6 64
MySQL 5.6  12 主 12备  每个实例 40个库，公480个分片库
MyCat  Mycat-server-1.3.0.3-release-20150527095523-linux
数据量：12-15 亿
-------------------------------------------------------------------------------------------------------

配置：server.xml
-------------------------------------------------------------------------------------------------------
			<property name="mutiNodeLimitType">0</property> 
	                <property name="mutiNodePatchSize">100</property>
			<property name="processors">8</property> 
			<property name="processorExecutor">16</property>
			
			
			<property name="serverPort">8066</property> 
			<property name="managerPort">9066</property> 
			<property name="idleTimeout">300000000</property> 
			 
			<property name="bindIp">0.0.0.0</property> 
			<property name="frontWriteQueueSize">8192</property>
			<property name="sequnceHandlerType">1</property>
			<property name="dataNodeHeartbeatPeriod">18000</property>
-------------------------------------------------------------------------------------------------------

配置：schema.xml
-------------------------------------------------------------------------------------------------------
				<dataHost name="host01" maxCon="500" minCon="100" balance="0" writeType="0" dbType="mysql"  dbDriver="native">
                <heartbeat>select user()</heartbeat>
                <writeHost host="host01_1" url="xxx.30.129.101:33061" user="migu" password="xxxxx"></writeHost>
                <writeHost host="host01_2" url="xxx.30.129.105:33061" user="migu" password="xxxxx"></writeHost>
        </dataHost>
				
				<dataHost name="host02" maxCon="500" minCon="100" balance="0" writeType="0" dbType="mysql"  dbDriver="native">
                <heartbeat>select user()</heartbeat>
                <writeHost host="host02_1" url="xxx.30.129.102:33061" user="migu" password="xxxxx"></writeHost>
                <writeHost host="host02_2" url="xxx.30.129.106:33061" user="migu" password="xxxxx"></writeHost>
        </dataHost>
				
				<dataHost name="host03" maxCon="500" minCon="100" balance="0" writeType="0" dbType="mysql"  dbDriver="native">
                <heartbeat>select user()</heartbeat>
                <writeHost host="host03_1" url="xxx.30.129.103:33061" user="migu" password="xxxxx"></writeHost>
                <writeHost host="host03_2" url="xxx.30.129.107:33061" user="migu" password="xxxxx"></writeHost>
        </dataHost>
        
        ...... 共 12 对
-------------------------------------------------------------------------------------------------------

现象：12主 分布在4台物理机上，实际测试直接选择一台掉电，应用不停止请求继续压测，正常在这种配置下mycat应该通过心跳判断出4个主挂了，这4对的写将写到对应的备上，现在的问题是感应到连接断了很快，但是总体恢复很慢，并且还导致了其它没有被断电的主从的连接出现很多超时异常，后来日志报错，应用恢复连接很慢

错误日志：
-------------------------------------------------------------------------------------------------------
INFO   | jvm 1    | 2015/06/10 09:54:50 | 06-10 09:54:50.877  ERROR [$_NIOREACTOR-3-RW] (PhysicalDBPool.java:252) -#!MyCat#host04 init failure
INFO   | jvm 1    | 2015/06/10 09:54:50 | 06-10 09:54:50.886  ERROR [$_NIOREACTOR-6-RW] (PhysicalDBPool.java:252) -#!MyCat#host05 init failure
INFO   | jvm 1    | 2015/06/10 09:54:50 | 06-10 09:54:50.889  ERROR [$_NIOREACTOR-1-RW] (PhysicalDBPool.java:252) -#!MyCat#host01 init failure
INFO   | jvm 1    | 2015/06/10 09:54:50 | 06-10 09:54:50.884  ERROR [$_NIOREACTOR-0-RW] (PhysicalDBPool.java:252) -#!MyCat#host04 init failure
INFO   | jvm 1    | 2015/06/10 09:54:50 | 06-10 09:54:50.877  ERROR [$_NIOREACTOR-5-RW] (PhysicalDBPool.java:252) -#!MyCat#host01 init failure
INFO   | jvm 1    | 2015/06/10 09:54:50 | 06-10 09:54:50.890  ERROR [$_NIOREACTOR-4-RW] (PhysicalDBPool.java:252) -#!MyCat#host06 init failure
INFO   | jvm 1    | 2015/06/10 09:54:50 | 06-10 09:54:50.898  ERROR [$_NIOREACTOR-2-RW] (PhysicalDBPool.java:252) -#!MyCat#host09 init failure
INFO   | jvm 1    | 2015/06/10 09:54:51 | 06-10 09:54:50.908  ERROR [$_NIOREACTOR-7-RW] (PhysicalDBPool.java:252) -#!MyCat#host09 init failure
INFO   | jvm 1    | 2015/06/10 09:55:51 | 06-10 09:55:51.037  ERROR [$_NIOREACTOR-6-RW] (PhysicalDBPool.java:252) -#!MyCat#host10 init failure
INFO   | jvm 1    | 2015/06/10 09:55:51 | 06-10 09:55:51.044  ERROR [$_NIOREACTOR-2-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 09:56:51 | 06-10 09:56:51.225  ERROR [$_NIOREACTOR-2-RW] (PhysicalDBPool.java:252) -#!MyCat#host04 init failure
INFO   | jvm 1    | 2015/06/10 09:56:51 | 06-10 09:56:51.243  ERROR [$_NIOREACTOR-0-RW] (PhysicalDBPool.java:252) -#!MyCat#host02 init failure
INFO   | jvm 1    | 2015/06/10 09:56:51 | 06-10 09:56:51.251  ERROR [$_NIOREACTOR-6-RW] (PhysicalDBPool.java:252) -#!MyCat#host11 init failure
INFO   | jvm 1    | 2015/06/10 09:57:51 | 06-10 09:57:51.289  ERROR [$_NIOREACTOR-0-RW] (PhysicalDBPool.java:252) -#!MyCat#host04 init failure
INFO   | jvm 1    | 2015/06/10 09:57:51 | 06-10 09:57:51.306  ERROR [$_NIOREACTOR-6-RW] (PhysicalDBPool.java:252) -#!MyCat#host04 init failure
INFO   | jvm 1    | 2015/06/10 09:57:51 | 06-10 09:57:51.343  ERROR [$_NIOREACTOR-5-RW] (PhysicalDBPool.java:252) -#!MyCat#host01 init failure
INFO   | jvm 1    | 2015/06/10 09:57:51 | 06-10 09:57:51.350  ERROR [$_NIOREACTOR-3-RW] (PhysicalDBPool.java:252) -#!MyCat#host01 init failure
INFO   | jvm 1    | 2015/06/10 09:58:51 | 06-10 09:58:51.393  ERROR [$_NIOREACTOR-3-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 09:58:51 | 06-10 09:58:51.400  ERROR [$_NIOREACTOR-7-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 09:58:51 | 06-10 09:58:51.465  ERROR [$_NIOREACTOR-0-RW] (PhysicalDBPool.java:252) -#!MyCat#host11 init failure
INFO   | jvm 1    | 2015/06/10 09:59:51 | 06-10 09:59:51.305  ERROR [$_NIOREACTOR-1-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 09:59:51 | 06-10 09:59:51.418  ERROR [$_NIOREACTOR-6-RW] (PhysicalDBPool.java:252) -#!MyCat#host01 init failure
INFO   | jvm 1    | 2015/06/10 09:59:51 | 06-10 09:59:51.453  ERROR [$_NIOREACTOR-7-RW] (PhysicalDBPool.java:252) -#!MyCat#host04 init failure
INFO   | jvm 1    | 2015/06/10 09:59:51 | 06-10 09:59:51.533  ERROR [$_NIOREACTOR-0-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 10:00:51 | 06-10 10:00:51.357  ERROR [$_NIOREACTOR-1-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 10:00:51 | 06-10 10:00:51.441  ERROR [$_NIOREACTOR-2-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 10:00:51 | 06-10 10:00:51.465  ERROR [$_NIOREACTOR-6-RW] (PhysicalDBPool.java:252) -#!MyCat#host03 init failure
INFO   | jvm 1    | 2015/06/10 10:00:51 | 06-10 10:00:51.496  ERROR [$_NIOREACTOR-4-RW] (PhysicalDBPool.java:252) -#!MyCat#host11 init failure
INFO   | jvm 1    | 2015/06/10 10:00:51 | 06-10 10:00:51.499  ERROR [$_NIOREACTOR-7-RW] (PhysicalDBPool.java:252) -#!MyCat#host11 init failure
INFO   | jvm 1    | 2015/06/10 10:00:51 | 06-10 10:00:51.509  ERROR [$_NIOREACTOR-5-RW] (PhysicalDBPool.java:252) -#!MyCat#host11 init failure
INFO   | jvm 1    | 2015/06/10 10:00:51 | 06-10 10:00:51.595  ERROR [$_NIOREACTOR-0-RW] (PhysicalDBPool.java:252) -#!MyCat#host04 init failure
-------------------------------------------------------------------------------------------------------

请问这个在新版本是否会出现

**Comment by songwie** [comment]
测试下最新的1.4，应该不会有，另外检测下writerhost name是不是重名，名字不能一样，哪怕不是一个datahost。

**Comment by mycatmerger** [comment]
测试最新1.4已经修复了切换慢的问题
