### ISSUE TITLE
CharsetUtil出现数组越界报错

### ISSUE THREAD

**Issue by litterJ** [MyCATApache/Mycat-Server#344]
堆栈：
jvm 1    | java.lang.ArrayIndexOutOfBoundsException: 192
jvm 1    | 	at org.opencloudb.mysql.CharsetUtil.getCharset(CharsetUtil.java:143)
jvm 1    | 	at org.opencloudb.mysql.nio.MySQLConnectionAuthenticator.processHandShakePacket(MySQLConnectionAuthenticator.java:128)
jvm 1    | 	at org.opencloudb.mysql.nio.MySQLConnectionAuthenticator.handle(MySQLConnectionAuthenticator.java:100)
jvm 1    | 	at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:256)
jvm 1    | 	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305)
jvm 1    | 	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
jvm 1    | 	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
jvm 1    | 	at org.opencloudb.net.BackendAIOConnection.register(BackendAIOConnection.java:47)
jvm 1    | 	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:138)
jvm 1    | 	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
jvm 1    | 	at java.lang.Thread.run(Thread.java:745)
jvm 1    | java.lang.Throwable
jvm 1    | 	at org.opencloudb.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:73)
jvm 1    | 	at org.opencloudb.backend.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:326)
jvm 1    | 	at org.opencloudb.mysql.nio.MySQLConnectionAuthenticator.handle(MySQLConnectionAuthenticator.java:112)
jvm 1    | 	at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:256)
jvm 1    | 	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:305)
jvm 1    | 	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
jvm 1    | 	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:267)
jvm 1    | 	at org.opencloudb.net.BackendAIOConnection.register(BackendAIOConnection.java:47)
jvm 1    | 	at org.opencloudb.net.NIOReactor$RW.register(NIOReactor.java:138)
jvm 1    | 	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:86)
jvm 1    | 	at java.lang.Thread.run(Thread.java:745)

日志报错：
06/11 10:36:11.384   WARN [$_NIOREACTOR-4-RW] (GetConnectionHandler.java:73) -connect error MySQLConnection [id=4, lastTime=1433990171013, schema=trsids5_performance, old shema=trsids5_performance, borrowed=false, fromSlaveDB=false, threadId=2550, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=192.168.101.216, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.ArrayIndexOutOfBoundsException: 192

mycat所在机器编码：
zh_CN.UTF-8
mysql所在机器编码：
zh_CN.UTF-8
mysql版本：5.5.21-log

**Comment by mycatmerger** [comment]
请坚持mysql中编码index为192的是？

**Comment by litterJ** [comment]
没有找到index=192的编码。
问题在于这个代码本身就会存在数组越界的风险？

**Comment by mycatmerger** [comment]
最新已经修改为动态可以配置，可以在配置文件中配置

**Comment by ramonli** [comment]
我们最近用mycat1.3.0.3连percona5.6.23就出现了这个异常，换成mysql5.6.264没问题，能解释一下这个异常的原因么？
