### ISSUE TITLE
mysql自增长主键

### ISSUE THREAD

**Issue by endy0114** [MyCATApache/Mycat-Server#352]
数据库的自增长不应该是table级别，而应该是database级别。无论如何last_insert_id只有路由到master才有效，所以autoIncrement参数设计在table标签上是不合理的！

**Comment by runfriends** [comment]
这个是合理的，last_insert_id是针对连接的，不是针对事务的，也不是针对数据库的，也不是针对表的
有些表还不是自增长的主键。如果针对库做配置会丢失很多灵活性



runfriends@126.com
 
发件人： endy0114
发送时间： 2015-06-15 20:19
收件人： MyCATApache/Mycat-Server
主题： [Mycat-Server] mysql自增长主键 (#352)
数据库的自增长不应该是table级别，而应该是database级别。无论如何last_insert_id只有路由到master才有效，所以autoIncrement参数设计在table标签上是不合理的！

**Comment by endy0114** [comment]
last_insert_id的作用是返回插入左后一条数据的ID（自增长），写入数据在主从里面肯定要从主里面写入，那么last_insert_id肯定要从主表返回。需要返回ID的情况一般会具体指明，例如ibatis框架就是在insert标签里面指明，在使用mycat的时候又要在table标签里面配置一次显得非常的冗余、繁琐（每次增加一张表都需要修改）。amobea在3的版本中已经修复这个问题！
