### ISSUE TITLE
正在调研。预计7月15号开始使用

### ISSUE THREAD

**Issue by account4github** [MyCATApache/Mycat-Server#388]

**Comment by songwie** [comment]
欢迎：
文档地址：https://github.com/MyCATApache/Mycat-doc，
代码demo：http://songwie.com/teachs?searthstr=mycat，
可以买官方权威指南，已发电子版http://item.taobao.com/item.htm?spm=0.0.0.0.JovBSi&id=44263828402&qq-pf-to=pcqq.group
