### ISSUE TITLE
mycat解析带有@@的语句没有返回正常结果。

### ISSUE THREAD

**Issue by An0nymous0** [MyCATApache/Mycat-Server#394]
最新版的jar包修改了获取连接时 获取mysql系统变量的代码。 从原来 select from 的方式修改为@@的方式直接取系统变量。带有@@的语句发送到mycat时解析有问题。 只返回了@@SESSION.auto_increment_increment字段 后面的其余字段都没有返回。然后jar包内代码在获取第二个字段时报错（java.sql.SQLException: Column Index out of range, 2 > 1.） 因为mycat只返回一个字段。 解析无误的情况下应该是10多个字段。

mysql-connector-java-5.1.36.jar 版本的jar包修改了获取mysql系统参数部分源码。
mysql-connector-java-5.1.36.jar  导致mycat报错的源码在com.mysql.jdbc.ConnectionImpl类的3832行
可以跟mysql-connector-java-5.1.35.jar   com.mysql.jdbc.ConnectionImpl 3820行对比一下跟老代码区别。

 
不可解析的语句， mycat返回只有一个字段就是auto_increment_increment

SELECT @@SESSION.auto_increment_increment,
	@@character_set_client,
	@@character_set_connection,
	@@character_set_results,
	@@character_set_server,
	@@init_connect,
	@@interactive_timeout,
	@@license,
	@@lower_case_table_names,
	@@max_allowed_packet,
	@@net_buffer_length,
	@@net_write_timeout,
	@@query_cache_size,
	@@query_cache_type,
	@@sql_mode,
	@@system_time_zone,
	@@time_zone,
	@@tx_isolation,
	@@wait_timeout

返回正常的语句：

SELECT 
         @@SESSION.auto_increment_increment,
	@@character_set_client,
	@@character_set_connection,
	@@character_set_results,
	@@character_set_server,
	@@init_connect,
	@@interactive_timeout,
	@@license,
	@@lower_case_table_names,
	@@max_allowed_packet,
	@@net_buffer_length,
	@@net_write_timeout,
	@@query_cache_size,
	@@query_cache_type,
	@@sql_mode,
	@@system_time_zone,
	@@time_zone,
	@@tx_isolation,
	@@wait_timeout

两者区别只是把 @@SESSION.auto_increment_increment,换了个行。

**Comment by magicdoom** [comment]
已经提交了修复的pr，等合并了你可以验证下

**Comment by An0nymous0** [comment]
@magicdoom thx
