### ISSUE TITLE
切换时的潜在问题

### ISSUE THREAD

**Issue by zzzhangjinpeng** [MyCATApache/Mycat-Server#401]
1：当前active writehost（A）被检测为error的时候，会选择另一个writehost（B）作为active的writehost，如果读模式选取的是BALANCE_ALL_BACK || BALANCE_ALL || BALANCE_ALL_READ那么有可能读取到其他writehost（除了A和B）以及他们对应的readhosts，而它们的数据从切换点开始是没有更新的。
2：每个MyCat自己检测后端MySQL实例的健康状态，从而选择是否切换，这样存在的问题是多个MyCat检测的时间点不同，也有可能由于其他原因比如网络等等检测到的结果有可能不一致，这样导致在有的Mycat中切换了有的没有，或者都切了但是在两个MyCat中新的active writehost不同。

**Comment by songwie** [comment]
1.4依赖于主从延时切换的基本可以避免，概率大大降低
