### ISSUE TITLE
切换失败

### ISSUE THREAD

**Issue by zzzhangjinpeng** [MyCATApache/Mycat-Server#402]
当选择的切换模式是SYN_STATUS_SWITCH_DS的时候，当前active writehost(A)发生问题的时候会选择一个数据完整的writehost（B）作为新的active writehost，但是当所有的writehost都没有完整的数据（可能发生在采用了半同步复制，但是A对应的readhost拿到了最新的数据）切换会失败。

**Comment by songwie** [comment]
试下最新的1.4
