### ISSUE TITLE
mycat1.4RC全局表where条件中使用or操作会导致返回重复数据

### ISSUE THREAD

**Issue by riverdba** [MyCATApache/Mycat-Server#406]
全局表：test1
配置：<table name="test1" primaryKey="t_id" type="global" dataNode="dn$1-256" />
问题描述：
1、explain select * from test1 where t_id=112233;  随机返回一个分片：正常
2、explain select * from test1 where t_type=0; 随机返回一个分片：正常
3、将上面合成一个查询：
explain select p_id,name,t_type from test1 where  t_id=112233 or t_type=0; 将随机返回2个分片：不正常
PS：where条件中有几个or就会返回几个分片的数据合集，造成多份重复数据！

**Comment by abirdman** [comment]
已修复，请拉1.4上最新代码测试，谢谢！

**Comment by riverdba** [comment]
经测试已经OK。感谢武大师！！！
