### ISSUE TITLE
volatile关键字误用导致mycat宕机

### ISSUE THREAD

**Issue by wangjild** [MyCATApache/Mycat-Server#412]
之前我们使用mycat 1.4版本，会隔几天在线上大量报“WARN [$_MyCatServer] (NIOAcceptor.java:121) -$_MyCatServer java.lang.ArrayIndexOutOfBoundsException” 这一类错误，而且在线下压力测试中没有复现过这一类异常。

我们阅读了 NIOAcceptor和NIOConnector以及NIOReactorPool的实现，发现在实现中有一些值得商榷的地方：

下面是ReactorPool的部分实现
```java
	private volatile int nextReactor;
	public NIOReactor getNextReactor() {
		if (++nextReactor == reactors.length) {
			nextReactor = 0;
		}
		return reactors[nextReactor];
	}
```

下面是NIOConnector的实现，这段代码是运行在多线程环境下面的：
```java
if (finishConnect(c, (SocketChannel) c.channel)) {
	clearSelectionKey(key);
	c.setId(ConnectIdGenerator.getINSTNCE().getId());
	NIOReactor reactor = reactorPool.getNextReactor();
	reactor.postRegister(c);
}
```

我们现在已经知道，volatile 关键字并不能有效地保证线程安全，所以这段代码应该考虑改用CAS操作来防止数组的越界。

**Comment by mycatmerger** [comment]
已经修复，建议再测试看看

**Comment by mycatmerger** [comment]
已经修复，先关闭
