### ISSUE TITLE
 [BUG]com.foundationdb.sql.StandardException: String literal too long

### ISSUE THREAD

**Issue by Hisen158** [MyCATApache/Mycat-Server#422]
场景：业务插入图片数据，insert语句，图片数据字段base64转换为String（mycat暂不支持blob），结果报此错误。
分析：定位到com.foundationdb.sql.parser.SQLParser.class
 if (image.length() > maxStringLiteralLength) {
            throw new StandardException("String literal too long");
        }
此String 已经严重超长，压缩后图片在50KB左右 仍然比较大。
疑问：已经通过 调整org.opencloudb.config.model.SystemConfig.class
private static final int DEFAULT_BUFFER_SIZE = 4096 * 2000;
	private static final int DEFAULT_BUFFER_CHUNK_SIZE = 204800; 屏蔽warn 日志。
目前应该只有修改private int maxStringLiteralLength = 65535;大小才能解决此问题，但是修改foundationdb源码包比较麻烦，可有其他办法？另修改maxStringLiteralLength 增大后会有哪些影响？

**Comment by Hisen158** [comment]
已经解决。
方法：org.opencloudb.parser.java 中设置maxStringLiteralLength 值
	protected SQLParser initialValue() {
             ..............
           //修改foundationdb String最大值用于业务支持长base64图片数据
           MycatConfig config = new MycatConfig();
           SystemConfig system = config.getSystem();
           parser.setMaxStringLiteralLength(system.getProcessorBufferChunk());
           ......
}
暂时测试一段时间 看是否还有其他问题。

**Comment by yoyoch1** [comment]
不是统一用druid了吗， foundationdb还用？？

**Comment by magicdoom** [comment]
用的1.3； 1.4已经废弃掉foundationdb的解析；统一全部用druid解析

**Comment by Hisen158** [comment]
1.3改动了许多，下次升级1.4再看看是否还有此问题，建议1.4考虑支持blob字段，可有实现思路？

**Comment by magicdoom** [comment]
支持blog，需要支持prepare指令，估计改动比较大，你可以研究看看
