### ISSUE TITLE
执行explain insert into语句自动提交

### ISSUE THREAD

**Issue by bridgechan** [MyCATApache/Mycat-Server#427]
指南中说明：
explain可以安全的执行多次，它仅仅是告诉你SQL的路由分片，而不会执行该SQL。
但是，我在mycat客户端执行如下语句：
test@TESTDB 01:07:51>explain insert into orders(id,customer_id) values(2,2); 
结果提示如下：
Query OK, 1 row affected (0.48 sec)
没有提示路由节点，却执行了插入操作。
验证如下所示：
![insert_into](https://cloud.githubusercontent.com/assets/10239269/9149670/9ecd935e-3de6-11e5-80df-b0741e4dd235.png)
----------------------------------------2015/08/08-----------------------------------------------------------

**Comment by DavidLiang001** [comment]
这个不能证明是explain导致的插入。有可能是表中原来就有数据，或是从其它渠道插入了数据。

mysql -umycat  -pmycat -h192.168.0.100 -P8066  test

mysql> truncate table t2;
Query OK, 0 rows affected (0.12 sec)

mysql> select * from t2; 
Empty set (0.02 sec)

mysql> desc t2;
+-------+------------------+------+-----+---------+----------------+
| Field | Type             | Null | Key | Default | Extra          |
+-------+------------------+------+-----+---------+----------------+
| id    | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name  | int(10) unsigned | NO   |     | NULL    |                |
+-------+------------------+------+-----+---------+----------------+
2 rows in set (0.01 sec)

mysql> explain  insert into t2 (id,name) values(1,'a');
+-----------+----------------------------------------+
| DATA_NODE | SQL                                    |
+-----------+----------------------------------------+
| dn1       | insert into t2 (id,name) values(1,'a') |
+-----------+----------------------------------------+
1 row in set (0.08 sec)

mysql> select * from t2;
Empty set (0.01 sec)

mysql> explain  insert into t2 (id,name) values(2,'a'); 
+-----------+----------------------------------------+
| DATA_NODE | SQL                                    |
+-----------+----------------------------------------+
| dn4       | insert into t2 (id,name) values(2,'a') |
+-----------+----------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t2;
Empty set (0.02 sec)
