### ISSUE TITLE
1.4-RC中的双主模式在启动时有自动切换的问题

### ISSUE THREAD

**Issue by testwangs** [MyCATApache/Mycat-Server#432]
经过测试发现，这个问题只存在于1.4RC的版本中，在1.3.0.3版本中，双主模式启动是没有问题的。

我在schema.xml中配置了双主同时设置switchType=1，发现每次启动，日志总先显示第一个数据源初始化成功，10s后就开始切换到第二个数据源，最终显示错误为heartbeat error。但是如果我把schema.xml中的原本两个数据源调换一下位置，并清除dnindex.properties，启动日志仍然为第一个初始化成功10s后就切换到第二个数据源。
schema.xml:
        <schema name="test" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1">
        </schema>
        <dataNode name="dn1" dataHost="localhost1" database="test" />
        <dataHost name="localhost1" maxCon="1000" minCon="1" balance="1"
                writeType="0" dbType="mysql" dbDriver="native" switchType="1">
                <heartbeat>select 1</heartbeat>
                <writeHost host="192.168.56.103" url="192.168.56.103:3306" user="root" password="root">
                </writeHost>
                <writeHost host="192.168.56.102" url="192.168.56.102:3306" user="root"  password="root">
                </writeHost>
        </dataHost>
mycat.log:
08/11 15:12:18.723   INFO [main] (MycatServer.java:195) -===============================================
08/11 15:12:18.723   INFO [main] (MycatServer.java:196) -MyCat is ready to startup ...
08/11 15:12:18.723   INFO [main] (MycatServer.java:206) -Startup processors ...,total processors:1,aio thread pool size:4    
 each process allocated socket buffer pool  bytes ,buffer chunk size:4096  buffer pool's capacity(buferPool/bufferChunk) is:1000
08/11 15:12:18.724   INFO [main] (MycatServer.java:207) -sysconfig params:SystemConfig [processorBufferLocalPercent=100, frontSock
etSoRcvbuf=1048576, frontSocketSoSndbuf=4194304, backSocketSoRcvbuf=4194304, backSocketSoSndbuf=1048576, frontSocketNoDelay=1, bac
kSocketNoDelay=1, maxStringLiteralLength=65535, frontWriteQueueSize=2048, bindIp=0.0.0.0, serverPort=8066, managerPort=9066, chars
et=utf8, processors=1, processorExecutor=4, timerExecutor=2, managerExecutor=2, idleTimeout=1800000, catletClassCheckSeconds=60, s
qlExecuteTimeout=300, processorCheckPeriod=1000, dataNodeIdleCheckPeriod=300000, dataNodeHeartbeatPeriod=10000, clusterHeartbeatUs
er=_HEARTBEAT_USER_, clusterHeartbeatPass=_HEARTBEAT_PASS_, clusterHeartbeatPeriod=5000, clusterHeartbeatTimeout=10000, clusterHea
rtbeatRetry=10, txIsolation=3, parserCommentVersion=50148, sqlRecordCount=10, processorBufferPool=4096000, processorBufferChunk=40
96, defaultMaxLimit=100, sequnceHandlerType=0, sqlInterceptor=org.opencloudb.interceptor.impl.DefaultSqlInterceptor, sqlIntercepto
rType=select, sqlInterceptorFile=/usr/local/mycat/conf/logs/sql.txt, mutiNodeLimitType=0, mutiNodePatchSize=100, defaultSqlParser=
druidparser, usingAIO=0, packetHeaderSize=4, maxPacketSize=16777216, mycatNodeId=1]
08/11 15:12:18.759   INFO [main] (MycatServer.java:266) -using nio network handler 
08/11 15:12:18.777   INFO [main] (MycatServer.java:284) -$_MyCatManager is started and listening on 9066
08/11 15:12:18.778   INFO [main] (MycatServer.java:288) -$_MyCatServer is started and listening on 8066
08/11 15:12:18.778   INFO [main] (MycatServer.java:290) -===============================================
08/11 15:12:18.778   INFO [main] (MycatServer.java:293) -Initialize dataHost ...
08/11 15:12:18.778   INFO [main] (PhysicalDBPool.java:272) -init backend myqsl source ,create connections total 1 for 192.168.56.1
03 index :0
08/11 15:12:18.780   INFO [main] (PhysicalDatasource.java:373) -not ilde connection in pool,create new connection for 192.168.56.1
03 of schema test
08/11 15:12:18.830   INFO [$_NIOREACTOR-0-RW] (GetConnectionHandler.java:66) -connected successfuly MySQLConnection [id=1, lastTim
e=1439277138830, schema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=21, charset=latin1, txIsolation=0, autoco
mmit=true, attachment=null, respHandler=null, host=192.168.56.103, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=f
alse]
08/11 15:12:18.984   INFO [main] (PhysicalDBPool.java:301) -init result :finished 1 success 1 target count:1
08/11 15:12:18.984  DEBUG [main] (PhysicalDatasource.java:403) -release channel MySQLConnection [id=1, lastTime=1439277138830, sch
ema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=21, charset=latin1, txIsolation=0, autocommit=true, attachmen
t=null, respHandler=null, host=192.168.56.103, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
08/11 15:12:18.985   INFO [main] (PhysicalDBPool.java:243) -localhost1 index:0 init success
08/11 15:12:18.985   INFO [main] (MycatServer.java:370) -save DataHost index  localhost1 cur index 0
08/11 15:12:28.996   INFO [Timer0] (MySQLHeartbeat.java:269) -try to switch datasource ,not checked slave synchronize status DBHos
tConfig [hostName=192.168.56.102, url=192.168.56.102:3306]
08/11 15:12:28.997   INFO [Timer0] (PhysicalDBPool.java:272) -init backend myqsl source ,create connections total 1 for 192.168.56
.102 index :1
08/11 15:12:28.999   INFO [Timer0] (PhysicalDatasource.java:373) -not ilde connection in pool,create new connection for 192.168.56
.102 of schema test
08/11 15:12:29.010   INFO [$_NIOREACTOR-0-RW] (GetConnectionHandler.java:66) -connected successfuly MySQLConnection [id=2, lastTim
e=1439277149010, schema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=31, charset=utf8, txIsolation=0, autocomm
it=true, attachment=null, respHandler=null, host=192.168.56.102, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=fal
se]
08/11 15:12:29.202   INFO [Timer0] (PhysicalDBPool.java:301) -init result :finished 1 success 1 target count:1
08/11 15:12:29.203  DEBUG [Timer0] (PhysicalDatasource.java:403) -release channel MySQLConnection [id=2, lastTime=1439277149010, s
chema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=31, charset=utf8, txIsolation=0, autocommit=true, attachmen
t=null, respHandler=null, host=192.168.56.102, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
08/11 15:12:29.204   INFO [Timer0] (PhysicalDBPool.java:243) -localhost1 index:1 init success
08/11 15:12:29.205   INFO [Timer0] (MycatServer.java:370) -save DataHost index  localhost1 cur index 1
08/11 15:12:29.208   INFO [Timer0] (AbstractConnection.java:446) -close connection,reason:switch datasource ,MySQLConnection [id=1
, lastTime=1439277138208, schema=test, old shema=test, borrowed=false, fromSlaveDB=false, threadId=21, charset=latin1, txIsolation
=0, autocommit=true, attachment=null, respHandler=null, host=192.168.56.103, port=3306, statusSync=null, writeQueue=0, modifiedSQL
Executed=false]
08/11 15:12:29.211   WARN [Timer0] (PhysicalDBPool.java:207) -[Host=localhost1,result=[0->1],reason=heartbeat error]

**Comment by testwangs** [comment]
重新贴一下配置文件。
![qq 20150812225054](https://cloud.githubusercontent.com/assets/6532629/9227143/a65c43e8-4144-11e5-8fad-3bf2b421d115.png)

**Comment by songwie** [comment]
dnindex.properties  配置发来看看

**Comment by testwangs** [comment]
dnindex.properties是自动生成的，如下
[root@centos conf]# cat /usr/local/mycat/conf/dnindex.properties 
#update
#Tue Aug 11 15:12:29 CST 2015
localhost1=1

**Comment by songwie** [comment]
localhost1=1   后面的1代表第二个writer ，如果文件是第二个 每次都是切，编号是从0开始的

**Comment by songwie** [comment]
如果文件有会根据文件里面的加载，不会按照顺序

**Comment by testwangs** [comment]
我清除了这个文件，但还是每次启动还都是第一个先成功，然后切换到第二个，就算调换datasource的顺序，再清除这个文件，也还是每次都启动第二个，所以我觉得是bug。

**Comment by testwangs** [comment]
1.3的release就没有这个问题

**Comment by songwie** [comment]
可能环境问题，测试发现没问题的

**Comment by testwangs** [comment]
请问你是在1.4-RC哪天的版本上测的？我之前在本地的虚机和测试机上都试过Mycat-server-1.4-RC-20150804150026-linux.tar.gz，都有问题。

**Comment by songwie** [comment]
最新的版本，你的看这不是最新的

**Comment by testwangs** [comment]
试了一下最新的Mycat-server-1.4-RC-20150811130027-linux.tar.gz，仍然是一样的问题，先初始化第一个，然后就switch到第二个。

08/16 10:55:29.661   INFO [main] (PhysicalDBPool.java:301) -init result :finished 1 success 1 target count:1
08/16 10:55:29.663  DEBUG [main] (PhysicalDatasource.java:403) -release channel MySQLConnection [id=1, lastTime=1439693729489, schema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=7, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=192.168.56.102, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
08/16 10:55:29.664   INFO [main] (PhysicalDBPool.java:243) -localhost1 index:0 init success
08/16 10:55:29.666   INFO [main] (MycatServer.java:370) -save DataHost index  localhost1 cur index 0
08/16 10:55:39.696   INFO [Timer0] (MySQLHeartbeat.java:269) -try to switch datasource ,not checked slave synchronize status DBHostConfig [hostName=192.168.56.103, url=192.168.56.103:3306]
08/16 10:55:39.696   INFO [Timer0] (PhysicalDBPool.java:272) -init backend myqsl source ,create connections total 1 for 192.168.56.103 index :1
08/16 10:55:39.696   INFO [Timer0] (PhysicalDatasource.java:373) -not ilde connection in pool,create new connection for 192.168.56.103 of schema test
08/16 10:55:39.703   INFO [$_NIOREACTOR-0-RW] (GetConnectionHandler.java:66) -connected successfuly MySQLConnection [id=2, lastTime=1439693739703, schema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=6, charset=latin1, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=192.168.56.103, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
08/16 10:55:39.898   INFO [Timer0] (PhysicalDBPool.java:301) -init result :finished 1 success 1 target count:1
08/16 10:55:39.901  DEBUG [Timer0] (PhysicalDatasource.java:403) -release channel MySQLConnection [id=2, lastTime=1439693739703, schema=test, old shema=test, borrowed=true, fromSlaveDB=false, threadId=6, charset=latin1, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=192.168.56.103, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
08/16 10:55:39.905   INFO [Timer0] (PhysicalDBPool.java:243) -localhost1 index:1 init success
08/16 10:55:39.913   INFO [Timer0] (MycatServer.java:370) -save DataHost index  localhost1 cur index 1
08/16 10:55:39.918   INFO [Timer0] (AbstractConnection.java:446) -close connection,reason:switch datasource ,MySQLConnection [id=1, lastTime=1439693719014, schema=test, old shema=test, borrowed=false, fromSlaveDB=false, threadId=7, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=192.168.56.102, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
08/16 10:55:39.925   WARN [Timer0] (PhysicalDBPool.java:207) -[Host=localhost1,result=[0->1],reason=heartbeat error]

**Comment by songwie** [comment]
08/16 10:55:39.925 WARN Timer0 -[Host=localhost1,result=[0->1],reason=heartbeat error]
心跳错了吧，发心跳看下

**Comment by testwangs** [comment]
怎么发心跳？上面的日志就是开了debug的。
这个错就是我这个问题里面最一开始描述的那个问题，我有两台机器，每次都是在配置里的第一台先成功，再报错，然后连到第二台，比如机器顺序是A，B，那最后就是B连接成功，但如果顺序是B，A，那最后就是A连接成功。这个问题很奇怪，找不到原因。

**Comment by songwie** [comment]
来群里问 Mycat用户支持群 228044360

**Comment by mycatmerger** [comment]
问题最新代码已经修复
