### ISSUE TITLE
关于使用SequoiaDB样例

### ISSUE THREAD

**Issue by jdzwhy** [MyCATApache/Mycat-Server#440]
能否在mycat.schema.xml里提供连接 SequoiaDB的配置和使用SequoiaDB测试样例代码

**Comment by sohudo** [comment]
配置表的地方：
<table name="people" primaryKey="_id"  dataNode="dn4"  rule="mod-long" />

配置节点的地方：
<dataNode name="dn4" dataHost="sequoiadb1" database="SAMPLE" />

配置Host的地方：
		<dataHost name="sequoiadb1" maxCon="1000" minCon="1" balance="0" dbType="sequoiadb" dbDriver="jdbc"> 
		<heartbeat> 		</heartbeat>
		 <writeHost host="hostM1" url="sequoiadb://1426587161.dbaas.sequoialab.net:11920/SAMPLE" user="jifeng" 	password="jifeng"></writeHost> 
		 </dataHost>

**Comment by sohudo** [comment]
![sdb](https://cloud.githubusercontent.com/assets/8189582/9360044/998d7cc2-46c6-11e5-8bfa-91d65bf34110.png)

**Comment by sohudo** [comment]
mysql> select * from people;
+--------------------------+------+------+------+------+------+
| _id                      | name | age  | sex  | diqu | lev  |
+--------------------------+------+------+------+------+------+
| 55c7783e6897e874604abe83 | xx   |   20 |    1 | gz   |    2 |
+--------------------------+------+------+------+------+------+
1 row in set (0.60 sec)

**Comment by mycatmerger** [comment]
已经提交了
