### ISSUE TITLE
mycat1.4rc版出现数组越界

### ISSUE THREAD

**Issue by litterJ** [MyCATApache/Mycat-Server#444]
堆栈：
08/02 05:34:30.059   WARN [$_NIOConnector] (NIOConnector.java:124) -$_NIOConnector
java.lang.ArrayIndexOutOfBoundsException: 272840
	at org.opencloudb.MycatServer.nextProcessor(MycatServer.java:413)
	at org.opencloudb.net.NIOConnector.finishConnect(NIOConnector.java:116)
	at org.opencloudb.net.NIOConnector.run(NIOConnector.java:82)
08/02 05:34:30.059   WARN [$_NIOConnector] (NewConnectionRespHandler.java:36) -MySQLConnection [id=198855, lastTime=1438464870040, schema=trsids, old shema=trsids, borrowed=false, fromSlaveDB=true, threadId=0, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=10.159.63.52, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.ArrayIndexOutOfBoundsException: 272840
08/02 05:34:30.060   INFO [$_NIOConnector] (AbstractConnection.java:446) -close connection,reason:java.lang.ArrayIndexOutOfBoundsException: 272840 ,MySQLConnection [id=198855, lastTime=1438464870040, schema=trsids, old shema=trsids, borrowed=false, fromSlaveDB=true, threadId=0, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=10.159.63.52, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]

从代码上看，逻辑处理可能有问题，在高并发多线程情况下确实存在这类问题。

另外，
如果出现这类问题，会不会导致mycat不停的尝试重连mysql，mysql端接收到这样频繁的请求，认为mycat的机器是有攻击行为，从而导致了mycat到mysql的通路存在问题呢？

因为mycat的日志中，还出现了：
is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'

如上字眼。

**Comment by magicdoom** [comment]
请确认1.4的具体版本？之前有修复过这个问题

**Comment by litterJ** [comment]
1.4 rc 标准版。

2015-08-21 22:04 GMT+08:00 magicdoom <notifications@github.com>:

**Comment by mycatmerger** [comment]
1.4rc是在不断自动编译的，请下载最新的版本测试看看，大概8月4号左右修复的

**Comment by litterJ** [comment]
已经看过代码。
确实在最新的rc版中做了修复。
想确认一个问题： 这个异常抛出来以后，会不会导致mycat不停的尝试重连mysql？

2015-08-24 13:05 GMT+08:00 mycatmerger <notifications@github.com>:

**Comment by mycatmerger** [comment]
心跳还是按原有间隔在不停心跳的

**Comment by litterJ** [comment]
mycat日志中还出现过：
is blocked because of many connection errors; unblock with 'mysqladmin
flush-hosts'

想请帮忙分析一下看看，这个异常会有可能导致mysql返回这样的错误吗？

2015-08-24 14:00 GMT+08:00 mycatmerger <notifications@github.com>:

**Comment by mycatmerger** [comment]
应该是错误尝试过多造成的
