### ISSUE TITLE
配置mycat的逻辑库当做另一个mycat的逻辑库的库来源时，访问该库里的数据报错

### ISSUE THREAD

**Issue by litterJ** [MyCATApache/Mycat-Server#450]
有一个mysqlDB1，将这个db配置成mycat1里的逻辑库schema1.

在mycat2中，将schema1当做一个db，配置成为schema2.

在mysql 的console里看schema2的状态，可以看到里面有哪些表，但是查看特定表的数据，就会提示报错：

mysql> use TEST0804;
Database changed
mysql> show tables;
+-----------------------+
| Tables in TEST0804 |
+-----------------------+
| user               |
+-----------------------+
1 row in set (0.00 sec)
mysql> select count(_) from user;
ERROR 1105 (HY000): Unknown charset 'latin1;SET SESSION TRANSACTION ISOLATION LE
VEL REPEATABLE READ;SELECT COUNT(_) AS COUNT0
FROM user
LIMIT 50'

请问一下，mycat是否可以支持将另一个mycat的schema配置进来？

因为存在如下需求：
每个租户一个schema，包含user表，并且user表可做分表处理。
在一个管理后台，希望可以管理到所有租户的所有表。所以需要在mycat上可以将每个租户的schema当做一个db，统一作为新的schema来管理。

**Comment by runfriends** [comment]
奇葩需求
你肯定没有在mycat2配置表



runfriends@126.com
 
发件人： litterJ
发送时间： 2015-08-26 10:30
收件人： MyCATApache/Mycat-Server
主题： [Mycat-Server] 配置mycat的逻辑库当做另一个mycat的逻辑库的库来源时，访问该库里的数据报错 (#450)
有一个mysqlDB1，将这个db配置成mycat1里的逻辑库schema1.
在mycat2中，将schema1当做一个db，配置成为schema2.
在mysql 的console里看schema2的状态，可以看到里面有哪些表，但是查看特定表的数据，就会提示报错：
mysql> use TEST0804;
Database changed
mysql> show tables;
+-----------------------+
| Tables in TEST0804 |
+-----------------------+
| user |
+-----------------------+
1 row in set (0.00 sec)
mysql> select count() from user;
ERROR 1105 (HY000): Unknown charset 'latin1;SET SESSION TRANSACTION ISOLATION LE
VEL REPEATABLE READ;SELECT COUNT() AS COUNT0
FROM user
LIMIT 50'
请问一下，mycat是否可以支持将另一个mycat的schema配置进来？
因为存在如下需求：
每个租户一个schema，包含user表，并且user表可做分表处理。
在一个管理后台，希望可以管理到所有租户的所有表。所以需要在mycat上可以将每个租户的schema当做一个db，统一作为新的schema来管理。

**Comment by litterJ** [comment]
如果没有配置表，那直接show tables应该是看不到表的。

按道理，mycat本身就是模拟了mysql的协议，可以理解为一个伪mysql，理论上感觉是可以支持这么配置的。
如果确定了不支持，那就换别的方法了。

在 2015年8月26日 上午10:35，WuJingrun <notifications@github.com>写道：
