### ISSUE TITLE
读写分离场景，事务提交完成后，查询还是定位到写库

### ISSUE THREAD

**Issue by ShawnYim** [MyCATApache/Mycat-Server#462]
测试读写分离
配置如下：
        <schema name="mysqldb" checkSQLschema="false" dataNode="dnm" sqlMaxLimit="100" />
        <dataNode name="dnm" dataHost="mysqldh" database="mycat" />

        <dataHost name="mysqldh" maxCon="1000" minCon="1" balance="1" writeType="0" dbType="mysql" dbDriver="native">
              <heartbeat>select user()</heartbeat>
              <writeHost host="hostM1" url="160.144.0.141:3306" user="root"  password="HEhe@123" >
              <readHost host="hostM2" url="160.144.0.137:3306" user="root"  password="HEhe@123" > </readHost>
              </writeHost>
        </dataHost>
0、2个库分别执行create table a(i int)创建表，写库插入2条数据，读库插入1条数据
1、mysql客户端登陆数据库，执行select * from a，查询到读库的数据
2、执行start transaction启动事务，执行insert into v values(3)插入数据，select * from a，查询到写库的数据
3、执行commit结束事务，再查询select * from a，还是查询到写库的数据
4、执行set autocommit = 1后，才能从读库查到数据

期望，在事务提交后，查询应该定位到读库上。

**Comment by magicdoom** [comment]
你需要手工设置set autocommit =on
