### ISSUE TITLE
PXC心跳检测时报can't sure connection syn result,so close it MySQLConnection

### ISSUE THREAD

**Issue by johnliu2008** [MyCATApache/Mycat-Server#467]
版本：
5.5.8-mycat-1.4-RELEASE-20150901112004，
OS: ContOS 6.5
MySQL: 5.6.24-72.2-25.11-log Percona XtraDB Cluster binary (GPL) 5.6.24-25.11, Revision, wsrep_25.11（3节点）

schema.xml配置如下：
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://org.opencloudb/"> 

        <schema name="spocosy" checkSQLschema="false" sqlMaxLimit="100" dataNode="41spocosy">
        </schema>

        <schema name="18test" checkSQLschema="false" sqlMaxLimit="100" dataNode="18test">
        </schema>
        <schema name="fb_console" checkSQLschema="false" sqlMaxLimit="100" dataNode="18fb_console">
        </schema>
        <schema name="football2" checkSQLschema="false" sqlMaxLimit="100" dataNode="18football2">
        </schema>
        <schema name="game" checkSQLschema="false" sqlMaxLimit="100" dataNode="18game">
        </schema>
        
        <schema name="gate" checkSQLschema="false" sqlMaxLimit="100" dataNode="18gate">
        </schema>
        <schema name="lahai" checkSQLschema="false" sqlMaxLimit="100" dataNode="18lahai">
        </schema>
        <schema name="win007" checkSQLschema="false" sqlMaxLimit="100" dataNode="18win007">
        </schema>
        <schema name="calc" checkSQLschema="false" sqlMaxLimit="100" dataNode="18calc">
        </schema>

        <schema name="test" checkSQLschema="false" sqlMaxLimit="100" dataNode="220test">
        </schema> 
        <schema name="fb_snap" checkSQLschema="false" sqlMaxLimit="100" dataNode="220fb_snap">
        </schema> 
        <schema name="football" checkSQLschema="false" sqlMaxLimit="100" dataNode="220football">
        </schema> 
        <schema name="forum" checkSQLschema="false" sqlMaxLimit="100" dataNode="220forum">
        </schema> 
        <schema name="console" checkSQLschema="false" sqlMaxLimit="100" dataNode="220console">
        </schema> 
        <schema name="leixj" checkSQLschema="false" sqlMaxLimit="100" dataNode="220leixj">
        </schema> 

        <dataNode name="41spocosy" dataHost="41" database="spocosy" />

        <dataNode name="18test" dataHost="18" database="test" />
        <dataNode name="18fb_console" dataHost="18" database="fb_console" />
        <dataNode name="18football2" dataHost="18" database="football2" />
        <dataNode name="18forum" dataHost="18" database="forum" />
        <dataNode name="18game" dataHost="18" database="game" />
        <dataNode name="18console" dataHost="18" database="console" />
        <dataNode name="18gate" dataHost="18" database="gate" />
        <dataNode name="18lahai" dataHost="18" database="lahai" />
        <dataNode name="18win007" dataHost="18" database="win007" />
        <dataNode name="18calc" dataHost="18" database="calc" />
        <dataNode name="18leixj" dataHost="18" database="leixj" />

        <dataNode name="220test" dataHost="220" database="test" /> 
        <dataNode name="220fb_snap" dataHost="220" database="fb_snap" /> 
        <dataNode name="220football" dataHost="220" database="football" /> 
        <dataNode name="220forum" dataHost="220" database="forum" /> 
        <dataNode name="220console" dataHost="220" database="console" /> 
        <dataNode name="220leixj" dataHost="220" database="leixj" /> 

        <dataHost name="41" maxCon="1500" minCon="10" balance="0"
                writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="41" url="192.168.100.41:3306" user="root" password="abc123"/>
        </dataHost>

        <dataHost name="18" maxCon="1500" minCon="10" balance="1"
                writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="11" url="192.168.88.11:3306" user="root" password="abc123"/>
                <writeHost host="12" url="192.168.88.12:3306" user="root" password="abc123"/>
                <writeHost host="13" url="192.168.88.13:3306" user="root" password="abc123"/> 
        </dataHost>

        <dataHost name="220" maxCon="1500" minCon="10" balance="0"
                writeType="0" dbType="mysql" dbDriver="native" switchType="2"  slaveThreshold="100">
                <heartbeat>show slave status</heartbeat>
                <writeHost host="220" url="192.168.88.220:3306" user="root" password="abc123"/>
                
        </dataHost>
</mycat:schema>

server.xml配置如下：
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mycat:server SYSTEM "server.dtd">
<mycat:server xmlns:mycat="http://org.opencloudb/">
        <system>
        <property name="defaultSqlParser">druidparser</property>
       
        
        
                
                
                
                
                
                
                
        <property name="serverPort">8066</property> <property name="managerPort">9066</property> 
        </system>

        <user name="spocosy">
                                        <property name="password">a</property>
                                        <property name="schemas">spocosy</property>
        </user>

        <user name="18test">
                                        <property name="password">a</property>
                                        <property name="schemas">18test</property>
        </user>
        <user name="fb_console">
                                        <property name="password">a</property>
                                        <property name="schemas">fb_console</property>
        </user>
        <user name="football2">
                                        <property name="password">a</property>
                                        <property name="schemas">football2</property>
        </user>
        <user name="game">
                                        <property name="password">a</property>
                                        <property name="schemas">game</property>
        </user>
        
        <user name="gate">
                                        <property name="password">a</property>
                                        <property name="schemas">gate</property>
        </user>
        <user name="lahai">
                                        <property name="password">a</property>
                                        <property name="schemas">lahai</property>
        </user>
        <user name="win007">
                                        <property name="password">a</property>
                                        <property name="schemas">win007</property>
        </user>
        <user name="calc">
                                        <property name="password">a</property>
                                        <property name="schemas">calc</property>
        </user>

        <user name="test">
                <property name="password">a</property>
                <property name="schemas">test</property>
        </user>
        <user name="fb_snap">
                <property name="password">a</property>
                <property name="schemas">fb_snap</property>
        </user>
        <user name="football">
                <property name="password">a</property>
                <property name="schemas">football</property>
        </user>
        <user name="forum">
                <property name="password">a</property>
                <property name="schemas">forum</property>
        </user>
        <user name="console">
                <property name="password">a</property>
                <property name="schemas">console</property>
        </user>
        <user name="leixj">
                <property name="password">a</property>
                <property name="schemas">leixj</property>
        </user>

        
        
        

</mycat:server>

wrapper.conf只修改了jdk的路径，其他默认，jdk版本1.7.0_60

--------------------------------------------------------------------------------------------

警告日志如下：
09/14 20:39:19.282   WARN [$_NIOREACTOR-4-RW] (MySQLConnection.java:551) -can't sure connection syn result,so close it MySQLConnection [id=4015, lastTime=1442234359270, schema=calc, old shema=football2, borrowed=true, fromSlaveDB=false, threadId=4527, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=calc,sql=select user(),  jobHandler=org.opencloudb.sqlengine.OneRawSQLQueryResultHandler@77409080], host=192.168.88.12, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@3f34b16b, writeQueue=0, modifiedSQLExecuted=false]
09/14 20:39:19.282   WARN [$_NIOREACTOR-5-RW] (MySQLConnection.java:551) -can't sure connection syn result,so close it MySQLConnection [id=4024, lastTime=1442234359270, schema=calc, old shema=football2, borrowed=true, fromSlaveDB=false, threadId=1149347, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=calc,sql=select user(),  jobHandler=org.opencloudb.sqlengine.OneRawSQLQueryResultHandler@2fcf00aa], host=192.168.88.13, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@1c6c0838, writeQueue=0, modifiedSQLExecuted=false]
09/14 20:39:29.282   WARN [$_NIOREACTOR-3-RW] (MySQLConnection.java:551) -can't sure connection syn result,so close it MySQLConnection [id=4022, lastTime=1442234369272, schema=calc, old shema=football2, borrowed=true, fromSlaveDB=false, threadId=1149344, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=calc,sql=select user(),  jobHandler=org.opencloudb.sqlengine.OneRawSQLQueryResultHandler@763f03c3], host=192.168.88.13, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@231033db, writeQueue=0, modifiedSQLExecuted=false]
09/14 20:39:29.283   WARN [$_NIOREACTOR-2-RW] (MySQLConnection.java:551) -can't sure connection syn result,so close it MySQLConnection [id=4013, lastTime=1442234369272, schema=calc, old shema=football2, borrowed=true, fromSlaveDB=false, threadId=4523, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=calc,sql=select user(),  jobHandler=org.opencloudb.sqlengine.OneRawSQLQueryResultHandler@3cdd9094], host=192.168.88.12, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@7cbc80d8, writeQueue=0, modifiedSQLExecuted=false]
09/14 20:39:39.282   WARN [$_NIOREACTOR-2-RW] (MySQLConnection.java:551) -can't sure connection syn result,so close it MySQLConnection [id=4028, lastTime=1442234379268, schema=calc, old shema=football2, borrowed=true, fromSlaveDB=false, threadId=4554, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=calc,sql=select user(),  jobHandler=org.opencloudb.sqlengine.OneRawSQLQueryResultHandler@689ac6da], host=192.168.88.12, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@72c10304, writeQueue=0, modifiedSQLExecuted=false]
09/14 20:39:39.283   WARN [$_NIOREACTOR-1-RW] (MySQLConnection.java:551) -can't sure connection syn result,so close it MySQLConnection [id=4027, lastTime=1442234379268, schema=calc, old shema=football2, borrowed=true, fromSlaveDB=false, threadId=1149381, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=SQLJob [ id=0,dataNodeOrDatabase=calc,sql=select user(),  jobHandler=org.opencloudb.sqlengine.OneRawSQLQueryResultHandler@97547dd], host=192.168.88.13, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@5dad3677, writeQueue=0, modifiedSQLExecuted=false]

将这个mycat的所有的文件拷贝一份，修改端口，在同一台机上面启起来，但是没有任何外来的连接请求，不报警告。

**Comment by magicdoom** [comment]
已经解决

**Comment by liuxyc** [comment]
@magicdoom 请问这个问题是在哪个mycat版本中被修复的？
