### ISSUE TITLE
1.4release版本上遇到聚合查询返回结果不一致的问题

### ISSUE THREAD

**Issue by riverdba** [MyCATApache/Mycat-Server#475]
直接到在分片的mysql上执行该sql返回结果是不会变化的，但是通过mycat查询每次刷新，结果集都会变化：
![1](https://cloud.githubusercontent.com/assets/13479223/10064681/b538bd76-62ad-11e5-9e79-28fc97ad9207.png)
![2](https://cloud.githubusercontent.com/assets/13479223/10064684/bb2edd6e-62ad-11e5-937e-5e318cddb084.png)

**Comment by riverdba** [comment]
在从零大师的指导下修改了下sql写法，解决了该问题。

**Comment by zzcclp** [comment]
能不能具体说明下原因？

**Comment by riverdba** [comment]
经过测试，发现去掉union all的部分结果是不变的，于是就把这部分放到最外面union，改写为如下：
![qq 20150930123716](https://cloud.githubusercontent.com/assets/13479223/10184528/0ac7bdf2-6770-11e5-8634-b85fae033ca7.png)
