### ISSUE TITLE
自增列的BUG与风险！！！

### ISSUE THREAD

**Issue by 18675552767** [MyCATApache/Mycat-Server#511]
Server version: 5.5.8-mycat-1.4-release-20151019230038 MyCat Server (monitor)

#id 是分片键且自增
A.insert into tb1(id,name)values(0,'a');
B.insert into tb1(id,name)values(NULL,'a');
C.insert into tb1(name)values('a');
都能正常执行，不报错，加了全局序列后，只有第三种逻辑是对的，其它两种，都会产生异常数据
风险：
A 和B 都能正常执行且不会报错，但是会产生非分片上的异常数据，”一颗老鼠屎坏了整锅汤“，运维风险超级高！！！

建议，加一层逻辑判断，A和B 直接报错，把问题抛出来，避免风险！！！！

**Comment by zhuam** [comment]
贴个配置，另外把异常数据也给截个图 那就更好

**Comment by songwie2** [comment]
B.insert into tb1(id,name)values(NULL,'a');
这种会报错 
A.insert into tb1(id,name)values(0,'a');
这种是错误 用法
