### ISSUE TITLE
字符串中有关键词时，识别错误

### ISSUE THREAD

**Issue by xladykiller** [MyCATApache/Mycat-Server#531]
insert into table ( txt) values ('SELECT') 会因为SELECT而报[Err] 1064 - multi insert not provided

**Comment by zhuam** [comment]
测试 insert into company ( name) values ('SELECT')  无异常

**Comment by magicdoom** [comment]
早期mycat版本全局序列替换时有这个bug，已经早修复了，确认使用最新1.4版本
