### ISSUE TITLE
PhysicalDatasource  中的 createNewConnection  在突然连接放大的时候，会造成连接创建不均匀的问题

### ISSUE THREAD

**Issue by zhuam** [MyCATApache/Mycat-Server#544]
如题

mysql> show @@datasource;
+----------+---------------+-------+--------------+-------+------+--------+------+------+---------+
| DATANODE | NAME          | TYPE  | HOST         | PORT  | W/R  | ACTIVE | IDLE | SIZE | EXECUTE |
+----------+---------------+-------+--------------+-------+------+--------+------+------+---------+
| dn1      | writeHost0251 | mysql | xxx.xxx.2.51 |  3306 | W    |      0 |   10 | 2000 |     484 |
| dn1      | readHost50    | mysql | xx.xx.xx.50  |  3306 | R    |      0 |    9 | 2000 |  210488 |
| dn1      | readHost51    | mysql | xx.xx.xx.51  |  3306 | R    |      0 |   10 | 2000 |  843118 |
| dn1      | readHost52    | mysql | xx.xx.xx.52  |  3306 | R    |      0 |   10 | 2000 |  843571 |
| dn1      | readHost0252  | mysql | xxx.xxx.2.52 |  3306 | R    |      0 |   62 | 2000 |  421898 |
+----------+---------------+-------+--------------+-------+------+--------+------+------+---------+

mysql> show @@datasource;
+----------+---------------+-------+--------------+-------+------+--------+------+------+---------+
| DATANODE | NAME          | TYPE  | HOST         | PORT  | W/R  | ACTIVE | IDLE | SIZE | EXECUTE |
+----------+---------------+-------+--------------+-------+------+--------+------+------+---------+
| dn1      | writeHost0251 | mysql | xxx.xxx.2.51 |  3306 | W    |      0 |   10 | 2000 |     517 |
| dn1      | readHost50    | mysql | xx.xx.xx.50  |  3306 | R    |      0 |    9 | 2000 |  225294 |
| dn1      | readHost51    | mysql | xx.xx.xx.51  |  3306 | R    |      0 |   10 | 2000 |  902332 |
| dn1      | readHost52    | mysql | 10.13.40.52  |  3306 | R    |      0 |   10 | 2000 |  902876 |
| dn1      | readHost0252  | mysql | xxx.xxx.2.52 |  3306 | R    |      0 |   13 | 2000 |  451466 |
+----------+---------------+-------+--------------+-------+------+--------+------+------+---------+

**Comment by zhuam** [comment]
readHost0252  的权重设置的是 2
readHost51  的权重设置的是 4
readHost52 的权重设置的是 4
readHost50  的权重设置的是 1,
通过上面这个图， SQL执行测的负载比较理想， 但突然访问量增大，连接不够的时候，在所在DB上创建的connection 严重不均匀

**Comment by songwie** [comment]
这个没关系 连接会动态调整  定期释放的

**Comment by zhuam** [comment]
恩，我知道会定期释放的，但是在特殊情况下，突然连接过大，超过阀值的时候，还是不好

**Comment by zhuam** [comment]
设置  readHost_11 的 weight = 4,  readHost_localhost 的 weight = 1, 结果如下

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |      11 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     29 |
  32 |  100 |   40606 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |      7 |
  14 |  100 |   10080 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.06 sec)


mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |      12 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     36 |
  25 |  100 |   42558 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |      7 |
  14 |  100 |   10630 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.19 sec)




翻过了  设置  readHost_11 的 weight = 1,  readHost_localhost 的 weight = 4, 结果如下

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       5 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |      8 |
  15 |  100 |    3153 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     27 |
  32 |  100 |   12235 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.05 sec)

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       5 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |      8 |
  15 |  100 |    3242 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     34 |
  25 |  100 |   12629 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.03 sec)



两个的weight 都设置为相同的 1， 比率较为均等，偶尔会出现 高出很多的情况，但总体来说，较为正常

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       3 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     19 |
  14 |  100 |    3963 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     20 |
  22 |  100 |    4220 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.06 sec)

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       3 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     22 |
  11 |  100 |    4414 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     24 |
  18 |  100 |    4703 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.03 sec)


测试结果，connection的创建及分配 根据 weight 的权重，未发生倾斜

**Comment by zhuam** [comment]
设置  readHost_11 的 weight = 4,  readHost_localhost 的 weight = 1, 结果如下

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |      11 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     29 |
  32 |  100 |   40606 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |      7 |
  14 |  100 |   10080 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.06 sec)


mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |      12 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     36 |
  25 |  100 |   42558 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |      7 |
  14 |  100 |   10630 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.19 sec)




翻过了  设置  readHost_11 的 weight = 1,  readHost_localhost 的 weight = 4, 结果如下

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       5 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |      8 |
  15 |  100 |    3153 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     27 |
  32 |  100 |   12235 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.05 sec)

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       5 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |      8 |
  15 |  100 |    3242 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     34 |
  25 |  100 |   12629 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.03 sec)



两个的weight 都设置为相同的 1， 比率较为均等，偶尔会出现 高出很多的情况，但总体来说，较为正常

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       3 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     19 |
  14 |  100 |    3963 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     20 |
  22 |  100 |    4220 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.06 sec)

mysql> show @@datasource;
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| DATANODE | NAME               | TYPE  | HOST         | PORT | W/R  | ACTIVE |
IDLE | SIZE | EXECUTE |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
| dn1      | writeHost_local    | mysql | localhost    | 3306 | W    |      0 |
   1 |  100 |       3 |
| dn1      | readHost_11        | mysql | 192.168.5.11 | 3306 | R    |     22 |
  11 |  100 |    4414 |
| dn1      | readHost_localhost | mysql | localhost    | 3306 | R    |     24 |
  18 |  100 |    4703 |
+----------+--------------------+-------+--------------+------+------+--------+-
-----+------+---------+
3 rows in set (0.03 sec)


测试结果，connection的创建及分配 根据 weight 的权重，未发生不合理的倾斜， 倾斜的尺度总体和 weight 的设置较为一致，合理
