### ISSUE TITLE
mycat sharejoin have an error  in mycat 1.4

### ISSUE THREAD

**Issue by wufeirong** [MyCATApache/Mycat-Server#567]
schemal.xml
 <table name ="ta" primaryKey="ID" dataNode="dn1,dn2,dn3" rule="mod-long" />
  <table name="tb" primaryKey="ID" dataNode="dn2,dn3,dn4" rule="mod-long"/>	

mysql> insert into ta(id ,bid,name)values(1,1,'aa'),(2,1,'ab'),(3,2,'ac');
Query OK, 3 rows affected (0.45 sec)

mysql> insert into tb(id,name)values(1,'bb'),(2,'bc'),(3,'bd');

测试非跨片join
mysql> select * from ta ,tb where ta.BID=tb.id;
+----+------+------+----+------+
| ID | BID  | NAME | ID | NAME |
+----+------+------+----+------+
|  2 |    1 | ab   |  1 | bb   |
+----+------+------+----+------+
1 row in set (0.07 sec)
测试 跨片join
/*!mycat:catlet=demo.catlets.ShareJoin */select *  from ta join tb on ta.BID=tb.id;
结果为空的

错误日志

11/25 09:12:52.804  DEBUG [$_NIOREACTOR-0-RW] (PhysicalDatasource.java:403) -release channel MySQLConnection [id=52, lastTime=1448413972781, schema=db1, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=2156, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.889  DEBUG [$_NIOREACTOR-1-RW] (ServerQueryHandler.java:56) -ServerConnection [id=8, schema=TESTDB, host=192.168.40.101, user=test,txIsolation=3, autocommit=true, schema=TESTDB]/*!mycat:catlet=demo.catlets.ShareJoin */select *  from ta join tb on ta.BID=tb.id
11/25 09:12:52.890  DEBUG [$_NIOREACTOR-1-RW] (HintCatletHandler.java:46) -load catelet class:demo.catlets.ShareJoin to run sql select *  from ta join tb on ta.BID=tb.id
11/25 09:12:52.901   INFO [$_NIOREACTOR-1-RW] (JoinParser.java:70) -SQL: select *  from ta join tb on ta.BID=tb.id
11/25 09:12:52.903   INFO [$_NIOREACTOR-1-RW] (ShareJoin.java:150) -Catlet exec:dn1,dn2,dn3, sql:select * from ta
11/25 09:12:52.903  DEBUG [BusinessExecutor2] (PhysicalDBPool.java:431) -select read source hostM1 for dataHost:localhost1
11/25 09:12:52.909  DEBUG [BusinessExecutor2] (SQLJob.java:85) -con query sql:select * from ta to con:MySQLConnection [id=52, lastTime=1448413972909, schema=db1, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=2156, charset=utf8, txIsolation=3, autocommit=true, attachment=dn1{select * from ta}, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.910  DEBUG [$_NIOREACTOR-0-RW] (PhysicalDatasource.java:403) -release channel MySQLConnection [id=52, lastTime=1448413972903, schema=db1, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=2156, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.911   INFO [$_NIOREACTOR-0-RW] (BatchSQLJob.java:41) -job finished SQLJob [ id=1,dataNodeOrDatabase=dn1,sql=select * from ta,  jobHandler=demo.catlets.ShareDBJoinHandler@3a91521d]
11/25 09:12:52.911  DEBUG [BusinessExecutor1] (PhysicalDBPool.java:431) -select read source hostM1 for dataHost:localhost1
11/25 09:12:52.912  DEBUG [BusinessExecutor1] (SQLJob.java:85) -con query sql:select * from ta to con:MySQLConnection [id=52, lastTime=1448413972912, schema=db2, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=2156, charset=utf8, txIsolation=3, autocommit=true, attachment=dn2{select * from ta}, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.912  DEBUG [BusinessExecutor1] (MySQLConnection.java:442) -con need syn ,total syn cmd 1 commands schema change:true con:MySQLConnection [id=52, lastTime=1448413972912, schema=db2, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=2156, charset=utf8, txIsolation=3, autocommit=true, attachment=dn2{select * from ta}, respHandler=SQLJob [ id=2,dataNodeOrDatabase=dn2,sql=select * from ta,  jobHandler=demo.catlets.ShareDBJoinHandler@3a91521d], host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.913   WARN [$_NIOREACTOR-0-RW] (MySQLConnection.java:551) -can't sure connection syn result,so close it MySQLConnection [id=52, lastTime=1448413972903, schema=db2, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=2156, charset=utf8, txIsolation=3, autocommit=true, attachment=dn2{select * from ta}, respHandler=SQLJob [ id=2,dataNodeOrDatabase=dn2,sql=select * from ta,  jobHandler=demo.catlets.ShareDBJoinHandler@3a91521d], host=172.16.4.83, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@1aa60bf5, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.914   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:452) -close connection,reason:syn status unkown  ,MySQLConnection [id=52, lastTime=1448413972903, schema=db2, old shema=db1, borrowed=true, fromSlaveDB=false, threadId=2156, charset=utf8, txIsolation=3, autocommit=true, attachment=dn2{select * from ta}, respHandler=null, host=172.16.4.83, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@1aa60bf5, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.914   INFO [$_NIOREACTOR-0-RW] (BatchSQLJob.java:41) -job finished SQLJob [ id=2,dataNodeOrDatabase=dn2,sql=select * from ta,  jobHandler=demo.catlets.ShareDBJoinHandler@3a91521d]
11/25 09:12:52.915  DEBUG [BusinessExecutor0] (PhysicalDBPool.java:431) -select read source hostM1 for dataHost:localhost1
11/25 09:12:52.915   INFO [BusinessExecutor0] (PhysicalDatasource.java:373) -not ilde connection in pool,create new connection for hostM1 of schema db3
11/25 09:12:52.918  DEBUG [$_NIOREACTOR-1-RW] (SQLJob.java:85) -con query sql:select * from ta to con:MySQLConnection [id=53, lastTime=1448413972918, schema=db3, old shema=db3, borrowed=true, fromSlaveDB=false, threadId=2157, charset=utf8, txIsolation=0, autocommit=true, attachment=dn3{select * from ta}, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.919  DEBUG [$_NIOREACTOR-1-RW] (PhysicalDatasource.java:403) -release channel MySQLConnection [id=53, lastTime=1448413972903, schema=db3, old shema=db3, borrowed=true, fromSlaveDB=false, threadId=2157, charset=utf8, txIsolation=0, autocommit=true, attachment=null, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.920  DEBUG [$_NIOREACTOR-1-RW] (RouterUtil.java:909) -try to find cache by primary key 
11/25 09:12:52.921  DEBUG [$_NIOREACTOR-1-RW] (EnchachePool.java:76) -TableID2DataNodeCache.TESTDB_TB  miss cache ,key:1
11/25 09:12:52.921  DEBUG [$_NIOREACTOR-1-RW] (EnchachePool.java:76) -TableID2DataNodeCache.TESTDB_TB  miss cache ,key:2
11/25 09:12:52.922  DEBUG [BusinessExecutor2] (PhysicalDBPool.java:431) -select read source hostM1 for dataHost:localhost1
11/25 09:12:52.922  DEBUG [BusinessExecutor2] (SQLJob.java:85) -con query sql:select * from tb where id in (1,2,1)  to con:MySQLConnection [id=53, lastTime=1448413972922, schema=db3, old shema=db3, borrowed=true, fromSlaveDB=false, threadId=2157, charset=utf8, txIsolation=0, autocommit=true, attachment=dn3{select * from tb where id in (1,2,1) }, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.922  DEBUG [BusinessExecutor1] (PhysicalDBPool.java:431) -select read source hostM1 for dataHost:localhost1
11/25 09:12:52.923   INFO [BusinessExecutor1] (PhysicalDatasource.java:373) -not ilde connection in pool,create new connection for hostM1 of schema db4
11/25 09:12:52.922   INFO [$_NIOREACTOR-1-RW] (ShareJoin.java:229) -SQLParallJob:dn3,dn4, sql:select * from tb where id in (1,2,1) 
11/25 09:12:52.924   INFO [$_NIOREACTOR-1-RW] (BatchSQLJob.java:41) -job finished SQLJob [ id=3,dataNodeOrDatabase=dn3,sql=select * from ta,  jobHandler=demo.catlets.ShareDBJoinHandler@3a91521d]
11/25 09:12:52.924  DEBUG [$_NIOREACTOR-1-RW] (EngineCtx.java:82) -packge id 1
11/25 09:12:52.925  DEBUG [$_NIOREACTOR-1-RW] (NIOReactor.java:101) -caught err:
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at demo.catlets.ShareRowOutPutDataHandler.onRowData(ShareJoin.java:370)
	at org.opencloudb.sqlengine.SQLJob.rowResponse(SQLJob.java:142)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:203)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:134)
	at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79)
	at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:257)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
	at java.lang.Thread.run(Thread.java:745)
11/25 09:12:52.925  DEBUG [$_NIOREACTOR-0-RW] (SQLJob.java:85) -con query sql:select * from tb where id in (1,2,1)  to con:MySQLConnection [id=54, lastTime=1448413972925, schema=db4, old shema=db4, borrowed=true, fromSlaveDB=false, threadId=2158, charset=utf8, txIsolation=0, autocommit=true, attachment=dn4{select * from tb where id in (1,2,1) }, respHandler=null, host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.926   INFO [$_NIOREACTOR-1-RW] (AbstractConnection.java:452) -close connection,reason:program err:java.lang.IndexOutOfBoundsException: Index: 2, Size: 2 ,MySQLConnection [id=53, lastTime=1448413972903, schema=db3, old shema=db3, borrowed=true, fromSlaveDB=false, threadId=2157, charset=utf8, txIsolation=0, autocommit=true, attachment=dn3{select * from tb where id in (1,2,1) }, respHandler=SQLJob [ id=4,dataNodeOrDatabase=dn3,sql=select * from tb where id in (1,2,1) ,  jobHandler=demo.catlets.ShareRowOutPutDataHandler@11c5ed81], host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.927   INFO [$_NIOREACTOR-1-RW] (BatchSQLJob.java:41) -job finished SQLJob [ id=4,dataNodeOrDatabase=dn3,sql=select * from tb where id in (1,2,1) ,  jobHandler=demo.catlets.ShareRowOutPutDataHandler@11c5ed81]
11/25 09:12:52.927  DEBUG [$_NIOREACTOR-0-RW] (NIOReactor.java:101) -caught err:
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at demo.catlets.ShareRowOutPutDataHandler.onRowData(ShareJoin.java:370)
	at org.opencloudb.sqlengine.SQLJob.rowResponse(SQLJob.java:142)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:203)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:134)
	at org.opencloudb.net.handler.BackendAsyncHandler.offerData(BackendAsyncHandler.java:36)
	at org.opencloudb.mysql.nio.MySQLConnectionHandler.handle(MySQLConnectionHandler.java:79)
	at org.opencloudb.net.AbstractConnection.handle(AbstractConnection.java:257)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:307)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:268)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:96)
	at java.lang.Thread.run(Thread.java:745)
11/25 09:12:52.930   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:452) -close connection,reason:program err:java.lang.IndexOutOfBoundsException: Index: 2, Size: 2 ,MySQLConnection [id=54, lastTime=1448413972923, schema=db4, old shema=db4, borrowed=true, fromSlaveDB=false, threadId=2158, charset=utf8, txIsolation=0, autocommit=true, attachment=dn4{select * from tb where id in (1,2,1) }, respHandler=SQLJob [ id=5,dataNodeOrDatabase=dn4,sql=select * from tb where id in (1,2,1) ,  jobHandler=demo.catlets.ShareRowOutPutDataHandler@11c5ed81], host=172.16.4.83, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
11/25 09:12:52.930   INFO [$_NIOREACTOR-0-RW] (BatchSQLJob.java:41) -job finished SQLJob [ id=5,dataNodeOrDatabase=dn4,sql=select * from tb where id in (1,2,1) ,  jobHandler=demo.catlets.ShareRowOutPutDataHandler@11c5ed81]
11/25 09:12:52.931   INFO [$_NIOREACTOR-0-RW] (EngineCtx.java:171) -all job finished  for front connection: ServerConnection [id=8, schema=TESTDB, host=192.168.40.101, user=test,txIsolation=3, autocommit=true, schema=TESTDB]
11/25 09:12:52.931   INFO [$_NIOREACTOR-0-RW] (EngineCtx.java:159) -write  eof ,packgId:7
11/25 09:12:52.931   INFO [$_NIOREACTOR-0-RW] (ShareJoin.java:159) -发送数据OK
11/25 09:12:53.026  DEBUG [$_NIOREACTOR-1-RW] (ServerQueryHandler.java:56) -ServerConnection [id=8, schema=TESTDB, host=192.168.40.101, user=test,txIsolation=3, autocommit=true, schema=TESTDB]SHOW STATUS
11/25 09:12:53.027  DEBUG [$_NIOREACTOR-1-RW] (NonBlockingSession.java:113) -ServerConnection [id=8, schema=TESTDB, host=192.168.40.101, user=test,txIsolation=3, autocommit=true, schema=TESTDB]SHOW STATUS, route={
   1 -> dn4{SHOW STATUS

**Comment by digdeep126** [comment]
1.4,1.5,2.0 的该bug已经被完美解决了。而且1.5，2.0新增了支持 join 字段是varchar/char类型的sharejoin，原来只支持join 字段为 int/bigint。
