### ISSUE TITLE
MyCAT支持useServerPrepStmts=true&rewriteBatchedStatements=true特性吗？

### ISSUE THREAD

**Issue by maxid** [MyCATApache/Mycat-Server#63]
如题支持MySQL批处理特性吗？
useServerPrepStmts=true
rewriteBatchedStatements=true

**Comment by csuagent** [comment]
对于sql 注入的问题有什么好的建议？

**Comment by magicdoom** [comment]
sql注入  jdbc驱动会客户端预编译的      1.6已经支持预编译
