### ISSUE TITLE
close connection,reason:syn status unkown

### ISSUE THREAD

**Issue by owenludong** [MyCATApache/Mycat-Server#644]
mycat.log中打印了大量的这种日志：
12/11 11:32:26.984   INFO [$_NIOREACTOR-0-RW] (AbstractConnection.java:458) -close connection,reason:syn status unkown  ,MySQLConnection [id=20, lastTime=1449804746971, user=x, schema=x, old shema=x, borrowed=true, fromSlaveDB=false, threadId=134308235, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=x, port=3306, statusSync=org.opencloudb.mysql.nio.MySQLConnection$StatusSync@278fc222, writeQueue=0, modifiedSQLExecuted=false]

schema.xml中的配置如下：
<dataHost name="newHost2" maxCon="1000" minCon="10" balance="1" switchType="2" slaveThreshold="100"  writeType="0" dbType="mysql"
                dbDriver="native">

              <heartbeat>show slave status</heartbeat>

              <writeHost host="hostM1"
                url="x:3306" user="x" password="x">

                    <readHost host="hostS1" url="x:3306" user="x"
                        password="x" />

              </writeHost>
        </dataHost>

**Comment by mycatmerger** [comment]
已经修复
