### ISSUE TITLE
mycat1.4出现java.util.NoSuchElementException

### ISSUE THREAD

**Issue by chenxingbao** [MyCATApache/Mycat-Server#661]
连接MYCAT时，有时出现如下报错，连接不稳定
com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.util.NoSuchElementException

STACKTRACE:

java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1206)
	at java.util.TreeMap.lastKey(TreeMap.java:274)
	at com.mysql.jdbc.Connection.buildCollationMapping(Connection.java:1665)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3938)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:207)

**Comment by chenxingbao** [comment]
代码如下：
public int updateTest() throws Exception {
		Connection conn = null;
		int r = -2;
		try {
			
			Class.forName("com.mysql.jdbc.Driver");
			String url = "jdbc:mysql://115.28.245.118:8066/TESTDB?user=test&password=test";
			conn = DriverManager.getConnection(url);
			conn.setAutoCommit(false);
			String sql = "update mt_vm_type set vt_name=vt_name||'2' where vt_id=2";
			Statement st = conn.createStatement();		
			r = st.executeUpdate(sql);
		    conn.commit();
			//System.out.println(r);	
			conn.close();
		} catch (SQLException ex) {
			//ex.printStackTrace();
		} catch (ClassNotFoundException ex) {
			//ex.printStackTrace();
		} catch (Exception ex) {
			//ex.printStackTrace();
		} finally {
			if (conn != null && !conn.isClosed())
				conn.close();
		}
		return r;
	}
testdb test = new testdb();
			//test.selectTest();
			for(int i=1;i<=50;i++)
			{
				System.out.println("第"+i+"次,"+test.updateTest());
				Thread.sleep(500);
		    }

**Comment by chenxingbao** [comment]
在mycat.log中出现
12/15 18:07:33.768   WARN [$_NIOREACTOR-0-RW] (SetHandler.java:127) -ServerConnection [id=331, schema=TESTDB, host=110.172.222.6, user=test,txIsolation=3, autocommit=true, schema=TESTDB]SET sql_mode='STRICT_TRANS_TABLES' is not recoginized and ignored

**Comment by magicdoom** [comment]
jdk版本问题

**Comment by magicdoom** [comment]
从buildCollationMapping这里看出  是jdbc在初始化字符集时  字符集为空的错误 。。可能是jdbc版本问题  推荐5.1.35到37
