### ISSUE TITLE
mycat1.4+oracle+date/timestamp+ORA-01861

### ISSUE THREAD

**Issue by zz846** [MyCATApache/Mycat-Server#682]
分片db均为oracle, insert date与timestamp类型字段，报错ORA-01861: 文字与格式字符串不匹配
log中发现发送的sql中对应字段值均为字符串，是这两个类型没做oracle语法处理还是使用中需要做配置？

**Comment by magicdoom** [comment]
dataHost的initsql配置设置oracle日期格式的语句  具体参考单元测试里面的配置
