### ISSUE TITLE
select avg(id) from test ;

### ISSUE THREAD

**Issue by dicome** [MyCATApache/Mycat-Server#69]
在没有分库字段情况下，avg函数会发到每个库去执行，解析每个库执行的sql也都是select avg(id) from test ，这样最终的结果是错误的。需要每个库返回count(id),sum(id),最后merge的时候重新计算avg

**Comment by linzhiqiang0514** [comment]
目前avg应该是支持的，你可以测试看看。

**Comment by magicdoom** [comment]
1.4已经支持

**Comment by mycatmerger** [comment]
1.4已经支持
