### ISSUE TITLE
只读事物不能路由查询到读节点上

### ISSUE THREAD

**Issue by StruggleBird** [MyCATApache/Mycat-Server#699]
业务场景中涉及到复杂的代码块，如果该代码快内涉及到多条查询SQL并且只有查询SQL时，为了优化SQL的执行效率 ，我们会预先在把当前代码块所在的事物标记为只读事物 ，但是看到Mycat权威指南中并没有支持只读事务路由到读节点的功能（据说目前只能强制路由到写节点）。希望支持这一特性 ，感谢！

**Comment by mycatmerger** [comment]
可以通过加blance注解解决

**Comment by StruggleBird** [comment]
```java
public boolean canRunnINReadDB(boolean autocommit) {
		return canRunInReadDB && autocommit && !hasBlanceFlag
			|| canRunInReadDB && !autocommit && hasBlanceFlag;
	}
```
blanceFlag的注解/*balance*/ 必须手动植入到代码中，对代码产生了一定的侵入性，也让开发人员在功能开发时难度加大了。

**Comment by digdeep126** [comment]
新增了sql hint（注解）/*#mycat:db_type=slave*/ 来支持强制走slave的功能。至于侵入性的问题，未来可能会实现自动识别吧。

**Comment by digdeep126** [comment]
自动识别也是不妥的。master和slave是可能有延迟的，所以mycat-server不能自作主张将你的sql发往slave，除非你使用了注解hint.

**Comment by StruggleBird** [comment]
并不是所有的主从复制都是有延迟的，目前采用pxc集群方案的公司还挺多 。要不要自动识别可以交由使用者来决定比较好一些 ，关于这个特性，我会有时间来自己尝试实现下，看看效果怎样。

**Comment by digdeep126** [comment]
要实现无侵入性，你可以试试自己实现一个注解，将需要发往slave的事务就使用该注解，在注解中拦截sql，添加前缀 /*#mycat:db_type=slave*/

**Comment by digdeep126** [comment]
不能用特殊情况来要求中间件的。

**Comment by StruggleBird** [comment]
我并不认为这是一个小众需求，特别是针对java开发者并且用了spring框架的场景来说这种情况会显得很常见 ，可能也只是我这样认为 。

**Comment by digdeep126** [comment]
https://github.com/digdeep126/MySQLProtocolAnalyzer/tree/master/src/main/java/com/github/digdeep126/mycatutil
连接中使用 mybatis的拦截器机制，实现了你想要的效果： spring中@readonly 注解的sql路由到slave的功能。仅供参考(我没有测试)

**Comment by StruggleBird** [comment]
好的，随后我测试下 。

**Comment by bluoy** [comment]
感觉“默认将只读事务路由到读节点，但可以通过sql hint强制路由到写节点”的策略更合理些。

**Comment by StruggleBird** [comment]
是的，@digdeep126 提供了一种思路 ，通过拦截器能够按照自己的意愿来路由只读事物的sql，但我刚刚看了源码，可能忘记考虑原有sql上是否有注解的可能，如果已经有了注解，该拦截器就可以不在进行处理，也就实现了楼上的功能 。

**Comment by digdeep126** [comment]
新版加入了 bluoy 要的功能：/*#mycat:db_type=master*/ 和 /*#mycat:db_type=slave*/
