### ISSUE TITLE
mycat2.0版本使用过程问题

### ISSUE THREAD

**Issue by zhoubingbing** [MyCATApache/Mycat-Server#715]
INSERT into company values (8, '111111');
INSERT into company(id, NAME) values (9, '111111');
结果
第一条成功
第二条 报这个错误 [Err] 1105 - Unknown column '_mycat_op_time' in 'field list'
期望：
希望第二条成功

**Comment by digdeep126** [comment]
这个全局表唯一的限制，未来可能会被fix掉。
全局表的使用，请看文档：https://github.com/MyCATApache/Mycat-doc/blob/master/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3/2.0/%E5%85%A8%E5%B1%80%E8%A1%A8%E4%B8%80%E8%87%B4%E6%80%A7%E6%A3%80%E6%B5%8B%E5%92%8CSQL%E6%8B%A6%E6%88%AA%E6%94%B9%E5%86%99%E7%9A%84%E5%AE%9E%E7%8E%B0.docx

**Comment by zhoubingbing** [comment]
好的，多谢解惑

**Comment by digdeep126** [comment]
该问题已经被fix掉了。但同时：如果要使用语法insert into t values(),必须保证内部列'_mycat_op_time'是在全局表的末尾。要么就不要使用这种语法insert全局表。

**Comment by digdeep126** [comment]
该问题已经被fix掉了。全局表已经没有任何限制了。但还是建议使用带有列名的insert语法进行插入，建议不要以任何方式操作内部列，就当其不存在就行了。
