### ISSUE TITLE
建议：对于没有配置table的，使用create table 写入到默认db中去

### ISSUE THREAD

**Issue by zhoubingbing** [MyCATApache/Mycat-Server#716]
mycat目前 使用必须要配置表，否则不能使用create table ，
mycat 支持创建一个默认的db， 如果没有配置表，则将创建的表放到默认db中，这样使用肯定能更加方便快捷点，否则一个系统中如果有几百张表 那岂不是要配置几百次

**Comment by mycatmerger** [comment]
支持非分片表配置默认节点的

**Comment by magicdoom** [comment]
可以验证下1.5版本是否解决

**Comment by magicdoom** [comment]
1.6验证已经解决
