### ISSUE TITLE
使用mycat的注解调用存储过程出现本应该入到node1上面的数据；却入到node2上面了

### ISSUE THREAD

**Issue by low901028** [MyCATApache/Mycat-Server#718]
一、问题
    在使用mycat的注解调用存储过程出现本应该入到node1上面的数据；却入到node2上面了
二、调用
   MySqlCommand myCommand = new MySqlCommand("/*!MyCat: sql=SELECT age FROM T_TEST1 WHERE age="+(14000+i)+" and name="+("admin_" + i) +";*/ exec p_insert N'"+("admin_"+i)+"', "+(14000+i)+"", connection);
三、配置
 （1）、schema.xml
    <?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://org.opencloudb/">

	<schema name="DataCenter_Odds" checkSQLschema="false" sqlMaxLimit="100">
		<table name="T_TEST1_1" dataNode="dn1"/>
		<table name="T_TEST1" dataNode="dn1,dn2" rule="mod-long"/>			
	</schema>

	<dataNode name="dn1" dataHost="localhost1" database="DataCenter_Odds" />
	<dataNode name="dn2" dataHost="localhost2" database="DataCenter_Odds" />
	
	<dataHost name="localhost1" maxCon="1000" minCon="1" balance="1" writeType="0" dbType="sqlserver" dbDriver="jdbc">
		<heartbeat></heartbeat>
		<connectionInitSql></connectionInitSql>
		<writeHost host="hostM1" url="jdbc:sqlserver://10.33.97.24:1433" user="sa" password="jdd">
			<readHost host="hostS1" url="jdbc:sqlserver://10.33.97.24:1433" user="sa" password="jdd"></readHost>						
		</writeHost>
	</dataHost>
	<dataHost name="localhost2" maxCon="1000" minCon="1" balance="1" writeType="0" dbType="sqlserver" dbDriver="jdbc">
		<heartbeat></heartbeat>
		<connectionInitSql></connectionInitSql>
		<writeHost host="hostM2"  url="jdbc:sqlserver://10.33.97.22:1433" user="jdd" password="123456">
			<readHost host="hostS2" url="jdbc:sqlserver://10.33.97.22:1433" user="jdd" password="123456"></readHost>			
		</writeHost>
	</dataHost>
</mycat:schema>
（2）、rule.xml
    <tableRule name="mod-long">
		<rule>
			<columns>age</columns>
			<algorithm>mod-long</algorithm>
		</rule>
	</tableRule>
     <function name="mod-long" class="org.opencloudb.route.function.PartitionByMod">
		
		<property name="count">2</property>
	</function>
是否有什么地方写的有问题

**Comment by magicdoom** [comment]
使用最新版本测试     最新完整支持了存储过程  有问题再打开
