### ISSUE TITLE
2.0版配置自增长ID出错

### ISSUE THREAD

**Issue by wciq1208** [MyCATApache/Mycat-Server#719]
配置文件system节点中配置了
<property name="sequnceHandlerType">1</property>

sequence-config节点中配置了
<sequence type="1" class="io.mycat.server.sequence.IncrSequenceMySQLHandler"></sequence>

schema节点中配置了
<table name="mycat_sequence" primaryKey="name" dataNode="dn3" />

并且在dn3所在的真实数据库中执行了
https://github.com/MyCATApache/Mycat-doc/blob/master/%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97/sequnce-sql.txt文件【其中初始改为0，步进改为1】

添加test2数据库设置id为主键并且自增，且执行
INSERT INTO `mycat_sequence` (`name`, `current_value`, `increment`) VALUES ('TEST2', '0', '1');

接着尝试在sequence_conf.properties或者自己创建一个sequence_db_conf.properties文件当中添加
TEST2=dn1

最后在执行INSERT INTO test2(`fields`) VALUES('ssss')时报错
[SQL]INSERT INTO test2(`fields`) VALUES('ssss')
[Err] 1003 - mycat sequnce err.io.mycat.server.config.ConfigException: can't find definition for sequence :TEST2

请问一下是不是哪里设置错了？

**Comment by magicdoom** [comment]
2.0是实验性版本，请使用稳定版1.5
