### ISSUE TITLE
mycat自然月分片算法查询sql若不带表别名将会路由到所有分片

### ISSUE THREAD

**Issue by zhaoshijie** [MyCATApache/Mycat-Server#727]
失败的写法：
			EXPLAIN SELECT * FROM `common_access_log_date` where create_time BETWEEN '2016-01-01 18:26:31' and '2016-02-02 18:26:31';
	成功的写法：
			EXPLAIN SELECT * FROM `common_access_log_date` t where t.create_time BETWEEN '2016-01-01 18:26:31' and '2016-02-02 18:26:31';

**Comment by yanqingluo** [comment]
此问题在1.4.1dev 版本 没重现，请附上 schema rule 等配置文件，方便排查。

**Comment by zhaoshijie** [comment]
我用的版本是，1.4-release-last

是按照常规配置的（参考的mycat权威文档），没有任何特殊。



zhaoshijie168@126.com
 
发件人： yan.ll
发送时间： 2016-01-22 14:29
收件人： MyCATApache/Mycat-Server
抄送： zhaoshijie
主题： Re: [Mycat-Server] mycat自然月分片算法查询sql若不带表别名将会路由到所有分片 (#727)
此问题在1.4.1dev 版本 没重现，请附上 schema rule 等配置文件，方便排查。

**Comment by magicdoom** [comment]
create_time 是否是分片字段，另外测试1.5版本看看是否有解决

**Comment by magicdoom** [comment]
测试1.6已经fix 没这个问题
