### ISSUE TITLE
invalid datasource0

### ISSUE THREAD

**Issue by xiaoliuliu2050** [MyCATApache/Mycat-Server#742]
我的环境  ： jdk1.8    ,mac10.10,mysql 5.6
这是我的schema.xml 配置
![image](https://cloud.githubusercontent.com/assets/6425930/12575119/e5639f7c-c444-11e5-85f7-a955de9cc35d.png)
这是我的server.xml
![image](https://cloud.githubusercontent.com/assets/6425930/12575149/2f77d65a-c445-11e5-8fc8-8445ed788753.png)

通过这些配置，我现在可以连接到my cat了，但是，
做操作的时候 会报错
![image](https://cloud.githubusercontent.com/assets/6425930/12575163/4b04b276-c445-11e5-992c-5fba14a82021.png)
请帮帮我，谢谢
希望达到的效果就是，连接上my cat，可以对my cat，进行增删改查操作。

**Comment by luotianwen** [comment]
改成字母看下

**Comment by luotianwen** [comment]
datahost

**Comment by magicdoom** [comment]
这个错就是后端mysql无法访问报出的  检查后端db连通性  用户名密码等
