### ISSUE TITLE
1.4 稳定版本 批量插入异常

### ISSUE THREAD

**Issue by zhongjimax** [MyCATApache/Mycat-Server#745]
如果表sbtest1和sbtest2设定了全局序列自增长，则MyCAT无法实现批量插入且报如下错误：
bad insert sql columnSize != valueSize:4 != 3values: VALUES (500739, '500739', '500739')

但如果撤销表sbtest1和sbtest2的全局序列自增长，则可以实现批量插入。

这个情况是我配置的问题，还是1.4存在的BUG，在1.5版本里是否修正了这个问题呢？

**Comment by magicdoom** [comment]
这个需要用注解
