### ISSUE TITLE
1.3.0.3使用ER关系构建分库会出第三层子节点找不到父节点的错误

### ISSUE THREAD

**Issue by lsdaliang** [MyCATApache/Mycat-Server#747]
myCat版本：1.3.0.3-alpha-20150211版本
配置schema相关代码：
`<table name="Employee" primaryKey="uuid" rule="sharding-by-murmur" dataNode="dn1,dn2,dn3">`
      `<childTable name="User" primaryKey="uuid" joinKey="employeeUuid" parentKey="uuid">`
       ` <childTable name="Issue" primaryKey="uuid" joinKey="userUuid" parentKey="uuid">`
          `<childTable name="IssueParticipatorInfo" primaryKey="uuid" joinKey="issueUuid" parentKey="uuid" />`
        `</childTable>`
    `</childTable>`
`</table>`

Employee表和User表可以依照对应分库完美insert，但是在insert Issue表的时候会报cant find (root)parent sharding node for sql：（Insert Into issue('uuid','userUuid')values('4000100020','10890001)）这个错误（insert 语句均是由数据库工具生成所以基本可以排除insert语句出错的问题，其他insert语句可以插入也侧面证明insert语句的正确性）
权威指南中描述的父子表在一个事物中的问题也不存在，因为我是先insert的父级表再insert子集表。

问题测试描述：
根据这个问题，我测试了一下当前库表，对应的userUuid在dn1中可以找到，insert语句，大小写等等问题都已经被排除。
本着探究问题的原则我尝试着插入了另一条数据，这条数据关联了另外一个user的主键。然后用explain命令分析了一下insert语句。首先这条user的数据被分在了dn2上，explain insert后，确实是应该插入到dn2上。然而，在我执行该条insert之后，发现他像全局表一样分在了三个库上。

以下是问题测试描述操作的结果截图
[errPic.zip](https://github.com/MyCATApache/Mycat-Server/files/115049/errPic.zip)

其他的这种Er table关系insert到第三层childTable也会时不时的出现这种问题。刚入门mycat，真心求教，谢谢各位大神指点。

**Comment by magicdoom** [comment]
1.3版本太老了  请用最新1.5正式版测试看看，如果没问题就关闭

**Comment by djx1314520** [comment]
ai
