### ISSUE TITLE
having子句无效

### ISSUE THREAD

**Issue by lingengbin** [MyCATApache/Mycat-Server#753]
select avg(id) as avg, name from customer group by name 返回[5.0, 'xx']， 
select avg(id) as avg, name from customer group by name having avg > 6; 同样返回[5.0, 'xx']

**Comment by winbillatgithub** [comment]
你好，测试没有发现错误，请将你的环境请描述一下？
我的测试结果：
bogon:shell winbill$ ./mysql.sh 
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.5.8-mycat-1.6-DEV-20160301234813 MyCat Server (OpenCloundDB)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use oe;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select avg(id) as avg, username from u_user group by username having avg > 6;
+------+------------+
| AVG  | username   |
+------+------------+
|  3.0 | shiwenbiao |
+------+------------+
1 row in set (0.04 sec)

**Comment by winbillatgithub** [comment]
目前来看having被屏蔽了
