### ISSUE TITLE
show slave status 检测 master slave 同步时间不精准

### ISSUE THREAD

**Issue by zhuam** [MyCATApache/Mycat-Server#756]
02/24 18:48:19.937   WARN [$_NIOREACTOR-6-RW] (MySQLDetector.java:158) -found MySQL master/slave Replication delay !!! DBHostConfig [hostName=host1, url=192.168.xx:3306], binlog sync time delay: 9602378s

02/24 20:49:40.031   WARN [$_NIOREACTOR-7-RW] (MySQLDetector.java:158) -found MySQL master/slave Replication delay !!! DBHostConfig [hostName=host1, url=192.168.xx:3306], binlog sync time delay: 97999s

02/24 22:49:00.130   WARN [$_NIOREACTOR-0-RW] (MySQLDetector.java:158) -found MySQL master/slave Replication delay !!! DBHostConfig [hostName=host1, url=192.168.xx:3306], binlog sync time delay: 105159s

02/25 00:39:10.203   WARN [$_NIOREACTOR-7-RW] (MySQLDetector.java:158) -found MySQL master/slave Replication delay !!! DBHostConfig [hostName=host1, url=192.168.xx:3306], binlog sync time delay: 111769s

02/25 03:49:00.346   WARN [$_NIOREACTOR-0-RW] (MySQLDetector.java:158) -found MySQL master/slave Replication delay !!! DBHostConfig [hostName=host1, url=192.168.xx:3306], binlog sync time delay: 123159s

**Comment by zhuam** [comment]
参加 http://imysql.com/2014/08/30/mysql-faq-howto-monitor-slave-lag.shtml

**Comment by magicdoom** [comment]
这个是不太精确  有一种方案是弄个监控表   可以考虑改进纳入
