### ISSUE TITLE
Mycat-server-1.5-GA-20160225120029 对DDL支持不完善

### ISSUE THREAD

**Issue by digdeep126** [MyCATApache/Mycat-Server#757]
schema.xml中有如下配置：
`<table name="hotnews" primaryKey="ID" dataNode="dn1,dn2,dn3" rule="mod-long" />`
各个节点实际上还没有 hotnews 表，使用下面的语句建表：
create table hotnews(id int not null auto_increment priamry, content varchar(255));
时，默认仅仅在 dn1 节点上建表，dn2,dn3对应的节点上不会执行建表语句。
drop table hotnews; 是正常的在指定的dataNode上执行。
全局表不存在该问题，是按照其指定的dataNode来执行的。

**Comment by magicdoom** [comment]
你看看修改提供pr

**Comment by digdeep126** [comment]
又测试过，发现 win 版有该问题，但是 Linux 版没有...
我在看看

**Comment by magicdoom** [comment]
检查下是否跟配置默认节点有关系

**Comment by magicdoom** [comment]
测了下 貌似没问题   先关闭  有问题再打开
