### ISSUE TITLE
关于基于数据库的全局序列号的配置

### ISSUE THREAD

**Issue by digdeep126** [MyCATApache/Mycat-Server#758]
基于数据库的全局序列号的配置，目前需要在 sequence_db_conf.properties 文件中进行配置如下的配置：
GLOBAL=dn1
USER=dn1
COMPANY=dn1

感觉应该可以直接在schema.xml中配置，无需sequence_db_conf.properties文件了：
`<table name="mycat_sequence" primaryKey="ID" type="global" dataNode="dn1" />`
经过测试，这样配置也是可行的。不过不支持将不同的 sequence 放到不同的dataNode上。只能将所有sequence放在一个dataNode上。
1.5的配置文件比较杂多。

**Comment by magicdoom** [comment]
这个后续会合并配置的
