### ISSUE TITLE
命令行连接Mycat 中文显示乱码，windows环境

### ISSUE THREAD

**Issue by sohudo** [MyCATApache/Mycat-Server#76]
命令行连接Mycat 中文显示乱码，windows环境下运行mycat和mysql命令行工具
mysql>  select id,name,vip from users order by id limit 5;
+----+-----------+--------------+
| id | name      | vip          |
+----+-----------+--------------+
|  1 | 濮氬埄钀?   | 鏅€氱敤鎴?    |
|  2 | 鍚村織鍑?   | 鏅€氱敤鎴?    |
|  3 | 寮犲皯绋?   | 鏅€氱敤鎴?    |
|  4 | 璋匠鏄?   | 鏅€氱敤鎴?    |
|  5 | 鍚村€?     | 鏅€氱敤鎴?    |
+----+-----------+--------------+
5 rows in set (0.01 sec)

JDBC连接mycat和命令行直接连接mysql 都正常

**Comment by apachemycat** [comment]
字符集问题有特殊性，Mycat  server.xml里面可以设置属性<property name="charset">utf-8</property>，但这个只影响客户端连接Mycat的字符集，Mycat连接MySQL的字符集，目前1.3.0.1的代码里则是由MySQL端的字符集决定的（握手报文中的server_language属性，对于character_set_server属性），
mysql> show variables like '%char%';
+--------------------------+----------------------------------------+
| Variable_name            | Value                                  |
+--------------------------+----------------------------------------+
| character_set_client     | utf8                                   |
| character_set_connection | utf8                                   |
| character_set_database   | latin1                                 |
| character_set_filesystem | binary                                 |
| character_set_results    | utf8                                   |
| character_set_server     | latin1                                 |
| character_set_system     | utf8                                   |
| character_sets_dir       | C:\mysql-5.6.13-winx64\share\charsets\ |
+--------------------------+----------------------------------------+
8 rows in set

建议 mysql的 character_set_server   ，character_set_database  ， character_set_client ，character_set_connection，character_set_results，character_set_system   等全部是UFT-8
