### ISSUE TITLE
ERROR 3009 (HY000): java.lang.IllegalArgumentException: Invalid DataSource:0

### ISSUE THREAD

**Issue by tanqr** [MyCATApache/Mycat-Server#760]
1.基本信息
CentOS release 6.7 (Final)
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.4.el6-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
mycat 1.5
2.mycat配置
    <dataHost name="testhost" maxCon="1000" minCon="10" balance="1"
       writeType="0" dbType="mysql" dbDriver="native">
       <heartbeat>select 1</heartbeat>
       
       <writeHost host="hostM1" url="192.168.0.101:3310" user="root" password="111" />
	   <writeHost host="hostM2" url="192.168.0.102:3310" user="root" password="111" />
    </dataHost>
![image](https://cloud.githubusercontent.com/assets/14049379/13384654/a24de32a-ded2-11e5-8399-09f36aa00e52.png)

3.问题描述。
经测试错误跟启动顺序有关。
3.1当hostM1关闭，hostM2开启的状态下，启动mycat，执行show tables，就会报标题的错误。启动hostM1后就正常了。
3.2当hostm1,hostm2都开启，再启动mycat，再停掉hostm1，此时不会报如上错误。

4.个人分析
    经反复测试，问题重现和启动顺利有关，个人觉得这是个bug，请问这个问题如何解决。

**Comment by magicdoom** [comment]
这个不是bug，默认是不自动切换  所以你hostM1关闭了   执行sql就会报错了

**Comment by tanqr** [comment]
@magicdoom  ，请看我截图中的配置参数 writeType=0, 自动切换已经打开，而且在按我提到的3.2的顺序启动了，经过实测，是可以自动切换的。

**Comment by Michaeljian** [comment]
请问这个问题现在我也出现了，但是具体是怎么解决呢，求教
![image](https://user-images.githubusercontent.com/16465064/39700842-5aa12b34-5231-11e8-8b50-476cdbf2acc1.png)
