### ISSUE TITLE
ER分片子表插入数据报错

### ISSUE THREAD

**Issue by songwie** [MyCATApache/Mycat-Server#763]
ER分片子表插入数据报错  如果子表的分片字段是字符串类型 在使用 字符串截取数据路由的规则中 
insert 操作中value 会报错 原因是 druid 解析出的 value 中 字符串为‘aaa’ 值解析的加了引号 导致截取字符串的时候报错

java.lang.NumberFormatException: For input string: "'0"

规则：
PartitionDirectBySubString

配置：
slice("0:2")

**Comment by magicdoom** [comment]
引号的问题  已经修复
