### ISSUE TITLE
插入和更新数据转义问题

### ISSUE THREAD

**Issue by jasonjoo2010** [MyCATApache/Mycat-Server#766]
在更新和插入数据时，当最后一个字符为\的时候，会出现转义问题，例：

update t set a = 'test just for test\\' where id = 3;

值将变成

test just for test'

而非是预计的

test just for test\

**Comment by jasonjoo2010** [comment]
涉及到的代码是DefaultSqlInterceptor这个类

**Comment by digdeep126** [comment]
这个应该是以前为了支持foundationdb parser导致的问题，将那行代码注释就行了。

**Comment by jasonjoo2010** [comment]
ok，主要是不知道还会不会支持所以是注释还是改，建议release中也更新下，现在生产中还是推荐release版本吧？

**Comment by digdeep126** [comment]
foundationdb 被 apple 收购了，github上都没有了....没法用了。已经看过代码，目前 Mycat根本就无法使用fondationdb parser. 相关初始化代码在 RouteStrategyFactory 类中。

要改也很简单，DefaultSqlInterceptor中的：
`Pattern.compile("\\'", Pattern.LITERAL);`
改为：
`Pattern.compile("[^\\]\\'", Pattern.LITERAL);`
就是排除掉 同时出现 两个 '\' 和一个 ' 的情况，就行了。

**Comment by jasonjoo2010** [comment]
ok，感谢，这个改动铺到了哪些分支了？现在的线上使用环境建议follow哪个分支呢？

**Comment by digdeep126** [comment]
1.6 开发版改了。1.5 稍后再改。

**Comment by xulei2016** [comment]
1.66版本仍然存在问题，请问解决了吗
