### ISSUE TITLE
jumpConsistentHash

### ISSUE THREAD

**Issue by fgy58963** [MyCATApache/Mycat-Server#772]
Mycat 1.5版本中，跳增一致性哈希分片，这个在目前的pdf文档中并没有被提及。在配置文件中也只有bucket数量一个设置。
这个导致一个问题，在数据迁移中并不知道数据运算使用的key。
这个key在配置文件中能否自定义？
Mycat-Server/src/main/java/io/mycat/route/function/PartitionByJumpConsistentHash.java

public static int jumpConsistentHash(-->final long key<--, final int buckets)

**Comment by magicdoom** [comment]
这个是一个志愿者提交  具体可以网上搜跳增hash的资料
