### ISSUE TITLE
配置逻辑库schema时能否支持正则

### ISSUE THREAD

**Issue by seanlook** [MyCATApache/Mycat-Server#777]
当前就是只是想把Mycat当做读写分离来用，不考虑分片，差不多就是当做mysql-proxy。但我一个数据库实例上面有10多个database，按照当前的配置方法，要在`schema.xml`中配置10多个schema，过于精细了。

如果schema支持正则匹配就好了，比如
```
<schema name="d_*" checkSQLschema="false" sqlMaxLimit="100" dataNode="dn1">
</schema>
```

**Comment by lvsazf** [comment]
强烈支持

**Comment by fireflyhoo** [comment]
这个功能略微叼逼, shema 需要在客户端展示,如果配置正则mycat就不知道到底有多少个 数据库(逻辑上的)
