### ISSUE TITLE
客户端DBeaver执行存储过程卡死，客户端连接主节点从节点执行OK,JDBC连接mycat执行OK。

### ISSUE THREAD

**Issue by roothomes** [MyCATApache/Mycat-Server#788]
mycat下面有一主三从的mysql，mycat端口 8066，主端口3306，从端口 3307 3308 3309
使用客户端 DBeaver 3.6.1，连接mycat 8066， 存储过程：
create procedure pro_add
(
   a int,
   b int
)
begin
   declare c int;
   if a is null then
      set a = 0;
   end if;
   if b is null then
      set b = 0;
   end if;
   set c = a + b;
   select c as sum;
end;

在DBeaver 3.6.1 与 SQLyog V11.13客户端执行存储过程的时候，出现卡顿：
call pro_add(10, 20);
使用客户端工具，连接3306 3307 3308 3309 都可以顺利执行。
使用JDBC连接mycat8066端口，也可以顺利执行。

**Comment by magicdoom** [comment]
存储过程最新已经支持返回out 和结果集 以及多个结果集   这个bug也修复了  参考群里文档
