### ISSUE TITLE
rule 按日期（天）分片 代码优化

### ISSUE THREAD

**Issue by jiang2015** [MyCATApache/Mycat-Server#809]
<function name="sharding-by-date" class="org.opencloudb.route.function.PartitionByDate">
		<property name="dateFormat">yyyy-MM-dd</property>
		<property name="sBeginDate">2016-04-04</property>
		<property name="sEndDate">2016-04-30</property> 
		<property name="sPartionDay">10</property> 
	</function>
以上的dateFormat配置单一，并且在执行sql的场合，日期格式必须是"yyyy-MM-dd"。并且不支持now()。
--------正确--------
mysql> insert into customer(id,name,phone,company_id,created_time,updated_time) values('12',"10000",null,1,'2016-04-04',now());
Query OK, 1 row affected (0.01 sec)
--------错误--------
mysql> insert into customer(id,name,phone,company_id,created_time,updated_time) values('13',"10000",null,1,'20160404',now());
ERROR 1064 (HY000): java.text.ParseException: Unparseable date: "20160404"

修改代码（PartitionByDate）：

package io.mycat.route.function;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.time.DateUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.text.ParseException;
import java.util.Date;

/**
 * 例子 按日期列分区 格式 between操作解析的范例
 * 
 * @author lxy
 */
public class PartitionByDate extends AbstractPartitionAlgorithm implements
        RuleAlgorithm {
    private static final Logger LOGGER = LoggerFactory
        .getLogger(PartitionByDate.class);

    private static final String SPILT_1 = ",";

    private static final String NOW = "now()";

    private String sBeginDate;
    private String sEndDate;
    private String sPartionDay;
    private String dateFormat;

    private String[] dateFormatArray = { "yyyy-MM-dd", "yyyyMMdd", "yyyy/MM/dd" };

    private long beginDate;
    private long partionTime;
    private long endDate;
    private int nCount;

    private static final long oneDay = 86400000;

    @Override
    public void init() {
        try {
            partionTime = Integer.parseInt(sPartionDay) * oneDay;

//			beginDate = new SimpleDateFormat(dateFormat).parse(sBeginDate).getTime();
            beginDate = this.getDateTime(sBeginDate);
            if (sEndDate != null && !sEndDate.equals("")) {
//			    endDate = new SimpleDateFormat(dateFormat).parse(sEndDate).getTime();
                endDate = this.getDateTime(sEndDate);
                nCount = (int) ((endDate - beginDate) / partionTime) + 1;
            }
        } catch (ParseException e) {
            throw new java.lang.IllegalArgumentException(e);
        }
    }

    @Override
    public Integer calculate(String columnValue) {
        try {
//			long targetTime = new SimpleDateFormat(dateFormat).parse(columnValue).getTime();
            long targetTime = this.getDateTime(columnValue);
            int targetPartition = (int) ((targetTime - beginDate) / partionTime);

            if (targetTime > endDate && nCount != 0) {
                targetPartition = targetPartition % nCount;
            }
            return targetPartition;

        } catch (ParseException e) {
            throw new java.lang.IllegalArgumentException(e);

        }
    }

    @Override
    public Integer[] calculateRange(String beginValue, String endValue) {
        return AbstractPartitionAlgorithm.calculateSequenceRange(this,
            beginValue, endValue);
    }

    public void setsBeginDate(String sBeginDate) {
        this.sBeginDate = sBeginDate;
    }

    public void setsPartionDay(String sPartionDay) {
        this.sPartionDay = sPartionDay;
    }

    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
        if (StringUtils.isNotBlank(dateFormat)) {
            if (dateFormat.contains(SPILT_1)) {
                this.dateFormatArray = this.dateFormat.split(SPILT_1);
            } else {
                this.dateFormatArray = new String[this.dateFormat.length()];
            }
        }
    }

    public String getsEndDate() {
        return this.sEndDate;
    }

    public void setsEndDate(String sEndDate) {
        this.sEndDate = sEndDate;
    }

    private long getDateTime(String columnValue) throws ParseException {

        return columnValue.equalsIgnoreCase(NOW) ? (new Date()).getTime()
            : DateUtils.parseDate(columnValue, dateFormatArray).getTime();
    }
}

**Comment by magicdoom** [comment]
你这个同时用多个日期格式不太好吧

**Comment by magicdoom** [comment]
同时有多种日期格式的字符串输入  不太合理
