### ISSUE TITLE
explain 注解的问题

### ISSUE THREAD

**Issue by huangll99** [MyCATApache/Mycat-Server#811]
explain /*!mycat:dataNode=dn1 */ SELECT seq_fun;
上面的语句mycat不能正确地执行，原因是截掉了explain之后没有trim,再拿截取后的字符串跟OLD_MYCAT_HINT或NEW_MYCAT_HINT做startwith()比较，总是返回false。
修改办法：在ExplainHanler的handle方法中第一行
stmt = stmt.substring(offset);改为
stmt = stmt.substring(offset).trim();

**Comment by magicdoom** [comment]
提交 pull request

**Comment by magicdoom** [comment]
已经提交到1.6分支 请验证
