### ISSUE TITLE
schema.xml中 配置 checkSQLschema="true" ，sql语句中含schema时，有bug

### ISSUE THREAD

**Issue by maoxueqiang** [MyCATApache/Mycat-Server#815]
schema.xml中 配置
	&lt;schema name="TESTDB" checkSQLschema="**true**" sqlMaxLimit="100" dataNode="dndefault"&gt;
		&lt;table name="sam_test" primaryKey="id_" dataNode="dn1,dn2" **autoIncrement="true"**
                        rule="mod-long-2" /&gt;
启用全局自增长sequence。

执行以下2句SQL：
1) INSERT INTO sam_test(name_,  user_id)   VALUES('mmm',233);  -- 执行正确，id取到了全局自增sequence；
2) INSERT INTO TESTDB.sam_test(name_,  user_id ) VALUES('23333dd',233); 
语句执行正确，但是id没有用全局自增sequence，而是表的自增id，与预期不符。

源码分析：
AbstractRouteStrategy.java

                  /** 
		 * 路由
		 */              
                  public RouteResultset route(SystemConfig sysConfig, SchemaConfig schema, int sqlType, String origSQL,
			String charset, ServerConnection sc, LayerCachePool cachePool) throws SQLNonTransientException {
                 
                 /** 
		 * 处理一些路由之前的逻辑
		 */
		if ( beforeRouteProcess(schema, sqlType, origSQL, sc) )
			return null;

		/**
		 * SQL 语句拦截
		 */
		String stmt = MycatServer.getInstance().getSqlInterceptor().interceptSQL(origSQL, sqlType);
		if (origSQL != stmt && LOGGER.isDebugEnabled()) {
			LOGGER.debug("sql intercepted to " + stmt + " from " + origSQL);
		}

		if (schema.isCheckSQLSchema()) {
			stmt = RouterUtil.removeSchema(stmt, schema.getName());
		}
}
 

看到removeSchema是beforeRouteProcess之后。即beforeRouteProcess处理SQL时包含schema信息，无法正确获取表配置信息。
		String tableName = StringUtil.getTableName(origSQL).toUpperCase(); //tableName:TESTDB.sam_test
		TableConfig tableConfig = schema.getTables().get(tableName);
                tableConfig 结果是null

**Comment by magicdoom** [comment]
请提交pull request吧

**Comment by magicdoom** [comment]
1.6已经修改  欢迎测试
