### ISSUE TITLE
Mycat与MySQL分表分区

### ISSUE THREAD

**Issue by kingzone** [MyCATApache/Mycat-Server#819]
使用了Mycat 的分表分库之后，还能同时用MySQL 自己的分表分区吗？推荐这样用吗，有什么需要注意的呢？

**Comment by kingzone** [comment]
第二个问题是，Mycat分库分表是不是一般不与MySQL的主从复制同时使用，如果能同时使用，是什么应用场景呢？

**Comment by magicdoom** [comment]
可以结合使用       同步由db自己完成 mycat不负责

**Comment by kingzone** [comment]
Writehost和readhost的同步是在哪个类实现的呢？

**Comment by magicdoom** [comment]
mycat不负责数据库同步

**Comment by kingzone** [comment]
那配置读写分离后，写入的数据如何从master到slave呢？

**Comment by HashZhang** [comment]
这个主从同步MySQL自带有binlog复制，并且5.7之后性能更好。MyCat只作为业务层和数据库层的一个中间件，让他去做数据库层的同步不太合适。

**Comment by kingzone** [comment]
嗯，mycat的读写分离配置还是要依赖于mysql的主从复制配置的，所以读写分离的粒度还是受此限制。
