### ISSUE TITLE
Python链接MyCat字符集报错

### ISSUE THREAD

**Issue by daiguadaidai** [MyCATApache/Mycat-Server#822]
**错误：**mysql.connector.errors.DatabaseError: 1115 (HY000): Unknown charset ''utf8' COLLATE 'utf8_general_ci''

**环境：**
MySQL Python API：mysql-connector-python-2.1.3
MyCat 1.5

**解决：**
1、找到自己的mysql-connector-python安装路径
```
python
import sys
sys.path

/usr/local/Canopy_64bit/User/lib/python2.7/site-packages
```

2、进入 mysql-connector-python 安装路径
`cd /usr/local/Canopy_64bit/User/lib/python2.7/site-packages/mysql/connector`

3、通过报错关键字找到 在哪个文件哪行
```
grep -n NAMES *
abstracts.py:653:        # self._execute_query("SET NAMES '{0}' COLLATE '{1}'".format(
```
可以看到在 abstracts.py 文件的 653 行

4、注释这行代码
```
cp abstracts.py abstracts.py_$(date +%F)
vim abstracts.py +653
        # self._execute_query("SET NAMES '{0}' COLLATE '{1}'".format(
        #     charset_name, collation_name))
```

**Comment by magicdoom** [comment]
多谢分享   建议写入mycat权威指南   联系群里  从零开始

**Comment by zhuam** [comment]
该错误，在1.6下应该不会再报错误，我已经修复了
