### ISSUE TITLE
代码修改意见

### ISSUE THREAD

**Issue by jiang2015** [MyCATApache/Mycat-Server#825]
io.mycat.backend.ConMap 中 
源：
private BackendConnection tryTakeCon(ConQueue queue, boolean autoCommit) {
BackendConnection con = null;
if (queue != null && ((con = queue.takeIdleCon(autoCommit)) != null)) {
            return con;
        } else {
            return null;
        }}
修改后：
return queue != null ? queue.takeIdleCon(autoCommit) : null;

**Comment by jiang2015** [comment]
类：io.mycat.backend.ConQueue
原：	public boolean isSameCon(BackendConnection con) {
		if (autoCommitCons.contains(con)) {
			return true;
		} else if (manCommitCons.contains(con)) {
			return true;
		}
		return false;
	}
改： return this.autoCommitCons.contains(con) || this.manCommitCons.contains(con);

**Comment by HashZhang** [comment]
哈哈，这个减少代码行数，但是可读性降低了吧

**Comment by linkerlin** [comment]
可读性提升了

**Comment by magicdoom** [comment]
可以提交 pull request
