### ISSUE TITLE
JDBCConnection class include some unimplemented method.

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#83]
for example: query(), recordSql(), etc.

**Comment by stonelion** [comment]
this class do not not meet JDBC standand,so it do not implement the java.sql.Connection interface.these method is not necessary to implement.

**Comment by bluoy** [comment]
FetchStoreNodeOfChildTableHandler's connectionAcquired() will call this query() method. when BackendConnection is JDBCConnection, it's a error because of this  unimplemented method.

**Comment by stonelion** [comment]
yes,the JDBCConnection class have some unimplemented method.These method will be completed in the future.

**Comment by bluoy** [comment]
Do you have a schedule? The jdbc connection is a important feature, better than others。

**Comment by stonelion** [comment]
Of course The jdbc connection  is a important feature.it is difficult to implement the jdbc connection,because the heartbeat,transfer resultset and so on.

**Comment by bluoy** [comment]
Our team  is evaluating Mycat. 
Can you give us some detail what you said? maybe we can do something...

**Comment by apachemycat** [comment]
There are some ugly codes in Mycat  ,some thing like query() method in JDBC Driver, it's not called at all but used in NIO MySQL Connection ,because it's difficult to abstract  BIO Driver and NIO Driver.

**Comment by apachemycat** [comment]
If anyone can take part in code or test jobs ,it's very helpful!

**Comment by bluoy** [comment]
we will try it...
