### ISSUE TITLE
怎么用maven编译源码？

### ISSUE THREAD

**Issue by linkerlin** [MyCATApache/Mycat-Server#831]
直接mvn package会报错。
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.3:create (default) on project Mycat-server: Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:1.3:create failed: Plugin org.codehaus.mojo:buildnumber-maven-plugin:1.3 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:buildnumber-maven-plugin:jar:1.3 -> org.apache.maven.scm:maven-scm-provider-gitexe:jar:RELEASE: Failed to read artifact descriptor for org.apache.maven.scm:maven-scm-provider-gitexe:jar:RELEASE: Failed to resolve version for org.apache.maven.scm:maven-scm-provider-gitexe:jar:RELEASE: Could not find metadata org.apache.maven.scm:maven-scm-provider-gitexe/maven-metadata.xml in local (C:\Users\Administrator\.m2\repository) -> [Help 1]

**Comment by linkerlin** [comment]
1.6 分支代码

**Comment by linkerlin** [comment]
windows 10 环境，不能编译，报上面的错误。
但是在一台Mac上可以编译。

**Comment by magicdoom** [comment]
这个测试了  没有问题的    应该是你配置哪里的问题
