### ISSUE TITLE
druidparser 分区字段会路由，like 情况下会报错

### ISSUE THREAD

**Issue by Hisen158** [MyCATApache/Mycat-Server#84]
说明：
druid解析器会走自定义分片规则，导致分片字段like 情况下异常，
 (RouterUtil.java:673) -can't find any valid datanode :

重现：
如sql 为 select * from table where 分区字段  like  '%3233%'
会传递到路由函数导致，
Integer nodeIndex = tableConfig.getRule().getRuleAlgorithm().calculate(pair.colValue);//RouterUtil.java -line 669

解决意见：
1.不支持like，如果like 分区字段，直接跳过，全节点筛选。
2.支持like , Integer nodeIndex  应该返回 Integer[]  nodeIndexs ,这个和路由规则有关。 
3.让路由函数子定义自己处理，希望pair.colValue 去掉 %或者_

**Comment by Hisen158** [comment]
master 和 1.3.0.2 版本下均存在此issue

**Comment by stonelion** [comment]
按照你的错误，我用select * from travelrecord where id like '%1%'; 报的错误是err:java.lang.NumberFormatException: For input string: "%1%"，已经是可以在路由计算函数里面进行自定义。没重现你的问题。能否发具体表和数据？

**Comment by wdw1206** [comment]
已修复，like条件全部忽略，不参与路由条件计算
