### ISSUE TITLE
分片的时候，关于每个数据库表ID唯一性的问题。

### ISSUE THREAD

**Issue by littleyang** [MyCATApache/Mycat-Server#849]
如果把一个表拆分到六个服务器上面。如果我在每个服务器上实现了ID唯一性的策略。也就是说不需要mycat验证id唯一性，怎么配置呢？

**Comment by magicdoom** [comment]
这个使用问题 去看权威指南 或者到群里交流

**Comment by littleyang** [comment]
那个文档似乎没写啊。看过了好几次呢。@magicdoom

**Comment by luotianwen** [comment]
用mycat的主键生成
