### ISSUE TITLE
浮点型数字函数truncate无法通过mycat的代理解析

### ISSUE THREAD

**Issue by naxiwer** [MyCATApache/Mycat-Server#852]
select truncate(12.0123,2);
mysql直连给出的结果会是 12.01

但通过mycat的代理，查询报错：

ERROR 1064 (HY000): com.alibaba.druid.sql.parser.ParserException: ERROR. token : TRUNCATE, pos : 15

我的mycat版本是 Mycat-server-1.5.1-RELEASE-20160416173036

**Comment by zhuam** [comment]
已经代为转到 druid

**Comment by zhuam** [comment]
https://github.com/alibaba/druid/issues/1208

**Comment by zhuam** [comment]
Druid 官方已修复
https://github.com/alibaba/druid/issues/1208

**Comment by naxiwer** [comment]
ok,thanks
