### ISSUE TITLE
1.5.1 release版中，读写分离，事务内执行查询，balance指定为1，无法走从节点？

### ISSUE THREAD

**Issue by snowqoo228** [MyCATApache/Mycat-Server#864]
balance注释为什么没有起作用，是写法问题，还是什么问题？大家帮忙看看

schema.xml:

`<dataHost name="mysql_newhaolyy" maxCon="1000" minCon="10" balance="1"
             writeType="0" dbType="mysql" dbDriver="native">
                
                <heartbeat>select user()</heartbeat>
                
                <writeHost host="hostM1" url="192.168.4.221:3306" user="root" password="sfsdfsd">
                        
                        <readHost host="hostS1" url="192.168.4.220:3306" user="root" password="sfsdfsd" weight="1"/>
                </writeHost>
        </dataHost>`

1、做了个测试，跑了一段查询:
select * from haolyy_users where mobile='13903330000140' limit 1;
走的是220，没有问题，

2、事务内，跑一段查询
set autocommit = 0;
select *  from haolyy_users where mobile='13900000140' limit 1;
commit;
走的是221，

根据1.5.1权威指南【事务内的SQL，默认走写节点，以注释/*balance*/开头，则会根据balance=“1”或“2”去获取】
也没有问题，

3、增加balance注释，想让他走220，hostS1
/*balance*/ select * from haolyy_users where mobile='13903330000140' limit 1;
select /* + balance */ * from haolyy_users where mobile='13903330000140' limit 1;
两种方法都试过，可结果走的还是221

**Comment by HashZhang** [comment]
是：/*balance*/ select * from haolyy_users where mobile='13903330000140' limit 1;

**Comment by HashZhang** [comment]
有人把那边的源代码改了。。。你应该这么写语句：/*db_type=slave*/ select * from haolyy_users where mobile='13903330000140' limit 1;

**Comment by snowqoo228** [comment]
好像还是不行，
`set autocommit = 0;
/*db_type=slave*/ select * from haolyy_users where mobile='13903330000140' limit 1;
commit;
`
下面为日志：
![default](https://cloud.githubusercontent.com/assets/19237589/15102452/99c0d8a2-15d2-11e6-8b22-179fb1f189b6.png)

**Comment by HashZhang** [comment]
这个可能还是有问题，只要加上事务就不判断/*db_type=slave*/直接走写节点。。你们前端用的什么框架？是Hibernate还是MyBatis，建议用MyBatis，MyBatis针对查询可以控制是否加上事务。我们之后可能会优化这里的代码，但是比较纠结，因为无法严格判断你这个事务是否只含有查询语句，你强制加上/*db_type=slave*/，可能逻辑不严谨。。。

**Comment by snowqoo228** [comment]
前端php代码，直连数据库的，目前是手动开启事务和关闭事务，强制加上/*db_type=slave*/，事务里面包含多个DML语句的话，逻辑方面都会有些问题的吧。

**Comment by zhuam** [comment]
含事务，走主

**Comment by HashZhang** [comment]
最好业务上控制下，纯查询不加事务

**Comment by naxiwer** [comment]
我也遇到过这个问题，今天才发现大神的解决方法。
 原来是注释方式变了，怎么官方文档里面没有说明呢？要浪费多少脑细胞哦~~

**Comment by HashZhang** [comment]
哈哈

**Comment by magicdoom** [comment]
db_type=slave这个注解1.6才引入     1.5里所以这个是个bug     各位可以跟踪下代码看看

**Comment by HashZhang** [comment]
我看1.5的源代码也是这么解析了

**Comment by jiawenjun1126** [comment]
我这就是配置了balance='1' 和'2' 和'3' 都试够了 貌似没有起作用啊,还只是走writeHost 里面的readHost不走.
<schema name="mycat-oasis" checkSQLschema="false" sqlMaxLimit="100">
		<table name="user" primaryKey="ID" dataNode="dn1,dn2,dn3,dn4,dn5,dn6,dn7,dn8,dn9,dn10" rule="mod-long"/>
	</schema>
	<dataNode name="dn1" dataHost="localhost1" database="oasis-1" />
         .....
	<dataNode name="dn10" dataHost="localhost1" database="oasis-10" />
	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="1"
		writeType="0" dbType="mysql" dbDriver="native" tempReadHostAvailable="1" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" url="192.168.1.50:3306" user="root"
			password="w-oasis123456">
			<readHost host="hostS2" url="192.168.1.51:3306" user="root" password="w-oasis123456" />
			<readHost host="hostS3" url="192.168.1.52:3306" user="root" password="w-oasis123456" />
		</writeHost>
	</dataHost>
我是1.5源码跑的 能否指导一下,我故意将从库中的数据修改了 验证是否走从库查询 但是还是走的主库.

**Comment by HashZhang** [comment]
你看看你是否用了事务，用事务只会走master

**Comment by jiawenjun1126** [comment]
我是用jdbc直接连的mycat 并且con.setAutoCommit(false);设置为fasle了 应该没有事务啊.

**Comment by HashZhang** [comment]
con.setAutoCommit(false);应该为true才是没有事务吧

**Comment by jiawenjun1126** [comment]
true 没有事务,OK,果然是事务的问题.

**Comment by magicdoom** [comment]
确认下是不是  不是bug    。如果不是就关闭吧
