### ISSUE TITLE
逻辑库用户的秘密是明码

### ISSUE THREAD

**Issue by liyongxian** [MyCATApache/Mycat-Server#872]
在server.xml配置逻辑用户时，秘密只能是明码，能支持加密算法吗，像AES算法，进行加密吗？

**Comment by HashZhang** [comment]
可以是密文密码，1.5已经支持：涉及工具类，用这个类可以生成密文密码：org.opencloudb.util.DecryptUtil。传入参数：1:host:user:password
1代表是后端db，host是连接串（ip+端口），user是用户名，password是密码。
设置usingDecrypt属性为1，在密码处填这个类的输出
