### ISSUE TITLE
用客户端 Navicat Premium 连接时，有报错提示信息

### ISSUE THREAD

**Issue by liyongxian** [MyCATApache/Mycat-Server#873]
部署的是Mycat 1.5版本，部署成功后， 用Navicat Premium 连接Mycat时，有报错信息，但不影响查询结果。报错信息如下：
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/*100,3), '%') AS `百分比` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= ' at line 1。

**Comment by HashZhang** [comment]
把语句给一下。可以把日志调到debug看看navicat究竟发了什么语句。navicat发的很多语句druidparser解析有问题。建议用navicat中的命令行

**Comment by AskNathan** [comment]
你可以直接用mysql客户端连接，navicat在执行sql的时候，会发出一些客户端自带的sql，mycat的druidparser无法解析。所以会报错。

**Comment by magicdoom** [comment]
1.6已经fix
