### ISSUE TITLE
1.5 版本 非主键的唯一性约束不起作用

### ISSUE THREAD

**Issue by lihanxie** [MyCATApache/Mycat-Server#878]
在mycat1.5 中发现有些字段建了唯一性约束不起作用  比如 ： 订单号  order_no  
只有在当这个表所以的分片都存在了相同的订单号的时候才会报异常。
理想状态应该是  mycat会检查所有分片中的唯一约束

**Comment by HashZhang** [comment]
目前只靠后台数据库做这个唯一性约束，MyCat去做，效率太低。插入前需要先在每个分片去查一遍。请考虑在缓存中实现这个唯一键吧

**Comment by lihanxie** [comment]
但是高并发也有这个问题

**Comment by songgw** [comment]
这个需要中间层配合nosql生成唯一约束，这个唯一约束不应该是中间层来支持，太耗性能，据我所知业界百度、阿里都是中间层配合redis实现来保证的
