### ISSUE TITLE
mycat 1.3版本问题很多，希望开发团队注意

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#88]
自1.2.3版本后，引入了aio,druid等等好多新的内容，但这些内容测试不够充分，问题很多。
希望开发团队在添加新特性的时候，还是要优先保证原有的功能动作正常。

希望能够追加1.2.x的分支，继续维护。目前该版本序列应该是比较稳定可靠的。

**Comment by apachemycat** [comment]
谢谢建议，1.3.x系列，作了比较大性能优化，同时在稳定性方面也有进一步提升，aio,druid都是第二套组件，目前默认并未开启，截至当前所发现的Bug，也多围绕Druid解析器，预计下个版本，这个解析器会真正成熟。另外建议你也加入Mycat开源研发，一起做中国最好开源软件。
