### ISSUE TITLE
mycat 1.5中查询中文数据出现全部是问号现象（易诊断非数据库编码错误）

### ISSUE THREAD

**Issue by sindCheng** [MyCATApache/Mycat-Server#885]
在for循环里面调用mycat 查询表语句，表里面含有中文字段。返回结果集有时候全是问号（中文部分），有时候部分是问号，部分不是问号，有时候返回数据又不会出现问号乱码。麻烦开源大哥解答这种现象是mycat解析原因还是其他原因（实测本地库调用（不用mycat代理时）不会出现乱码现象）

**Comment by HashZhang** [comment]
什么客户端？连接串字符集是什么？数据库字符集是什么？

**Comment by magicdoom** [comment]
客户端指定编码方式    然后中文字段额

**Comment by magicdoom** [comment]
客户端指定编码方式 然后中文字段改掉     如果还有问题  再打开这个isses
