### ISSUE TITLE
mycat多表关联更新不支持

### ISSUE THREAD

**Issue by ksgimi** [MyCATApache/Mycat-Server#901]
update table_a set a_col1=1 where
       (a_col2,a_col3) in (
         select b_col2,b_col3  from table_b 
        where b_col4=1 and b_col5=0)

出错:[Err] 1064 - multi table related update not supported,tables:[table_a,table_b]
这个功能为啥不支持

**Comment by HashZhang** [comment]
你这个功能还是分两步自己做吧，也没有太大麻烦。MyCat要做要考虑的逻辑很多。如果是OLTP系统要避免这种语句

**Comment by ksgimi** [comment]
目前我是这样处理的：
1) insert into table_a_update_log (col2,col3)
     select b_col2,b_col3  from table_b 
    where b_col4=1 and b_col5=0

2)select * from table_a_update_log 再让应用循环处理。

不知道跟你说的分两步是不是同一个意思，可否范例一下，谢谢!

**Comment by magicdoom** [comment]
多分片的话  逻辑意义上可能不对 所以禁止了     单分片可以用注解   多分片就分步骤
