### ISSUE TITLE
关于全局ID生成

### ISSUE THREAD

**Issue by HashZhang** [MyCATApache/Mycat-Server#902]
为何在插入语句，全局ID生成的时候，不直接调用sequencehandler的nextID方法，而是将SQL语句和session封装成一个对象放到一个队列中，由另一个ExecuteThread单线程消费这个阻塞队列，统一执行sequencehandler的nextID方法改写SQL并发送到后端。这样TPS会受影响吧，是因为考虑线程安全么？基于文件的全局ID生成有线程安全问题？我写的那两个基于ZK的sequenceHandler是线程安全的，我可否改写成每个ReactorRW线程直接调用sequencehandler的nextID方法改写SQL并执行？

**Comment by HashZhang** [comment]
使用sequencehandler=3的全局ID生成器：
将对应代码修改前，测试（100线程，100次循环）
![1](https://cloud.githubusercontent.com/assets/15627489/15421107/106e33c6-1ea4-11e6-98da-775f32efd5b7.PNG)
将对应代码修改后：
![2](https://cloud.githubusercontent.com/assets/15627489/15421108/10a8d0b2-1ea4-11e6-9bf7-3862caf24283.PNG)

**Comment by magicdoom** [comment]
这个主要是避免NIO线程阻塞，以后应该是异步的，但还没想好框架

**Comment by HashZhang** [comment]
嗯，理解你说的。像是我那种全局自增生成ID，的确应该交给其他线程，如果是那种无序的，就不用了。我的理解是，只有耗时间的操作（复杂计算，IO）需要将操作交给其他线程来提高吞吐量，如果生成ID本来就应该是高效的操作（生成一个无序ID的TPS应该在几十万）。不用交给其他线程提高线程上下文切换

**Comment by HashZhang** [comment]
还有一点，放到同一队列中，只能单线程消费（并发会有问题，insert语句只要用全局ID生成器就会有吞吐量瓶颈）。否则会有事务乱序问题。这个需要每个和Session绑定的RW去做，感觉这个是几乎不可避免的。

**Comment by magicdoom** [comment]
自增id有步长的概念  所以步长大点   也还好
