### ISSUE TITLE
idea的databse工具连接mycat不显示表名

### ISSUE THREAD

**Issue by bk201sama** [MyCATApache/Mycat-Server#915]
test成功,schema也能勾选,但是就是看不到表,报 1 duplicate reports

**Comment by HashZhang** [comment]
idea通过发送的查看表的命令语句知道表有啥。这个命令是啥你最好看一下（开debug），我用idea做IDE，但是连接数据库我不用它

**Comment by magicdoom** [comment]
推荐用dbworkbench和navicat来连mycat   这2个根据支持的比较好

**Comment by magicdoom** [comment]
暂时没有计划支持idea的连接数据库功能    欢迎其他人提交pr支持
