### ISSUE TITLE
Mycat-1.5 release version. 不支持 SQL  like N'%中文%'

### ISSUE THREAD

**Issue by dockerlet** [MyCATApache/Mycat-Server#918]

**Comment by HashZhang** [comment]
1.5支持的

![13](https://cloud.githubusercontent.com/assets/15627489/15624643/e054ff18-24bf-11e6-93f8-be4296634571.PNG)

**Comment by magicdoom** [comment]
设置下客户端编码  服务器编码等等尝试下吧
