### ISSUE TITLE
distinct只在单个DataNode下生效，跨DataNode查询会查出多个重复的结果

### ISSUE THREAD

**Issue by shin74** [MyCATApache/Mycat-Server#92]
测试环境：

硬件：CPU E7500, 内存 4G
软件：WIN7 64位系统，JDK1.7.0_72 64位，MySQL Community 5.6.22.0单实例

测试使用的表按照《MyCat_In_Action_中文版》中快速上手部分使用的SQL进行创建，schema.xml使用默认设置，没有进行修改。

测试使用的是hotnews这个比较简单的表，象棋中插入5条数据，ID分别是1到5，title全部为“123”，查询SQL：select distinct title from hotnews;
结果：三个123（因为数据保存在三个DataNode上）

**Comment by apachemycat** [comment]
distinct在跨分片的结果集上，目前并不支持，建议的写法是 select title,count(title) group by title

**Comment by magicdoom** [comment]
1.4已经通过自动转化成group by的方式支持了

**Comment by mycatmerger** [comment]
1.4已经实现
