### ISSUE TITLE
mycat不支持mysql prepare指令

### ISSUE THREAD

**Issue by danielzheng** [MyCATApache/Mycat-Server#923]
你好，

mycat功能强大，性能很高。
但是对prepare指令缺少支持。
请问什么时候能加上这个特性。

谢谢

**Comment by HashZhang** [comment]
这个你觉得直接转发到某一个后台分片还是我们自己解析过程出来呢

**Comment by danielzheng** [comment]
$BD>@\(B??$B9!Bf="9%!#(B

Sent from my iPhone

On May 31, 2016, at 19:22, HashZhang <notifications@github.com<mailto:notifications@github.com>> wrote:


?$BP$(B??$BF@D>@\(B??$BE~K?0lP$9!BfJ,JR(B?$B@'2f(B?$B<+8J2r@O(B?$BDx=PMh(B?

-

**Comment by magicdoom** [comment]
`1.6支持

**Comment by hanlin3210** [comment]
xxxxxx

**Comment by danielzheng** [comment]
我测试了1.6的prepare，使用mysql命令行登录，返回com.alibaba.druid.sql.parser.ParserException: error SELECT

**Comment by magicdoom** [comment]
那你研究下代码看看  可能没移植完全   代码从master分支移植过来的
