### ISSUE TITLE
set autocommit=1

### ISSUE THREAD

**Issue by iloler** [MyCATApache/Mycat-Server#929]
执行语句的时候会自动添加set autocommit=1？我们用的postgresql不支持set autocommit=1，在哪里关闭自动添加set autocommit=1呢？

**Comment by HashZhang** [comment]
后台数据库类型指定是PG

**Comment by magicdoom** [comment]
pg的话   SET AUTOCOMMIT  = ON | OFF

**Comment by iloler** [comment]
unrecognized configuration parameter "autocommit"，9.5版本的pg似乎不支持autocommit

**Comment by iloler** [comment]
哈哈，搞定了，贴一下schema.xml留给后来人吧！

<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
	
	<schema name="demo" checkSQLschema="false" sqlMaxLimit="100">
		
		<table name="product" dataNode="dn1,dn2" rule="auto-sharding-long" />
		
		<table name="nihao" dataNode="dn1,dn2" rule="auto-sharding-long" />
	</schema>
	
	<dataNode name="dn1" dataHost="localhost1" database="demo" />
	<dataNode name="dn2" dataHost="localhost2" database="demo" />
	
	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="postgresql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
		<heartbeat>select 1</heartbeat>
		
		<writeHost host="hostM1" url="jdbc:postgresql://192.168.99.100:32777/demo" user="postgres"
				   password="">
		</writeHost>
		
		
	</dataHost>
	
	<dataHost name="localhost2" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="postgresql" dbDriver="jdbc" switchType="1"  slaveThreshold="100">
		<heartbeat>select 1</heartbeat>
		<writeHost host="hostM2" url="jdbc:postgresql://192.168.99.100:33333/demo" user="postgres"
				   password="" />
	</dataHost>
	
</mycat:schema>
