### ISSUE TITLE
Error happen when backend is jdbc connection.

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#93]
Mysql jdbc driver at app side will send some packets like the following text, backend jdbc connection can not parse and execute it. 
----------------------------------------------------------
"/* mysql-connector-java-5.1.34 ( revision: jess.balint@oracle.com-20141014163213-wqbwpf1ok2kvo1om ) */show variables where variable_name ='language' or variable_name = 'net_write_timeout' or variable_name = 'interactive_timeout' or variable_name = 'wait_timeout' or variable_name = 'character_set_client' or variable_name = 'character_set_connection' or variable_name = 'character_set' or variable_name = 'character_set_server' or variable_name = 'tx_isolation' or variable_name = 'transaction_isolation' or variable_name = 'character_set_results' or variable_name = 'timezone' or variable_name = 'time_zone' or variable_name = 'system_time_zone' or variable_name = 'lower_case_table_names' or variable_name = 'max_allowed_packet' or variable_name = 'net_buffer_length' or variable_name = 'sql_mode' or variable_name = 'query_cache_type' or variable_name = 'query_cache_size' or variable_name = 'license' or variable_name = 'init_connect'"

**Comment by linzhiqiang0514** [comment]
之前这个代码改的似乎有点问题，没有merge回退了，请重新确认一下。

**Comment by mycatmerger** [comment]
后端jdbc已经支持show variables 语句
