### ISSUE TITLE
当分库字段为uuid时，使用sharding-by-murmur规则配置主子表关系，导致主子表关联数据无法插入到同一个库中

### ISSUE THREAD

**Issue by quinnzhuang** [MyCATApache/Mycat-Server#938]
表结构为：
create table test(
  id varchar(36) not null,
  a varchar(36) not null,
  b int not null,
  c varchar(36) default null,
  primary key(id)
);

create table test1(
	id varchar(36) not null,
    test_id varchar(36) not null,
    d varchar(36) not null,
    e int not null,
    primary key(id),
    key test_id_d_index(test_id, d)
);
insert into test(id, a, b, c) values('afdmsaodfswefe', 'demo', 1, 'haha');
insert into test1(id, test_id, d, e) values('mlsadfadfasfd', 'afdmsaodfswefe', 't', 1);
如使用以下配置：
`<table name="test" primaryKey="ID" dataNode="dn1,dn3"
                        rule="sharding-by-murmur">
                        <childTable name="test1" primaryKey="ID" joinKey="test_id"
                                parentKey="id">
                        </childTable>
</table>`
插入数据时主子表关联的数据不会写入同一个库中。
**原因是在类RouterUtil的processERChildTable方法中，解析子表插入数据时，
使用String joinKeyVal = insertStmt.getValues().getValues().get(joinKeyIndex).toString();
获取字段插入值时带有单引号，而计算hash的时候单引号也会一起跟着计算，但是在主表插入数据时却不带单引号。**

**Comment by quinnzhuang** [comment]
有人来修复这个bug吗

**Comment by magicdoom** [comment]
你可以自己尝试一下
