### ISSUE TITLE
1.5.1 mysql表名带有敏感字的时候，会出错

### ISSUE THREAD

**Issue by hhping821** [MyCATApache/Mycat-Server#945]
例如：我的表名叫 desc ,  那么这个表会连不上，下面这句会执行不了，报错：
SHOW FULL COLUMNS FROM desc

只会有show语法中有问题，select,update,insert,delete都没有问题。希望能解决这个问题，本人只是自己做了个强制替换，没有通读代码去修这个bug。

**Comment by magicdoom** [comment]
这个还是自己表名注意下吧

**Comment by yjqg6666** [comment]
试试 SHOW FULL COLUMNS FROM `desc`

**Comment by magicdoom** [comment]
这个应该从自己应用的规范来解决  不要使用敏感关键词
