### ISSUE TITLE
MyCat 1.5 having子句不起做用

### ISSUE THREAD

**Issue by cusele** [MyCATApache/Mycat-Server#952]
Mycat-server-1.5.1-RELEASE-20160613195853-linux.tar.gz
在hash分片表上
使用group by时having 子句不起做用
mysql> EXPLAIN select info ,count(*) from t_test group by info HAVING count(*)>2;
+-----------+---------------------------------------------------------------------+
| DATA_NODE | SQL                                                                 |
+-----------+---------------------------------------------------------------------+
| dn01      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn02      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn03      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn04      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn05      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn06      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn07      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn08      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn09      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
| dn10      | SELECT info, COUNT(*) AS COUNT1 FROM t_test GROUP BY info LIMIT 100 |
+-----------+---------------------------------------------------------------------+
10 rows in set (0.00 sec)

mysql> select info ,count(*) from t_test group by info HAVING count(*)>2;
+------+--------+
| info | COUNT1 |
+------+--------+
| 1    |      1 |
| 4    |      1 |
| 5    |      1 |
| 3    |      1 |
| xxx  |      1 |
| 2    |      1 |
+------+--------+
6 rows in set (0.01 sec)

**Comment by magicdoom** [comment]
EXPLAIN select info ,count() as aa from test group by info HAVING aa>2;    请用别名   否则druid在解析时会报错
