### ISSUE TITLE
MyCat 1.5 /*balance*/注解不起做用

### ISSUE THREAD

**Issue by cusele** [MyCATApache/Mycat-Server#953]
Mycat-server-1.5.1-RELEASE-20160613195853-linux.tar.gz
使用注解指定从写库读无法实现
mysql> /*balance*/select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           2 |
+-------------+
1 row in set (0.00 sec)

**Comment by songgw** [comment]
格式是/*balance*/,你写的是不是不对？

**Comment by cusele** [comment]
mysql> select @@server_id;
+-------------+
| @@server_id |
+-------------+
|           3 |
+-------------+
1 row in set (0.00 sec)

mysql> /balance/ select @@server_id;
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql>

**Comment by magicdoom** [comment]
请提供详细的配置     之前刚测过这块没问题

**Comment by magicdoom** [comment]
select @@server_id 这种语句可能有问题     测试用你真实的表
