### ISSUE TITLE
1.5版本 使用阿里云的rds 搭建mycat后 报错 General error: 1047 Prepare unsupported!

### ISSUE THREAD

**Issue by wanghaozi** [MyCATApache/Mycat-Server#954]
`[2016-06-14 20:00:16] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1047 Prepare unsupported!' in /home/huimin/activity.alpha.huimin100.cn/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:40`
使用的php语言 laravel5.2 框架, 异常栈显示在 prepare的时候 报错了 .

**Comment by zhuam** [comment]
Prepare unsupported!

**Comment by ZzzCrazyPig** [comment]
1.5版本仍然未支持Prepare statement，可以试试1.6-DEV版本

**Comment by magicdoom** [comment]
jdbc的驱动默认都是关闭这个选项 驱动内部自动拼接的 你可以研究下php里是否也有这个选项

**Comment by l25359423** [comment]
我想请问解决了吗

**Comment by ZzzCrazyPig** [comment]
@l25359423 预处理的实现在1.6版本才有 1.5没有这个功能
