### ISSUE TITLE
使用mysql connector c++连接mycat的问题

### ISSUE THREAD

**Issue by Shannon1** [MyCATApache/Mycat-Server#957]
在使用mysql提供的c++ API [mysql connector c++](https://dev.mysql.com/doc/connector-cpp/en/) 连接mycat的时候，在调用prepareStatement的时候mycat会返回`Prepare unsupported`的错误。
```
try {
    sql::mysql::MySQL_Driver* driver = sql::mysql::get_mysql_driver_instance();
    boost::scoped_ptr< sql::Connection > conn(driver->connect(host.c_str(), user.c_str(), password.c_str()));
    std::string sql = "select * from table";
    boost::scoped_ptr< sql::PreparedStatement > prep_stmt(conn->prepareStatement(sql));

    // ...

} catch (sql::SQLException& e) {
    std::cout << e.what() << std::endl;
    std::cout << e.getErrorCode() << std::endl;
    std::cout << e.getSQLStateCStr() << std::endl;
}

// 程序输出
Prepare unsupported！
1047
HY000
```

同样的代码直接连mysql的时候是正常的。

不用prepareStatement方法直接执行语句也是正常的。

mycat版本1.4-Release
mysql connector c++ 版本1.1.7

请问这个问题是什么原因呢

**Comment by zhuam** [comment]
MYCAT1.4 不支持 prepareStatement， 请使用 1.5+版本

**Comment by Shannon1** [comment]
@zhuam 你好，我试了mycat 1.5.1-Release版本，该问题依然存在 T T

**Comment by ZzzCrazyPig** [comment]
@Shannon1 mycat prepare statement的支持在master和1.6开发分支里面 1.6-DEV版本是可以支持的，你可以试试

**Comment by magicdoom** [comment]
jdbc的驱动默认都是关闭这个选项 驱动内部自动拼接的      你可以研究下c++里是否也有这个选项

**Comment by Shannon1** [comment]
@magicdoom 你指的“这个选项”具体是什么，预处理吗？

**Comment by magicdoom** [comment]
对

**Comment by magicdoom** [comment]
1.6已经支持prepare
