### ISSUE TITLE
limit() in the select SQL is not be supported by oracle.

### ISSUE THREAD

**Issue by bluoy** [MyCATApache/Mycat-Server#96]
and DB2, SQL Server, etc.

**Comment by apachemycat** [comment]
这个需要转换为Oracle的特殊SQL写法，目前还没能实现

**Comment by apachemycat** [comment]
新的源码再考虑这个问题

**Comment by linzhiqiang0514** [comment]
master的1.4-dev版本，有人提交了needAddLimit的参数，可以配置，在oracle等数据库中去除limit，请测试。

**Comment by bluoy** [comment]
如果不加限制，大结果集merge起来会不会有问题？

**Comment by sohudo** [comment]
请用ROWNUM ,master版本已经支持
