### ISSUE TITLE
分片表中的字段建唯一索引失效

### ISSUE THREAD

**Issue by shinyke** [MyCATApache/Mycat-Server#961]
你好，我在使用分片表的过程遇到了唯一索引不生效的情况：建立了唯一索引的字段还是出现重复值。

DROP TABLE IF EXISTS `t_user_setting`;
CREATE TABLE `t_user_setting` (
  `ACCOUNT_ID` varchar(150) NOT NULL COMMENT '用户ID',
  `ACCOUNT_NAME` varchar(150) NOT NULL COMMENT '用户名',
.....
  PRIMARY KEY (`ACCOUNT_ID`),
  UNIQUE KEY `ACCOUNT_NAME` (`ACCOUNT_NAME`)  -- 建立对ACCOUNT_NAME的唯一索引
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

在以上表中插入重复值的ACCOUNT_NAME系统仍是允许的。

是否mycat中的UNIQUE index 并非全局。有无办法可解决？谢谢！

**Comment by magicdoom** [comment]
索引等是由mysql本身的控制    mycat不校验你数据的唯一性   需要你应用自己保证

**Comment by EthanMR** [comment]
请问解决了吗
