### ISSUE TITLE
1.5版本升级druid 1.0.19后报ClassNotFoundException: com.alibaba.druid.sql.dialect.mysql.ast.expr.MySqlSelectGroupByExpr

### ISSUE THREAD

**Issue by flyshadowhan** [MyCATApache/Mycat-Server#966]
sql里使用了truncate()函数,mycat1.5版本自带的druid 1.0.14不支持,于是druid升级到1.0.19后,日志提示ClassNotFoundException: com.alibaba.druid.sql.dialect.mysql.ast.expr.MySqlSelectGroupByExpr.求助...

**Comment by magicdoom** [comment]
1.6支持了druid新版   需要做不少修改的
