### ISSUE TITLE
1.6-dev 启动报错

### ISSUE THREAD

**Issue by ActorJamesTsai** [MyCATApache/Mycat-Server#968]
Connection timed out for connection string (10.202.44.206:2181) and timeout (15000) / elapsed (58261) org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss

**Comment by HashZhang** [comment]
这个是因为新的id生成器依赖zk，你把server.xml中的<property name="sequnceHandlerType">3</property>改为<property name="sequnceHandlerType">1</property>或者搭建一套ZK，将sequence_distributed_conf.properties中zk地址修改下

发件人: Actor:JamesTsai [mailto:notifications@github.com]
发送时间: 2016年7月4日 20:19
收件人: MyCATApache/Mycat-Server
主题: [MyCATApache/Mycat-Server] 1.6-dev 启动报错 (#968)


Connection timed out for connection string (10.202.44.206:2181) and timeout (15000) / elapsed (58261) org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss

**Comment by magicdoom** [comment]
如果验证没问题了 就关闭吧
