### ISSUE TITLE
Mycat-Server-1.5-RELEASE  按日期分片，循环使用分片节点，跨分片查询时出现NullPointerException

### ISSUE THREAD

**Issue by fighting515** [MyCATApache/Mycat-Server#974]
异常出现的场景：
1.按日期分片，10天一个分片，10个分片节点
2.跨第一个分片和第十个分片查询时会出现   ERROR 1064 (HY000): NullPointerException

源代码分析：
	/**
	 * 对于存储数据按顺序存放的字段做范围路由，可以使用这个函数
	 * @param algorithm
	 * @param beginValue
	 * @param endValue
	 * @return
	 */
	public static Integer[] calculateSequenceRange(AbstractPartitionAlgorithm algorithm, String beginValue, String endValue) {
		Integer begin = 0, end = 0;
		begin = algorithm.calculate(beginValue);
		end = algorithm.calculate(endValue);

		if(begin == null || end == null){
			return new Integer[0];
		}
		
		if (end >= begin) {     //该判断在以上场景时   end为0   begin为9  ，导致判断不通过返回了null
			int len = end-begin+1;
			Integer [] re = new Integer[len];
			
			for(int i =0;i<len;i++){
				re[i]=begin+i;
			}
			
			return re;
		}else{
			return null;
		}
	}

**Comment by magicdoom** [comment]
你可以研究下怎么修复比较好

**Comment by fighting515** [comment]
目前我只能临时做下处理，不返回null ,返回new Integer[0]，这样会将sql路由到所有分片节点去执行。

**Comment by magicdoom** [comment]
应该可以算出来   具体欢迎提交pr

**Comment by fighting515** [comment]
但是这个借口的参数没有分片节点的数量，如果有的话，可以根据总数计算出来具体路由到哪些分片节点

**Comment by fighting515** [comment]
但是这个接口参数没有分片节点的总数，如果有总数的话，可以根据总数算出具体路由到哪些节点

**Comment by magicdoom** [comment]
你先提个pr到1.6   先发到所有分片这种方式先处理    后续再其他优化

**Comment by magicdoom** [comment]
目前已经有pr处理了  先关闭
