### ISSUE TITLE
update出错了

### ISSUE THREAD

**Issue by java131313** [MyCATApache/Mycat-Server#986]
select * from app_crash_log where id=1439448774\G;

update app_crash_log set osVersion='4.8' where id=1439448774\G;
ERROR 1105 (HY000): Unknown column '_mycat_op_time' in 'field list'
ERROR: 
No query specified，？？

**Comment by java131313** [comment]
求回答？

**Comment by fireflyhoo** [comment]
请提供版本,和日志信息

**Comment by quinnzhuang** [comment]
你这个是因为全局表没创建_mycat_op_time字段导致的，全局表出了需要业务字段，还需要_mycat_op_time字段供mycat使用

**Comment by magicdoom** [comment]
1.6全局表校验  需要这个字段     没有自动加 就手工加下吧
