### ISSUE TITLE
对于非分片表如何配置呢?

### ISSUE THREAD

**Issue by kalsolio** [MyCATApache/Mycat-Server#987]
`分片的 如 <table name="test" dataNode="test" rule="auto-sharding-long" />`

**Comment by ZzzCrazyPig** [comment]
去掉rule配置即可

**Comment by magicdoom** [comment]
配置默认节点   具体看权威指南

2016-07-17 22:22 GMT+08:00 CrazyPig <notifications@github.com>:

**Comment by panqizhen** [comment]
schema配置里加dataNode,就会默认走这个, 比如:
<schema name="TESTDB" checkSQLschema="false"  randomDataNode="dn1" dataNode="dn1">
