### ISSUE TITLE
插入数据失败

### ISSUE THREAD

**Issue by xiangwan** [MyCATApache/Mycat-Server#990]
各位好。
使用navicat导入数据时，它生成的insert语句里int类型的数据也被引号包围（`104`）。如果这一列是普通的列的话，是可以导入的。但是如果这一列是分片键，就会报错 "1064  for input string '104'"。
是bug吧？

**Comment by HashZhang** [comment]
用的什么分片方法？

**Comment by xiangwan** [comment]
mod-long @HashZhang

**Comment by HashZhang** [comment]
这个分片方法的确是没有考虑，考虑改下

**Comment by xiangwan** [comment]
@HashZhang 辛苦

**Comment by HashZhang** [comment]
已经修改合并到1.6

**Comment by xiangwan** [comment]
这么快的修复速度。赞！ @HashZhang

**Comment by HashZhang** [comment]
我今天还会修改一些其他bug并且同时推到1.5和1.6分支，请问你用的是哪个版本？

**Comment by xiangwan** [comment]
我现在用的1.6
